// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["./BaseVersionManager","./utils"],function(k,l){function h(){this.versions=[{version:"1.0",description:"The version embedded in portal 10.3 final.",upgrader:function(a){return a},compatible:!0},{version:"1.1",description:"The version embedded in online3.6, and used in developer edition 1.0.",upgrader:function(a){a.widgetOnScreen&&a.widgetOnScreen.panel&&("themes/FoldableTheme/panels/TitlePanel/Panel"===a.widgetOnScreen.panel.uri||"jimu/BaseWidgetPanel"===a.widgetOnScreen.panel.uri)&&(a.widgetOnScreen.panel.uri=
"jimu/PreloadWidgetIconPanel");return a},compatible:!0},{version:"1.2",description:"The version embedded in online3.7.",upgrader:function(a){var c=0;if(a.widgetOnScreen&&a.widgetOnScreen.widgets){for(var b=!1,c=0;c<a.widgetOnScreen.widgets.length;c++)"widgets/Splash/Widget"===a.widgetOnScreen.widgets[c].uri&&(b=!0);b||a.widgetOnScreen.widgets.push({uri:"widgets/Splash/Widget",visible:!1,positionRelativeTo:"browser",version:"1.2"});b=!1;for(c=0;c<a.widgetOnScreen.widgets.length;c++)"widgets/TimeSlider/Widget"===
a.widgetOnScreen.widgets[c].uri&&(b=!0);b||a.widgetOnScreen.widgets.push({uri:"widgets/TimeSlider/Widget",visible:!1,position:{bottom:55,left:7},version:"1.2"});b=!1;for(c=0;c<a.widgetOnScreen.widgets.length;c++)"widgets/Swipe/Widget"===a.widgetOnScreen.widgets[c].uri&&(b=!0);b||a.widgetOnScreen.widgets.push({uri:"widgets/Swipe/Widget",visible:!1,position:{top:145,left:7},version:"1.2"})}return a},compatible:!0},{version:"1.3",description:"The version embedded in online3.8 \x26 online3.9.",upgrader:function(a){(function(a){l.visitElement(a,
function(a){a.positionRelativeTo&&(a.position?a.position.relativeTo=a.positionRelativeTo:a.position={relativeTo:a.positionRelativeTo},a.panel&&(a.panel.position?a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo}))});var b=a.widgetOnScreen;b&&b.panel&&b.panel.positionRelativeTo&&(b.panel.position?b.panel.position.relativeTo=b.panel.positionRelativeTo:b.panel.position={relativeTo:b.panel.positionRelativeTo});(b=a.widgetPool)&&b.panel&&b.panel.positionRelativeTo&&
(b.panel.position?b.panel.position.relativeTo=b.panel.positionRelativeTo:b.panel.position={relativeTo:b.panel.positionRelativeTo})})(a);a.widgetOnScreen&&a.widgetOnScreen.panel&&"jimu/PreloadWidgetIconPanel"===a.widgetOnScreen.panel.uri&&(a.widgetOnScreen.panel.uri="jimu/OnScreenWidgetPanel");(function(a){if(a.widgetOnScreen&&a.widgetOnScreen.widgets&&a.theme&&"FoldableTheme"===a.theme.name){var b=null,c=null;if(b=a.widgetOnScreen.widgets[4])void 0!==b.position.top?(b={position:{left:205,top:45}},
c={position:{left:255,top:45}}):(b={position:{left:205,bottom:55}},c={position:{left:255,bottom:55}}),a.widgetOnScreen.widgets.splice(7,0,b,c)}})(a);(function(){for(var c=0,b=0,e=!1,c=0;c<a.widgetOnScreen.widgets.length;c++)if("widgets/Geocoder/Widget"===a.widgetOnScreen.widgets[c].uri){e=!0;break}for(var d=!1,b=0;b<a.widgetOnScreen.widgets.length;b++)if("widgets/Search/Widget"===a.widgetOnScreen.widgets[b].uri){d=!0;break}!d&&e&&(c=a.widgetOnScreen.widgets[c],c.uri="widgets/Search/Widget",c.name=
"Search")})(a);(function(a){for(var b=0,b=a.widgetOnScreen.widgets.length-1;0<=b;b--){var c=a.widgetOnScreen.widgets[b];if("widgets/Swipe/Widget"===c.uri&&!c.closeable&&(a.widgetOnScreen.widgets.splice(b,1),!1!==c.visible)){c.closeable=!0;var d;a:{for(d=d=0;d<a.widgetOnScreen.widgets.length;d++)if(!a.widgetOnScreen.widgets[d].uri)break a;d=-1}0<=d&&(c.position=a.widgetOnScreen.widgets[d].position,a.widgetOnScreen.widgets[d]=c)}"widgets/TimeSlider/Widget"===c.uri&&(!1===c.visible?a.widgetOnScreen.widgets.splice(b,
1):c.closeable=!0)}})(a);a.widgetOnScreen.widgets.push({uri:"widgets/ZoomSlider/Widget",position:{top:5,left:7},version:"1.3"});a.loadingPage||(a.loadingPage={backgroundColor:"#508dca",backgroundImage:{visible:!1},loadingGif:{visible:!0,uri:"configs/loading/images/predefined_loading_1.gif",width:58,height:58}});return a},compatible:!0},{version:"1.4",description:"The version embedded in online3.10.",upgrader:function(a){if(a.theme){var c=a.theme.name;if(("FoldableTheme"===c||"JewelryBoxTheme"===c)&&
a.widgetOnScreen){var b=a.widgetOnScreen.widgets;if(b&&0<b.length)for(var c="themes/"+c+"/widgets/HeaderController/Widget",e=null,d=0;d<b.length;d++)(e=b[d])&&e.uri===c&&e.position&&310===e.position.paddingRight&&(e.position.paddingRight=275)}}return a},compatible:!0},{version:"2.0beta",description:"The version for Developer Edition beta 2.0.",upgrader:function(a){a.keepAppState=!0;return a},compatible:!0},{version:"2.0",description:"The version for Online 4.1.",upgrader:function(a){return a},compatible:!0},
{version:"2.0.1",description:"The version for Developer Edition 2.0.",upgrader:function(a){return a},compatible:!0},{version:"2.1",description:"The version for Online 4.2.",upgrader:function(a){return a},compatible:!0},{version:"2.2",description:"The version for Online 4.3.",upgrader:function(a){return a},compatible:!0},{version:"2.3",description:"The version for Online 4.4.",upgrader:function(a){function c(a,b){if(!a||!b)return!1;for(var d in b)if(b.hasOwnProperty(d))if("object"===typeof b[d]){if(!c(a[d],
b[d]))return!1}else if(a[d]!==b[d])return!1;return!0}function b(a){function b(){var b=c(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),d=c(a[12],{position:{top:10,right:195}});return b&&d}function d(){var b=c(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,bottom:45}}),d=c(a[12],{position:{left:15,top:233}});return b&&d}function e(){var b=c(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),d=c(a[12],{position:{right:15,top:195}});return b&&d}(function(){var b=
c(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),d=c(a[12],{position:{left:240,top:53}});return b&&d})()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,top:159},version:"2.3"}):b()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,top:159},version:"2.3"}):d()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,bottom:195},version:"2.3"}):e()&&a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,
top:159},version:"2.3"})}function e(a){function b(){var b=c(a[9],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}),d=c(a[2],{uri:"widgets/Search/Widget",position:{left:55,top:5}}),e=c(a[4],{position:{left:7,bottom:70}});return b&&d&&e}function d(){var b=c(a[9],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}),d=c(a[2],{uri:"widgets/Search/Widget",position:{right:2,top:2,relativeTo:"browser"}}),e=c(a[4],{position:{left:7,bottom:70}});return b&&d&&e}(function(){var b=c(a[9],{uri:"widgets/MyLocation/Widget",
position:{left:7,top:110}}),d=c(a[2],{uri:"widgets/Search/Widget",position:{left:55,top:5}}),e=c(a[4],{position:{left:55,top:45}});return b&&d&&e}()||b()||d())&&a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:148,left:7},version:"2.3"})}(function(a,f,g){a=a.theme&&a.theme.name;if("FoldableTheme"===a)if(c(f[11],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}))f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:150,left:7},version:"2.3"});else if(c(f[11],
{uri:"widgets/MyLocation/Widget",position:{left:12,bottom:164}}))f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:12,bottom:203},version:"2.3"}),g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{right:12,top:211},version:"2.3"});else{if(c(f[11],{uri:"widgets/MyLocation/Widget",position:{left:164,bottom:14}})){f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:203,bottom:14,height:30},version:"2.3"});for(a=0;a<f.length;a++){var d=f[a];c(d,{uri:"widgets/Scalebar/Widget",
position:{left:220,bottom:5}})&&(d.position.left=288);c(d,{uri:"widgets/Coordinate/Widget",position:{left:395,bottom:5}})&&(d.position.left=463)}g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:209,left:12},version:"2.3"})}}else if("BillboardTheme"===a)b(f);else if("BoxTheme"===a)f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:10,top:131},version:"2.3"});else if("JewelryBoxTheme"===a)e(f);else if("LaunchpadTheme"===a){if(c(f[6],{uri:"widgets/MyLocation/Widget",
position:{left:25,top:215}})||c(f[6],{uri:"widgets/MyLocation/Widget",position:{left:25,top:215}}))f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:255,left:25},version:"2.3"}),g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{right:10,bottom:238},version:"2.3"})}else"PlateauTheme"===a?(c(f[6],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}})&&f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:149,left:7},version:2.3}),c(f[6],{uri:"widgets/MyLocation/Widget",
position:{left:12,bottom:164}})&&f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:12,bottom:201},version:2.3})):"TabTheme"===a&&c(f[11],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}})&&f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:149,left:7},version:"2.3"})})(a,a.widgetOnScreen.widgets,a.mobileLayout&&a.mobileLayout.widgetOnScreen&&a.mobileLayout.widgetOnScreen.widgets);return a},compatible:!0},{version:"2.4",description:"The version for Online 5.1.",
upgrader:function(a){return a},compatible:!0},{version:"2.5",description:"The version for Online 5.2.",upgrader:function(a){function c(a,e){if(!a||!e)return!1;for(var b in e)if(e.hasOwnProperty(b))if("object"===typeof e[b]){if(!c(a[b],e[b]))return!1}else if(a[b]!==e[b])return!1;return!0}(function(a,e){a=a.theme&&a.theme.name;if("BillboardTheme"===a){a=c(e[8],{position:{left:60,top:53}});var b=c(e[8],{position:{left:15,top:53}});a||b?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,
top:8},version:"2.5"}):e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,bottom:55},version:"2.5"})}else if("BoxTheme"===a){a:{a=0;for(b=e.length;a<b;a++){var f=e[a];if(f&&f.uri&&"themes/BoxTheme/widgets/BoxController/Widget"===f.uri){a=f;break a}}a=null}c(a,{position:{right:0,bottom:0}})?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,bottom:8},version:"2.5"})}else"DartTheme"===
a?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"FoldableTheme"===a?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"DashboardTheme"===a?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"JewelryBoxTheme"===a?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"LaunchpadTheme"===a?e.push({uri:"widgets/FullScreen/Widget",visible:!1,
position:{right:70,top:20},version:"2.5"}):"PlateauTheme"===a?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"TabTheme"===a&&(c(e[7],{position:{left:45,top:45}})?e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):e.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,bottom:55},version:"2.5"}))})(a,a.widgetOnScreen.widgets);return a},compatible:!0},{version:"2.6",description:"The version for Online 5.3.",
upgrader:function(a){return a},compatible:!0},{version:"2.7",description:"The version for Online 5.4.",upgrader:function(a){return a},compatible:!0},{version:"2.8",description:"The version for Online 6.1.",upgrader:function(a){function c(a){var b=[];if("object"===typeof a)for(var c in a){var f=a[c];"FeatureStatistics"===f.type&&b.push(f)}return b}(function(a){(a=a.dataSource&&a.dataSource.dataSources)&&(a=c(a))&&a.length&&a.forEach(function(a){(a=a.dataSchema&&a.dataSchema.statistics)&&a.length&&
a.forEach(function(a){if(a&&"count"===a.statisticType&&"count"===a.outStatisticFieldName)a.outStatisticFieldName="STAT_COUNT";else{var b;b=(b=a.outStatisticFieldName)&&b.toUpperCase();a.outStatisticFieldName=b}})})})(a);return a},compatible:!0},{version:"2.9",description:"The version for Online 6.2.",upgrader:function(a){return a},compatible:!0},{version:"2.10",description:"The version for Online 6.3.",upgrader:function(a){return a},compatible:!0},{version:"2.11",description:"The version for Online 6.4.",
upgrader:function(a){return a},compatible:!0},{version:"2.12",description:"The version for Online 7.1",upgrader:function(a){return a},compatible:!0},{version:"2.13",description:"The version for Online 7.2",upgrader:function(a){if(a.theme&&"PlateauTheme"===a.theme.name&&a.widgetOnScreen&&a.widgetOnScreen.widgets)for(var c=a.widgetOnScreen.widgets,b=0;b<c.length;b++)if("widgets/AttributeTable/Widget"===c[b].uri&&c[b].position){c[b].position.relativeTo="browser";break}return a},compatible:!0},{version:"2.14",
description:"The version for Online 7.3",upgrader:function(a){return a},compatible:!0},{version:"2.15",description:"The version for Online 7.4",upgrader:function(a){return a},compatible:!0},{version:"2.16",description:"The version for Online 8.1",upgrader:function(a){return a},compatible:!0},{version:"2.17",description:"The version for Online 8.2",upgrader:function(a){return a},compatible:!0}];this.isCompatible=function(a,c){a=this.getVersionIndex(a);c=this.getVersionIndex(c);for(a+=1;a<=c;a++)if(!1===
this.versions[a].compatible)return!1;return!0}}h.prototype=new k;return h.prototype.constructor=h});