//>>built
/*

 Copyright 2000, Silicon Graphics, Inc. All Rights Reserved.
 Copyright 2015, Google Inc. All Rights Reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice including the dates of first publication and
 either this permission notice or a reference to http://oss.sgi.com/projects/FreeB/
 shall be included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 SILICON GRAPHICS, INC. BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
 IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 Original Code. The Original Code is: OpenGL Sample Implementation,
 Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
 Inc. The Original Code is Copyright (c) 1991-2000 Silicon Graphics, Inc.
 Copyright in any portions created by third parties is as indicated
 elsewhere herein. All Rights Reserved.
*/
define([],function(){var a={};return a.DEBUG=!1,a.assert=function(b,c){if(a.DEBUG&&!b)throw Error("Assertion failed"+(c?": "+c:""));},a.GLU_TESS_MAX_COORD=1E150,a.TRUE_PROJECT=!1,a.GLU_TESS_DEFAULT_TOLERANCE=0,a.windingRule={GLU_TESS_WINDING_ODD:100130,GLU_TESS_WINDING_NONZERO:100131,GLU_TESS_WINDING_POSITIVE:100132,GLU_TESS_WINDING_NEGATIVE:100133,GLU_TESS_WINDING_ABS_GEQ_TWO:100134},a.primitiveType={GL_LINE_LOOP:2,GL_TRIANGLES:4,GL_TRIANGLE_STRIP:5,GL_TRIANGLE_FAN:6},a.errorType={GLU_TESS_MISSING_BEGIN_POLYGON:100151,
GLU_TESS_MISSING_END_POLYGON:100153,GLU_TESS_MISSING_BEGIN_CONTOUR:100152,GLU_TESS_MISSING_END_CONTOUR:100154,GLU_TESS_COORD_TOO_LARGE:100155,GLU_TESS_NEED_COMBINE_CALLBACK:100156},a.gluEnum={GLU_TESS_BEGIN:100100,GLU_TESS_VERTEX:100101,GLU_TESS_END:100102,GLU_TESS_ERROR:100103,GLU_TESS_EDGE_FLAG:100104,GLU_TESS_COMBINE:100105,GLU_TESS_BEGIN_DATA:100106,GLU_TESS_VERTEX_DATA:100107,GLU_TESS_END_DATA:100108,GLU_TESS_ERROR_DATA:100109,GLU_TESS_EDGE_FLAG_DATA:100110,GLU_TESS_COMBINE_DATA:100111,GLU_TESS_MESH:100112,
GLU_TESS_TOLERANCE:100142,GLU_TESS_WINDING_RULE:100140,GLU_TESS_BOUNDARY_ONLY:100141,GLU_INVALID_ENUM:100900,GLU_INVALID_VALUE:100901},a.PQHandle,a.geom={},a.geom.vertEq=function(b,a){return b.s===a.s&&b.t===a.t},a.geom.vertLeq=function(b,a){return b.s<a.s||b.s===a.s&&b.t<=a.t},a.geom.edgeEval=function(b,c,d){a.assert(a.geom.vertLeq(b,c)&&a.geom.vertLeq(c,d));var e=c.s-b.s,f=d.s-c.s;return 0<e+f?e<f?c.t-b.t+e/(e+f)*(b.t-d.t):c.t-d.t+f/(e+f)*(d.t-b.t):0},a.geom.edgeSign=function(b,c,d){a.assert(a.geom.vertLeq(b,
c)&&a.geom.vertLeq(c,d));var e=c.s-b.s,f=d.s-c.s;return 0<e+f?(c.t-d.t)*e+(c.t-b.t)*f:0},a.geom.transLeq=function(b,a){return b.t<a.t||b.t===a.t&&b.s<=a.s},a.geom.transEval=function(b,c,d){a.assert(a.geom.transLeq(b,c)&&a.geom.transLeq(c,d));var e=c.t-b.t,f=d.t-c.t;return 0<e+f?e<f?c.s-b.s+e/(e+f)*(b.s-d.s):c.s-d.s+f/(e+f)*(d.s-b.s):0},a.geom.transSign=function(b,c,d){a.assert(a.geom.transLeq(b,c)&&a.geom.transLeq(c,d));var e=c.t-b.t,f=d.t-c.t;return 0<e+f?(c.s-d.s)*e+(c.s-b.s)*f:0},a.geom.edgeGoesLeft=
function(b){return a.geom.vertLeq(b.dst(),b.org)},a.geom.edgeGoesRight=function(b){return a.geom.vertLeq(b.org,b.dst())},a.geom.vertL1dist=function(b,a){return Math.abs(b.s-a.s)+Math.abs(b.t-a.t)},a.geom.vertCCW=function(b,a,d){return 0<=b.s*(a.t-d.t)+a.s*(d.t-b.t)+d.s*(b.t-a.t)},a.geom.interpolate_=function(b,a,d,e){return b=0>b?0:b,d=0>d?0:d,b<=d?0===d?(a+e)/2:a+b/(b+d)*(e-a):e+d/(b+d)*(a-e)},a.geom.edgeIntersect=function(b,c,d,e,f){var g,h,k;a.geom.vertLeq(b,c)||(k=b,b=c,c=k);a.geom.vertLeq(d,
e)||(k=d,d=e,e=k);a.geom.vertLeq(b,d)||(k=b,b=d,d=k,k=c,c=e,e=k);a.geom.vertLeq(d,c)?a.geom.vertLeq(c,e)?(g=a.geom.edgeEval(b,d,c),h=a.geom.edgeEval(d,c,e),0>g+h&&(g=-g,h=-h),f.s=a.geom.interpolate_(g,d.s,h,c.s)):(g=a.geom.edgeSign(b,d,c),h=-a.geom.edgeSign(b,e,c),0>g+h&&(g=-g,h=-h),f.s=a.geom.interpolate_(g,d.s,h,e.s)):f.s=(d.s+c.s)/2;a.geom.transLeq(b,c)||(k=b,b=c,c=k);a.geom.transLeq(d,e)||(k=d,d=e,e=k);a.geom.transLeq(b,d)||(k=b,b=d,d=k,k=c,c=e,e=k);a.geom.transLeq(d,c)?a.geom.transLeq(c,e)?(g=
a.geom.transEval(b,d,c),h=a.geom.transEval(d,c,e),0>g+h&&(g=-g,h=-h),f.t=a.geom.interpolate_(g,d.t,h,c.t)):(g=a.geom.transSign(b,d,c),h=-a.geom.transSign(b,e,c),0>g+h&&(g=-g,h=-h),f.t=a.geom.interpolate_(g,d.t,h,e.t)):f.t=(d.t+c.t)/2},a.mesh={},a.mesh.makeEdge=function(b){var c=a.mesh.makeEdgePair_(b.eHead);return a.mesh.makeVertex_(c,b.vHead),a.mesh.makeVertex_(c.sym,b.vHead),a.mesh.makeFace_(c,b.fHead),c},a.mesh.meshSplice=function(b,c){var d=!1,e=!1;b!==c&&(c.org!==b.org&&(e=!0,a.mesh.killVertex_(c.org,
b.org)),c.lFace!==b.lFace&&(d=!0,a.mesh.killFace_(c.lFace,b.lFace)),a.mesh.splice_(c,b),e||(a.mesh.makeVertex_(c,b.org),b.org.anEdge=b),d||(a.mesh.makeFace_(c,b.lFace),b.lFace.anEdge=b))},a.mesh.deleteEdge=function(b){var c=b.sym,d=!1;b.lFace!==b.rFace()&&(d=!0,a.mesh.killFace_(b.lFace,b.rFace()));b.oNext===b?a.mesh.killVertex_(b.org,null):(b.rFace().anEdge=b.oPrev(),b.org.anEdge=b.oNext,a.mesh.splice_(b,b.oPrev()),d||a.mesh.makeFace_(b,b.lFace));c.oNext===c?(a.mesh.killVertex_(c.org,null),a.mesh.killFace_(c.lFace,
null)):(b.lFace.anEdge=c.oPrev(),c.org.anEdge=c.oNext,a.mesh.splice_(c,c.oPrev()));a.mesh.killEdge_(b)},a.mesh.addEdgeVertex=function(b){var c=a.mesh.makeEdgePair_(b),d=c.sym;return a.mesh.splice_(c,b.lNext),c.org=b.dst(),a.mesh.makeVertex_(d,c.org),c.lFace=d.lFace=b.lFace,c},a.mesh.splitEdge=function(b){var c=a.mesh.addEdgeVertex(b).sym;return a.mesh.splice_(b.sym,b.sym.oPrev()),a.mesh.splice_(b.sym,c),b.sym.org=c.org,c.dst().anEdge=c.sym,c.sym.lFace=b.rFace(),c.winding=b.winding,c.sym.winding=b.sym.winding,
c},a.mesh.connect=function(b,c){var d=!1,e=a.mesh.makeEdgePair_(b),f=e.sym;return c.lFace!==b.lFace&&(d=!0,a.mesh.killFace_(c.lFace,b.lFace)),a.mesh.splice_(e,b.lNext),a.mesh.splice_(f,c),e.org=b.dst(),f.org=c.org,e.lFace=f.lFace=b.lFace,b.lFace.anEdge=f,d||a.mesh.makeFace_(e,b.lFace),e},a.mesh.zapFace=function(b){var c,d=b.anEdge,e=d.lNext;do if(c=e,e=c.lNext,c.lFace=null,null===c.rFace()){c.oNext===c?a.mesh.killVertex_(c.org,null):(c.org.anEdge=c.oNext,a.mesh.splice_(c,c.oPrev()));var f=c.sym;f.oNext===
f?a.mesh.killVertex_(f.org,null):(f.org.anEdge=f.oNext,a.mesh.splice_(f,f.oPrev()));a.mesh.killEdge_(c)}while(c!==d);c=b.prev;b=b.next;b.prev=c;c.next=b},a.mesh.meshUnion=function(b,a){var c=b.fHead,e=b.vHead,f=b.eHead,g=a.fHead,h=a.vHead;a=a.eHead;return g.next!==g&&(c.prev.next=g.next,g.next.prev=c.prev,g.prev.next=c,c.prev=g.prev),h.next!==h&&(e.prev.next=h.next,h.next.prev=e.prev,h.prev.next=e,e.prev=h.prev),a.next!==a&&(f.sym.next.sym.next=a.next,a.next.sym.next=f.sym.next,a.sym.next.sym.next=
f,f.sym.next=a.sym.next),b},a.mesh.deleteMesh=function(b){},a.mesh.makeEdgePair_=function(b){var c=new a.GluHalfEdge,d=new a.GluHalfEdge,e=b.sym.next;return d.next=e,e.sym.next=c,c.next=b,b.sym.next=d,c.sym=d,c.oNext=c,c.lNext=d,d.sym=c,d.oNext=d,d.lNext=c,c},a.mesh.splice_=function(b,a){var c=b.oNext,e=a.oNext;c.sym.lNext=a;e.sym.lNext=b;b.oNext=e;a.oNext=c},a.mesh.makeVertex_=function(b,c){var d=c.prev,e=new a.GluVertex(c,d);d.next=e;c.prev=e;c=e.anEdge=b;do c.org=e,c=c.oNext;while(c!==b)},a.mesh.makeFace_=
function(b,c){var d=c.prev,e=new a.GluFace(c,d);d.next=e;c.prev=e;e.anEdge=b;e.inside=c.inside;c=b;do c.lFace=e,c=c.lNext;while(c!==b)},a.mesh.killEdge_=function(b){var a=b.next;b=b.sym.next;a.sym.next=b;b.sym.next=a},a.mesh.killVertex_=function(b,a){var c=b.anEdge,e=c;do e.org=a,e=e.oNext;while(e!==c);a=b.prev;b=b.next;b.prev=a;a.next=b},a.mesh.killFace_=function(b,a){var c=b.anEdge,e=c;do e.lFace=a,e=e.lNext;while(e!==c);a=b.prev;b=b.next;b.prev=a;a.next=b},a.normal={},a.normal.S_UNIT_X_=1,a.normal.S_UNIT_Y_=
0,a.normal.projectPolygon=function(b,c,d,e){var f=!1,g=[c,d,e];0===c&&0===d&&0===e&&(a.normal.computeNormal_(b,g),f=!0);d=a.normal.longAxis_(g);c=b.mesh.vHead;if(a.TRUE_PROJECT){a.normal.normalize_(g);e=[0,0,0];var h=[0,0,0];e[d]=0;e[(d+1)%3]=a.normal.S_UNIT_X_;e[(d+2)%3]=a.normal.S_UNIT_Y_;d=a.normal.dot_(e,g);e[0]-=d*g[0];e[1]-=d*g[1];e[2]-=d*g[2];a.normal.normalize_(e);h[0]=g[1]*e[2]-g[2]*e[1];h[1]=g[2]*e[0]-g[0]*e[2];h[2]=g[0]*e[1]-g[1]*e[0];a.normal.normalize_(h);for(g=c.next;g!==c;g=g.next)g.s=
a.normal.dot_(g.coords,e),g.t=a.normal.dot_(g.coords,h)}else for(e=(d+1)%3,h=(d+2)%3,d=0<g[d]?1:-1,g=c.next;g!==c;g=g.next)g.s=g.coords[e],g.t=d*g.coords[h];f&&a.normal.checkOrientation_(b)},a.normal.dot_=function(b,a){return b[0]*a[0]+b[1]*a[1]+b[2]*a[2]},a.normal.normalize_=function(b){var c=b[0]*b[0]+b[1]*b[1]+b[2]*b[2];a.assert(0<c);c=Math.sqrt(c);b[0]/=c;b[1]/=c;b[2]/=c},a.normal.longAxis_=function(b){var a=0;return Math.abs(b[1])>Math.abs(b[0])&&(a=1),Math.abs(b[2])>Math.abs(b[a])&&(a=2),a},
a.normal.computeNormal_=function(b,c){var d,e=[-2*a.GLU_TESS_MAX_COORD,-2*a.GLU_TESS_MAX_COORD,-2*a.GLU_TESS_MAX_COORD],f=[2*a.GLU_TESS_MAX_COORD,2*a.GLU_TESS_MAX_COORD,2*a.GLU_TESS_MAX_COORD],g=[],h=[];b=b.mesh.vHead;for(d=b.next;d!==b;d=d.next)for(var k=0;3>k;++k){var l=d.coords[k];l<f[k]&&(f[k]=l,h[k]=d);l>e[k]&&(e[k]=l,g[k]=d)}d=0;if(e[1]-f[1]>e[0]-f[0]&&(d=1),e[2]-f[2]>e[d]-f[d]&&(d=2),f[d]>=e[d])return c[0]=0,c[1]=0,void(c[2]=1);e=0;f=h[d];g=g[d];h=[0,0,0];f=[f.coords[0]-g.coords[0],f.coords[1]-
g.coords[1],f.coords[2]-g.coords[2]];k=[0,0,0];for(d=b.next;d!==b;d=d.next)k[0]=d.coords[0]-g.coords[0],k[1]=d.coords[1]-g.coords[1],k[2]=d.coords[2]-g.coords[2],h[0]=f[1]*k[2]-f[2]*k[1],h[1]=f[2]*k[0]-f[0]*k[2],h[2]=f[0]*k[1]-f[1]*k[0],l=h[0]*h[0]+h[1]*h[1]+h[2]*h[2],l>e&&(e=l,c[0]=h[0],c[1]=h[1],c[2]=h[2]);0>=e&&(c[0]=c[1]=c[2]=0,c[a.normal.longAxis_(f)]=1)},a.normal.checkOrientation_=function(b){for(var a=0,d=b.mesh.fHead,e=d.next;e!==d;e=e.next){var f=e.anEdge;if(!(0>=f.winding)){do a+=(f.org.s-
f.dst().s)*(f.org.t+f.dst().t),f=f.lNext;while(f!==e.anEdge)}}if(0>a)for(b=b.mesh.vHead,a=b.next;a!==b;a=a.next)a.t=-a.t},a.render={},a.render.renderMesh=function(b,c,d){for(var e=!1,f=-1,g=c.fHead.prev;g!==c.fHead;g=g.prev)if(g.inside){e||(b.callBeginCallback(a.primitiveType.GL_TRIANGLES),e=!0);var h=g.anEdge;a.assert(h.lNext.lNext.lNext===h,"renderMesh called with non-triangulated mesh");do{if(d){var k=h.rFace().inside?0:1;f!==k&&(f=k,b.callEdgeFlagCallback(!!f))}b.callVertexCallback(h.org.data);
h=h.lNext}while(h!==g.anEdge)}e&&b.callEndCallback()},a.render.renderBoundary=function(b,c){for(var d=c.fHead.next;d!==c.fHead;d=d.next)if(d.inside){b.callBeginCallback(a.primitiveType.GL_LINE_LOOP);var e=d.anEdge;do b.callVertexCallback(e.org.data),e=e.lNext;while(e!==d.anEdge);b.callEndCallback()}},a.sweep={},a.sweep.SENTINEL_COORD_=4*a.GLU_TESS_MAX_COORD,a.sweep.TOLERANCE_NONZERO_=!1,a.sweep.computeInterior=function(b){b.fatalError=!1;a.sweep.removeDegenerateEdges_(b);a.sweep.initPriorityQ_(b);
a.sweep.initEdgeDict_(b);for(var c;null!==(c=b.pq.extractMin());){for(;;){var d=b.pq.minimum();if(null===d||!a.geom.vertEq(d,c))break;d=b.pq.extractMin();a.sweep.spliceMergeVertices_(b,c.anEdge,d.anEdge)}a.sweep.sweepEvent_(b,c)}c=b.dict.getMin().getKey();b.event=c.eUp.org;a.sweep.doneEdgeDict_(b);a.sweep.donePriorityQ_(b);a.sweep.removeDegenerateFaces_(b.mesh);b.mesh.checkMesh()},a.sweep.addWinding_=function(a,c){a.winding+=c.winding;a.sym.winding+=c.sym.winding},a.sweep.edgeLeq_=function(b,c,d){b=
b.event;c=c.eUp;d=d.eUp;return c.dst()===b?d.dst()===b?a.geom.vertLeq(c.org,d.org)?0>=a.geom.edgeSign(d.dst(),c.org,d.org):0<=a.geom.edgeSign(c.dst(),d.org,c.org):0>=a.geom.edgeSign(d.dst(),b,d.org):d.dst()===b?0<=a.geom.edgeSign(c.dst(),b,c.org):a.geom.edgeEval(c.dst(),b,c.org)>=a.geom.edgeEval(d.dst(),b,d.org)},a.sweep.deleteRegion_=function(b,c){c.fixUpperEdge&&a.assert(0===c.eUp.winding);c.eUp.activeRegion=null;b.dict.deleteNode(c.nodeUp);c.nodeUp=null},a.sweep.fixUpperEdge_=function(b,c){a.assert(b.fixUpperEdge);
a.mesh.deleteEdge(b.eUp);b.fixUpperEdge=!1;b.eUp=c;c.activeRegion=b},a.sweep.topLeftRegion_=function(b){var c=b.eUp.org;do b=b.regionAbove();while(b.eUp.org===c);b.fixUpperEdge&&(c=a.mesh.connect(b.regionBelow().eUp.sym,b.eUp.lNext),a.sweep.fixUpperEdge_(b,c),b=b.regionAbove());return b},a.sweep.topRightRegion_=function(a){var b=a.eUp.dst();do a=a.regionAbove();while(a.eUp.dst()===b);return a},a.sweep.addRegionBelow_=function(b,c,d){var e=new a.ActiveRegion;return e.eUp=d,e.nodeUp=b.dict.insertBefore(c.nodeUp,
e),d.activeRegion=e,e},a.sweep.isWindingInside_=function(b,c){switch(b.windingRule){case a.windingRule.GLU_TESS_WINDING_ODD:return 0!=(1&c);case a.windingRule.GLU_TESS_WINDING_NONZERO:return 0!==c;case a.windingRule.GLU_TESS_WINDING_POSITIVE:return 0<c;case a.windingRule.GLU_TESS_WINDING_NEGATIVE:return 0>c;case a.windingRule.GLU_TESS_WINDING_ABS_GEQ_TWO:return 2<=c||-2>=c}return a.assert(!1),!1},a.sweep.computeWinding_=function(b,c){c.windingNumber=c.regionAbove().windingNumber+c.eUp.winding;c.inside=
a.sweep.isWindingInside_(b,c.windingNumber)},a.sweep.finishRegion_=function(b,c){var d=c.eUp,e=d.lFace;e.inside=c.inside;e.anEdge=d;a.sweep.deleteRegion_(b,c)},a.sweep.finishLeftRegions_=function(b,c,d){var e=c;for(c=c.eUp;e!==d;){e.fixUpperEdge=!1;var f=e.regionBelow(),g=f.eUp;if(g.org!==c.org){if(!f.fixUpperEdge){a.sweep.finishRegion_(b,e);break}g=a.mesh.connect(c.lPrev(),g.sym);a.sweep.fixUpperEdge_(f,g)}c.oNext!==g&&(a.mesh.meshSplice(g.oPrev(),g),a.mesh.meshSplice(c,g));a.sweep.finishRegion_(b,
e);c=f.eUp;e=f}return c},a.sweep.addRightEdges_=function(b,c,d,e,f,g){var h=!0;do a.assert(a.geom.vertLeq(d.org,d.dst())),a.sweep.addRegionBelow_(b,c,d.sym),d=d.oNext;while(d!==e);null===f&&(f=c.regionBelow().eUp.rPrev());for(var k;k=c.regionBelow(),d=k.eUp.sym,d.org===f.org;)d.oNext!==f&&(a.mesh.meshSplice(d.oPrev(),d),a.mesh.meshSplice(f.oPrev(),d)),k.windingNumber=c.windingNumber-d.winding,k.inside=a.sweep.isWindingInside_(b,k.windingNumber),c.dirty=!0,!h&&a.sweep.checkForRightSplice_(b,c)&&(a.sweep.addWinding_(d,
f),a.sweep.deleteRegion_(b,c),a.mesh.deleteEdge(f)),h=!1,c=k,f=d;c.dirty=!0;a.assert(c.windingNumber-d.winding===k.windingNumber);g&&a.sweep.walkDirtyRegions_(b,c)},a.sweep.callCombine_=function(b,c,d,e,f){var g=[c.coords[0],c.coords[1],c.coords[2]];c.data=null;c.data=b.callCombineCallback(g,d,e);null===c.data&&(f?b.fatalError||(b.callErrorCallback(a.errorType.GLU_TESS_NEED_COMBINE_CALLBACK),b.fatalError=!0):c.data=d[0])},a.sweep.spliceMergeVertices_=function(b,c,d){var e=[null,null,null,null];e[0]=
c.org.data;e[1]=d.org.data;a.sweep.callCombine_(b,c.org,e,[.5,.5,0,0],!1);a.mesh.meshSplice(c,d)},a.sweep.vertexWeights_=function(b,c,d,e,f){var g=a.geom.vertL1dist(c,b),h=a.geom.vertL1dist(d,b),k=f+1;e[f]=.5*h/(g+h);e[k]=.5*g/(g+h);b.coords[0]+=e[f]*c.coords[0]+e[k]*d.coords[0];b.coords[1]+=e[f]*c.coords[1]+e[k]*d.coords[1];b.coords[2]+=e[f]*c.coords[2]+e[k]*d.coords[2]},a.sweep.getIntersectData_=function(b,c,d,e,f,g){var h=[0,0,0,0],k=[d.data,e.data,f.data,g.data];c.coords[0]=c.coords[1]=c.coords[2]=
0;a.sweep.vertexWeights_(c,d,e,h,0);a.sweep.vertexWeights_(c,f,g,h,2);a.sweep.callCombine_(b,c,k,h,!0)},a.sweep.checkForRightSplice_=function(b,c){var d=c.regionBelow(),e=c.eUp,f=d.eUp;if(a.geom.vertLeq(e.org,f.org)){if(0<a.geom.edgeSign(f.dst(),e.org,f.org))return!1;a.geom.vertEq(e.org,f.org)?e.org!==f.org&&(b.pq.remove(e.org.pqHandle),a.sweep.spliceMergeVertices_(b,f.oPrev(),e)):(a.mesh.splitEdge(f.sym),a.mesh.meshSplice(e,f.oPrev()),c.dirty=d.dirty=!0)}else{if(0>a.geom.edgeSign(e.dst(),f.org,e.org))return!1;
c.regionAbove().dirty=c.dirty=!0;a.mesh.splitEdge(e.sym);a.mesh.meshSplice(f.oPrev(),e)}return!0},a.sweep.checkForLeftSplice_=function(b,c){var d;d=c.regionBelow();b=c.eUp;var e=d.eUp;if(a.assert(!a.geom.vertEq(b.dst(),e.dst())),a.geom.vertLeq(b.dst(),e.dst())){if(0>a.geom.edgeSign(b.dst(),e.dst(),b.org))return!1;c.regionAbove().dirty=c.dirty=!0;d=a.mesh.splitEdge(b);a.mesh.meshSplice(e.sym,d);d.lFace.inside=c.inside}else{if(0<a.geom.edgeSign(e.dst(),b.dst(),e.org))return!1;c.dirty=d.dirty=!0;d=a.mesh.splitEdge(e);
a.mesh.meshSplice(b.lNext,e.sym);d.rFace().inside=c.inside}return!0},a.sweep.checkForIntersect_=function(b,c){var d=c.regionBelow(),e=c.eUp,f=d.eUp,g=e.org,h=f.org,k=e.dst(),l=f.dst(),m=new a.GluVertex;if((a.assert(!a.geom.vertEq(l,k)),a.assert(0>=a.geom.edgeSign(k,b.event,g)),a.assert(0<=a.geom.edgeSign(l,b.event,h)),a.assert(g!==b.event&&h!==b.event),a.assert(!c.fixUpperEdge&&!d.fixUpperEdge),g===h)||Math.min(g.t,k.t)>Math.max(h.t,l.t))return!1;if(a.geom.vertLeq(g,h)){if(0<a.geom.edgeSign(l,g,h))return!1}else if(0>
a.geom.edgeSign(k,h,g))return!1;a.geom.edgeIntersect(k,g,l,h,m);a.assert(Math.min(g.t,k.t)<=m.t);a.assert(m.t<=Math.max(h.t,l.t));a.assert(Math.min(l.s,k.s)<=m.s);a.assert(m.s<=Math.max(h.s,g.s));a.geom.vertLeq(m,b.event)&&(m.s=b.event.s,m.t=b.event.t);var n=a.geom.vertLeq(g,h)?g:h;return(a.geom.vertLeq(n,m)&&(m.s=n.s,m.t=n.t),a.geom.vertEq(m,g)||a.geom.vertEq(m,h))?(a.sweep.checkForRightSplice_(b,c),!1):!a.geom.vertEq(k,b.event)&&0<=a.geom.edgeSign(k,b.event,m)||!a.geom.vertEq(l,b.event)&&0>=a.geom.edgeSign(l,
b.event,m)?l===b.event?(a.mesh.splitEdge(e.sym),a.mesh.meshSplice(f.sym,e),c=a.sweep.topLeftRegion_(c),e=c.regionBelow().eUp,a.sweep.finishLeftRegions_(b,c.regionBelow(),d),a.sweep.addRightEdges_(b,c,e.oPrev(),e,e,!0),!0):k===b.event?(a.mesh.splitEdge(f.sym),a.mesh.meshSplice(e.lNext,f.oPrev()),d=c,c=a.sweep.topRightRegion_(c),g=c.regionBelow().eUp.rPrev(),d.eUp=f.oPrev(),f=a.sweep.finishLeftRegions_(b,d,null),a.sweep.addRightEdges_(b,c,f.oNext,e.rPrev(),g,!0),!0):(0<=a.geom.edgeSign(k,b.event,m)&&
(c.regionAbove().dirty=c.dirty=!0,a.mesh.splitEdge(e.sym),e.org.s=b.event.s,e.org.t=b.event.t),0>=a.geom.edgeSign(l,b.event,m)&&(c.dirty=d.dirty=!0,a.mesh.splitEdge(f.sym),f.org.s=b.event.s,f.org.t=b.event.t),!1):(a.mesh.splitEdge(e.sym),a.mesh.splitEdge(f.sym),a.mesh.meshSplice(f.oPrev(),e),e.org.s=m.s,e.org.t=m.t,e.org.pqHandle=b.pq.insert(e.org),a.sweep.getIntersectData_(b,e.org,g,k,h,l),c.regionAbove().dirty=c.dirty=d.dirty=!0,!1)},a.sweep.walkDirtyRegions_=function(b,c){for(var d=c.regionBelow();;){for(;d.dirty;)c=
d,d=d.regionBelow();if(!c.dirty&&(d=c,null===(c=c.regionAbove())||!c.dirty))break;c.dirty=!1;var e=c.eUp,f=d.eUp;if(e.dst()!==f.dst()&&a.sweep.checkForLeftSplice_(b,c)&&(d.fixUpperEdge?(a.sweep.deleteRegion_(b,d),a.mesh.deleteEdge(f),d=c.regionBelow(),f=d.eUp):c.fixUpperEdge&&(a.sweep.deleteRegion_(b,c),a.mesh.deleteEdge(e),c=d.regionAbove(),e=c.eUp)),e.org!==f.org)if(e.dst()===f.dst()||c.fixUpperEdge||d.fixUpperEdge||e.dst()!==b.event&&f.dst()!==b.event)a.sweep.checkForRightSplice_(b,c);else if(a.sweep.checkForIntersect_(b,
c))break;e.org===f.org&&e.dst()===f.dst()&&(a.sweep.addWinding_(f,e),a.sweep.deleteRegion_(b,c),a.mesh.deleteEdge(e),c=d.regionAbove())}},a.sweep.connectRightVertex_=function(b,c,d){var e=d.oNext,f=c.regionBelow(),g=c.eUp,h=f.eUp,k=!1;if(g.dst()!==h.dst()&&a.sweep.checkForIntersect_(b,c),a.geom.vertEq(g.org,b.event)&&(a.mesh.meshSplice(e.oPrev(),g),c=a.sweep.topLeftRegion_(c),e=c.regionBelow().eUp,a.sweep.finishLeftRegions_(b,c.regionBelow(),f),k=!0),a.geom.vertEq(h.org,b.event)&&(a.mesh.meshSplice(d,
h.oPrev()),d=a.sweep.finishLeftRegions_(b,f,null),k=!0),k)return void a.sweep.addRightEdges_(b,c,d.oNext,e,e,!0);e=a.geom.vertLeq(h.org,g.org)?h.oPrev():g;e=a.mesh.connect(d.lPrev(),e);a.sweep.addRightEdges_(b,c,e,e.oNext,e.oNext,!1);e.sym.activeRegion.fixUpperEdge=!0;a.sweep.walkDirtyRegions_(b,c)},a.sweep.connectLeftDegenerate_=function(b,c,d){var e=c.eUp;if(a.geom.vertEq(e.org,d))return a.assert(a.sweep.TOLERANCE_NONZERO_),void(a.sweep.TOLERANCE_NONZERO_&&a.sweep.spliceMergeVertices_(b,e,d.anEdge));
if(!a.geom.vertEq(e.dst(),d))return a.mesh.splitEdge(e.sym),c.fixUpperEdge&&(a.mesh.deleteEdge(e.oNext),c.fixUpperEdge=!1),a.mesh.meshSplice(d.anEdge,e),void a.sweep.sweepEvent_(b,d);if(a.assert(a.sweep.TOLERANCE_NONZERO_),a.sweep.TOLERANCE_NONZERO_){c=a.sweep.topRightRegion_(c);var e=c.regionBelow(),f=e.eUp.sym,g=f.oNext,h=g;e.fixUpperEdge&&(a.assert(g!==f),a.sweep.deleteRegion_(b,e),a.mesh.deleteEdge(f),f=g.oPrev());a.mesh.meshSplice(d.anEdge,f);a.geom.edgeGoesLeft(g)||(g=null);a.sweep.addRightEdges_(b,
c,f.oNext,h,g,!0)}},a.sweep.connectLeftVertex_=function(b,c){var d=new a.ActiveRegion;d.eUp=c.anEdge.sym;var d=b.dict.search(d).getKey(),e=d.regionBelow(),f=d.eUp,g=e.eUp;if(0===a.geom.edgeSign(f.dst(),c,f.org))return void a.sweep.connectLeftDegenerate_(b,d,c);e=a.geom.vertLeq(g.dst(),f.dst())?d:e;d.inside||e.fixUpperEdge?(f=e===d?a.mesh.connect(c.anEdge.sym,f.lNext):a.mesh.connect(g.dNext(),c.anEdge).sym,e.fixUpperEdge?a.sweep.fixUpperEdge_(e,f):a.sweep.computeWinding_(b,a.sweep.addRegionBelow_(b,
d,f)),a.sweep.sweepEvent_(b,c)):a.sweep.addRightEdges_(b,d,c.anEdge,c.anEdge,null,!0)},a.sweep.sweepEvent_=function(b,c){b.event=c;for(var d=c.anEdge;null===d.activeRegion;)if((d=d.oNext)===c.anEdge)return void a.sweep.connectLeftVertex_(b,c);c=a.sweep.topLeftRegion_(d.activeRegion);var e=c.regionBelow(),d=e.eUp,e=a.sweep.finishLeftRegions_(b,e,null);e.oNext===d?a.sweep.connectRightVertex_(b,c,e):a.sweep.addRightEdges_(b,c,e.oNext,d,d,!0)},a.sweep.addSentinel_=function(b,c){var d=new a.ActiveRegion,
e=a.mesh.makeEdge(b.mesh);e.org.s=a.sweep.SENTINEL_COORD_;e.org.t=c;e.dst().s=-a.sweep.SENTINEL_COORD_;e.dst().t=c;b.event=e.dst();d.eUp=e;d.windingNumber=0;d.inside=!1;d.fixUpperEdge=!1;d.sentinel=!0;d.dirty=!1;d.nodeUp=b.dict.insert(d)},a.sweep.initEdgeDict_=function(b){b.dict=new a.Dict(b,a.sweep.edgeLeq_);a.sweep.addSentinel_(b,-a.sweep.SENTINEL_COORD_);a.sweep.addSentinel_(b,a.sweep.SENTINEL_COORD_)},a.sweep.doneEdgeDict_=function(b){for(var c,d=0;null!==(c=b.dict.getMin().getKey());)c.sentinel||
(a.assert(c.fixUpperEdge),a.assert(1==++d)),a.assert(0===c.windingNumber),a.sweep.deleteRegion_(b,c);b.dict=null},a.sweep.removeDegenerateEdges_=function(b){for(var c,d=b.mesh.eHead,e=d.next;e!==d;e=c){c=e.next;var f=e.lNext;a.geom.vertEq(e.org,e.dst())&&e.lNext.lNext!==e&&(a.sweep.spliceMergeVertices_(b,f,e),a.mesh.deleteEdge(e),e=f,f=e.lNext);f.lNext===e&&(f!==e&&(f!==c&&f!==c.sym||(c=c.next),a.mesh.deleteEdge(f)),e!==c&&e!==c.sym||(c=c.next),a.mesh.deleteEdge(e))}},a.sweep.initPriorityQ_=function(b){var c=
new a.PriorityQ;b.pq=c;var d=b.mesh.vHead;for(b=d.next;b!==d;b=b.next)b.pqHandle=c.insert(b);c.init()},a.sweep.donePriorityQ_=function(a){a.pq.deleteQ();a.pq=null},a.sweep.removeDegenerateFaces_=function(b){for(var c,d=b.fHead.next;d!==b.fHead;d=c)c=d.next,d=d.anEdge,a.assert(d.lNext!==d),d.lNext.lNext===d&&(a.sweep.addWinding_(d.oNext,d),a.mesh.deleteEdge(d))},a.tessmono={},a.tessmono.tessellateMonoRegion_=function(b){b=b.anEdge;for(a.assert(b.lNext!==b&&b.lNext.lNext!==b);a.geom.vertLeq(b.dst(),
b.org);b=b.lPrev());for(;a.geom.vertLeq(b.org,b.dst());b=b.lNext);for(var c,d=b.lPrev();b.lNext!==d;)if(a.geom.vertLeq(b.dst(),d.org)){for(;d.lNext!==b&&(a.geom.edgeGoesLeft(d.lNext)||0>=a.geom.edgeSign(d.org,d.dst(),d.lNext.dst()));)c=a.mesh.connect(d.lNext,d),d=c.sym;d=d.lPrev()}else{for(;d.lNext!==b&&(a.geom.edgeGoesRight(b.lPrev())||0<=a.geom.edgeSign(b.dst(),b.org,b.lPrev().org));)c=a.mesh.connect(b,b.lPrev()),b=c.sym;b=b.lNext}for(a.assert(d.lNext!==b);d.lNext.lNext!==b;)c=a.mesh.connect(d.lNext,
d),d=c.sym},a.tessmono.tessellateInterior=function(b){for(var c,d=b.fHead.next;d!==b.fHead;d=c)c=d.next,d.inside&&a.tessmono.tessellateMonoRegion_(d)},a.tessmono.discardExterior=function(b){for(var c,d=b.fHead.next;d!==b.fHead;d=c)c=d.next,d.inside||a.mesh.zapFace(d)},a.tessmono.setWindingNumber=function(b,c,d){for(var e,f=b.eHead.next;f!==b.eHead;f=e)e=f.next,f.rFace().inside!==f.lFace.inside?f.winding=f.lFace.inside?c:-c:d?a.mesh.deleteEdge(f):f.winding=0},a.Dict=function(b,c){this.head_=new a.DictNode;
this.frame_=b;this.leq_=c},a.Dict.prototype.deleteDict_=function(){},a.Dict.prototype.insertBefore=function(b,c){do b=b.prev;while(null!==b.key&&!this.leq_(this.frame_,b.key,c));c=new a.DictNode(c,b.next,b);return b.next.prev=c,b.next=c,c},a.Dict.prototype.insert=function(a){return this.insertBefore(this.head_,a)},a.Dict.prototype.deleteNode=function(a){a.next.prev=a.prev;a.prev.next=a.next},a.Dict.prototype.search=function(a){var b=this.head_;do b=b.next;while(null!==b.key&&!this.leq_(this.frame_,
a,b.key));return b},a.Dict.prototype.getMin=function(){return this.head_.next},a.Dict.prototype.getMax=function(){return this.head_.prev},a.DictNode=function(a,c,d){this.key=a||null;this.next=c||this;this.prev=d||this},a.DictNode.prototype.getKey=function(){return this.key},a.DictNode.prototype.getSuccessor=function(){return this.next},a.DictNode.prototype.getPredecessor=function(){return this.prev},a.GluTesselator=function(){this.state_=a.GluTesselator.tessState_.T_DORMANT;this.errorCallback_=this.mesh=
this.lastEdge_=null;this.normal_=[0,0,0];this.windingRule=a.windingRule.GLU_TESS_WINDING_ODD;this.fatalError=!1;this.combineCallback_=this.event=this.pq=this.dict=null;this.boundaryOnly_=!1;this.polygonData_=this.meshCallback_=this.endCallback_=this.vertexCallback_=this.edgeFlagCallback_=this.beginCallback_=null},a.GluTesselator.tessState_={T_DORMANT:0,T_IN_POLYGON:1,T_IN_CONTOUR:2},a.GluTesselator.prototype.gluDeleteTess=function(){this.requireState_(a.GluTesselator.tessState_.T_DORMANT)},a.GluTesselator.prototype.gluTessProperty=
function(b,c){switch(b){case a.gluEnum.GLU_TESS_TOLERANCE:return;case a.gluEnum.GLU_TESS_WINDING_RULE:switch(c){case a.windingRule.GLU_TESS_WINDING_ODD:case a.windingRule.GLU_TESS_WINDING_NONZERO:case a.windingRule.GLU_TESS_WINDING_POSITIVE:case a.windingRule.GLU_TESS_WINDING_NEGATIVE:case a.windingRule.GLU_TESS_WINDING_ABS_GEQ_TWO:return void(this.windingRule=c)}break;case a.gluEnum.GLU_TESS_BOUNDARY_ONLY:return void(this.boundaryOnly_=!!c);default:return void this.callErrorCallback(a.gluEnum.GLU_INVALID_ENUM)}this.callErrorCallback(a.gluEnum.GLU_INVALID_VALUE)},
a.GluTesselator.prototype.gluGetTessProperty=function(b){switch(b){case a.gluEnum.GLU_TESS_TOLERANCE:return 0;case a.gluEnum.GLU_TESS_WINDING_RULE:return b=this.windingRule,a.assert(b===a.windingRule.GLU_TESS_WINDING_ODD||b===a.windingRule.GLU_TESS_WINDING_NONZERO||b===a.windingRule.GLU_TESS_WINDING_POSITIVE||b===a.windingRule.GLU_TESS_WINDING_NEGATIVE||b===a.windingRule.GLU_TESS_WINDING_ABS_GEQ_TWO),b;case a.gluEnum.GLU_TESS_BOUNDARY_ONLY:return a.assert(!0===this.boundaryOnly_||!1===this.boundaryOnly_),
this.boundaryOnly_;default:this.callErrorCallback(a.gluEnum.GLU_INVALID_ENUM)}return!1},a.GluTesselator.prototype.gluTessNormal=function(a,c,d){this.normal_[0]=a;this.normal_[1]=c;this.normal_[2]=d},a.GluTesselator.prototype.gluTessCallback=function(b,c){c=c||null;switch(b){case a.gluEnum.GLU_TESS_BEGIN:case a.gluEnum.GLU_TESS_BEGIN_DATA:return void(this.beginCallback_=c);case a.gluEnum.GLU_TESS_EDGE_FLAG:case a.gluEnum.GLU_TESS_EDGE_FLAG_DATA:return void(this.edgeFlagCallback_=c);case a.gluEnum.GLU_TESS_VERTEX:case a.gluEnum.GLU_TESS_VERTEX_DATA:return void(this.vertexCallback_=
c);case a.gluEnum.GLU_TESS_END:case a.gluEnum.GLU_TESS_END_DATA:return void(this.endCallback_=c);case a.gluEnum.GLU_TESS_ERROR:case a.gluEnum.GLU_TESS_ERROR_DATA:return void(this.errorCallback_=c);case a.gluEnum.GLU_TESS_COMBINE:case a.gluEnum.GLU_TESS_COMBINE_DATA:return void(this.combineCallback_=c);case a.gluEnum.GLU_TESS_MESH:return void(this.meshCallback_=c);default:return void this.callErrorCallback(a.gluEnum.GLU_INVALID_ENUM)}},a.GluTesselator.prototype.gluTessVertex=function(b,c){var d=!1,
e=[0,0,0];this.requireState_(a.GluTesselator.tessState_.T_IN_CONTOUR);for(var f=0;3>f;++f){var g=b[f];g<-a.GLU_TESS_MAX_COORD&&(g=-a.GLU_TESS_MAX_COORD,d=!0);g>a.GLU_TESS_MAX_COORD&&(g=a.GLU_TESS_MAX_COORD,d=!0);e[f]=g}d&&this.callErrorCallback(a.errorType.GLU_TESS_COORD_TOO_LARGE);this.addVertex_(e,c)},a.GluTesselator.prototype.gluTessBeginPolygon=function(b){this.requireState_(a.GluTesselator.tessState_.T_DORMANT);this.state_=a.GluTesselator.tessState_.T_IN_POLYGON;this.mesh=new a.GluMesh;this.polygonData_=
b},a.GluTesselator.prototype.gluTessBeginContour=function(){this.requireState_(a.GluTesselator.tessState_.T_IN_POLYGON);this.state_=a.GluTesselator.tessState_.T_IN_CONTOUR;this.lastEdge_=null},a.GluTesselator.prototype.gluTessEndContour=function(){this.requireState_(a.GluTesselator.tessState_.T_IN_CONTOUR);this.state_=a.GluTesselator.tessState_.T_IN_POLYGON},a.GluTesselator.prototype.gluTessEndPolygon=function(){if(this.requireState_(a.GluTesselator.tessState_.T_IN_POLYGON),this.state_=a.GluTesselator.tessState_.T_DORMANT,
a.normal.projectPolygon(this,this.normal_[0],this.normal_[1],this.normal_[2]),a.sweep.computeInterior(this),!this.fatalError){var b=this.mesh;if(this.boundaryOnly_?a.tessmono.setWindingNumber(b,1,!0):a.tessmono.tessellateInterior(b),this.mesh.checkMesh(),this.beginCallback_||this.endCallback_||this.vertexCallback_||this.edgeFlagCallback_)this.boundaryOnly_?a.render.renderBoundary(this,this.mesh):a.render.renderMesh(this,this.mesh,!!this.edgeFlagCallback_);if(this.meshCallback_)return a.tessmono.discardExterior(this.mesh),
this.meshCallback_(this.mesh),this.mesh=null,void(this.polygonData_=null)}a.mesh.deleteMesh(this.mesh);this.mesh=this.polygonData_=null},a.GluTesselator.prototype.requireState_=function(a){this.state_!==a&&this.gotoState_(a)},a.GluTesselator.prototype.gotoState_=function(b){for(;this.state_!==b;)if(this.state_<b)switch(this.state_){case a.GluTesselator.tessState_.T_DORMANT:this.callErrorCallback(a.errorType.GLU_TESS_MISSING_BEGIN_POLYGON);this.gluTessBeginPolygon(null);break;case a.GluTesselator.tessState_.T_IN_POLYGON:this.callErrorCallback(a.errorType.GLU_TESS_MISSING_BEGIN_CONTOUR),
this.gluTessBeginContour()}else switch(this.state_){case a.GluTesselator.tessState_.T_IN_CONTOUR:this.callErrorCallback(a.errorType.GLU_TESS_MISSING_END_CONTOUR);this.gluTessEndContour();break;case a.GluTesselator.tessState_.T_IN_POLYGON:this.callErrorCallback(a.errorType.GLU_TESS_MISSING_END_POLYGON),this.gluTessEndPolygon()}},a.GluTesselator.prototype.addVertex_=function(b,c){var d=this.lastEdge_;null===d?(d=a.mesh.makeEdge(this.mesh),a.mesh.meshSplice(d,d.sym)):(a.mesh.splitEdge(d),d=d.lNext);
d.org.data=c;d.org.coords[0]=b[0];d.org.coords[1]=b[1];d.org.coords[2]=b[2];d.winding=1;d.sym.winding=-1;this.lastEdge_=d},a.GluTesselator.prototype.callBeginCallback=function(a){this.beginCallback_&&this.beginCallback_(a,this.polygonData_)},a.GluTesselator.prototype.callVertexCallback=function(a){this.vertexCallback_&&this.vertexCallback_(a,this.polygonData_)},a.GluTesselator.prototype.callEdgeFlagCallback=function(a){this.edgeFlagCallback_&&this.edgeFlagCallback_(a,this.polygonData_)},a.GluTesselator.prototype.callEndCallback=
function(){this.endCallback_&&this.endCallback_(this.polygonData_)},a.GluTesselator.prototype.callCombineCallback=function(a,c,d){return this.combineCallback_?this.combineCallback_(a,c,d,this.polygonData_)||null:null},a.GluTesselator.prototype.callErrorCallback=function(a){this.errorCallback_&&this.errorCallback_(a,this.polygonData_)},a.GluFace=function(a,c){this.next=a||this;this.prev=c||this;this.anEdge=null;this.inside=!1},a.GluHalfEdge=function(a){this.next=a||this;this.activeRegion=this.lFace=
this.org=this.lNext=this.oNext=this.sym=null;this.winding=0},a.GluHalfEdge.prototype.rFace=function(){return this.sym.lFace},a.GluHalfEdge.prototype.dst=function(){return this.sym.org},a.GluHalfEdge.prototype.oPrev=function(){return this.sym.lNext},a.GluHalfEdge.prototype.lPrev=function(){return this.oNext.sym},a.GluHalfEdge.prototype.dPrev=function(){return this.lNext.sym},a.GluHalfEdge.prototype.rPrev=function(){return this.sym.oNext},a.GluHalfEdge.prototype.dNext=function(){return this.rPrev().sym},
a.GluHalfEdge.prototype.rNext=function(){return this.oPrev().sym},a.GluMesh=function(){this.vHead=new a.GluVertex;this.fHead=new a.GluFace;this.eHead=new a.GluHalfEdge;this.eHeadSym=new a.GluHalfEdge;this.eHead.sym=this.eHeadSym;this.eHeadSym.sym=this.eHead},a.GluMesh.prototype.checkMesh=function(){if(a.DEBUG){var b,c,d=this.fHead,e=this.vHead,f=this.eHead;for(b=b=d;(c=b.next)!==d;b=c){a.assert(c.prev===b);b=c.anEdge;do a.assert(b.sym!==b),a.assert(b.sym.sym===b),a.assert(b.lNext.oNext.sym===b),a.assert(b.oNext.sym.lNext===
b),a.assert(b.lFace===c),b=b.lNext;while(b!==c.anEdge)}a.assert(c.prev===b&&null===c.anEdge);for(b=b=e;(c=b.next)!==e;b=c){a.assert(c.prev===b);b=c.anEdge;do a.assert(b.sym!==b),a.assert(b.sym.sym===b),a.assert(b.lNext.oNext.sym===b),a.assert(b.oNext.sym.lNext===b),a.assert(b.org===c),b=b.oNext;while(b!==c.anEdge)}a.assert(c.prev===b&&null===c.anEdge&&null===c.data);for(e=e=f;(b=e.next)!==f;e=b)a.assert(b.sym.next===e.sym),a.assert(b.sym!==b),a.assert(b.sym.sym===b),a.assert(null!==b.org),a.assert(null!==
b.dst()),a.assert(b.lNext.oNext.sym===b),a.assert(b.oNext.sym.lNext===b);a.assert(b.sym.next===e.sym&&b.sym===this.eHeadSym&&b.sym.sym===b&&null===b.org&&null===b.dst()&&null===b.lFace&&null===b.rFace())}},a.GluVertex=function(a,c){this.next=a||this;this.prev=c||this;this.data=this.anEdge=null;this.coords=[0,0,0];this.pqHandle=this.t=this.s=0},a.PriorityQ=function(){this.verts_=[];this.order_=null;this.size_=0;this.initialized_=!1;this.heap_=new a.PriorityQHeap},a.PriorityQ.prototype.deleteQ=function(){this.verts_=
this.order_=this.heap_=null},a.PriorityQ.prototype.init=function(){this.order_=[];for(var b=0;b<this.size_;b++)this.order_[b]=b;b=function(b){return function(c,d){return a.geom.vertLeq(b[c],b[d])?1:-1}}(this.verts_);if(this.order_.sort(b),this.initialized_=!0,this.heap_.init(),a.DEBUG)for(var c=0+this.size_-1,b=0;b<c;++b)a.assert(a.geom.vertLeq(this.verts_[this.order_[b+1]],this.verts_[this.order_[b]]))},a.PriorityQ.prototype.insert=function(a){if(this.initialized_)return this.heap_.insert(a);var b=
this.size_++;return this.verts_[b]=a,-(b+1)},a.PriorityQ.prototype.extractMin=function(){if(0===this.size_)return this.heap_.extractMin();var b=this.verts_[this.order_[this.size_-1]];if(!this.heap_.isEmpty()){var c=this.heap_.minimum();if(a.geom.vertLeq(c,b))return this.heap_.extractMin()}do--this.size_;while(0<this.size_&&null===this.verts_[this.order_[this.size_-1]]);return b},a.PriorityQ.prototype.minimum=function(){if(0===this.size_)return this.heap_.minimum();var b=this.verts_[this.order_[this.size_-
1]];if(!this.heap_.isEmpty()){var c=this.heap_.minimum();if(a.geom.vertLeq(c,b))return c}return b},a.PriorityQ.prototype.remove=function(b){if(0<=b)return void this.heap_.remove(b);b=-(b+1);a.assert(b<this.verts_.length&&null!==this.verts_[b]);for(this.verts_[b]=null;0<this.size_&&null===this.verts_[this.order_[this.size_-1]];)--this.size_},a.PriorityQHeap=function(){this.heap_=a.PriorityQHeap.reallocNumeric_([0],a.PriorityQHeap.INIT_SIZE_+1);this.verts_=[null,null];this.handles_=[0,0];this.size_=
0;this.max_=a.PriorityQHeap.INIT_SIZE_;this.freeList_=0;this.initialized_=!1;this.heap_[1]=1},a.PriorityQHeap.INIT_SIZE_=32,a.PriorityQHeap.reallocNumeric_=function(a,c){for(var b=Array(c),e=0;e<a.length;e++)b[e]=a[e];for(;e<c;e++)b[e]=0;return b},a.PriorityQHeap.prototype.init=function(){for(var a=this.size_;1<=a;--a)this.floatDown_(a);this.initialized_=!0},a.PriorityQHeap.prototype.insert=function(b){var c=++this.size_;2*c>this.max_&&(this.max_*=2,this.handles_=a.PriorityQHeap.reallocNumeric_(this.handles_,
this.max_+1));var d;return 0===this.freeList_?d=c:(d=this.freeList_,this.freeList_=this.handles_[this.freeList_]),this.verts_[d]=b,this.handles_[d]=c,this.heap_[c]=d,this.initialized_&&this.floatUp_(c),d},a.PriorityQHeap.prototype.isEmpty=function(){return 0===this.size_},a.PriorityQHeap.prototype.minimum=function(){return this.verts_[this.heap_[1]]},a.PriorityQHeap.prototype.extractMin=function(){var a=this.heap_,c=this.verts_,d=this.handles_,e=a[1],f=c[e];return 0<this.size_&&(a[1]=a[this.size_],
d[a[1]]=1,c[e]=null,d[e]=this.freeList_,this.freeList_=e,0<--this.size_&&this.floatDown_(1)),f},a.PriorityQHeap.prototype.remove=function(b){var c=this.heap_,d=this.verts_,e=this.handles_;a.assert(1<=b&&b<=this.max_&&null!==d[b]);var f=e[b];if(c[f]=c[this.size_],e[c[f]]=f,f<=--this.size_)1>=f?this.floatDown_(f):a.geom.vertLeq(d[c[f>>1]],d[c[f]])?this.floatDown_(f):this.floatUp_(f);d[b]=null;e[b]=this.freeList_;this.freeList_=b},a.PriorityQHeap.prototype.floatDown_=function(b){for(var c=this.heap_,
d=this.verts_,e=this.handles_,f=c[b];;){var g=b<<1;g<this.size_&&a.geom.vertLeq(d[c[g+1]],d[c[g]])&&(g+=1);a.assert(g<=this.max_);var h=c[g];if(g>this.size_||a.geom.vertLeq(d[f],d[h]))return c[b]=f,void(e[f]=b);c[b]=h;e[h]=b;b=g}},a.PriorityQHeap.prototype.floatUp_=function(b){for(var c=this.heap_,d=this.verts_,e=this.handles_,f=c[b];;){var g=b>>1,h=c[g];if(0===g||a.geom.vertLeq(d[h],d[f]))return c[b]=f,void(e[f]=b);c[b]=h;e[h]=b;b=g}},a.ActiveRegion=function(){this.nodeUp=this.eUp=null;this.windingNumber=
0;this.fixUpperEdge=this.dirty=this.sentinel=this.inside=!1},a.ActiveRegion.prototype.regionBelow=function(){return this.nodeUp.getPredecessor().getKey()},a.ActiveRegion.prototype.regionAbove=function(){return this.nodeUp.getSuccessor().getKey()},a});