define({
  "styleText": "Pyyhkäisytyökalun tyyppi",
  "vertical": "Pystypalkki",
  "horizontal": "Vaakapalkki",
  "scope": "Kiikari",
  "placement": "Suunta",
  "showLeftSide": "Näytä pyyhkäistyt karttatasot vasemmalla puolella",
  "showRigthSide": "Näytä pyyhkäistyt karttatasot oikealla puolella",
  "showUpSide": "Näytä pyyhkäistyt karttatasot yläpuolella",
  "showDownSide": "Näytä pyyhkäistyt karttatasot alapuolella",
  "barColor": "Pylvään väri",
  "swipeMode": "Pyyhkäisytila",
  "singleLayer": "Yksi karttataso",
  "MultipleLayers": "Useita karttatasoja",
  "allowToSwipe": "Salli pyyhkäisy",
  "layer": "Karttataso",
  "swipeByDefault": "Käytä pyyhkäisyä oletusarvoisesti",
  "defaultLayerMustBeVisible": "oletuskarttatason on oltava näkyvissä",
  "noDefaultLayer": "Määritä, että pyyhkäisyä käytetään karttatasoissa oletusarvoisesti",
  "defaultLayerHolder": "Valitse napsauttamalla",
  "selectLayers": "Valitse karttatasot",
  "layerText": "Oletusarvoiset pyyhkäisytasot",
  "spyglassText": "Valitse karttataso, joka näkyy kiikarissa oletusarvoisesti.",
  "layerHint": "Huomautus: jos karttataso on piirtojärjestyksessä ylempänä olevien karttatasojen peitossa, pyyhkäisyt eivät vaikuta mitenkään.",
  "isZoom": "Tarkenna pyyhkäisytasoon",
  "isZooms": "Tarkenna pyyhkäisytasoihin",
  "layersAvailable": "Pyyhkäistävissä olevat karttatasot",
  "hidePanel": "Piilota karttatason valintapaneeli, kun pienoisohjelma avautuu"
});