//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/Deferred dojo/promise/all jimu/portalUrlUtils jimu/WidgetManager jimu/PanelManager esri/lang esri/graphicsUtils ./NlsStrings dijit/Dialog".split(" "),function(v,m,h,u,w,x,y,z,k,B,A,n){var d={},p=function(a){a=document.getElementById(window.chkSelectableLayer+a);null!=a&&1==a.checked&&(a.checked=!1)},q=function(a,b,c,f){if(0<b.length){var e=new XMLHttpRequest;e.overrideMimeType("application/json");e.open("GET",b.pop(),!0);e.onreadystatechange=
function(){if(4==e.readyState&&"200"==e.status)if(a(e.responseText,c))switch(f){case "eaDescription":if("eaDescription"in d){var g=new n({title:layer.name,style:"width: 300px"});g.show();g.set("content",d.eaDescription)}else alert("Map description is not available for this layer");break;case "eaMetadata":"eaMetadata"in d?"eaScale"in d&&"NATIONAL"==d.eaScale?(metaDataID=window.nationalMetadataDic[d.eaMetadata],window.open(window.matadata+"?uuid\x3d%7B"+metaDataID+"%7D")):window.communitySelected==
window.strAllCommunity?window.open(window.communityMetadataDic[d.eaMetadata][window.communitySelected]):(metaDataID=window.communityMetadataDic[d.eaMetadata][window.communitySelected],window.open(window.matadata+"?uuid\x3d%7B"+metaDataID+"%7D")):alert("Metadata is not available for this layer");break;case "eaDfsLink":"eaDfsLink"in d?window.open(window.dataFactSheet+d.eaDfsLink):alert("Data fact sheet is not available for this layer")}else{switch(f){case "eaDescription":0!=b.length||"eaDescription"in
d||alert("Map description is not available for this layer");break;case "eaMetadata":0!=b.length||"eaMetadata"in d||alert("Metadata is not available for this layer");break;case "eaDfsLink":0!=b.length||"eaDescription"in d||alert("Data fact sheet is not available for this layer")}q(r,b,c,f)}};e.send(null)}},r=function(a,b){var c="",f=!1;a=JSON.parse(a).layers.layer;index=0;for(len=a.length;index<len;++index)if(layer=a[index],layer.hasOwnProperty("eaID")&&(0<=b.indexOf("http")&&layer.hasOwnProperty("eaLyrNum")&&
(c=layer.url+"/"+layer.eaLyrNum.toString()),null!=c&&""!=c&&"/"==c.substr(c.length-1)&&(c=c.substr(0,c.length-2)),b===layer.eaID.toString()||b==c)){f=!0;layer.hasOwnProperty("eaDescription")&&(d.eaDescription=layer.eaDescription);layer.hasOwnProperty("eaMetadata")&&(d.eaMetadata=layer.eaMetadata);layer.hasOwnProperty("eaDfsLink")&&(d.eaDfsLink=layer.eaDfsLink);layer.hasOwnProperty("eaScale")&&(d.eaScale=layer.eaScale);break}return f},t=function(a,b,c){if("eaDescription"==c){if("added_ClimateChange"==
a){a=new n({title:"Change analysis layer",style:"width: 300px"});a.show();a.set("content","This map depicts the change in the selected climate variable (max temp, min temp, precipitation, potential evapotranspiration) between two time periods based on the selected RCP scenario (2.6, 4.0, 6.5 8.5) and the selected season.");return}if(a==window.timeSeriesLayerId){a=new n({title:"Time series data",style:"width: 300px"});a.show();a.set("content","This map depicts historical or forecasted time series data for the selected climate variable (max temp, min temp, precipitation, potential evapotranspiration) based on the selected RCP scenario (2.6, 4.0, 6.5 8.5) and the selected season.");
return}}d={};var f=a.replace(window.layerIdPrefix,"").replace(window.layerIdPBSPrefix,"").replace(window.layerIdBndrPrefix,""),e=[];0<=a.indexOf(window.layerIdPrefix)?(e.push("widgets/SimpleSearchFilter/config_layer.json"),q(r,e,f,c)):(e.push("widgets/SimpleSearchFilter/config_layer.json"),q(r,e,b,c))},l=v([],{_candidateMenuItems:null,_displayItems:null,_layerInfo:null,_layerType:null,_appConfig:null,constructor:function(a,b,c,f){this.nls=A.value;this._layerInfo=a;this._layerType=c;d={};this.layerListWidget=
f;this._initCandidateMenuItems();this._initDisplayItems(b)},_getATagLabel:function(){var a,b;this._layerInfo.isItemLayer&&this._layerInfo.isItemLayer();a=this._layerInfo.getUrl();(b=this._layerInfo.isItemLayer())?(a=this._getItemDetailsPageUrl(b)||a,b=this.nls.itemShowItemDetails):!a||"CSVLayer"!==this._layerType&&"KMLLayer"!==this._layerType?(a=a&&"WMSLayer"===this._layerType?a+(-1<a.indexOf("?")?"\x26":"?")+"SERVICE\x3dWMS\x26REQUEST\x3dGetCapabilities":a&&"WFSLayer"===this._layerType?a+(-1<a.indexOf("?")?
"\x26":"?")+"SERVICE\x3dWFS\x26REQUEST\x3dGetCapabilities":a?a:"",b=this.nls.itemDesc):b=this.nls.itemDownload;this._ATagLabelUrl=a;return'\x3ca class\x3d"menu-item-description" target\x3d"_blank" href\x3d"'+a+'"\x3e'+b+"\x3c/a\x3e"},_getItemDetailsPageUrl:function(a){var b="";return b=x.getItemDetailsPageUrl(a.portalUrl,a.itemId)},_initCandidateMenuItems:function(){this._candidateMenuItems=[{key:"separator",label:""},{key:"empty",label:this.nls.empty},{key:"mapDescription",label:this.nls.itemMapDescription},
{key:"dataFactSheet",label:this.nls.itemDataFactSheet},{key:"metadataDownload",label:this.nls.itemMetadataDownload},{key:"changeSymbology",label:this.nls.itemChangeSymbology},{key:"remove",label:this.nls.itemRemove},{key:"movetotop",label:this.nls.itemMovetoTop},{key:"transparency",label:this.nls.itemTransparency},{key:"table",label:this.nls.itemToAttributeTable},{key:"controlPopup",label:this.nls.removePopup},{key:"controlLabels",label:this.nls.showLabels},{key:"url",label:this._getATagLabel()}]},
_initDisplayItems:function(a){this._displayItems=[];m.forEach(a,function(a){m.forEach(this._candidateMenuItems,function(b){a.key===b.key&&(this._displayItems.push(h.clone(b)),a.onClick&&(this._displayItem.onClick=a.onClick))},this)},this)},_isSupportedByAT:function(){return!0},_isSupportedByAT_bk:function(a,b){a=a.config;a=0===a.layerInfos.length?!0:m.some(a.layerInfos,function(a){if(a.id===this._layerInfo.id&&a.show)return!0},this);return b.isSupportedLayer&&b.isSupportQuery&&!b.otherReasonCanNotSupport&&
a?!0:!1},getDeniedItems:function(){var a=new u,b=[];this.layerListWidget.layerListView.isFirstDisplayedLayerInfo(this._layerInfo)&&b.push({key:"moveup",denyType:"disable"});this.layerListWidget.layerListView.isLastDisplayedLayerInfo(this._layerInfo)&&b.push({key:"movedown",denyType:"disable"});this._ATagLabelUrl||b.push({key:"url",denyType:"disable"});this._layerInfo.canShowLabel()||b.push({key:"controlLabels",denyType:"hidden"});this._layerInfo.originOperLayer.featureCollection?b.push({key:"setVisibilityRange",
denyType:"hidden"}):this._layerInfo.isRootLayer()||"esri.layers.ArcGISTiledMapServiceLayer"!==this._layerInfo.getRootLayerInfo().layerObject.declaredClass?this._layerInfo.isRootLayer()||"esri.layers.ArcGISDynamicMapServiceLayer"!==this._layerInfo.getRootLayerInfo().layerObject.declaredClass||this._layerInfo.getRootLayerInfo().layerObject.supportsDynamicLayers?this._layerInfo.isRootLayer()&&"esri.layers.ArcGISImageServiceLayer"===this._layerInfo.getRootLayerInfo().layerObject.declaredClass&&b.push({key:"changeSymbology",
denyType:"hidden"}):b.push({key:"setVisibilityRange",denyType:"disable"}):b.push({key:"setVisibilityRange",denyType:"hidden"});var c=this._layerInfo.loadInfoTemplate(),d=this._layerInfo.getSupportTableInfo();w({infoTemplate:c,supportTableInfo:d}).then(h.hitch(this,function(c){c.infoTemplate||b.push({key:"controlPopup",denyType:"disable"});c=c.supportTableInfo;var d=this.layerListWidget.appConfig.getConfigElementsByName("AttributeTable")[0];d&&d.visible?this._isSupportedByAT(d,c)||(this._layerInfo.parentLayerInfo&&
this._layerInfo.parentLayerInfo.isMapNotesLayerInfo()?b.push({key:"table",denyType:"hidden"}):b.push({key:"table",denyType:"disable"})):b.push({key:"table",denyType:"hidden"});a.resolve(b)}),function(){a.resolve(b)});return a},getDisplayItems:function(){return this._displayItems},onPopupMenuClick:function(a){var b={closeMenu:!0};switch(a.itemKey){case "zoomto":this._onItemZoomToClick(a);case "mapDescription":this._onItemMapDescriptionClick(a);break;case "dataFactSheet":this._onItemDataFactSheetClick(a);
break;case "metadataDownload":this._onItemMetadataDownloadClick(a);break;case "changeSymbology":this._onItemChangeSymbologyClick(a);break;case "remove":this._onItemRemoveClick(a);break;case "movetotop":this._onMoveToTopClick(a);break;case "moveup":this._onMoveUpItemClick(a);break;case "movedown":this._onMoveDownItemClick(a);break;case "table":this._onTableItemClick(a);break;case "transparencyChanged":this._onTransparencyChanged(a);b.closeMenu=!1;break;case "controlPopup":this._onControlPopup();break;
case "controlLabels":this._onControlLabels()}return b},_onItemZoomToClick:function(a){this._layerInfo.zoomTo()},_onMoveToTopClick:function(a){lyr=this._layerInfo.map.getLayer(this._layerInfo.id);""!=window.topLayerID&&(a=document.getElementById(window.layerTitlePrefix+window.topLayerID),null!=a&&(a.style["font-weight"]="400"));window.topLayerID=this._layerInfo.id;document.getElementById(window.layerTitlePrefix+this._layerInfo.id).style["font-weight"]="bold";isImageLayer=isTiledLayer=isDynamicLayer=
!1;if(lyr){for(ii in window.dynamicLayerNumber)if(eachDynamicLyrId=window.layerIdPrefix+window.dynamicLayerNumber[ii],eachDynamicLyrId==this._layerInfo.id&&(isDynamicLayer=!0),eachDynamicLyr=this._layerInfo.map.getLayer(eachDynamicLyrId))dynamicLayerElem=document.getElementById("map_"+eachDynamicLyrId),null!=dynamicLayerElem&&(dynamicLayerElem.style.zIndex="0");for(ii in window.tiledLayerNumber)if(eachTiledLyrId=window.layerIdPrefix+window.tiledLayerNumber[ii],eachTiledLyrId==this._layerInfo.id&&
(isTiledLayer=!0),eachTiledLyr=this._layerInfo.map.getLayer(eachTiledLyrId))tiledLayerElem=document.getElementById("map_"+eachTiledLyrId),null!=tiledLayerElem&&(tiledLayerElem.style.zIndex="0");for(ii in window.imageLayerNumber)if(eachImageLyrId=window.layerIdPrefix+window.imageLayerNumber[ii],eachImageLyrId==this._layerInfo.id&&(isImageLayer=!0),eachImageLyr=this._layerInfo.map.getLayer(eachImageLyrId))imageLayerElem=document.getElementById("map_"+eachImageLyrId),null!=imageLayerElem&&(imageLayerElem.style.zIndex=
"0");1==isDynamicLayer||1==isTiledLayer||1==isImageLayer?document.getElementById("map_"+this._layerInfo.id).style.zIndex="1":this._layerInfo.map.reorderLayer(lyr,300)}(lyrTiled=this._layerInfo.map.getLayer(window.layerIdTiledPrefix+this._layerInfo.id.replace(window.layerIdPrefix,"")))&&this._layerInfo.map.reorderLayer(lyrTiled,300)},_isValidExtent:function(a){var b=!1;k.isDefined(a)&&k.isDefined(a.xmin)&&isFinite(a.xmin)&&k.isDefined(a.ymin)&&isFinite(a.ymin)&&k.isDefined(a.xmax)&&isFinite(a.xmax)&&
k.isDefined(a.ymax)&&isFinite(a.ymax)&&(b=!0);return b},_onMoveUpItemClick:function(a){this._layerInfo.isFirst||a.layerListView.moveUpLayer(this._layerInfo)},_onMoveDownItemClick:function(a){this._layerInfo.isLast||a.layerListView.moveDownLayer(this._layerInfo)},_onTableItemClick:function(a){this._layerInfo.getSupportTableInfo().then(h.hitch(this,function(b){var c=this.layerListWidget.appConfig.getConfigElementsByName("AttributeTable")[0];this._isSupportedByAT(c,b)&&(b=y.getInstance(),b.triggerWidgetOpen(c.id).then(h.hitch(this,
function(){a.layerListWidget.publishData({target:"AttributeTable",layer:this._layerInfo})})))}))},_onItemMapDescriptionClick:function(a){layerId=this._layerInfo.id;t(layerId,this._layerInfo.layerObject.url,"eaDescription")},_onItemDataFactSheetClick:function(a){layerId=this._layerInfo.id;t(layerId,this._layerInfo.layerObject.url,"eaDfsLink")},_onItemChangeSymbologyClick:function(a){layerId=this._layerInfo.id;-1<layerId.indexOf(window.layerIdPrefix)&&(lyrTiled=this._layerInfo.map.getLayer(layerId.replace(window.layerIdPrefix,
window.layerIdTiledPrefix)))&&lyrTiled.setVisibility(!1);-1<layerId.indexOf(window.layerIdPBSPrefix)&&(lyrTiledPBS=this._layerInfo.map.getLayer(layerId.replace(window.layerIdPBSPrefix,window.layerIdTiledPrefix)))&&lyrTiledPBS.setVisibility(!1);this.layerListWidget.publishData({message:layerId},!0);a=this.layerListWidget.appConfig.getConfigElementsByName("DynamicSymbology");var b=z.getInstance();a[0].visible&&b.closePanel(a[0].id+"_panel");b.showPanel(a[0]);console.log("Open Dynamic Symbology")},_onItemMetadataDownloadClick:function(a){layerId=
this._layerInfo.id;t(layerId,this._layerInfo.layerObject.url,"eaMetadata")},_onItemRemoveClick:function(a){layerId=this._layerInfo.id;if(lyr=this._layerInfo.map.getLayer(layerId))this._layerInfo.map.removeLayer(lyr),p(layerId.replace(window.layerIdPrefix,"")),p(layerId.replace(window.layerIdBndrPrefix,"")),p(layerId.replace(window.layerIdPBSPrefix,""));(lyrTiled=this._layerInfo.map.getLayer(layerId.replace(window.layerIdPrefix,window.layerIdTiledPrefix)))&&this._layerInfo.map.removeLayer(lyrTiled)},
_onTransparencyChanged:function(a){this._layerInfo.setOpacity(1-a.extraData.newTransValue);layerId=this._layerInfo.id;(lyrTiled=this._layerInfo.map.getLayer(layerId.replace(window.layerIdPrefix,window.layerIdTiledPrefix)))&&lyrTiled.setOpacity(1-a.extraData.newTransValue)},_onControlPopup:function(a){this._layerInfo.controlPopupInfo.enablePopup?this._layerInfo.disablePopup():this._layerInfo.enablePopup();this._layerInfo.map.infoWindow.hide()},_onControlLabels:function(a){this._layerInfo.canShowLabel()&&
(this._layerInfo.isShowLabels()?this._layerInfo.hideLabels():this._layerInfo.showLabels())}});l.create=function(a,b){var c=new u,d=a.isRootLayer(),e={RootLayer:[{key:"zoomto"},{key:"transparency"},{key:"setVisibilityRange"},{key:"movetotop"},{key:"remove"},{key:"separator"},{key:"mapDescription"},{key:"dataFactSheet"},{key:"url"},{key:"metadataDownload"}],RootLayerAndNonFeatureLayer:[{key:"transparency"},{key:"movetotop"},{key:"remove"},{key:"separator"},{key:"mapDescription"},{key:"dataFactSheet"},
{key:"url"},{key:"metadataDownload"},{key:"separator"},{key:"table"}],RootLayerAndFeatureLayer:[{key:"zoomto"},{key:"transparency"},{key:"setVisibilityRange"},{key:"movetotop"},{key:"changeSymbology"},{key:"remove"},{key:"separator"},{key:"mapDescription"},{key:"dataFactSheet"},{key:"url"},{key:"metadataDownload"},{key:"separator"},{key:"controlLabels"},{key:"separator"},{key:"table"}],FeatureLayer:[{key:"setVisibilityRange"},{key:"separator"},{key:"controlPopup"},{key:"separator"},{key:"table"},
{key:"separator"},{key:"url"}],SublayerOfDynamicMapserviceLayer:[{key:"setVisibilityRange"},{key:"separator"},{key:"url"}],GroupLayer:[{key:"setVisibilityRange"},{key:"separator"},{key:"url"}],Table:[{key:"table"},{key:"separator"},{key:"url"}],BasemapLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"url"}],"default":[{key:"url",onClick:null}]};a.getLayerType().then(h.hitch(this,function(g){var f="",f=a.isBasemap()&&a.isRootLayer()?"BasemapLayer":a.isBasemap()?"default":!d||"FeatureLayer"!==
g&&"CSVLayer"!==g&&"ArcGISImageServiceLayer"!==g&&"StreamLayer"!==g&&"ArcGISImageServiceVectorLayer"!==g?d?"RootLayer":"FeatureLayer"===g||"CSVLayer"===g?"FeatureLayer":a.isLeaf()&&a.getRootLayerInfo()&&a.getRootLayerInfo().layerObject&&"esri.layers.ArcGISDynamicMapServiceLayer"===a.getRootLayerInfo().layerObject.declaredClass?"SublayerOfDynamicMapserviceLayer":"GroupLayer"===g?"GroupLayer":"Table"===g?"Table":"default":"RootLayerAndFeatureLayer";c.resolve(new l(a,e[f],g,b))}),h.hitch(this,function(){c.resolve(new l(a,
[{key:"empty"}]))}));return c};return l});