define({
  "showLayerLabels": "Mostra els noms de les capes",
  "autoPlay": "Reprodueix el control lliscant automàticament",
  "loopPlay": "Repeteix el temps de manera contínua",
  "dateAndTimeFormat": "Format de data i hora",
  "mapDefault": "Per defecte del mapa",
  "custom": "Personalitzat",
  "formatInstruction": "Instrucció de format",
  "playback": "posició de reproducció desada amb el mapa",
  "MMMMYYYY": "Juliol de 2015",
  "MMMYYYY": "Jul. 2015",
  "MMMMDYYYY": "21 de juliol de 2015",
  "dddMMMDDYYYY": "Dimarts 21 de juliol de 2015",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00 am",
  "dddMMMDDhmma": "Dimarts 21 de juliol, 8:00 am",
  "sliderSetting": "Configuració del control lliscant",
  "autoRefresh": "Actualitza el control lliscant cada",
  "timeSetting": "Configuració de temps",
  "useWebMapSetting": "Respecta la configuració de temps al mapa web",
  "useConfigureSetting": "Configura el temps",
  "timeSettingBtn": "configuració",
  "calenderError": "L'hora d'inici ha de ser menor que l'hora de finalització.",
  "timeSpan": "Interval de temps",
  "startTime": "Hora d'inici",
  "endTime": "Hora de finalització",
  "unit": "Unitat",
  "timeDisplay": "Visualització del temps",
  "displayDataIn": "Mostra dades en",
  "interval": "Interval",
  "displayAllData": "Mostra de totes les dades de manera progressiva",
  "layerTimeExtent": "Habilita l'animació temporal",
  "layerTableCol1": "Capa",
  "layerTableCol2": "Extensió de temps",
  "timeTo": "a",
  "calender": "Calendari",
  "time": "Hora",
  "now": "Ara",
  "today": "Avui",
  "maximum": "Tot seleccionat com a màxim",
  "minimum": "Tot seleccionat com a mínim"
});