define({
  "styleText": "Slinkimo įrankio tipas",
  "vertical": "Vertikali juosta",
  "horizontal": "Horizontali juosta",
  "scope": "Didinamasis stiklas",
  "placement": "Kryptis",
  "showLeftSide": "Slankiklio sluoksnius rodyti kairėje pusėje",
  "showRigthSide": "Slankiklio sluoksnius rodyti dešinėje pusėje",
  "showUpSide": "Slankiklio sluoksnius rodyti viršuje",
  "showDownSide": "Slankiklio sluoksnius rodyti apačioje",
  "barColor": "Stulpelio spalva",
  "swipeMode": "Keitiklio režimas",
  "singleLayer": "Vienas sluoksnis",
  "MultipleLayers": "Keli sluoksniai",
  "allowToSwipe": "Leisti keisti",
  "layer": "Sluoksnis",
  "swipeByDefault": "Keisti pagal numatytuosius parametrus",
  "defaultLayerMustBeVisible": "numatytasis sluoksnis turi būti matomas",
  "noDefaultLayer": "Nustatykite sluoksnius, kurie bus keičiami pagal numatytuosius nustatymus",
  "defaultLayerHolder": "Spustelėkite, norėdami pasirinkti",
  "selectLayers": "Pasirinkite sluoksnius",
  "layerText": "Numatytasis (-ieji) slankiklio sluoksnis (-iai)",
  "spyglassText": "Pasirinkite sluoksnį, kuris atsiras po didinamuoju stiklu pagal nutylėjimą.",
  "layerHint": "Pastaba: Jei sluoksnis paslėptas po aukščiau esančiais sluoksniais, keitiklis neturės jokio poveikio.",
  "isZoom": "Priartinti slenkamą sluoksnį",
  "isZooms": "Priartinti slenkamą sluoksnį (-ius)",
  "layersAvailable": "Galimi slinkti sluoksniai",
  "hidePanel": "Kai atidaromas valdiklis, slėpti sluoksnio pasirinkimo skiltį"
});