define({
  "showLayerLabels": "Zobrazit názvy vrstev",
  "autoPlay": "Spouštět posuvník automaticky",
  "loopPlay": "Nepřetržitá časová smyčka",
  "dateAndTimeFormat": "Formát data a času",
  "mapDefault": "Výchozí nastavení mapy",
  "custom": "Vlastní",
  "formatInstruction": "Instrukce formátu",
  "playback": "pozice přehrávání uložena v mapě",
  "MMMMYYYY": "Červenec 2015",
  "MMMYYYY": "Čvc 2015",
  "MMMMDYYYY": "Červenec 21,2015",
  "dddMMMDDYYYY": "Út 21. čvc, 2015",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00",
  "dddMMMDDhmma": "Út 21. července 8:00",
  "sliderSetting": "Nastavení posuvníku",
  "autoRefresh": "Obnovit posuvník každé",
  "timeSetting": "Časové nastavení dat",
  "useWebMapSetting": "Zohlednit nastavení času webové mapy",
  "useConfigureSetting": "Konfigurovat nastavení času",
  "timeSettingBtn": "nastavení",
  "calenderError": "Počáteční čas musí být menší než koncový čas.",
  "timeSpan": "Časový úsek",
  "startTime": "Čas začátku",
  "endTime": "Koncový čas",
  "unit": "Jednotky",
  "timeDisplay": "Zobrazení času",
  "displayDataIn": "Zobrazit data v",
  "interval": "Interval",
  "displayAllData": "Postupně zobrazit všechna data",
  "layerTimeExtent": "Povolit animaci času",
  "layerTableCol1": "Vrstva",
  "layerTableCol2": "Časový rozsah",
  "timeTo": "až",
  "calender": "Kalendář",
  "time": "Čas",
  "now": "Nyní",
  "today": "Dnes",
  "maximum": "Zvoleno maximum všeho",
  "minimum": "Zvoleno minimum všeho"
});