//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/query dojo/on dojo/json dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable ./SingleSearchEdit ./DefaultSearchSymEdit ./DefaultBufferEdit ./SpatialRelationshipsEdit ./GraphicalEdit ./DisableTabEdit ./ResultFormatEdit jimu/dijit/Message jimu/dijit/Popup dojo/keys dijit/form/NumberTextBox dijit/form/TextBox dijit/form/Select esri/request dojo/dom-attr".split(" "),function(l,b,k,f,x,e,y,m,n,
z,p,q,r,t,u,v,w,h,g,c,A,B,C,D,E){return l([n,m],{baseClass:"widget-esearch-setting",ds:null,layerUniqueCache:null,layerInfoCache:null,bufferDefaults:null,spatialrelationships:null,graphicalsearchoptions:null,disabledTabs:null,popup:null,popup2:null,popup3:null,popup4:null,popup5:null,popup6:null,popup7:null,popup8:null,popupSRedit:null,popupGOedit:null,popupDisableTabedit:null,defaultBufferedit:null,defaultSingleSearchedit:null,defaultSearchSymedit:null,popupformatedit:null,postCreate:function(){this.inherited(arguments);
this.layerUniqueCache={};this.layerInfoCache={};this._bindEvents();this.setConfig(this.config)},setConfig:function(a){setTimeout(function(){var a=dojo.query(".help-link");a[0].href="http://gis.calhouncounty.org/WAB/V2.5/widgets/eSearch/help/eSearch_Help.htm";f.setStyle(a[0],"display","block")},600);this.config=a;this.reset();this.config&&(this.graphicalsearchoptions=this.config.graphicalsearchoptions,this._initSearchesTable(),this.enablePopupsCbx.setValue(this.config.enablePopupsOnResultClick),this.disablePopupsCbx.setValue(this.config.disablePopups),
this.disableUVCacheCbx.setValue(this.config.disableuvcache),this.limit2MapExtCbx.setValue(this.config.limitsearch2mapextentchecked),this.exportSearchURLCbx.setValue(this.config.exportsearchurlchecked),a=this.config.hasOwnProperty("autozoomtoresults")&&!this.config.autozoomtoresults?!1:!0,this.autoZoomCbx.setValue(a),this.mouseOverGraphicsCbx.setValue(this.config.mouseovergraphics||!1),this.config.hasOwnProperty("disabledtabs")&&(this.disabledTabs=this.config.disabledtabs),this.config.initialView&&
this.selectInitialView.set("value",this.config.initialView),this.config.selectfilter?this.selectFilter.set("value",this.config.selectfilter):this.selectFilter.set("value","contains"),this.bufferDefaults=this.config.bufferDefaults,this.spatialrelationships=this.config.spatialrelationships)},getConfig:function(){var a={};a.layers=this._getAllLayers();a.initialView=this.selectInitialView.get("value");a.selectfilter=this.selectFilter.get("value");this.disabledTabs&&0<this.disabledTabs.length&&(a.disabledtabs=
this.disabledTabs);a.enablePopupsOnResultClick=this.enablePopupsCbx.getValue();a.disablePopups=this.disablePopupsCbx.getValue();a.disableuvcache=this.disableUVCacheCbx.getValue();a.exportsearchurlchecked=this.exportSearchURLCbx.getValue();a.limitsearch2mapextentchecked=this.limit2MapExtCbx.getValue();a.autozoomtoresults=this.autoZoomCbx.getValue();a.mouseovergraphics=this.mouseOverGraphicsCbx.getValue();a.bufferDefaults=this.bufferDefaults;a.spatialrelationships=this.spatialrelationships;a.graphicalsearchoptions=
this.graphicalsearchoptions;a.symbols={};this.config.symbols&&(a.symbols=b.mixin({},this.config.symbols));a.resultFormat=this.config.resultFormat;this.config=b.mixin({},a);return a},_getAllLayers:function(){var a=this.searchesTable._getNotEmptyRows();return k.map(a,b.hitch(this,function(a){return a.singleSearch}))},_onFormatEditOk:function(){this.config.resultFormat=this.popupformatedit.getConfig().format;this.popup8.close();this.popupState=""},_onFormatEditClose:function(){this.popup8=this.popupfromatedit=
null},_openFormatEdit:function(a){this.popupformatedit=new w({nls:this.nls,config:this.config||{}});this.popup8=new g({titleLabel:a,autoHeight:!0,content:this.popupformatedit,container:"main-page",width:540,buttons:[{label:this.nls.ok,key:c.ENTER,onClick:b.hitch(this,"_onFormatEditOk")},{label:this.nls.cancel,key:c.ESCAPE}],onClose:b.hitch(this,"_onFormatEditClose")});f.addClass(this.popup8.domNode,"widget-setting-format");this.popupformatedit.startup()},_onSREditOk:function(){var a=this.popupSRedit.getConfig();
if(0>a.length)new h({message:this.nls.warning});else{var b={};b.spatialrelationship=a;this.spatialrelationships=b;this.popup2.close()}},_onSREditClose:function(){this.popup2=this.popupSRedit=null},_openSREdit:function(a,d){this.popupSRedit=new t({nls:this.nls,config:d||{}});this.popup2=new g({titleLabel:a,autoHeight:!0,content:this.popupSRedit,container:"main-page",width:640,height:485,buttons:[{label:this.nls.ok,key:c.ENTER,onClick:b.hitch(this,"_onSREditOk")},{label:this.nls.cancel,key:c.ESCAPE}],
onClose:b.hitch(this,"_onSREditClose")});f.addClass(this.popup2.domNode,"widget-setting-popup");this.popupSRedit.startup()},_onGOEditOk:function(){var a=this.popupGOedit.getConfig();0>a.length?new h({message:this.nls.warning}):(this.graphicalsearchoptions=a,this.popup5.close())},_onGOEditClose:function(){this.popup5=this.popupGOedit=null},_openGOEdit:function(a,d){this.popupGOedit=new u({nls:this.nls,config:d||{}});this.popup5=new g({titleLabel:a,autoHeight:!0,content:this.popupGOedit,container:"main-page",
width:960,buttons:[{label:this.nls.ok,key:c.ENTER,onClick:b.hitch(this,"_onGOEditOk")},{label:this.nls.cancel,key:c.ESCAPE}],onClose:b.hitch(this,"_onGOEditClose")});f.addClass(this.popup5.domNode,"widget-setting-popup");this.popupGOedit.startup()},_onDTEditOk:function(){var a=this.popupDisableTabedit.getConfig();0>a.length?new h({message:this.nls.warning}):(this.disabledTabs=a,this.popup7.close())},_onDTEditClose:function(){this.popup7=this.popupDisableTabedit=null},_openDTEdit:function(a,d){this.popupDisableTabedit=
new v({nls:this.nls,config:d||{}});this.popup7=new g({titleLabel:a,autoHeight:!0,content:this.popupDisableTabedit,container:"main-page",width:640,buttons:[{label:this.nls.ok,key:c.ENTER,onClick:b.hitch(this,"_onDTEditOk")},{label:this.nls.cancel,key:c.ESCAPE}],onClose:b.hitch(this,"_onDTEditClose")});f.addClass(this.popup7.domNode,"widget-setting-popup");this.popupDisableTabedit.startup()},_onBufferEditOk:function(){var a=this.defaultBufferedit.getConfig();0>a.length?new h({message:this.nls.warning}):
(this.config.bufferDefaults=a,this.popup3.close())},_onBufferEditClose:function(){this.popup3=this.defaultBufferedit=null},_openBufferEdit:function(a,d){this.defaultBufferedit=new r({nls:this.nls,config:d||{}});this.popup3=new g({titleLabel:a,autoHeight:!0,content:this.defaultBufferedit,container:"main-page",height:525,buttons:[{label:this.nls.ok,key:c.ENTER,onClick:b.hitch(this,"_onBufferEditOk")},{label:this.nls.cancel,key:c.ESCAPE}],onClose:b.hitch(this,"_onBufferEditClose")});f.addClass(this.popup3.domNode,
"widget-setting-popup");this.defaultBufferedit.startup()},_onSymbolEditOk:function(){var a=this.defaultSearchSymedit.getConfig();0>a.length?new h({message:this.nls.warning}):(this.config.symbols=a,this.popup4.close())},_onSymbolEditClose:function(){this.popup4=this.defaultSearchSymedit=null},_openSymbolEdit:function(a,d){this.defaultSearchSymedit=new q({nls:this.nls,config:d||{},widget:this});this.popup4=new g({titleLabel:a,autoHeight:!0,content:this.defaultSearchSymedit,container:"main-page",buttons:[{label:this.nls.ok,
key:c.ENTER,onClick:b.hitch(this,"_onSymbolEditOk")},{label:this.nls.cancel,key:c.ESCAPE}],onClose:b.hitch(this,"_onSymbolEditClose")});f.addClass(this.popup4.domNode,"widget-setting-popup");this.defaultSearchSymedit.startup()},_onSingleSearchEditOk:function(){var a=this.defaultSingleSearchedit.getConfig();0>a.length?new h({message:this.nls.warning}):("ADD"===this.popupState?(this.searchesTable.editRow(this.defaultSingleSearchedit.tr,{name:a.name}),this.defaultSingleSearchedit.tr.singleSearch=a,this.popupState=
""):(this.searchesTable.editRow(this.defaultSingleSearchedit.tr,{name:a.name}),this.defaultSingleSearchedit.tr.singleSearch=a),this.popup6.close(),this.popupState="")},_onSingleSearchEditClose:function(){"ADD"===this.popupState&&this.searchesTable.deleteRow(this.defaultSingleSearchedit.tr);this.popup6=this.defaultSearchSymedit=null},_openSingleSearchEdit:function(a,d){this.defaultSingleSearchedit=new p({nls:this.nls,config:d.singleSearch||{},searchSetting:this,layerUniqueCache:this.layerUniqueCache,
layerInfoCache:this.layerInfoCache,tr:d,disableuvcache:this.config.disableuvcache,mainConfig:this.config});this.popup6=new g({titleLabel:a,autoHeight:!1,content:this.defaultSingleSearchedit,container:"main-page",buttons:[{label:this.nls.ok,key:c.ENTER,onClick:b.hitch(this,"_onSingleSearchEditOk")},{label:this.nls.cancel,key:c.ESCAPE}],onClose:b.hitch(this,"_onSingleSearchEditClose")});f.addClass(this.popup6.domNode,"widget-setting-popup");this.defaultSingleSearchedit.startup()},_need2ChkPopups:function(){this.disablePopupsCbx.getValue()?
(this.enablePopupsCbx.setValue(!1),this.mouseOverGraphicsCbx.setValue(!1),this.enablePopupsCbx.setStatus(!1),this.mouseOverGraphicsCbx.setStatus(!1)):(this.enablePopupsCbx.setStatus(!0),this.mouseOverGraphicsCbx.setStatus(!0))},_bindEvents:function(){this.disablePopupsCbx.onChange=b.hitch(this,this._need2ChkPopups);this.own(e(this.btnAddSearch,"click",b.hitch(this,function(){this.popupState="ADD";var a=this._createSingleSearch({config:null});a&&this._showSingleSearchEdit(a)})));this.own(e(this.btnSymSearch,
"click",b.hitch(this,function(){this._openSymbolEdit(this.nls.editDefaultSym,this.config)})));this.own(e(this.btnBufferSearch,"click",b.hitch(this,function(){this._openBufferEdit(this.nls.updateBuffer,this.config)})));this.own(e(this.btnSpatialSearch,"click",b.hitch(this,function(){this._openSREdit(this.nls.addspatalrelationships,this.spatialrelationships.spatialrelationship)})));this.own(e(this.btnGraphicalSearch,"click",b.hitch(this,function(){this._openGOEdit(this.nls.addgraphicalsearchoptions,
this.graphicalsearchoptions)})));this.own(e(this.btnDisableTabs,"click",b.hitch(this,function(){this._openDTEdit(this.nls.editdisabledtaboptions,this.disabledTabs)})));this.own(e(this.searchesTable,"actions-edit",b.hitch(this,function(a){this.popupState="EDIT";this._showSingleSearchEdit(a)})));this.own(e(this.searchesTable,"row-delete",b.hitch(this,function(a){delete a.singleSearch})));this.own(e(this.btnFormatResults,"click",b.hitch(this,function(){this._openFormatEdit(this.nls.editResultFormat)})))},
reset:function(){this.searchesTable.clear()},_showSingleSearchEdit:function(a){this._openSingleSearchEdit(this.nls.updateSearch,a)},_initSearchesTable:function(){this.searchesTable.clear();k.forEach(this.config&&this.config.layers,b.hitch(this,function(a,b){this._createSingleSearch(a)}))},_createSingleSearch:function(a){var b=this.searchesTable.addRow({name:a&&a.name||""});if(!b.success)return null;b.tr.singleSearch=a;return b.tr}})});