define({
  "styleText": "Jenis alat geser",
  "vertical": "Bilah vertikal",
  "horizontal": "Bilah horizontal",
  "scope": "Teropong",
  "placement": "Arah",
  "showLeftSide": "Tampilkan layer yang digeser pada sisi kiri",
  "showRigthSide": "Tampilkan layer yang digeser pada sisi kanan",
  "showUpSide": "Tampilkan layer yang digeser pada sisi atas",
  "showDownSide": "Tampilkan layer yang digeser pada sisi bawah",
  "barColor": "Warna bilah",
  "swipeMode": "Mode geser",
  "singleLayer": "Layer tunggal",
  "MultipleLayers": "Beberapa layer",
  "allowToSwipe": "Izinkan menggeser",
  "layer": "Layer",
  "swipeByDefault": "Geser secara default",
  "defaultLayerMustBeVisible": "layer default harus terlihat",
  "noDefaultLayer": "Harap atur layer untuk menggeser secara default",
  "defaultLayerHolder": "Klik untuk memilih",
  "selectLayers": "Pilih layer",
  "layerText": "Geser layer default",
  "spyglassText": "Pilih layer agar muncul dalam teropong secara default.",
  "layerHint": "Catatan: Jika layer tertutup oleh layer di atasnya, menggeser tidak akan memiliki efek.",
  "isZoom": "Zoom ke layer geser",
  "isZooms": "Perbesar untuk menggeser layer",
  "layersAvailable": "Layer yang dapat digeser",
  "hidePanel": "Sembunyikan panel pemilihan layer jika widget terbuka"
});