define({
  "showLayerLabels": "顯示圖層名稱",
  "autoPlay": "自動播放滑桿",
  "loopPlay": "持續地循環時間",
  "dateAndTimeFormat": "日期和時間格式",
  "mapDefault": "地圖預設值",
  "custom": "自訂",
  "formatInstruction": "格式指示",
  "playback": "將播放位置儲存在地圖中",
  "MMMMYYYY": "2015 年 7 月",
  "MMMYYYY": "2015 年 7 月",
  "MMMMDYYYY": "2015 年 7 月 21 日",
  "dddMMMDDYYYY": "2015 年 7 月 21 日星期二",
  "MDDYYYY": "2015 年 7 月 21 日",
  "YYYYMDD": "2015 年 7 月 21 日",
  "MDDYY": "2015 年 7 月 21 日",
  "YYYY": "2015",
  "MDDYYYYhmma": "2015 年 7 月 21 日上午 8:00",
  "dddMMMDDhmma": "7 月 21 日星期二上午 8:00",
  "sliderSetting": "滑桿設定",
  "autoRefresh": "重新整理滑桿間隔",
  "timeSetting": "時間設定",
  "useWebMapSetting": "遵守 Web 地圖的時間設定",
  "useConfigureSetting": "配置時間設定",
  "timeSettingBtn": "設定",
  "calenderError": "開始時間必須小於結束時間。",
  "timeSpan": "時間跨度",
  "startTime": "開始時間",
  "endTime": "結束時間",
  "unit": "單位",
  "timeDisplay": "時間顯示",
  "displayDataIn": "資料顯示方式",
  "interval": "間隔",
  "displayAllData": "逐步顯示所有資料",
  "layerTimeExtent": "啟用時間動畫",
  "layerTableCol1": "圖層",
  "layerTableCol2": "時間範圍",
  "timeTo": "至",
  "calender": "行事曆",
  "time": "時間",
  "now": "目前時間",
  "today": "今天",
  "maximum": "所有選定的最大值",
  "minimum": "所有選定的最小值"
});