define({
  "showLayerLabels": "Wyświetlaj nazwy warstw",
  "autoPlay": "Automatycznie odtwarzaj suwak",
  "loopPlay": "Stale powtarzaj odtwarzanie",
  "dateAndTimeFormat": "Format daty i czasu",
  "mapDefault": "Mapa domyślna",
  "custom": "Niestandardowy",
  "formatInstruction": "Formatuj instrukcję",
  "playback": "od punktu odtwarzania zapisanego z mapą",
  "MMMMYYYY": "Lipiec 2015",
  "MMMYYYY": "Lip 2015",
  "MMMMDYYYY": "21 lipca 2015",
  "dddMMMDDYYYY": "Wtorek, 21 lipca 2015",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00",
  "dddMMMDDhmma": "Wtorek, 21 lipca 8:00",
  "sliderSetting": "Ustawienia suwaka",
  "autoRefresh": "Odświeżaj suwak co",
  "timeSetting": "Ustawienia czasu",
  "useWebMapSetting": "Uwzględniaj ustawienia czasu na mapie internetowej",
  "useConfigureSetting": "Konfiguracja ustawień czasu",
  "timeSettingBtn": "ustawienie",
  "calenderError": "Czas rozpoczęcia musi być wcześniejszy od czasu zakończenia.",
  "timeSpan": "Przedział czasu",
  "startTime": "Czas rozpoczęcia",
  "endTime": "Czas zakończenia",
  "unit": "Jednostka",
  "timeDisplay": "Wyświetlanie czasu",
  "displayDataIn": "Wyświetlaj dane w",
  "interval": "Przedział",
  "displayAllData": "Stopniowo wyświetlaj wszystkie dane",
  "layerTimeExtent": "Włączanie animacji upływu czasu",
  "layerTableCol1": "Warstwa",
  "layerTableCol2": "Zasięg czasowy",
  "timeTo": "do",
  "calender": "Kalendarz",
  "time": "Czas",
  "now": "Teraz",
  "today": "Dzisiaj",
  "maximum": "Maksymalny z wszystkich zaznaczonych",
  "minimum": "Minimalny z wszystkich zaznaczonych"
});