define({
  "visible": "Privzeto pokaži pregled karte",
  "minWidth": "Minimalna širina",
  "minHeight": "Minimalna višina",
  "maxWidth": "Maksimalna širina",
  "maxHeight": "Maksimalna višina",
  "minText": "Minimum",
  "maxText": "maksimum",
  "attachText": "Določite, v kateri kot karte boste pripeli ta pripomoček.",
  "expandText": "Na začetku razširi pripomoček",
  "topLeft": "Zgoraj levo",
  "topRight": "Zgoraj desno",
  "bottomLeft": "Spodaj levo",
  "bottomRight": "Spodaj desno",
  "baseLayerType": "Prikaži",
  "BaseMap": "To je temeljna karta karte",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "Ploščične kartne storitve ArcGIS",
  "dynamicMapService": "Dinamična kartna storitev ArcGIS",
  "imageService": "Slikovna storitev ArcGIS",
  "OSM": "Open Street Map",
  "bingRoad": "Bing Maps ceste",
  "bingAerial": "Bing Maps zračna",
  "bingHybrid": "Bing Maps kombinirana",
  "WebTiled": "Spletni ploščični sloj",
  "VETiled": "Virtualni zemeljski ploščični sloj",
  "tileLayerUrl": "URL ploščičnega sloja",
  "tile": "Ime",
  "credits": "Krediti",
  "subdomain": "Poddomena",
  "extent": "Obseg",
  "initExtent": "Začetni obseg",
  "tileInfo": "Info. ploščic",
  "VEStyle": "Virtualni zemeljski slog",
  "Aerial": "Bing Maps zračni sloj",
  "AerialWithLabels": "Zračno s slojem oznak",
  "Roads": "Sloj cest",
  "errWkid": "wkid se ne ujema",
  "errUrl": "Neveljaven URL",
  "errReqTimeout": "Presežena časovna omejitev",
  "layerPlaceholder": "Vnesi URL"
});