//>>built
require({cache:{"widgets/HomeButton/_build-generate_module":function(){define(["dojo/i18n!./nls/strings"],function(){})},"*now":function(b){b(['dojo/i18n!*preload*widgets/HomeButton/nls/Widget*["","ROOT"]'])}}});
require({cache:{"esri/dijit/HomeButton":function(){define("dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/Deferred dojo/text!./templates/HomeButton.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style".split(" "),function(b,f,c,n,k,p,g,q,l,r,h,a,m,t){b=f("esri.dijit.HomeButton",[p,q,b],{templateString:h,options:{theme:"HomeButton",map:null,extent:null,fit:!1,visible:!0},constructor:function(e,d){e=c.mixin({},
this.options,e);this.domNode=d;this._i18n=a;this.set("map",e.map);this.set("theme",e.theme);this.set("visible",e.visible);this.set("extent",e.extent);this.set("fit",e.fit);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"homeContainer",home:"home",loading:"loading"}},postCreate:function(){this.inherited(arguments);this.own(l(this._homeNode,g,c.hitch(this,this.home)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("HomeButton::map required"));
if(this.map.loaded)this._init();else l.once(this.map,"load",c.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},home:function(){var a=new r,d=this.get("extent");this._showLoading();var b={extent:d};d?this.map.extent!==d?this.map.setExtent(d,this.get("fit")).then(c.hitch(this,function(){this._hideLoading();this.emit("home",b);a.resolve(b)}),c.hitch(this,function(d){d||(d=Error("HomeButton::Error setting map extent"));b.error=d;this.emit("home",b);a.reject(d)})):(this._hideLoading(),
this.emit("home",b),a.resolve(b)):(this._hideLoading(),d=Error("HomeButton::home extent is undefined"),b.error=d,this.emit("home",b),a.reject(d));return a.promise},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},_init:function(){this._visible();this.get("extent")||this.set("extent",this.map.extent);this.set("loaded",!0);this.emit("load",{})},_showLoading:function(){m.add(this._homeNode,this._css.loading)},_hideLoading:function(){m.remove(this._homeNode,this._css.loading)},
_updateThemeWatch:function(a,b,c){m.remove(this.domNode,b);m.add(this.domNode,c)},_visible:function(){this.get("visible")?t.set(this.domNode,"display","block"):t.set(this.domNode,"display","none")}});n("extend-esri")&&c.setObject("dijit.HomeButton",b,k);return b})},"widgets/HomeButton/_build-generate_module":function(){define(["dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:esri/dijit/templates/HomeButton.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"_homeNode" title\x3d"${_i18n.widgets.homeButton.home.title}" role\x3d"button" class\x3d"${_css.home}" tabindex\x3d"0"\x3e\x3cspan\x3e${_i18n.widgets.homeButton.home.button}\x3c/span\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',
"url:widgets/HomeButton/css/style.css":".jimu-widget-homebutton {background-color: rgba(0,0,0,0.1); border-radius: 5px; border: 1px solid #999;}.jimu-widget-homebutton .HomeButton .home {background-color: rgba(0,0,0,0.4);}.jimu-widget-homebutton.inHome {background-color: rgba(0,0,0,0.2);}.jimu-widget-homebutton .HomeButton .home:hover {background-color: rgba(0,0,0,0.6);}.jimu-widget-homebutton.inHome .HomeButton .home {background-color: rgba(0,0,0,0.2);}","*now":function(b){b(['dojo/i18n!*preload*widgets/HomeButton/nls/Widget*["ar","bs","ca","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","hu","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])},
"*noref":1}});
define("dojo/_base/declare dojo/_base/lang jimu/BaseWidget esri/dijit/HomeButton esri/geometry/Extent esri/SpatialReference dojo/_base/html dojo/dom-construct dojo/topic dojo/keys dojo/on".split(" "),function(b,f,c,n,k,p,g,q,l,r,h){return b([c],{name:"HomeButton",baseClass:"jimu-widget-homebutton",moveTopOnActive:!1,postCreate:function(){g.setAttr(this.domNode,"aria-label",window.apiNls.widgets.homeButton.home.title);this.own(l.subscribe("appConfigChanged",f.hitch(this,this.onAppConfigChanged)))},startup:function(){var a=
null;this.inherited(arguments);this.own(h(this.map,"extent-change",f.hitch(this,"onExtentChange")));a=(a=this.appConfig&&this.appConfig.map&&this.appConfig.map.mapOptions&&this.appConfig.map.mapOptions.extent)?new k(a.xmin,a.ymin,a.xmax,a.ymax,new p(a.spatialReference)):this.map._initialExtent||this.map.extent;this.createHomeDijit({map:this.map,extent:a})},createHomeDijit:function(a){this.homeDijit=new n(a,q.create("div"));this.own(h(this.homeDijit,"home",f.hitch(this,"onHome")));this.own(h(this.domNode,
"keydown",f.hitch(this,this.onHomeKeyDown)));g.place(this.homeDijit.domNode,this.domNode);this.homeDijit.startup()},onAppConfigChanged:function(a,b,c){"mapOptionsChange"===b&&c&&a&&c.extent&&(a=new k(c.extent),this.homeDijit.set("extent",a))},onExtentChange:function(){g.removeClass(this.domNode,"inHome")},onHomeKeyDown:function(a){a.keyCode===r.ENTER&&this.homeDijit.home()},onHome:function(a){a&&a.error||g.addClass(this.domNode,"inHome")}})});