define({
  root: ({
    visible: "Show overview map by default",
    minWidth: "Min width",
    minHeight: "Min meight",
    maxWidth: "Max width",
    maxHeight: "Max height",
    minText: "Minimum",
    maxText: "maximum",
    attachText: "Specify which corner of the map to attach this widget.",
    expandText: "Initially expand the widget",
    topLeft: "Top left",
    topRight: "Top right",
    bottomLeft: "Bottom left",
    bottomRight: "Bottom right",

    baseLayerType: "Display",
    BaseMap: "The map's basemap",
    ArcGIS: "ArcGIS",
    tiledMapService: "ArcGIS Tiled Map Service",
    dynamicMapService: "ArcGIS Dynamic Map Service",
    imageService: "ArcGIS Image Service",
    OSM: "Open Street Map",
    bingRoad: "Bing Maps Road",
    bingAerial: "Bing Maps Aerial",
    bingHybrid: "Bing Maps Hybrid",

    WebTiled: "Web Tiled Layer",
    VETiled: "Virtual Earth Tiled Layer",
    tileLayerUrl: "Tile Layer Url",
    tile: "Title",
    credits: "Credits",
    subdomain: "Subdomain",
    extent: "Extent",
    initExtent: "Init Extent",
    tileInfo: "TileInfo",
    VEStyle: "Virtual Earth Style",

    Aerial: "Bing Maps Aerial layer",
    AerialWithLabels: "Aerial with Labels layer",
    Roads: "Roads layer",

    errWkid: "wkid not match",
    errUrl : "Invalid URL",
    errReqTimeout: "Timeout exceeded",

    layerPlaceholder: "Enter URL"
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});