define({
  "showLayerLabels": "Visualizza nomi layer",
  "autoPlay": "Riproduci automaticamente il cursore",
  "loopPlay": "Ciclo di tempo continuo",
  "dateAndTimeFormat": "Formato data e ora",
  "mapDefault": "Impostazioni predefinite mappa",
  "custom": "Personalizzata",
  "formatInstruction": "Istruzione sul formato",
  "playback": "posizione di riproduzione salvata con la mappa",
  "MMMMYYYY": "Luglio 2015",
  "MMMYYYY": "Lug 2015",
  "MMMMDYYYY": "Luglio 21,2015",
  "dddMMMDDYYYY": "Mar Luglio 21,2015",
  "MDDYYYY": "21/07/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "21/07/2015",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00 am",
  "dddMMMDDhmma": "Mar Luglio 21 8:00 am",
  "sliderSetting": "Impostazioni cursore",
  "autoRefresh": "Aggiorna cursore ogni",
  "timeSetting": "Impostazioni temporali",
  "useWebMapSetting": "Rispetta impostazioni temporali della mappa Web",
  "useConfigureSetting": "Configurare le impostazioni temporali",
  "timeSettingBtn": "impostazione",
  "calenderError": "Ora di inizio deve essere inferiore a Ora di fine.",
  "timeSpan": "Periodo di tempo",
  "startTime": "Ora di inizio",
  "endTime": "Ora di fine",
  "unit": "Unità",
  "timeDisplay": "Visualizzazione tempo",
  "displayDataIn": "Visualizza dati in",
  "interval": "Intervallo",
  "displayAllData": "Visualizza progressivamente tutti i dati",
  "layerTimeExtent": "Abilitare l'animazione temporale",
  "layerTableCol1": "Layer",
  "layerTableCol2": "Estensione temporale",
  "timeTo": "a",
  "calender": "Calendario",
  "time": "Tempo",
  "now": "Adesso",
  "today": "Oggi",
  "maximum": "Massimo di tutto selezionato",
  "minimum": "Minimo di tutto selezionato"
});