//>>built
define("../core/declare ../core/Accessor ../core/JSONSupport ../core/kebabDictionary ../core/screenUtils ../core/lang ../core/Error ../support/arcadeUtils ../webdoc/support/opacityUtils ../Color ./support/utils ./support/AuthoringInfo".split(" "),function(L,M,N,t,A,h,B,r,E,n,O,P){var u=t({sizeInfo:"size",colorInfo:"color",transparencyInfo:"opacity",rotationInfo:"rotation"}),C=t({widthAndDepth:"width-and-depth"}),Q=t({unknown:"unknown",inch:"inches",foot:"feet",yard:"yards",mile:"miles","nautical-mile":"nautical-miles",
millimeter:"millimeters",centimeter:"centimeters",decimeter:"decimeters",meter:"meters",kilometer:"kilometers","decimal-degree":"decimal-degrees"}),F=(t({classedSize:"classed-size",classedColor:"classed-color",univariateColorSize:"univariate-color-size"}),t({esriClassifyEqualInterval:"equal-interval",esriClassifyManual:"manual",esriClassifyNaturalBreaks:"natural-breaks",esriClassifyQuantile:"quantile",esriClassifyStandardDeviation:"standard-deviation"}),t({percentTotal:"percent-of-total"}),Math.PI),
D=E.opacityToTransparency,K=E.transparencyToOpacity;return L([M,N],{declaredClass:"esri.renderers.Renderer",properties:{authoringInfo:{type:P,value:null,json:{write:!0}},requiredFields:{dependsOn:["visualVariables"],get:function(){var a=Object.create(null);return this.collectRequiredFields(a),Object.keys(a).sort()}},type:{type:String,readOnly:!0,json:{read:!1,write:{ignoreOrigin:!0}}},visualVariables:{json:{read:{source:["visualVariables","rotationType","rotationExpression"],reader:function(a,b){return this._readVariables(a,
b)}},write:function(a,b,c,d){var e=[];a.forEach(function(a,b){"size"===a.type?e.push(this._writeSizeInfo(a,d,b)):"color"===a.type?e.push(this._writeColorInfo(a,d,b)):"opacity"===a.type?e.push(this._writeOpacityInfo(a,d,b)):"rotation"===a.type&&e.push(this._writeRotationInfo(a,d,b))},this);b.visualVariables=e}}}},constructor:function(){this._cache={}},_rotationRE:/^\[([^\]]+)\]$/i,_viewScaleRE:/^\s*(return\s+)?\$view\.scale\s*(;)?\s*$/i,_visualVariablesSetter:function(a){var b=this._cache;this.visualVariables&&
this.visualVariables.forEach(function(a,d){b.hasOwnProperty(d)&&(b[d]=null)},this);a&&a.some(function(a){return!!a.target})&&a.sort(function(a,b){return a.target===b.target?0:a.target?1:-1});a&&a.forEach(function(a,d){"color"===a.type?b[d]=this._processColorInfo(a):"opacity"===a.type?b[d]=this._processOpacityInfo(a):"size"===a.type?b[d]=this._processSizeInfo(a):"rotation"===a.type&&(b[d]=this._processRotationInfo(a))},this);this._set("visualVariables",a)},getSymbol:function(a,b){},getVisualVariableValues:function(a,
b){var c,d=this.visualVariables;return d&&(c=d.map(function(d){var c,e=d.type,f=e+"Info";switch(b=h.mixin({},b),b[f]=d,e){case "size":c=this.getSize(a,b);break;case "color":c=this.getColor(a,b);break;case "opacity":c=this.getOpacity(a,b);break;case "rotation":c=this.getRotationAngle(a,b)}return{variable:d,value:c}},this).filter(function(a){return null!=a.value},this)),c},hasVisualVariables:function(a,b){return a?!!this.getVisualVariablesForType(a,b):!!(this.getVisualVariablesForType("size",b)||this.getVisualVariablesForType("color",
b)||this.getVisualVariablesForType("opacity",b)||this.getVisualVariablesForType("rotation",b))},getVisualVariablesForType:function(a,b){var c,d=this.visualVariables;return d&&(c=d.filter(function(d){return d.type===a&&("string"==typeof b?d.target===b:!1!==b||!d.target)}))&&0===c.length&&(c=void 0),c},getSize:function(a,b){var c=this._getVarInfo(b&&b.sizeInfo,"size"),d=c.variable,c=this._cache[c.cacheKey],e=null;if(d)var k=d.minSize,e=d.maxSize,k="object"==typeof k&&k?this._getSize(a,k,c&&c.minSize,
b):k,e="object"==typeof e&&e?this._getSize(a,e,c&&c.maxSize,b):e,e=this._getSize(a,d,c&&c.root,b,[k,e]);return e},getSizeRangeAtScale:function(a,b){var c;a=this._getVarInfo(a,"size");var d=this._cache[a.cacheKey],e={scale:b};(a=a.variable)&&b&&(b=a.minSize,a=a.maxSize,b="object"==typeof b&&b?this._getSize({},b,d&&d.minSize,e):b,d="object"==typeof a&&a?this._getSize({},a,d&&d.maxSize,e):a,null!=b||null!=d)&&(b>d&&(b=d=b),c={minSize:b,maxSize:d});return c},getColor:function(a,b){var c=this._getVarInfo(b&&
b.colorInfo,"color");return this._getColorComponent(a,c.variable,this._cache[c.cacheKey],b)},getOpacity:function(a,b){var c=this._getVarInfo(b&&b.opacityInfo,"opacity");return this._getColorComponent(a,c.variable,this._cache[c.cacheKey],b,!0)},getRotationAngle:function(a,b){var c=this._getVarInfo(b&&b.rotationInfo,"rotation"),d=c.variable,e=this._cache[c.cacheKey],k=d.axis||"heading",c="heading"===k&&"arithmetic"===d.rotationType?90:0,k="heading"===k&&"arithmetic"===d.rotationType?-1:1,d=d.field,
e=e&&e.compiledFunc,x=a.attributes,f=0;return(d||e)&&(e?f=r.executeFunction(e,r.createExecContext(a,r.getViewInfo(b))):"function"==typeof d?f=d.apply(this,arguments):x&&(f=x[d]||0),f="number"!=typeof f||isNaN(f)?null:c+k*f),f},collectRequiredFields:function(a){var b=[];this.visualVariables&&(b=b.concat(this.visualVariables));b.forEach(function(b){b&&(b.field&&(a[b.field]=!0),b.normalizationField&&(a[b.normalizationField]=!0),b.valueExpression&&r.extractFieldNames(b.valueExpression).forEach(function(b){a[b]=
!0}))})},_getVarInfo:function(a,b){var c;a&&a.type===b&&this.visualVariables?(c=this.visualVariables.indexOf(a),a=this.visualVariables[c]):this.visualVariables&&(a=(a=this.getVisualVariablesForType(b))&&a[0],c=this.visualVariables.indexOf(a));return{variable:a,cacheKey:c}},_readSizeInfo:function(a){return a.axis&&(a.axis=C.fromJSON(a.axis)),a.valueUnit&&(a.valueUnit=Q.fromJSON(a.valueUnit)),a},_readColorInfo:function(a){return a&&(a.colors&&a.colors.forEach(function(b,c){Array.isArray(b)?a.colors[c]=
n.fromJSON(b):a.colors[c]=new n(b)}),a.stops&&a.stops.forEach(function(b,c){b.color&&Array.isArray(b.color)?a.stops[c].color=n.fromJSON(b.color):b.color&&(a.stops[c].color=new n(b.color))})),a},_readOpacityInfo:function(a){var b;return a&&(b=h.mixin({},a),b.transparencyValues&&(b.opacityValues=b.transparencyValues.map(K),delete b.transparencyValues),b.stops&&(b.stops=b.stops.map(function(a){return a=h.mixin({},a),a.opacity=K(a.transparency),delete a.transparency,a}))),b},_readVariables:function(a,
b){a&&(a=a.map(function(a){return a=h.clone(a),a.type=u.fromJSON(a.type),"size"===a.type?a=this._readSizeInfo(a):"color"===a.type?a=this._readColorInfo(a):"opacity"===a.type&&(a=this._readOpacityInfo(a)),a},this));var c=b.rotationType;if(b=b.rotationExpression)c={type:"rotation",rotationType:c},(b=b.match(this._rotationRE))&&b[1]&&(c.field=b[1],a||(a=[]),a.push(c));return a},_createCache:function(a){var b=a&&a.valueExpression,c=r.createSyntaxTree(b),c=r.createFunction(c),d=!(!a||!a.expression)||this._viewScaleRE.test(b);
return{ipData:this._interpolateData(a),hasExpr:!!b,compiledFunc:c,isScaleDriven:d}},_processColorInfo:function(a){return a&&(a.colors&&a.colors.forEach(function(b,c){b instanceof n||(a.colors[c]=new n(b))}),a.stops&&a.stops.forEach(function(b,c){!b.color||b.color instanceof n||(a.stops[c].color=new n(b.color))}),this._sortStops(a.stops)),this._createCache(a)},_processOpacityInfo:function(a){return this._sortStops(a&&a.stops),this._createCache(a)},_processSizeInfo:function(a){return a.stops&&Array.isArray(a.stops)?
a.stops=this._processSizeInfoStops(a.stops):(a.minSize=a.minSize&&this._processSizeInfoSize(a.minSize),a.maxSize=a.maxSize&&this._processSizeInfoSize(a.maxSize)),{root:this._createCache(a),minSize:this._createCache(a.minSize),maxSize:this._createCache(a.maxSize)}},_processSizeInfoSize:function(a){return"object"==typeof a?a.stops=this._processSizeInfoStops(a.stops):a=A.toPt(a),a},_processSizeInfoStops:function(a){return a&&Array.isArray(a)&&(a.forEach(function(a){a.size=A.toPt(a.size)}),this._sortStops(a)),
a},_sortStops:function(a){a&&Array.isArray(a)&&a.sort(function(a,c){return a.value-c.value})},_processRotationInfo:function(a){return this._createCache(a)},_getSize:function(a,b,c,d,e){var k=a.attributes,x=b.field,f=b.stops,g=0,h=c&&c.hasExpr,n=c&&c.compiledFunc,t=c&&c.ipData,u=c&&c.isScaleDriven,y="number"==typeof a,m=y?a:null;if(x||u||h){var p,A=d&&d.scale,l=e?e[0]:b.minSize,q=e?e[1]:b.maxSize,w=b.minDataValue,H=b.maxDataValue,B=b.valueUnit||"unknown",I=b.valueRepresentation,E=b.scaleBy,C=b.normalizationField,
G=k?parseFloat(k[C]):void 0,z=d&&d.shape;if(u?m=null==A?this._getAverageValue(b):A:"number"!=typeof m&&(h?m=r.executeFunction(n,r.createExecContext(a,r.getViewInfo(d))):"function"==typeof x?m=x.apply(this,arguments):k&&(m=k[x])),null==m||C&&!y&&(isNaN(G)||0===G))return null;if(isNaN(G)||y||(m/=G),f){var J,D,q=this._lookupData(m,t);p=q[0];l=q[1];p===l?g=f[p].size:(J=f[p].size,D=f[l].size,g=J+(D-J)*q[2])}else null!=l&&null!=q&&null!=w&&null!=H?m<=w?g=l:m>=H?g=q:(p=(m-w)/(H-w),"area"===E&&z)?(f=(g="circle"===
z)?F*Math.pow(l/2,2):l*l,f+=p*((g?F*Math.pow(q/2,2):q*q)-f),g=g?2*Math.sqrt(f/F):Math.sqrt(f)):g=l+p*(q-l):"unknown"===B?null!=l&&null!=w?(l&&w?(p=m/w,g="circle"===z?2*Math.sqrt(p*Math.pow(l/2,2)):"square"===z||"diamond"===z||"image"===z?Math.sqrt(p*Math.pow(l,2)):p*l):g=m+(l||w),g=g<l?l:g,null!=q&&g>q&&(g=q)):g=m:(f=(d&&d.resolution?d.resolution:1)*O.meterIn[B],"area"===I?(g=Math.sqrt(m/F)/f,g*=2):(g=m/f,"radius"!==I&&"distance"!==I||(g*=2)),null!=l&&g<l&&(g=l),null!=q&&g>q&&(g=q))}else b&&null==
(g=f&&f[0]&&f[0].size)&&(g=b.minSize);return g=isNaN(g)?0:g},_getAverageValue:function(a){var b,c,d=a.stops;return d?(b=d[0].value,c=d[d.length-1].value):(b=a.minDataValue||0,c=a.maxDataValue||0),(b+c)/2},_getColorComponent:function(a,b,c,d,e,k){var h,f=a.attributes,g=b&&b.field,n="number"==typeof a,v=n?a:null,t=c&&c.hasExpr,u=c&&c.compiledFunc,y=c&&c.ipData;if(g||t){var m=b.normalizationField,p=f?parseFloat(f[m]):void 0;"number"!=typeof v&&(t?v=r.executeFunction(u,r.createExecContext(a,r.getViewInfo(d))):
"function"==typeof g?v=g.apply(this,arguments):f&&(v=f[g]));null==v||m&&!n&&(isNaN(p)||0===p)||(isNaN(p)||n||(v/=p),h=e?this._getOpacity(v,b,y):this._getColor(v,b,y))}else b&&(f=b.stops,e?null==(h=f&&f[0]&&f[0].opacity)&&(h=b.opacityValues&&b.opacityValues[0]):h=f&&f[0]&&f[0].color||b.colors&&b.colors[0]);return k&&(k.data=v,k.value=h),k||h},_interpolateData:function(a){var b;if(a)if(a.colors||a.opacityValues){var c=(a.colors||a.opacityValues).length,d=a.minDataValue,e=(a.maxDataValue-d)/(c-1);b=
[];for(a=0;a<c;a++)b[a]=d+a*e}else a.stops&&(b=a.stops.map(function(a){return a.value||0}));return b},_getOpacity:function(a,b,c){var d;a=this._lookupData(a,c);if(b=b||this.opacityInfo,a){var e,k;c=a[0];var h=a[1];c===h?d=this._getOpacValue(b,c):(e=this._getOpacValue(b,c),k=this._getOpacValue(b,h),d=e+(k-e)*a[2])}return d},_getOpacValue:function(a,b){return a.opacityValues?a.opacityValues[b]:a.stops[b].opacity},_getColor:function(a,b,c){var d;a=this._lookupData(a,c);if(b=b||this.colorInfo,a)d=a[0],
c=a[1],d=d===c?this._getColorObj(b,d):n.blendColors(this._getColorObj(b,d),this._getColorObj(b,c),a[2]),d=new n(d);return d},_getColorObj:function(a,b){return a.colors?a.colors[b]:a.stops[b].color},_lookupData:function(a,b){var c;if(b){var d=0,e=b.length-1;b.some(function(b,c){return a<b?(e=c,!0):(d=c,!1)});c=[d,e,(a-b[d])/(b[e]-b[d])]}return c},_processForContext:function(a,b,c){if(b&&"web-scene"===b.origin){var d=null!=a.expression,e=null!=a.valueExpressionTitle&&"rotation"===a.type;b.messages&&
(d&&b.messages.push(new B("property:unsupported",a.type+"VisualVariable.expression is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,propertyName:c+".expression",context:b})),e&&b.messages.push(new B("property:unsupported",a.type+"VisualVariable.valueExpressionTitle is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,propertyName:c+".valueExpressionTitle",context:b})));d&&delete a.expression;e&&delete a.valueExpressionTitle}else"size"===
a.type&&this._convertExpressionToArcade(a)},_writeRotationInfo:function(a,b,c){return a&&(a=h.mixin({},a),this._processForContext(a,b,"visualVariables["+c+"]"),a.type=u.toJSON(a.type),a=h.fixJson(a,!0)),a},_convertExpressionToArcade:function(a){a&&a.expression&&(a.valueExpression="$view.scale")},_writeSizeInfo:function(a,b,c){if(a){a=h.mixin({},a);this._processForContext(a,b,"string"==typeof c?c:"visualVariables["+c+"]");var d=a.minSize,e=a.maxSize;d&&(a.minSize="number"==typeof d?d:this._writeSizeInfo(d,
b,"visualVariables["+c+"].minSize"));e&&(a.maxSize="number"==typeof e?e:this._writeSizeInfo(e,b,"visualVariables["+c+"].maxSize"));b=a.legendOptions;c=a.axis;a.type=u.toJSON(a.type);c&&(a.axis=C.toJSON(c));b&&(a.legendOptions=h.mixin({},b),(b=b.customValues)&&(a.legendOptions.customValues=b.slice(0)));a.stops&&(a.stops=a.stops.map(function(a){return a=h.mixin({},a),null===a.label&&delete a.label,a}));a=h.fixJson(a,!0)}return a},_writeColorInfo:function(a,b,c){return a&&(a=h.mixin({},a),this._processForContext(a,
b,"visualVariables["+c+"]"),a.type=u.toJSON(a.type),a.colors&&(a.colors=a.colors.map(function(a){return n.toJSON(a)})),a.stops&&(a.stops=a.stops.map(function(a){return a=h.mixin({},a),a.color&&(a.color=n.toJSON(a.color)),null==a.value&&(a.value=0),null===a.label&&delete a.label,a})),a.legendOptions&&(a.legendOptions=h.mixin({},a.legendOptions)),a=h.fixJson(a,!0)),a},_writeOpacityInfo:function(a,b,c){var d;return a&&(d=h.mixin({},a),this._processForContext(d,b,"visualVariables["+c+"]"),d.type=u.toJSON(d.type),
d.opacityValues&&(d.transparencyValues=d.opacityValues.map(D),delete d.opacityValues),d.stops&&(d.stops=d.stops.map(function(a){return a=h.mixin({},a),a.transparency=D(a.opacity),delete a.opacity,null===a.label&&delete a.label,a})),d.legendOptions&&(d.legendOptions=h.mixin({},d.legendOptions)),d=h.fixJson(d,!0)),d}})});