define({
  "styleText": "卷帘工具的类型",
  "vertical": "垂直条块",
  "horizontal": "水平条块",
  "scope": "望远镜",
  "placement": "方向",
  "showLeftSide": "在左侧显示卷帘图层",
  "showRigthSide": "在右侧显示卷帘图层",
  "showUpSide": "在上方显示卷帘图层",
  "showDownSide": "在下方显示卷帘图层",
  "barColor": "条形图颜色",
  "swipeMode": "卷帘模式",
  "singleLayer": "单个图层",
  "MultipleLayers": "多个图层",
  "allowToSwipe": "允许应用卷帘",
  "layer": "图层",
  "swipeByDefault": "默认应用卷帘",
  "defaultLayerMustBeVisible": "默认图层必须可见",
  "noDefaultLayer": "请将图层设置为默认应用卷帘",
  "defaultLayerHolder": "单击以选择",
  "selectLayers": "选择图层",
  "layerText": "默认卷帘图层",
  "spyglassText": "选择默认显示在望远镜中的图层。",
  "layerHint": "注意: 如果上面的图层隐藏了该图层，则卷帘功能不会生效。",
  "isZoom": "缩放至卷帘图层",
  "isZooms": "缩放至卷帘图层",
  "layersAvailable": "可卷帘图层",
  "hidePanel": "微件打开时隐藏图层选择面板"
});