define({
  root: ({
    styleText: "Type of swipe tool",
    vertical: "Vertical bar",
    horizontal: "Horizontal bar",
    scope: "Spyglass",

    placement: "Direction",
    showLeftSide: "Display swiped layers on the left side",
    showRigthSide: "Display swiped layers on the right side",
    showUpSide: "Display swiped layers on the upper side",
    showDownSide: "Display swiped layers on the lower side",

    barColor: "Bar color",

    swipeMode: "Swipe mode",
    singleLayer: "Single layer",
    MultipleLayers: "Multiple layers",

    allowToSwipe: "Allow to swipe",
    layer: "Layer",
    swipeByDefault: "Swipe by default",

    defaultLayerMustBeVisible: "default layer must be visible",
    noDefaultLayer: "Please set the layers to swipe by default",
    defaultLayerHolder: "Click to select",
    selectLayers: "Select layers",

    layerText: "Default swipe layer(s)",
    spyglassText: "Select the layer to appear within the spyglass by default.",
    layerHint: "Note: If the layer is hidden by upper layers, swipe won't have any effect.",

    isZoom: "Zoom to the swipe layer" ,
    isZooms: "Zoom to the swipe layer(s)" ,
    layersAvailable: "Swipeable layers",
    hidePanel: "Hide the layer choosing panel when the widget opens",
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
