// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define([],function(){return{ar:{date:{"short":"d/M/y",medium:"dd/MM/y","long":"d MMMM. y",onlyDate:"dd/MM",mNoDay:"MM/y",sNoDay:"M/y"},time:{"short":"h:mm a",medium:"h:mm:ss a"}},bs:{date:{"short":"d.M.yy.",medium:"d. MMM. y.","long":"d. MMMM y.",onlyDate:"d. MMM.",mNoDay:"MMM. y.",sNoDay:"M.yy"}},cs:{date:{"short":"dd.MM.yy",medium:"d. M. y",onlyDate:"d. M.",mNoDay:"M. y",sNoDay:"MM.yy"}},da:{date:{"short":"dd/MM/y",medium:"d. MMM y","long":"d. MMMM y",onlyDate:"d. MMM",mNoDay:"MMM y",sNoDay:"MM/y"}},
de:{date:{"short":"dd.MM.yy",medium:"dd.MM.y",onlyDate:"dd.MM."},connector:" , ",mNoDay:"MM.y",sNoDay:"MM.yy"},el:{date:{"short":"d/M/yy",medium:"d MMM y",onlyDate:"d MMM"},connector:" , ",mNoDay:"MMM y",sNoDay:"M/yy"},en:{date:{"short":"M/d/yy",medium:"MMM d, y",onlyDate:"MMM d",mNoDay:"MMM, y",sNoDay:"M/yy"}},es:{date:{"short":"d/M/yy",medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"M/yy"}},et:{date:{"short":"d.MM.y",medium:"d. MMM y",onlyDate:"d. MMM",mNoDay:"MMM y",sNoDay:"MM.y"},time:{"short":"H:mm",
medium:"H:mm:ss"}},fi:{date:{"short":"d.M.y",medium:"d.M.y",onlyDate:"d.M.",mNoDay:"M.y",sNoDay:"M.y"},connector:" 'klo' "},fr:{date:{"short":"dd/MM/y",medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"MM/y"},connector:" '\u00e0' "},he:{date:{"short":"dd/MM/yy",medium:"d '\u05d1'MMM y",onlyDate:"d '\u05d1'MMM",mNoDay:"'\u05d1'MMM y",sNoDay:"MM/yy"},connector:" , "},hi:{date:{"short":"d/M/yy",medium:"dd/MM/y","long":"d MMMM y",onlyDate:"dd/MM",mNoDay:"MM/y",sNoDay:"M/yy"},time:{"short":"h:mm a",
medium:"h:mm:ss a",sNoDay:""},connector:" , "},hr:{date:{"short":"d.M.y",medium:"d. MMM y.",onlyDate:"d. MMM",mNoDay:"MMM y.",sNoDay:"M.y"}},id:{"short":"dd/MM/yy",date:{medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"MM/yy"}},it:{date:{medium:"dd MMM y","long":"d MMMM y",onlyDate:"dd MMM",mNoDay:"MMM y",sNoDay:"MM/yy"},connector:" , "},ja:{date:{medium:"y/MM/dd",onlyDate:"MM/dd",mNoDay:"y/MM",sNoDay:"y/MM"},time:{"short":"a h:mm",medium:"a h:mm:ss"}},ko:{date:{medium:"y. M. d.",onlyDate:"M. d.",
mNoDay:"y. M.",sNoDay:"yy. M."}},lt:{date:{medium:"y-MM-dd","long":"y 'm'. MMMM d 'd'.",onlyDate:"MM-dd",mNoDay:"y-MM",sNoDay:"y-MM"},time:{medium:"HH:mm:ss"}},lv:{date:{"short":"dd.MM.y",medium:"y. 'gada' d. MMM.","long":"y. 'gada' d. MMMM",onlyDate:"d. MMM.",mNoDay:"y. 'gada' MMM.",sNoDay:"MM.y"}},nb:{date:{"short":"dd.MM.y",medium:"d. MMM y","long":"d. MMMM y",onlyDate:"d. MMM",mNoDay:"MMM y",sNoDay:"MM.y"},time:{"short":"HH:mm",medium:"HH:mm:ss"},connector:" , "},nl:{date:{medium:"d MMM y",onlyDate:"d MMM",
mNoDay:"MMM y",sNoDay:"MM-yy"}},pl:{date:{medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"MM.y"},connector:" , "},"pt-br":{date:{"short":"dd/MM/y",medium:"d 'de' MMM 'de' y",onlyDate:"d 'de' MMM",mNoDay:"MMM 'de' y",sNoDay:"MM/y"}},"pt-pt":{date:{medium:"dd/MM/y",onlyDate:"dd/MM",mNoDay:"MM/y",sNoDay:"MM/yy"}},ro:{date:{medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"MM.y"},connector:" , "},ru:{date:{"short":"dd.MM.y",medium:"d MMM y '\u0433.'",onlyDate:"d MMM",mNoDay:"MMM y '\u0433.'",
sNoDay:"MM.y"},connector:" , "},sr:{date:{medium:"dd.MM.y.",onlyDate:"dd.MM.",mNoDay:"MM.y.",sNoDay:"M.yy."},time:{"short":"HH:mm",medium:"HH:mm:ss"}},sv:{date:{medium:"d MMM. y",onlyDate:"d MMM.",mNoDay:"MMM. y",sNoDay:"y-MM"}},th:{date:{medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"M/yy"}},tr:{date:{medium:"d MMM y",onlyDate:"d MMM",mNoDay:"MMM y",sNoDay:"MM.y"}},vi:{date:{"short":"dd/MM/y",medium:"d MMM, y","long":"'Ng\u00e0y' dd 'th\u00e1ng' MM 'n\u0103m' y",onlyDate:"d MMM",mNoDay:"MMM, y",
sNoDay:"MM/y"},time:{"short":"hh:mm a",medium:"hh:mm:ss a"},connector:" , "},"zh-cn":{date:{"short":"y/M/d",medium:"y'\u5e74'M'\u6708'd'\u65e5'",onlyDate:"M'\u6708'd'\u65e5'",mNoDay:"y'\u5e74'M'\u6708'",sNoDay:"y/M"}},"zh-hk":{date:{medium:"y'\u5e74'M'\u6708'd'\u65e5'",onlyDate:"M'\u6708'd'\u65e5'",mNoDay:"y'\u5e74'M'\u6708'",sNoDay:"M/y"}},"zh-tw":{date:{medium:"y'\u5e74'M'\u6708'd'\u65e5'",onlyDate:"M'\u6708'd'\u65e5'",mNoDay:"y'\u5e74'M'\u6708'",sNoDay:"y/M"}}}});