// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query esri/graphic jimu/ArcadeUtils".split(" "),function(e,l,n,u,q,p,t,w,x,y,z,A){function v(b){var a=l.clone(b.attributes);(b=b.geometry)&&"point"===b.type&&("x"in a?a._x=b.x:a.x=b.x,"y"in a?a._y=b.y:a.y=b.y);return a}e.exportCSV=function(b,a,c){return e._createCSVStr(a,c).then(function(a){return e._download(b+".csv",a)})};e.exportCSVFromFeatureLayer=function(b,
a,c){c=c||{};return e._getExportData(a,{datas:c.datas,objectIds:c.objectIds,fromClient:c.fromClient,withGeometry:c.withGeometry,outFields:c.outFields,filterExpression:c.filterExpression,outSpatialReference:c.outSpatialReference,arcadeExpressions:c.arcadeExpressions}).then(function(d){return e._formattedData(a,d,{formatNumber:c.formatNumber,formatDate:c.formatDate,formatCodedValue:c.formatCodedValue,richText:{clearFormat:c.richTextFieldsToClear&&!!c.richTextFieldsToClear.length,fieldsToClear:c.richTextFieldsToClear||
[]},popupInfo:c.popupInfo}).then(function(a){return e.exportCSV(b,a.datas,a.columns)})})};e.exportCSVByAttributes=function(b,a,c,d){d=l.mixin({},d);d.datas=c;return e.exportCSVFromFeatureLayer(b,a,d)};e.exportCSVByGraphics=function(b,a,c,d){c=n.map(c,function(a){return a.attributes});return e.exportCSVByAttributes(b,a,c,d)};e._createCSVStr=function(b,a){var c=new p,d="",e=0,f=0,g="",h="";try{a=n.map(a,function(a){return"string"===typeof a?{name:a}:a});n.forEach(a,function(a){a=a.alias||a.name;-1<
a.toString().indexOf(",")&&(a='"'+a+'"');d=d+g+a;g=","});for(var d=d+"\r\n",e=b.length,f=a.length,k=0;k<e;k++){for(var g="",r=0;r<f;r++)(h=b[k][a[r].name])||"number"===typeof h||(h=""),h&&/[",\r\n]/g.test(h)&&(h='"'+h.replace(/(")/g,'""')+'"'),d=d+g+h,g=",";d+="\r\n"}c.resolve(d)}catch(B){console.error(B),c.resolve("")}return c};e._isIE11=function(){return 11===t.has("ie")};e._isEdge=function(){return t.has("edge")};e._getDownloadUrl=function(b){return window.Blob&&window.URL&&window.URL.createObjectURL?
(b=new Blob(["\ufeff"+b],{type:"text/csv"}),URL.createObjectURL(b)):"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(b)};e._download=function(b,a){var c=new p;try{if(q("ie")&&10>q("ie")){var d=window.top.open("about:blank","_blank");d.document.write("sep\x3d,\r\n"+a);d.document.close();d.document.execCommand("SaveAs",!0,b);d.close()}else if(10===q("ie")||e._isIE11()||e._isEdge()){var m=new Blob(["\ufeff"+a],{type:"text/csv"});navigator.msSaveBlob(m,b)}else{var f=u.create("a",{href:e._getDownloadUrl(a),
target:"_blank",download:b},document.body);if(q("safari")){var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);f.dispatchEvent(g)}else f.click();u.destroy(f)}c.resolve()}catch(h){c.reject(h)}return c};e._getExportData=function(b,a){var c=new p,d=null,m=[],f=a.datas,g=a.withGeometry,h=!!a.arcadeExpressions,d=a.outFields;d&&d.length||(d=b.fields);d=l.clone(d);if(g&&!(f&&0<f.length)){h?(m=n.filter(b.fields,function(a){return-1===a.name.indexOf("expression/")}),m=l.clone(m)):m=l.clone(d);
var k="",k=-1!==d.indexOf("x")?"_x":"x";d.push({name:k,alias:k,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});k=-1!==d.indexOf("y")?"_y":"y";d.push({name:k,alias:k,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}f&&0<f.length?(h&&(f=e._getAttrsWithExpressionsBatch(f,a.arcadeExpressions)),c.resolve({data:f||[],outFields:d})):a.fromClient?(f=n.map(b.graphics,function(b){b=g?v(b):l.clone(b);return b=h?e._getAttrsWithExpressions(b,a.arcadeExpressions):
b}),c.resolve({data:f||[],outFields:d})):e._getExportDataFromServer(b,m,a).then(function(b){h&&(b=e._getAttrsWithExpressionsBatch(b,a.arcadeExpressions));c.resolve({data:b||[],outFields:d})});return c};e._getExportDataFromServer=function(b,a,c){var d=new p;if("esri.layers.FeatureLayer"!==b.declaredClass)return d.resolve([]),d;var e=new x(b.url),f=new y;f.where=c.filterExpression||b.getDefinitionExpression&&b.getDefinitionExpression()||"1\x3d1";0<a.length?(b=n.map(a,function(a){return a.name}),f.outFields=
b):f.outFields=["*"];f.objectIds=c.objectIds;f.returnGeometry=c.withGeometry;f.outSR=c.spatialReference;e.execute(f,function(a){a=n.map(a.features,function(a){return v(a)});d.resolve(a)},function(a){console.error(a);d.resolve([])});return d};e._formattedData=function(b,a,c){var d=new p,m=[],f=a.data;a=a.outFields;for(var g=0,h=f.length;g<h;g++){for(var k={},r=0;r<a.length;r++){var l=a[r];k[l.name]=e._getExportValue(f[g][l.name],l,b.objectIdField,b.typeIdField,f[g][b.typeIdField],b.types,c)}m.push(k)}b=
n.map(a,function(a){return{alias:a.alias,name:a.name}});d.resolve({datas:m,columns:b});return d};e._getExportValue=function(b,a,c,d,e,f,g){function h(a){if(l&&w.isDefined(l.fieldInfos))for(var b=0,c=l.fieldInfos.length;b<c;b++){var d=l.fieldInfos[b];if(d.fieldName===a)return d.format}return null}function k(a){for(var b=0,c=m.length;b<c;b++)if(m[b].fieldName===a)return!0;return!1}var l=g.popupInfo,m=g.richText.fieldsToClear,p=!!a.domain&&g.formatCodedValue,q="esriFieldTypeDate"===a.type&&g.formatDate,
u=c&&a.name===c;d=d&&a.name===d;k="esriFieldTypeString"===a.type&&g.richText.clearFormat&&k(a.name);return q?t.fieldFormatter.getFormattedDate(b,h(a.name)):d?t.fieldFormatter.getTypeName(b,f):p?t.fieldFormatter.getCodedValue(a.domain,b):k?b?(a=document.createElement("span"),a.innerHTML=b,a.textContent||a.innerText||""):b:p||q||u||d||k?b:(g=null,c&&f&&0<f.length&&(c=(c=n.filter(f,function(a){return a.id===e}))&&c[0])&&c.domains&&c.domains[a.name]&&c.domains[a.name].codedValues&&(g=t.fieldFormatter.getCodedValue(c.domains[a.name],
b)),null!==g?g:b)};e._getAttrsWithExpressions=function(b,a){var c=l.getObject("expressionInfos",!1,a);a=l.getObject("layerDefinition",!1,a);var d=new z(null,null,b);return A.customExpr.getAttributesFromCustomArcadeExpr(c,d,a)||b};e._getAttrsWithExpressionsBatch=function(b,a){var c=[];return c=n.map(b,function(b){return e._getAttrsWithExpressions(b,a)})}});