// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define([],function(){function t(b){var d;a:{d=b[0];for(var a=0;a<d.length;a++)if(d[a]!==b[b.length-1][a]){d=!1;break a}d=!0}d||b.push(b[0]);return b}function u(b){var d=0,a=0,c=b.length,f=b[a],e;for(a;a<c-1;a++)e=b[a+1],d+=(e[0]-f[0])*(e[1]+f[1]),f=e;return 0<=d}function w(b,d){for(var a=0;a<b.length-1;a++)for(var c=0;c<d.length-1;c++){var f;a:{var e=b[a],h=b[a+1],g=d[c],l=d[c+1],k=(l[0]-g[0])*(e[1]-g[1])-(l[1]-g[1])*(e[0]-g[0]);f=(h[0]-e[0])*(e[1]-g[1])-(h[1]-e[1])*(e[0]-g[0]);e=(l[1]-g[1])*(h[0]-
e[0])-(l[0]-g[0])*(h[1]-e[1]);if(0!==e&&(k/=e,f/=e,0<=k&&1>=k&&0<=f&&1>=f)){f=!0;break a}f=!1}if(f)return!0}return!1}function p(b){var d=[];b=b.slice(0);var a=t(b.shift().slice(0));if(4<=a.length)for(u(a)||a.reverse(),d.push(a),a=0;a<b.length;a++){var c=t(b[a].slice(0));4<=c.length&&(u(c)&&c.reverse(),d.push(c))}return d}function x(b){var d={},a;for(a in b)b.hasOwnProperty(a)&&(d[a]=b[a]);return d}var r={arcgisToGeoJSON:function(b,d){var a={};"number"===typeof b.x&&"number"===typeof b.y&&(a.type=
"Point",a.coordinates=[b.x,b.y]);b.points&&(a.type="MultiPoint",a.coordinates=b.points.slice(0));b.paths&&(1===b.paths.length?(a.type="LineString",a.coordinates=b.paths[0].slice(0)):(a.type="MultiLineString",a.coordinates=b.paths.slice(0)));if(b.rings){var c=b.rings.slice(0),a=[],f=[],e,h;for(h=0;h<c.length;h++){var g=t(c[h].slice(0));4>g.length||(u(g)?a.push([g]):f.push(g))}for(g=[];f.length;){h=f.pop();for(var l=!1,c=a.length-1;0<=c;c--){var k=e=a[c][0],m=h;e=w(k,m);for(var m=m[0],v=!1,n=-1,p=k.length,
q=p-1;++n<p;q=n)(k[n][1]<=m[1]&&m[1]<k[q][1]||k[q][1]<=m[1]&&m[1]<k[n][1])&&m[0]<(k[q][0]-k[n][0])*(m[1]-k[n][1])/(k[q][1]-k[n][1])+k[n][0]&&(v=!v);k=v;if(!e&&k){a[c].push(h);l=!0;break}}l||g.push(h)}for(;g.length;){h=g.pop();f=!1;for(c=a.length-1;0<=c;c--)if(e=a[c][0],w(e,h)){a[c].push(h);f=!0;break}f||a.push([h.reverse()])}a=1===a.length?{type:"Polygon",coordinates:a[0]}:{type:"MultiPolygon",coordinates:a}}if(b.geometry||b.attributes)a.type="Feature",a.geometry=b.geometry?r.arcgisToGeoJSON(b.geometry):
null,a.properties=b.attributes?x(b.attributes):null,b.attributes&&(a.id=b.attributes[d]||b.attributes.OBJECTID||b.attributes.FID);return a},geojsonToArcGIS:function(b,d){d=d||"OBJECTID";var a={wkid:4326},c={};switch(b.type){case "Point":c.x=b.coordinates[0];c.y=b.coordinates[1];c.spatialReference=a;break;case "MultiPoint":c.points=b.coordinates.slice(0);c.spatialReference=a;break;case "LineString":c.paths=[b.coordinates.slice(0)];c.spatialReference=a;break;case "MultiLineString":c.paths=b.coordinates.slice(0);
c.spatialReference=a;break;case "Polygon":c.rings=p(b.coordinates.slice(0));c.spatialReference=a;break;case "MultiPolygon":d=c;b=b.coordinates.slice(0);for(var f=[],e=0;e<b.length;e++)for(var h=p(b[e]),g=h.length-1;0<=g;g--){var l=h[g].slice(0);f.push(l)}d.rings=f;c.spatialReference=a;break;case "Feature":b.geometry&&(c.geometry=r.geojsonToArcGIS(b.geometry,d));c.attributes=b.properties?x(b.properties):{};b.id&&(c.attributes[d]=b.id);break;case "FeatureCollection":c=[];for(a=0;a<b.features.length;a++)c.push(r.geojsonToArcGIS(b.features[a],
d));break;case "GeometryCollection":for(c=[],a=0;a<b.geometries.length;a++)c.push(r.geojsonToArcGIS(b.geometries[a],d))}return c}};return r});