define({
  "visible": "Prikaži preglednu kartu prema zadanim postavkama",
  "minWidth": "Min. širina",
  "minHeight": "Min, visina",
  "maxWidth": "Maks. širina",
  "maxHeight": "Maks. visina",
  "minText": "Minimum",
  "maxText": "maksimum",
  "attachText": "Odredite u koji kut karte želite umetnuti ovaj widget.",
  "expandText": "Na početku proširite widget",
  "topLeft": "Gore lijevo",
  "topRight": "Gore desno",
  "bottomLeft": "Donje lijevo",
  "bottomRight": "Donje desno",
  "baseLayerType": "Prikaži",
  "BaseMap": "Kartografska podloga karte",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "Usluge pločaste karte ArcGIS",
  "dynamicMapService": "Usluge dinamičke karte ArcGIS",
  "imageService": "Usluga slika ArcGIS",
  "OSM": "Open Street Map",
  "bingRoad": "Bing Maps Road",
  "bingAerial": "Bing Maps Aerial",
  "bingHybrid": "Bing Maps Hybrid",
  "WebTiled": "Pločasti sloj na webu",
  "VETiled": "Pločasti sloj virtualne zemlje",
  "tileLayerUrl": "URL pločastog sloja",
  "tile": "Naziv",
  "credits": "Zasluge",
  "subdomain": "Poddomena",
  "extent": "Obuhvat",
  "initExtent": "Obuhvat Init",
  "tileInfo": "Informacije o ploči",
  "VEStyle": "Stil virtualne zemlje",
  "Aerial": "Sloj Bing Maps Aerial",
  "AerialWithLabels": "Sloj zračnih snimki s oznakama",
  "Roads": "Sloj cesta",
  "errWkid": "wkid se ne podudara",
  "errUrl": "Neispravan URL",
  "errReqTimeout": "Premašeno vremensko ograničenje",
  "layerPlaceholder": "Unesite URL"
});