define({
  "_widgetLabel": "Druka",
  "title": "Kartes virsraksts",
  "format": "Formāts",
  "layout": "Izkārtojums",
  "settings": "Papildus",
  "labels": "Kartes teksti",
  "showLabels": "Rādīt kartes tekstus",
  "mapScaleExtent": "Kartes mērogs/pārklājums",
  "preserve": "Saglabāt",
  "mapScale": "kartes mērogs",
  "mapExtent": "kartes pārklājums",
  "forceScale": "Uzspiest mērogu",
  "getCurrentScale": "pašreizējais",
  "mapMetadata": "Izkārtojuma metadati",
  "author": "Autors",
  "copyright": "Autortiesības",
  "fullLayoutOptions": "Pilna izkārtojuma opcijas",
  "scaleBarUnit": "Grafiskā mēroga mērvienība",
  "scaleBarUnitsMetric": "Metriskas mēroga joslas vienības",
  "scaleBarUnitsNonMetric": "Ne metriskas mēroga joslas vienības",
  "unitsMiles": "Jūdzes",
  "unitsKilometers": "Kilometri",
  "unitsMeters": "Metri",
  "unitsFeet": "Pēdas",
  "unitsYards": "Jardi",
  "unitsNauticalMiles": "Jūras jūdzes",
  "lncludeLegend": "Iekļaut apzīmējumus",
  "printQualityOptions": "Drukas kvalitāte",
  "dpi": "DPI",
  "mapOnlyOptions": "MAP_ONLY lielums",
  "width": "Platums (px)",
  "height": "Augstums (px)",
  "print": "Drukāt",
  "clearList": "Notīrīt izdrukas",
  "creatingPrint": "Drukas izveide",
  "printError": "Kļūda, mēģiniet vēlreiz",
  "forceFeatureAttributes": "Elementu atribūti",
  "includeFeatureAttributes": "Iekļaut atribūtus",
  "outputSR": "Izvades telpiskā atskaite",
  "invalidWkid": "Nederīgs WKID"
});