define({
  "showLayerLabels": "Exibir nomes de camadas",
  "autoPlay": "Reproduzir slider automaticamente",
  "loopPlay": "Repetir tempo continuamente",
  "dateAndTimeFormat": "Formato de data e hora",
  "mapDefault": "Predefinição de mapa",
  "custom": "Personalizar",
  "formatInstruction": "Instrução de formatação",
  "playback": "posição de reprodução guardada com o mapa.",
  "MMMMYYYY": "Julho de 2015",
  "MMMYYYY": "Jul 2015",
  "MMMMDYYYY": "21 de Julho,2015",
  "dddMMMDDYYYY": "Ter 21 Jul,2015",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00",
  "dddMMMDDhmma": "Ter 21 Jul 8:00",
  "sliderSetting": "Definições de Controlo Deslizante",
  "autoRefresh": "Atualizar controlo deslizante a cada",
  "timeSetting": "Configurações de Tempo",
  "useWebMapSetting": "Respeite as definições de tempo do mapa web",
  "useConfigureSetting": "Configurar definições de tempo",
  "timeSettingBtn": "definição",
  "calenderError": "A hora de Início tem de ser inferior à hora de Fim.",
  "timeSpan": "Espaço de tempo",
  "startTime": "Tempo Inicial",
  "endTime": "Tempo Final",
  "unit": "Unidade",
  "timeDisplay": "Exibição do tempo",
  "displayDataIn": "Exibir dados em",
  "interval": "Intervalo",
  "displayAllData": "Exibir progressivamente todos os dados",
  "layerTimeExtent": "Activar animação de tempo",
  "layerTableCol1": "Camada",
  "layerTableCol2": "Intervalo de Tempo",
  "timeTo": "até",
  "calender": "Calendário",
  "time": "Tempo",
  "now": "Agora",
  "today": "Hoje",
  "maximum": "Máximo de todos os selecionados",
  "minimum": "Mínimo de todos os selecionados"
});