define({
  "visible": "Mostrar mapa de vista general de manera predeterminada",
  "minWidth": "Ancho mín.",
  "minHeight": "Altura mín.",
  "maxWidth": "Ancho máx.",
  "maxHeight": "Altura máx.",
  "minText": "Mínimo",
  "maxText": "máximo",
  "attachText": "Especifica la esquina del mapa en la que vas a adjuntar este widget.",
  "expandText": "Expandir inicialmente el widget",
  "topLeft": "Superior izquierda",
  "topRight": "Superior derecha",
  "bottomLeft": "Inferior izquierda",
  "bottomRight": "Inferior derecha",
  "baseLayerType": "Mostrar",
  "BaseMap": "El mapa base del mapa",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "Servicio de mapas de teselas de ArcGIS",
  "dynamicMapService": "Servicio de mapas dinámicos de ArcGIS",
  "imageService": "Servicio de imágenes de ArcGIS",
  "OSM": "Open Street Map",
  "bingRoad": "Bing Maps Road",
  "bingAerial": "Bing Maps Aerial",
  "bingHybrid": "Bing Maps Hybrid",
  "WebTiled": "Capas de teselas web",
  "VETiled": "Capa de teselas Virtual Earth",
  "tileLayerUrl": "URL de capa de teselas",
  "tile": "Título",
  "credits": "Créditos",
  "subdomain": "Subdominio",
  "extent": "Extensión",
  "initExtent": "Extensión inicial",
  "tileInfo": "TileInfo",
  "VEStyle": "Estilo Virtual Earth",
  "Aerial": "Capa Bing Maps Aerial",
  "AerialWithLabels": "Capa Aerial with Labels",
  "Roads": "Capa Roads",
  "errWkid": "wkid no coincide",
  "errUrl": "URL no válida",
  "errReqTimeout": "Tiempo de espera rebasado",
  "layerPlaceholder": "Introducir URL"
});