define({
  "showLayerLabels": "Prikaži imena slojev",
  "autoPlay": "Samodejno predvajaj drsnik",
  "loopPlay": "Neprekinjena časovna zanka",
  "dateAndTimeFormat": "Oblika datuma in ure",
  "mapDefault": "Privzeto",
  "custom": "Po meri",
  "formatInstruction": "Oblika datuma",
  "playback": "položaju predvajanja, shranjenem s karto",
  "MMMMYYYY": "julij 2015",
  "MMMYYYY": "jul. 2015",
  "MMMMDYYYY": "21. julij 2015",
  "dddMMMDDYYYY": "torek, 21. julij 2015",
  "MDDYYYY": "21. 07. 2015",
  "YYYYMDD": "21/7/2015",
  "MDDYY": "21. 07. 2015",
  "YYYY": "2015",
  "MDDYYYYhmma": "21/7/2015 ob 8:00",
  "dddMMMDDhmma": "torek, 21. julij, ob 8:00",
  "sliderSetting": "Nastavitve drsnika",
  "autoRefresh": "Osveži drsnik vsake",
  "timeSetting": "Časovne nastavitve",
  "useWebMapSetting": "Upoštevajte časovne nastavitve spletne karte",
  "useConfigureSetting": "Konfiguriraj časovne nastavitve",
  "timeSettingBtn": "nastavitev",
  "calenderError": "Začetni čas mora biti manjši od končnega časa.",
  "timeSpan": "Časovni razpon",
  "startTime": "Začetni čas",
  "endTime": "Končni čas",
  "unit": "Enota",
  "timeDisplay": "Prikaz časa",
  "displayDataIn": "Prikaži podatke v",
  "interval": "Interval",
  "displayAllData": "Progresivno prikaži vse podatke",
  "layerTimeExtent": "Omogoči časovno animacijo",
  "layerTableCol1": "Sloj",
  "layerTableCol2": "Časovni razpon",
  "timeTo": "do",
  "calender": "Koledar",
  "time": "Čas",
  "now": "Zdaj",
  "today": "Danes",
  "maximum": "Maksimum od vseh izbranih",
  "minimum": "Minimum od vseh izbranih"
});