define({
  "showLayerLabels": "Katman adlarını görüntüle",
  "autoPlay": "Kaydırıcıyı otomatik olarak oynat",
  "loopPlay": "Sürekli zaman döngüsü",
  "dateAndTimeFormat": "Tarih ve zaman biçimi",
  "mapDefault": "Harita varsayılanı",
  "custom": "Özel",
  "formatInstruction": "Biçim talimatı",
  "playback": "kayıttan oynatma konumu haritayla kaydedildi",
  "MMMMYYYY": "Temmuz 2015",
  "MMMYYYY": "Tem 2015",
  "MMMMDYYYY": "21 Temmuz 2015",
  "dddMMMDDYYYY": "21 Tem 2015 Salı",
  "MDDYYYY": "21/07/2015",
  "YYYYMDD": "21/7/2015",
  "MDDYY": "21/07/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "21/7/2015 8:00",
  "dddMMMDDhmma": "21 Tem Salı 8:00",
  "sliderSetting": "Kaydırıcı ayarları",
  "autoRefresh": "Kaydırıcı yenileme süresi",
  "timeSetting": "Zaman ayarları",
  "useWebMapSetting": "Web haritası zaman ayarlarını kullan",
  "useConfigureSetting": "Zaman ayarlarını yapılandır",
  "timeSettingBtn": "ayar",
  "calenderError": "Başlangıç zamanı, bitiş zamanından önce olmalıdır.",
  "timeSpan": "Zaman aralığı",
  "startTime": "Başlama Zamanı",
  "endTime": "Bitiş Zamanı",
  "unit": "Birim",
  "timeDisplay": "Zaman göstergesi",
  "displayDataIn": "Verileri",
  "interval": "Aralık",
  "displayAllData": "Tüm verileri ilerlemeli biçimde göster",
  "layerTimeExtent": "Zaman canlandırmasını etkinleştir",
  "layerTableCol1": "Katman",
  "layerTableCol2": "Zaman Yayılımı",
  "timeTo": "-",
  "calender": "Takvim",
  "time": "Saat",
  "now": "Şimdi",
  "today": "Bugün",
  "maximum": "Tüm seçilenlerin maksimumu",
  "minimum": "Tüm seçilenlerin minimumu"
});