define({
  "visible": "Hiển thị bản đồ toàn cảnh theo mặc định",
  "minWidth": "Chiều rộng tối thiểu",
  "minHeight": "Chiều cao tối thiểu",
  "maxWidth": "Chiều rộng tối đa",
  "maxHeight": "Chiều cao tối đa",
  "minText": "Tối thiểu",
  "maxText": "tối đa",
  "attachText": "Chỉ định góc bản đồ đính kèm tiện ích này.",
  "expandText": "Mở rộng tiện ích lúc ban đầu",
  "topLeft": "Trên cùng bên trái",
  "topRight": "Trên cùng bên phải",
  "bottomLeft": "Dưới cùng bên trái",
  "bottomRight": "Dưới cùng bên phải",
  "baseLayerType": "Hiển thị",
  "BaseMap": "Bản đồ nền của bản đồ",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "Dịch vụ ArcGIS Tiled Map",
  "dynamicMapService": "Dịch vụ Bản đồ Động ArcGIS",
  "imageService": "Dịch vụ Hình ảnh ArcGIS",
  "OSM": "Open Street Map",
  "bingRoad": "Bing Maps Road",
  "bingAerial": "Bing Maps Aerial",
  "bingHybrid": "Bing Maps Hybrid",
  "WebTiled": "Lớp Web Tiled",
  "VETiled": "Lớp Virtual Earth Tiled",
  "tileLayerUrl": "URL Lớp Tile",
  "tile": "Tiêu đề",
  "credits": "Credits",
  "subdomain": "Miền con",
  "extent": "Phạm vi",
  "initExtent": "Phạm vi Init",
  "tileInfo": "TileInfo",
  "VEStyle": "Virtual Earth Style",
  "Aerial": "Lớp Bing Maps Aerial",
  "AerialWithLabels": "Lớp Aerial with Labels",
  "Roads": "Lớp Đường",
  "errWkid": "wkid không khớp",
  "errUrl": "URL không hợp lệ",
  "errReqTimeout": "Vượt quá Thời gian chờ",
  "layerPlaceholder": "Nhập URL"
});