define({
  "showLayerLabels": "显示图层名称",
  "autoPlay": "自动播放滑块",
  "loopPlay": "不断循环时间",
  "dateAndTimeFormat": "日期和时间格式",
  "mapDefault": "默认地图",
  "custom": "自定义",
  "formatInstruction": "格式说明",
  "playback": "回放位置随地图保存",
  "MMMMYYYY": "2015 年 7 月",
  "MMMYYYY": "2015 年 7 月",
  "MMMMDYYYY": "2015 年 7 月 21 日",
  "dddMMMDDYYYY": "2015 年 7 月 21 日星期二",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00 am",
  "dddMMMDDhmma": "7 月 21 日星期二 8:00 am",
  "sliderSetting": "滑块设置",
  "autoRefresh": "刷新滑块间隔",
  "timeSetting": "时间设置",
  "useWebMapSetting": "支持 web 地图的时间设置",
  "useConfigureSetting": "配置时间设置",
  "timeSettingBtn": "设置",
  "calenderError": "起始时间必须小于结束时间。",
  "timeSpan": "时间跨度",
  "startTime": "开始时间",
  "endTime": "结束时间",
  "unit": "单位",
  "timeDisplay": "时间显示",
  "displayDataIn": "数据显示方式",
  "interval": "间隔",
  "displayAllData": "逐步显示所有数据",
  "layerTimeExtent": "启用时间动画",
  "layerTableCol1": "图层",
  "layerTableCol2": "时间范围",
  "timeTo": "至",
  "calender": "日历",
  "time": "时间",
  "now": "现在",
  "today": "今天",
  "maximum": "所有已选内容的最大值",
  "minimum": "所有已选内容的最小值"
});