//>>built
define("require exports ./tsSupport/declareExtendsHelper ./tsSupport/decorateHelper dojo/aspect ./Accessor ./ArrayPool ./Evented ./lang ./ObjectPool ./scheduling ./accessorSupport/decorators ./accessorSupport/ensureType".split(" "),function(D,Q,H,z,I,J,w,K,L,M,N,r,E){function y(d){return!!d&&d.isInstanceOf&&d.isInstanceOf(F)}function A(d){return d?y(d)?d.toArray():d.length?Array.prototype.slice.apply(d):[]:[]}function B(d){if(d&&d.length)return d[0]}function G(d,b,l,a){b&&b.forEach(function(c,m,b){d.push(c);
G(d,l.call(a,c,m,b),l,a)})}D=function(){function d(){this.target=null;this.defaultPrevented=this.cancellable=!1}return d.prototype.preventDefault=function(){this.cancellable&&(this.defaultPrevented=!0)},d.prototype.reset=function(b){this.defaultPrevented=!1;this.item=b},d}();var O=function(){},l=new M(D,!0,function(d){d.item=null;d.target=null}),p=new Set,q=new Set,v=new Set,C=new Map,P=0,F=function(d){function b(a){a=d.call(this,a)||this;return a._boundDispatch=a._dispatchColChange.bind(a),a._chgListeners=
[],a._notifications=null,a._timer=null,a.length=0,a._items=[],Object.defineProperty(a,"uid",{value:P++}),a}return H(b,d),u=b,b.ofType=function(a){if(!a)return u;if(C.has(a))return C.get(a);var c;if("function"==typeof a)c=a.prototype.declaredClass;else if(a.base)c=a.base.prototype.declaredClass;else for(var m in a.typeMap){var b=a.typeMap[m].prototype.declaredClass;c?c+=" | "+b:c=b}c=u.createSubclass({declaredClass:"esri.core.Collection\x3c"+c+"\x3e"});m={Type:a,ensureType:"function"==typeof a?E.ensureType(a):
E.ensureOneOfType(a)};return Object.defineProperty(c.prototype,"itemType",{value:m}),C.set(a,c),c},b.prototype.normalizeCtorArgs=function(a){return a?Array.isArray(a)||y(a)?{items:a}:a:{}},Object.defineProperty(b.prototype,"items",{get:function(){return this._items},set:function(a){this._emitBeforeChanges()||(this._splice.apply(this,[0,this.length].concat(A(a))),this._emitAfterChanges())},enumerable:!0,configurable:!0}),b.prototype.on=function(a,c){var m;if(Array.isArray(a)?m=a:-1<a.indexOf(",")&&
(m=a.split(/\s*,\s*/)),m){var b=[];for(a=0;a<m.length;a++)b.push(this.on(m[a],c));return b.remove=function(){for(var a=0;a<b.length;a++)b[a].remove()},b}if("change"===a){var e=this._chgListeners,n={removed:!1,callback:c};return e.push(n),this._notifications&&this._notifications.push({listeners:e.slice(),items:this._items.slice(),changes:[]}),{remove:function(){this.remove=O;n.removed=!0;e.splice(e.indexOf(n),1)}}}return I.after(this,"on"+a,c,!0)},b.prototype.hasEventListener=function(a){return"change"===
a?0<this._chgListeners.length:this.inherited(arguments)},b.prototype.add=function(a,c){if(this._emitBeforeChanges())return this;c=this.getNextIndex(c);return this._splice(c,0,a),this._emitAfterChanges(),this},b.prototype.addMany=function(a,c){if((void 0===c&&(c=this._items.length),!a||!a.length)||this._emitBeforeChanges())return this;c=this.getNextIndex(c);return this._splice.apply(this,[c,0].concat(A(a))),this._emitAfterChanges(),this},b.prototype.removeAll=function(){if(!this.length||this._emitBeforeChanges())return[];
var a=this._splice(0,this.length)||[];return this._emitAfterChanges(),a},b.prototype.clone=function(){return this._createNewInstance({items:this._items.map(L.clone)})},b.prototype.concat=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];a=a.map(A);return this._createNewInstance({items:(b=this._items).concat.apply(b,a)});var b},b.prototype.drain=function(a,c){if(this.length&&!this._emitBeforeChanges()){for(var b=this._splice(0,this.length),f=b.length,e=0;e<f;e++)a.call(c,b[e],e,
b);this._emitAfterChanges()}},b.prototype.every=function(a,c){return this._items.every(a,c)},b.prototype.filter=function(a,c){var b;return b=2===arguments.length?this._items.filter(a,c):this._items.filter(a),this._createNewInstance({items:b})},b.prototype.find=function(a,c){if("function"!=typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,f=b.length,e=0;e<f;e++){var n=b[e];if(a.call(c,n,e,b))return n}},b.prototype.findIndex=function(a,c){if("function"!=typeof a)throw new TypeError(a+
" is not a function");for(var b=this._items,f=b.length,e=0;e<f;e++)if(a.call(c,b[e],e,b))return e;return-1},b.prototype.flatten=function(a,c){var b=[];return G(b,this,a,c),new u(b)},b.prototype.forEach=function(a,c){for(var b=this._items,f=b.length,e=0;e<f;e++)a.call(c,b[e],e,b)},b.prototype.getItemAt=function(a){return this._items[a]},b.prototype.getNextIndex=function(a){var c=this.length;return a=null==a?c:a,0>a?a=0:a>c&&(a=c),a},b.prototype.includes=function(a,c){return void 0===c&&(c=0),!!arguments.length&&
-1!==this._items.indexOf(a,c)},b.prototype.indexOf=function(a,c){return void 0===c&&(c=0),this._items.indexOf(a,c)},b.prototype.join=function(a){return void 0===a&&(a=","),this._items.join(a)},b.prototype.lastIndexOf=function(a,c){return void 0===c&&(c=this.length-1),this._items.lastIndexOf(a,c)},b.prototype.map=function(a,c){a=this._items.map(a,c);return new u({items:a})},b.prototype.reorder=function(a,c){void 0===c&&(c=this.length-1);var b=this.indexOf(a);if(-1!==b){if(0>c?c=0:c>=this.length&&(c=
this.length-1),b!==c){if(this._emitBeforeChanges())return a;this._splice(b,1);this._splice(c,0,a);this._emitAfterChanges()}return a}},b.prototype.pop=function(){if(this.length&&!this._emitBeforeChanges()){var a=B(this._splice(this.length-1,1));return this._emitAfterChanges(),a}},b.prototype.push=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];return this._emitBeforeChanges()?this.length:(this._splice.apply(this,[this.length,0].concat(a)),this._emitAfterChanges(),this.length)},
b.prototype.reduce=function(a,c){var b=this._items;return 2===arguments.length?b.reduce(a,c):b.reduce(a)},b.prototype.reduceRight=function(a,c){var b=this._items;return 2===arguments.length?b.reduceRight(a,c):b.reduceRight(a)},b.prototype.remove=function(a){return this.removeAt(this.indexOf(a))},b.prototype.removeAt=function(a){if(!(0>a||a>=this.length||this._emitBeforeChanges()))return a=B(this._splice(a,1)),this._emitAfterChanges(),a},b.prototype.removeMany=function(a){if(!a||!a.length||this._emitBeforeChanges())return[];
a=y(a)?a.toArray():a;for(var c=this._items,b=[],f=a.length,e=0;e<f;e++){var n=c.indexOf(a[e]);if(-1<n){for(var d=e+1,g=n+1,h=Math.min(a.length-d,c.length-g),k=0;k<h&&a[d+k]===c[g+k];)k++;d=1+k;(n=this._splice(n,d))&&0<n.length&&b.push.apply(b,n);e+=d-1}}return this._emitAfterChanges(),b},b.prototype.reverse=function(){if(this._emitBeforeChanges())return this;var a=this._splice(0,this.length);return a&&(a.reverse(),this._splice.apply(this,[0,0].concat(a))),this._emitAfterChanges(),this},b.prototype.shift=
function(){if(this.length&&!this._emitBeforeChanges()){var a=B(this._splice(0,1));return this._emitAfterChanges(),a}},b.prototype.slice=function(a,c){return void 0===a&&(a=0),void 0===c&&(c=this.length),this._createNewInstance({items:this._items.slice(a,c)})},b.prototype.some=function(a,c){return this._items.some(a,c)},b.prototype.sort=function(a){if(!this.length||this._emitBeforeChanges())return this;var c=this._splice(0,this.length);return arguments.length?c.sort(a):c.sort(),this._splice.apply(this,
[0,0].concat(c)),this},b.prototype.splice=function(a,c){for(var b=[],f=2;f<arguments.length;f++)b[f-2]=arguments[f];if(this._emitBeforeChanges())return[];b=this._splice.apply(this,[a,c].concat(b))||[];return this._emitAfterChanges(),b},b.prototype.toArray=function(){return this._items.slice()},b.prototype.toJSON=function(){return this.toArray()},b.prototype.toLocaleString=function(){return this._items.toLocaleString()},b.prototype.toString=function(){return this._items.toString()},b.prototype.unshift=
function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];return this._emitBeforeChanges()?this.length:(this._splice.apply(this,[0,0].concat(a)),this._emitAfterChanges(),this.length)},b.prototype._createNewInstance=function(a){return new this.constructor(a)},b.prototype._splice=function(a,c){for(var b=[],f=2;f<arguments.length;f++)b[f-2]=arguments[f];var e,d,f=this._items,x=this.constructor.prototype.itemType;if(!this._notifications&&this.hasEventListener("change")&&(this._notifications=
[{listeners:this._chgListeners.slice(),items:this._items.slice(),changes:[]}],this._timer&&this._timer.remove(),this._timer=N.schedule(this._boundDispatch)),c){if(d=f.splice(a,c),this.hasEventListener("before-remove")){var g=l.acquire();g.target=this;g.cancellable=!0;for(var h=0,k=d.length;h<k;h++)e=d[h],g.reset(e),this.emit("before-remove",g),g.defaultPrevented&&(d.splice(h,1),f.splice(a,0,e),a+=1,--h,--k);l.release(g)}if(this.length=this._items.length,this.hasEventListener("after-remove")){e=l.acquire();
e.target=this;e.cancellable=!1;k=d.length;for(h=0;h<k;h++)e.reset(d[h]),this.emit("after-remove",e);l.release(e)}}if(b&&b.length){if(x){h=[];for(k=0;k<b.length;k++)e=b[k],g=x.ensureType(e),null==g&&null!=e||h.push(g);b=h}x=this.hasEventListener("before-add");h=this.hasEventListener("after-add");k=a===this.length;if(x||h){e=l.acquire();e.target=this;e.cancellable=!0;g=l.acquire();g.target=this;g.cancellable=!1;for(var p=0,q=b;p<q.length;p++){var t=q[p];x?(e.reset(t),this.emit("before-add",e),e.defaultPrevented||
(k?f.push(t):f.splice(a++,0,t),this._set("length",f.length),h&&(g.reset(t),this.emit("after-add",g)))):(k?f.push(t):f.splice(a++,0,t),this._set("length",f.length),g.reset(t),this.emit("after-add",g))}l.release(e)}else k?f.push.apply(f,b):f.splice.apply(f,[a,0].concat(b)),this._set("length",f.length)}return(b&&b.length||d&&d.length)&&this._notifyChangeEvent(b,d),d},b.prototype._emitBeforeChanges=function(){var a=!1;if(this.hasEventListener("before-changes")){var b=l.acquire();b.target=this;b.cancellable=
!0;this.emit("before-changes",b);a=b.defaultPrevented;l.release(b)}return a},b.prototype._emitAfterChanges=function(){if(this.hasEventListener("after-changes")){var a=l.acquire();a.target=this;a.cancellable=!1;this.emit("after-changes",a);l.release(a)}},b.prototype._notifyChangeEvent=function(a,b){this.hasEventListener("change")&&this._notifications[this._notifications.length-1].changes.push({added:a,removed:b})},b.prototype._dispatchColChange=function(){if(this._timer&&(this._timer.remove(),this._timer=
null),this._notifications){var a=this._notifications;this._notifications=null;for(var b=this,d=0;d<a.length;d++)!function(a){var c=a.changes;p.clear();q.clear();v.clear();for(var d=0;d<c.length;d++){var f=c[d],g=f.added,f=f.removed;if(g)if(0===v.size&&0===q.size)for(var h=0,k=g;h<k.length;h++)g=k[h],p.add(g);else for(h=0,k=g;h<k.length;h++)g=k[h],q.has(g)?(v.add(g),q.delete(g)):v.has(g)||p.add(g);if(f)if(0===v.size&&0===p.size)for(h=0;h<f.length;h++)g=f[h],q.add(g);else for(h=0;h<f.length;h++)g=f[h],
p.has(g)?p.delete(g):(v.delete(g),q.add(g))}var l=w.acquire();p.forEach(function(a){l.push(a)});var m=w.acquire();q.forEach(function(a){m.push(a)});var t=b._items,u=a.items,r=w.acquire();if(v.forEach(function(a){u.indexOf(a)!==t.indexOf(a)&&r.push(a)}),a.listeners&&(l.length||m.length||r.length))for(c={target:b,added:l,removed:m,moved:r},d=a.listeners.length,g=0;g<d;g++)f=a.listeners[g],f.removed||f.callback.call(b,c);w.release(l);w.release(m);w.release(r)}(a[d]);p.clear();q.clear();v.clear()}},b.isCollection=
y,z([r.property()],b.prototype,"length",void 0),z([r.property()],b.prototype,"items",null),b=u=z([r.subclass("esri.core.Collection")],b);var u}(r.declared(J,K));return F});