//>>built
define(["require","exports"],function(h,k){return function(){function b(a,c,b,d){this._tag=0;this._dataType=99;this._data=a;this._dataView=c;this._pos=b||0;this._end=d||a.byteLength}return b.prototype.clone=function(){return new b(this._data,this._dataView,this._pos,this._end)},b.prototype.pos=function(){return this._pos},b.prototype.next=function(a){for(;;){if(this._pos===this._end)return!1;var c=this._decodeVarint();if(this._tag=c>>3,this._dataType=7&c,!a||a===this._tag)break;this.skip()}return!0},
b.prototype.empty=function(){return this._pos>=this._end},b.prototype.tag=function(){return this._tag},b.prototype.getInt32=function(){return this._decodeVarint()},b.prototype.getInt64=function(){return this._decodeVarint()},b.prototype.getUInt32=function(){var a=4294967295;return a=(127&this._data[this._pos])>>>0,128>this._data[this._pos++]?a:(a=(a|(127&this._data[this._pos])<<7)>>>0,128>this._data[this._pos++]?a:(a=(a|(127&this._data[this._pos])<<14)>>>0,128>this._data[this._pos++]?a:(a=(a|(127&
this._data[this._pos])<<21)>>>0,128>this._data[this._pos++]?a:(a=(a|(15&this._data[this._pos])<<28)>>>0,128>this._data[this._pos++]?a:void 0))))},b.prototype.getUInt64=function(){return this._decodeVarint()},b.prototype.getSInt32=function(){var a=this.getUInt32();return a>>>1^-(1&a)|0},b.prototype.getSInt64=function(){return this._decodeSVarint()},b.prototype.getBool=function(){var a=0!==this._data[this._pos];return this._skip(1),a},b.prototype.getEnum=function(){return this._decodeVarint()},b.prototype.getFixed64=
function(){var a=this._dataView,c=this._pos,a=a.getUint32(c,!0)+4294967296*a.getUint32(c+4,!0);return this._skip(8),a},b.prototype.getSFixed64=function(){var a=this._dataView,c=this._pos,a=a.getUint32(c,!0)+4294967296*a.getInt32(c+4,!0);return this._skip(8),a},b.prototype.getDouble=function(){var a=this._dataView.getFloat64(this._pos,!0);return this._skip(8),a},b.prototype.getFixed32=function(){var a=this._dataView.getUint32(this._pos,!0);return this._skip(4),a},b.prototype.getSFixed32=function(){var a=
this._dataView.getInt32(this._pos,!0);return this._skip(4),a},b.prototype.getFloat=function(){var a=this._dataView.getFloat32(this._pos,!0);return this._skip(4),a},b.prototype.getString=function(){var a=this._getLength(),c=this._pos,c=this._toString(this._data,c,c+a);return this._skip(a),c},b.prototype.getBytes=function(){var a=this._getLength(),c=this._pos,c=this._toBytes(this._data,c,c+a);return this._skip(a),c},b.prototype.getMessage=function(){var a=this._getLength(),c=this._pos,c=new b(this._data,
this._dataView,c,c+a);return this._skip(a),c},b.prototype.skip=function(){switch(this._dataType){case 0:this._decodeVarint();break;case 1:this._skip(8);break;case 2:this._skip(this._getLength());break;case 5:this._skip(4);break;default:throw Error("Invalid data type!");}},b.prototype._skip=function(a){if(this._pos+a>this._end)throw Error("Attempt to skip past the end of buffer!");this._pos+=a},b.prototype._decodeVarint=function(){var a,c=this._data,b=this._pos,d=0;if(10<=this._end-b){if(a=c[b++],
d|=127&a,0!=(128&a))if(a=c[b++],d|=(127&a)<<7,0!=(128&a))if(a=c[b++],d|=(127&a)<<14,0!=(128&a))if(a=c[b++],d|=(127&a)<<21,0!=(128&a))if(a=c[b++],d+=268435456*(127&a),0!=(128&a))if(a=c[b++],d+=34359738368*(127&a),0!=(128&a))if(a=c[b++],d+=4398046511104*(127&a),0!=(128&a))if(a=c[b++],d+=562949953421312*(127&a),0!=(128&a))if(a=c[b++],d+=72057594037927936*(127&a),0!=(128&a))if(a=c[b++],d+=0x7fffffffffffffff*(127&a),0!=(128&a))throw Error("Varint too long!");}else{for(var e=1;b!==this._end&&0!=(128&(a=
c[b]));)++b,d+=(127&a)*e,e*=128;if(b===this._end)throw Error("Varint overrun!");++b;d+=a*e}return this._pos=b,d},b.prototype._decodeSVarint=function(){var a=this._decodeVarint();return a%2?-(a+1)/2:a/2},b.prototype._getLength=function(){if(2!==this._dataType)throw Error("Not a delimited data type!");return this._decodeVarint()},b.prototype._toString=function(a,b,f){var c="",e="";for(f=Math.min(this._end,f);b<f;++b){var g=a[b];128&g?e+="%"+g.toString(16):(c+=decodeURIComponent(e)+String.fromCharCode(g),
e="")}return e.length&&(c+=decodeURIComponent(e)),c},b.prototype._toBytes=function(a,b,f){return f=Math.min(this._end,f),new Uint8Array(a.buffer,b,f-b)},b}()});