define({
  "showLayerLabels": "Visualizar nombres de capas",
  "autoPlay": "Reproducir el control deslizante automáticamente",
  "loopPlay": "Reproducción temporal continua",
  "dateAndTimeFormat": "Formato de fecha y hora",
  "mapDefault": "Predeterminado de mapa",
  "custom": "Personalizado",
  "formatInstruction": "Instrucción de formato",
  "playback": "posición de reproducción guardada con el mapa",
  "MMMMYYYY": "Julio de 2015",
  "MMMYYYY": "Jul 2015",
  "MMMMDYYYY": "Julio 21,2015",
  "dddMMMDDYYYY": "Mar jul 21,2015",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15",
  "YYYY": "2015",
  "MDDYYYYhmma": "7/21/2015 8:00 am",
  "dddMMMDDhmma": "Mar jul 21 8:00 am",
  "sliderSetting": "Ajustes de control deslizante",
  "autoRefresh": "Refrescar control deslizante cada",
  "timeSetting": "Configuración de tiempo",
  "useWebMapSetting": "Respetar la configuración de tiempo del mapa web",
  "useConfigureSetting": "Configurar los ajustes de tiempo",
  "timeSettingBtn": "configurar",
  "calenderError": "La hora de inicio debe ser anterior a la hora de finalización.",
  "timeSpan": "Intervalo de tiempo",
  "startTime": "Hora de inicio",
  "endTime": "Hora de finalización",
  "unit": "Unidad",
  "timeDisplay": "Visualización de la hora",
  "displayDataIn": "Mostrar datos en",
  "interval": "Intervalo",
  "displayAllData": "Mostrar progresivamente todos los datos",
  "layerTimeExtent": "Habilitar la animación temporal",
  "layerTableCol1": "Capa",
  "layerTableCol2": "Extensión de tiempo",
  "timeTo": "a",
  "calender": "Calendario",
  "time": "Tiempo",
  "now": "Ahora",
  "today": "Hoy",
  "maximum": "Máximo de seleccionados",
  "minimum": "Mínimo de seleccionados"
});