define({
  root: ({
    _widgetLabel: "Demo",
    label1: "I am a demo widget.",
    label2: "This is configurable.",
    nationalLayerText: "Changing the appearance of national layers is not possible when you are zoomed out beyond a multi-county area. Zoom in to view data with customized appearance or use the reset button to return to the default appearance."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 1
});
