define({
  "styleText": "Kaydırma aracı türü",
  "vertical": "Dikey çubuk",
  "horizontal": "Yatay çubuk",
  "scope": "Dürbün",
  "placement": "Yön",
  "showLeftSide": "Kaydırılan katmanları sol tarafta göster",
  "showRigthSide": "Kaydırılan katmanları sağ tarafta göster",
  "showUpSide": "Kaydırılan katmanları üst tarafta göster",
  "showDownSide": "Kaydırılan katmanları alt tarafta göster",
  "barColor": "Çubuk rengi",
  "swipeMode": "Kaydırma modu",
  "singleLayer": "Tek katman",
  "MultipleLayers": "Birden çok katman",
  "allowToSwipe": "Kaydırmaya izin ver",
  "layer": "Katman",
  "swipeByDefault": "Varsayılan olarak kaydır",
  "defaultLayerMustBeVisible": "varsayılan katman görünür olmalıdır",
  "noDefaultLayer": "Lütfen varsayılan olarak kaydırılacak katmanları ayarlayın",
  "defaultLayerHolder": "Seçmek için tıklayın",
  "selectLayers": "Katmanları seç",
  "layerText": "Varsayılan kaydırma katmanları",
  "spyglassText": "Küçük dürbünde varsayılan olarak görüntülenecek katmanı seçin.",
  "layerHint": "Not: Katman daha üst katmanlar tarafından gizleniyorsa, kaydırmanın herhangi bir etkisi olmaz.",
  "isZoom": "Kaydırma katmanına yakınlaştır",
  "isZooms": "Kaydırma katman(lar)ına yakınlaştır",
  "layersAvailable": "Kaydırılabilir katmanlar",
  "hidePanel": "Araç açıldığında katman seçme panelini gizle"
});