define({
  "styleText": "סוג כלי החלקה",
  "vertical": "סרגל אנכי",
  "horizontal": "סרגל אופקי",
  "scope": "זכוכית מגדלת",
  "placement": "כיוון",
  "showLeftSide": "הצג שכבות החלקה בצד שמאל",
  "showRigthSide": "הצג שכבות החלקה בצד ימין",
  "showUpSide": "הצג שכבות החלקה בחלק העליון",
  "showDownSide": "הצג שכבות החלקה בחלק התחתון",
  "barColor": "צבע סרגל",
  "swipeMode": "מצב החלקה",
  "singleLayer": "שכבה יחידה",
  "MultipleLayers": "שכבות מרובות",
  "allowToSwipe": "אפשר כדי להחליק",
  "layer": "שכבה",
  "swipeByDefault": "החלקה כברירת מחדל",
  "defaultLayerMustBeVisible": "השכבה המוגדרת כברירת מחדל חייב להיות גלויה",
  "noDefaultLayer": "הגדר את השכבות להחלקה כברירת מחדל",
  "defaultLayerHolder": "לחץ כדי לבחור",
  "selectLayers": "בחר שכבות",
  "layerText": "ברירת מחדל של שכבות החלקה",
  "spyglassText": "בחר את השכבה שתוצג בזכוכית מגדלת כברירת מחדל.",
  "layerHint": "הערה: אם השכבה מוסתרת על ידי שכבות עליונות יותר, להחלפה לא תהיה השפעה.",
  "isZoom": "התמקד בשכבת ההחלקה",
  "isZooms": "התמקד בשכבות ההחלקה",
  "layersAvailable": "שכבות שניתנות להחלקה",
  "hidePanel": "הסתר את השכבה על ידי בחירת פאנל כאשר הווידג'ט נפתח"
});