define({
  "visible": "Exibir mapa de vista geral por defeito",
  "minWidth": "Largura mínima",
  "minHeight": "Peso mínima",
  "maxWidth": "Largura máxima",
  "maxHeight": "Altura máxima",
  "minText": "Mínimo",
  "maxText": "máximo",
  "attachText": "Especifique o canto do mapa no qual este widget será anexado.",
  "expandText": "Expandir o widget inicialmente",
  "topLeft": "Superior esquerda",
  "topRight": "Superior direita",
  "bottomLeft": "Inferior esquerda",
  "bottomRight": "Inferior direita",
  "baseLayerType": "Exibir",
  "BaseMap": "O mapa base do mapa",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "Serviço de mapa do mosaico do ArcGIS",
  "dynamicMapService": "Serviço de mapa dinâmico do ArcGIS",
  "imageService": "Serviço de imagem do ArcGIS",
  "OSM": "OpenStreetMap",
  "bingRoad": "Bing Maps Estradas",
  "bingAerial": "Bing Maps Aéreos",
  "bingHybrid": "Bing Maps Híbridos",
  "WebTiled": "Camada de mosaicos web",
  "VETiled": "Camada de mosaicos Virtual Earth",
  "tileLayerUrl": "URL da camada de mosaicos",
  "tile": "Título",
  "credits": "Créditos",
  "subdomain": "Subdomínio",
  "extent": "Extensão:",
  "initExtent": "Inic Extensão",
  "tileInfo": "TileInfo",
  "VEStyle": "Estilo de Virtual Earth",
  "Aerial": "Camada aérea de Bing Maps",
  "AerialWithLabels": "Camada aérea com rótulos",
  "Roads": "Camada de estradas",
  "errWkid": "wkid não coincide",
  "errUrl": "O URL não é válido",
  "errReqTimeout": "Limite de tempo excedido",
  "layerPlaceholder": "Introduzir URL"
});