//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/_base/lang dojox/gfx dojo/on dojo/dom-construct dojo/dom-attr dojo/_base/array dojo/dom dojo/query dojo/dom-class dojo/dom-style dojo/Evented esri/symbols/jsonUtils".split(" "),function(t,y,u,z,w,b,m,x,D,A,f,n,B,C){return t([y,B],{"class":"widgets-Search-list",_itemCSS:"search-list-item",_itemSelectedCSS:"search-list-item selected",_itemAltCSS:"search-list-item alt",parentWidget:null,_wrapResults:null,startup:function(){this.items=[];this.selectedIndex=
-1;this._selectedNode=null;this._listContainer=b.create("div");f.add(this._listContainer,"search-list-container");this.own(w(this._listContainer,"click",u.hitch(this,this._onClick)));b.place(this._listContainer,this.domNode)},add:function(a){if(0!==arguments.length){this.items.push(a);var d=b.create("div");m.set(d,"id",this.id.toLowerCase()+a.id);var p=b.create("div");m.set(p,"id",this.id.toLowerCase()+a.id);f.add(p,"iconDiv");b.place(p,d);var c=b.create("div");b.place(c,d);f.add(c,"removediv");m.set(c,
"id",this.id.toLowerCase()+a.id);var e=b.create("div");f.add(e,"removedivImg");b.place(e,c);m.set(e,"id",this.id.toLowerCase()+a.id);m.set(e,"title",a.removeResultMsg);this.own(w(e,"click",u.hitch(this,this._onRemove)));c=b.create("p");m.set(c,"id",this.id.toLowerCase()+a.id);f.add(c,"_title");c.textContent=c.innerText=a.title;b.place(c,d);a.alt?f.add(d,this._itemAltCSS):f.add(d,this._itemCSS);this._wrapResults&&f.add(d,"result-wrap");if(""!==a.rsltcontent)for(var c=a.rsltcontent.split("\x3cbr\x3e"),
h,g,r,k,l,t=c.length,v=0;v<t;v++){e=c[v].split(": ");k=b.create("font");m.set(k,"id",this.id.toLowerCase()+a.id);-1<e[0].toLowerCase().indexOf("\x3cem\x3e")&&n.set(k,"font-style","italic");-1<e[0].toLowerCase().indexOf("\x3cstrong\x3e")&&n.set(k,"font-weight","bold");-1<e[0].toLowerCase().indexOf("\x3cu\x3e")&&n.set(k,"text-decoration","underline");if(h=-1<e[0].toLowerCase().indexOf("\x3cfont color\x3d'")?!0:!1)g=e[0].toLowerCase().indexOf("\x3cfont color\x3d'")+13,r=e[0].toLowerCase().indexOf("'\x3e",
g),h=e[0].substr(g,r-g),n.set(k,"color",h);k.textContent=k.innerText=e[0].replace(/<[\/]{0,1}(em|EM|strong|STRONG|font|FONT|u|U)[^><]*>/g,"");h=b.create("p");m.set(h,"id",this.id.toLowerCase()+a.id);f.add(h,"label");l=b.create("font");-1<e[1].toLowerCase().indexOf("\x3cem\x3e")&&n.set(l,"font-style","italic");-1<e[1].toLowerCase().indexOf("\x3cstrong\x3e")&&n.set(l,"font-weight","bold");-1<e[1].toLowerCase().indexOf("\x3cu\x3e")&&n.set(l,"text-decoration","underline");if(g=-1<e[1].toLowerCase().indexOf("\x3cfont color\x3d'")?
!0:!1)g=e[1].toLowerCase().indexOf("\x3cfont color\x3d'")+13,r=e[1].toLowerCase().indexOf("'\x3e",g),g=e[1].substr(g,r-g),n.set(l,"color",g);l.textContent="null"===e[1]?l.innerText=": ":l.innerText=": "+e[1].replace(/<[\/]{0,1}(em|EM|strong|STRONG|font|FONT|u|U)[^><]*>/g,"");b.place(k,h);b.place(l,h);b.place(h,d)}else c=b.create("p"),f.add(c,"label"),c.textContent=c.innerText=" ",b.place(c,d);if(!document.all||document.addEventListener)p=z.createSurface(p,40,40),c=C.getShapeDescriptors(a.sym),c.defaultShape&&
p.createShape(c.defaultShape).setFill(c.fill).setStroke(c.stroke).applyTransform({dx:20,dy:20});var q;if(a.links&&0<a.links.length||a.showRelate)q=b.create("div"),b.place(q,d),f.add(q,"linksdiv");x.forEach(a.links,function(a){"text"===a.popuptype?(a=b.toDom("\x3cp\x3e\x3ca href\x3d'"+a.link+"' target\x3d'_blank' title\x3d'"+a.alias+"'\x3e"+a.alias+"\x3c/a\x3e\x3c/p\x3e"),b.place(a,q,"before"),f.add(a,"labellink")):(a=b.toDom("\x3ca href\x3d'"+a.link+"' target\x3d'_blank' title\x3d'"+a.alias+"'\x3e\x3cimg src\x3d'"+
a.icon+"' alt\x3d'"+a.alias+"' border\x3d'0' width\x3d'20px' height\x3d'20px'\x3e\x3c/a\x3e"),b.place(a,q),f.add(a,"linkIcon"))});b.place(d,this._listContainer)}},addComplete:function(){this.clearSelection()},remove:function(a){var d=this.items[a];b.destroy(this.id.toLowerCase()+d.id+"");this.items.splice(a,1);0===this.items.length&&this._init();d.id===this._selectedNode&&(this._selectedNode=null);this.clearSelection()},_init:function(){this.selectedIndex=-1;this._selectedNode=null},clear:function(){this.items.length=
0;this._listContainer.innerHTML="";this._init()},_onClick:function(a){if(""!==a.target.id||""!==a.target.parentNode.id){var d=a.target.id.toLowerCase();d||(d=a.target.parentNode.id);if(a=this._getItemById(d)){f.replace(d,this._itemSelectedCSS,a.alt?this._itemAltCSS:this._itemCSS);if(this._selectedNode){var b=this._getItemById(this._selectedNode);b&&f.replace(this._selectedNode,b.alt?this._itemAltCSS:this._itemCSS,this._itemSelectedCSS)}this._selectedNode=d;this.emit("click",this.selectedIndex,a)}}},
_onRemove:function(a){a.stopPropagation();var d=a.target.id.toLowerCase();d||(d=a.target.parentNode.id);if(a=this._getItemById(d))this._selectedNode=d,this.emit("remove",this.selectedIndex,a)},_getItemById:function(a){a=a.replace(this.id.toLowerCase(),"");for(var d=this.items.length,b,c=0;c<d;c++)if(b=this.items[c],b.id===a)return this.selectedIndex=c,b;return null},clearSelection:function(){this._selectedNode=null;this.selectedIndex=-1;A(".search-list-item").forEach(function(a){f.remove(a,"alt")});
x.map(this.items,u.hitch(this,function(a,b){a.alt=0===b%2;a.alt&&f.add(this.id.toLowerCase()+a.id+"","alt")}))},setSelectedItem:function(a){var b=this._getItemById(a);b&&(f.replace(a,this._itemSelectedCSS,b.alt?this._itemAltCSS:this._itemCSS),this._selectedNode&&(b=this._getItemById(this._selectedNode))&&f.replace(this._selectedNode,b.alt?this._itemAltCSS:this._itemCSS,this._itemSelectedCSS),this._selectedNode=a)},getSelectedItem:function(){if(this._selectedNode)return this._getItemById(this._selectedNode)},
hasSelectedItem:function(){return this._selectedNode?!0:!1}})});