//>>built
define("dojo/_base/declare dojo/Evented dojo/on dojo/_base/lang dojo/_base/html esri/tasks/query esri/tasks/QueryTask esri/tasks/FeatureSet dojo/keys dojo/date/locale".split(" "),function(h,k,n,b,p,g,l,q,r,m){return h([k],{baseClass:"search-paging-query-task",uri:"",fieldName:"",query:null,queryTask:null,objectIdsArray:[],iStart:0,iMaxRecords:0,isQuerying:!1,featuresProcessed:0,featuresTotal:0,dateFormat:"",useUTC:!0,blankStringExists:!1,allString:"all",defExpr:"",version:0,allValues:[],uniqueValues:[],
esc:!1,isRequired:!1,maxRecordCount:250,startup:function(){this.inherited(arguments);this.query=new g},execute:function(){this.uniqueValues=[];this.blankStringExists=!1;this.featuresTotal=this.featuresProcessed=this.iMaxRecords=this.iStart=0;this.isQuerying=!0;this.query.returnGeometry=!1;this.query.outFields=[this.fieldName];10.11<this.version&&(this.query.orderByFields=[this.fieldName]);this.query.objectIds=null;this.query.where=this.defExpr&&""!==this.defExpr?this.defExpr:"1\x3d1";if(""===this.uri)this.emit("pagingFault");
else if(console.info(this.uri),this.queryTask=new l(this.uri),10.1<=this.version){var a=new g;a.where=this.defExpr&&""!==this.defExpr?this.defExpr:"1\x3d1";this.queryTask.executeForCount(a,b.hitch(this,function(a){this.featuresTotal=a;a<=this.maxRecordCount?(this.allValues=[],this.query.returnDistinctValues=!0,this.queryTask.execute(this.query,b.hitch(this,this.onSearchFinish),b.hitch(this,this.onSearchError))):(delete this.query.orderByFields,this.queryTask.executeForIds(this.query,b.hitch(this,
this.onSearchIdsFinish),b.hitch(this,this.onSearchError)))}))}else this.queryTask.executeForIds(this.query,b.hitch(this,this.onSearchIdsFinish),b.hitch(this,this.onSearchError))},onSearchFinish:function(a){this.query.where="";this.query.text=null;if(10.1>this.version||this.featuresTotal>this.maxRecordCount)this.featuresProcessed+=a.features.length,this.emit("featuresProcessed",this.featuresProcessed);for(var d=a.features.length,e=0;e<d;e++){var f=a.features[e].attributes,c;for(c in f)f[c]&&this.allValues.push(f[c])}10.1<=
this.version&&this.featuresTotal<=this.maxRecordCount?(this.isQuerying=!1,""!==this.dateFormat?this.replaceDatesWithStrings():(this.uniqueValues=this.getDistinctValues(this.allValues),!1===this.isRequired&&(this.blankStringExists&&(a={code:" ",name:'" "'},this.uniqueValues.splice(0,0,a)),a={code:"",name:""},this.uniqueValues.splice(0,0,a)),this.uniqueValues.push({code:"allu",name:this.allString}),this.emit("pagingComplete",this.uniqueValues))):this.featuresProcessed>=this.objectIdsArray.length?(this.uniqueValues=
this.getDistinctValues(this.allValues),""!==this.dateFormat?this.replaceDatesWithStrings():(!1===this.isRequired&&(this.blankStringExists&&(a={code:" ",name:'" "'},this.uniqueValues.splice(0,0,a)),a={code:"",name:""},this.uniqueValues.splice(0,0,a)),this.uniqueValues.push({code:"allu",name:this.allString}),this.emit("pagingComplete",this.uniqueValues),this.isQuerying=!1)):(0===this.iMaxRecords&&(this.iMaxRecords=this.featuresProcessed,this.iStart+=this.iMaxRecords),this.iStart<this.objectIdsArray.length&&
!1===this.esc&&(this.isQuerying=!0,this.query.objectIds=this.objectIdsArray.slice(this.iStart,this.iStart+this.iMaxRecords),this.queryTask.execute(this.query,b.hitch(this,this.onSearchFinish),b.hitch(this,this.onSearchError)),this.iStart+=this.iMaxRecords),!0===this.esc&&(this.isQuerying=this.esc=!1,this.emit("pagingComplete",this.uniqueValues)),this.uniqueValues=this.getDistinctValues(this.allValues))},_formatDate:function(a,d){this.dateFormat&&(this.dateFormat=this.dateFormat.replace(/D/g,"d").replace(/Y/g,
"y"));return m.format(new Date(a),{selector:"date",datePattern:d})},replaceDatesWithStrings:function(){for(var a,d=0;d<this.uniqueValues.length;d++){var b=Number(this.uniqueValues[d].code);isNaN(b)||(a=this._formatDate(b,this.dateFormat));this.uniqueValues[d].name=a;this.uniqueValues[d].code=a}this.isQuerying=!1;this.emit("pagingComplete",this.uniqueValues)},onSearchError:function(){this.objectIdsArray=[];this.esc=this.isQuerying=!1;this.emit("pagingFault")},onSearchIdsFinish:function(a){0<a.length?
(this.allValues=[],this.objectIdsArray=a,this.featuresTotal=this.objectIdsArray.length,this.emit("featuresTotal",this.featuresTotal),this.query.where=null,this.query.text=null,this.query.objectIds=this.objectIdsArray.slice(0,this.maxRecordCount),this.queryTask.execute(this.query,b.hitch(this,this.onSearchFinish),b.hitch(this,this.onSearchError))):(console.error("onSearchIdsFinish returned zero length"),this.esc=this.isQuerying=!1,this.emit("pagingFault"))},getDistinctValues:function(a){var b=[],e=
[],f=a.length,c;for(c=0;c<f;c++)b[a[c]]||(b[a[c]]=!0," "===a[c]?this.blankStringExists=!0:e.push(null===a[c]?{code:"null",name:"null"}:{code:a[c],name:a[c]}));return function(a,b){return a.sort(function(a,c){a=a[b];c=c[b];"string"==typeof a&&(a=a.toLowerCase().trim(),c=c.toLowerCase().trim());return a<c?-1:a>c?1:0})}(e,"code")}})});