define({
  "instruction": "Uzplaiksnījuma ekrāns tiks parādīts, pirms iespējams piekļūt lietotnei.",
  "defaultContent": "Šeit varat pievienot tekstu, tīmekļa saites un nelielus attēlus.",
  "requireConfirm": "Pieprasīt apstiprinājumu, lai turpinātu",
  "noRequireConfirm": "Nepieprasīt apstiprinājumu, lai turpinātu",
  "optionText": "Iespēja deaktivizēt uzplaiksnījuma ekrānu, lietotājam startējot lietotni.",
  "confirmLabel": "Apstiprinājuma teksti: ",
  "confirmLabelColor": "Apstiprinājuma teksta krāsa",
  "defaultConfirmText": "Piekrītu iepriekš norādītajiem noteikumiem un nosacījumiem",
  "confirmOption": "Vienmēr rādīt šo uzplaiksnījuma ekrānu ikreiz, kad tiek palaista lietotne",
  "backgroundColor": "Fona krāsa",
  "content": "Saturs",
  "contentDescription": "Definējiet saturu, kas tiek parādīts uzplaiksnījuma ekrānā.",
  "appearance": "Izskats",
  "appearanceDescription": "Iestatiet uzplaiksnījuma ekrāna izskatu.",
  "size": "Izmērs",
  "width": "Platums",
  "height": "Augstums",
  "custom": "Pielāgots",
  "background": "Fons",
  "colorFill": "Krāsu aizpildījums",
  "imageFill": "Attēlu aizpildījums",
  "chooseFile": "Izvēlēties failu",
  "noFileChosen": "Nav izvēlēts neviens fails",
  "sizeFill": "Aizpildījums",
  "sizeFit": "Ietilpināt",
  "sizeStretch": "Izstiept, lai aizpildītu",
  "sizeCenter": "Centrs",
  "sizeTile": "Mozaīka",
  "buttonColor": "Pogas krāsa",
  "buttonText": "Pogas teksts",
  "buttonTextColor": "Pogas teksta krāsa",
  "contentAlign": "Satura līdzinājums",
  "alignTop": "Augšdaļā",
  "alignMiddle": "Vidū",
  "maskColor": "Maskas krāsa",
  "options": "Iespējas",
  "optionsDescription": "Iestatiet uzplaiksnījuma ekrāna uzvedību."
});