define({
  "visible": "Átnézeti térkép megjelenítése alapértelmezésben",
  "minWidth": "Min. szélesség",
  "minHeight": "Min. magasság",
  "maxWidth": "Max. szélesség",
  "maxHeight": "Max. magasság",
  "minText": "Minimum",
  "maxText": "maximum",
  "attachText": "Adja meg, hogy a térkép melyik sarkában legyen ez a widget.",
  "expandText": "A widget kezdeti kibontása",
  "topLeft": "Bal felső",
  "topRight": "Jobb felső",
  "bottomLeft": "Bal alsó",
  "bottomRight": "Jobb alsó",
  "baseLayerType": "Megjelenítés",
  "BaseMap": "A térkép alaptérképe",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "ArcGIS csempézett térképi adatszolgáltatás",
  "dynamicMapService": "Szakasz dinamikus térképi adatszolgáltatás",
  "imageService": "ArcGIS képszolgáltatás",
  "OSM": "Open Street Map",
  "bingRoad": "Bing térkép – úthálózat",
  "bingAerial": "Bing térkép – távérzékelt",
  "bingHybrid": "Bing térkép – hibrid",
  "WebTiled": "Webes csemperéteg",
  "VETiled": "Virtuális Föld-csemperéteg",
  "tileLayerUrl": "Csemperéteg URL-je",
  "tile": "Cím",
  "credits": "Kreditek",
  "subdomain": "Altartomány",
  "extent": "Kiterjedés",
  "initExtent": "Kezdeti kiterjedés",
  "tileInfo": "Csempeinformáció",
  "VEStyle": "Virtuális Föld-stílus",
  "Aerial": "Bing térkép – távérzékelt réteg",
  "AerialWithLabels": "Távérzékelt – feliratréteggel",
  "Roads": "Úthálózati réteg",
  "errWkid": "wkid nem egyezik",
  "errUrl": "Érvénytelen URL",
  "errReqTimeout": "Időtúllépés",
  "layerPlaceholder": "Írja be az URL-címet"
});