define({
  "visible": "Mostrar mapa de visão geral por padrão",
  "minWidth": "Largura mínima",
  "minHeight": "Altura mínima",
  "maxWidth": "Largura máxima",
  "maxHeight": "Altura máxima",
  "minText": "Mínimo",
  "maxText": "Máximo",
  "attachText": "Especifica qual canto do mapa anexar este widget.",
  "expandText": "Expandir inicialmente o widget",
  "topLeft": "Superior esquerdo",
  "topRight": "Superior direito",
  "bottomLeft": "Inferior esquerdo",
  "bottomRight": "Inferior direito",
  "baseLayerType": "Exibir",
  "BaseMap": "O mapa base do mapa",
  "ArcGIS": "utilitário",
  "tiledMapService": "Serviços de Mapa do Mosaico do ArcGIS",
  "dynamicMapService": "Serviços de Mapa do Dinâmico do ArcGIS",
  "imageService": "Serviços de Imagem do ArcGIS",
  "OSM": "Abrir Mapa de Estradas",
  "bingRoad": "Bing Maps Rodoviários",
  "bingAerial": "Bing Maps Aéreos",
  "bingHybrid": "Bing Maps Híbridos",
  "WebTiled": "Camada de Mosaico da Web",
  "VETiled": "Camada de Mosaico do Virtual Earth",
  "tileLayerUrl": "URL da Camada de Mosaico",
  "tile": "Título",
  "credits": "Créditos",
  "subdomain": "Subdomínio",
  "extent": "Extensão",
  "initExtent": "Extensão Inicial",
  "tileInfo": "TileInfo",
  "VEStyle": "Estilo do Virtual Earth",
  "Aerial": "Camada do Bing Maps Aéreo",
  "AerialWithLabels": "Aéreo com Camada de Rótulos",
  "Roads": "Camada de Estradas",
  "errWkid": "wkid não correspondente",
  "errUrl": "URL Inválida",
  "errReqTimeout": "Tempo limite excedido",
  "layerPlaceholder": "Digitar URL"
});