define({
  "showLayerLabels": "Vis lagnavne",
  "autoPlay": "Afspil automatisk skydekontrollen",
  "loopPlay": "Kontinuerlig tidsløkke",
  "dateAndTimeFormat": "Dato- og tidsformat",
  "mapDefault": "Kortstandard",
  "custom": "Brugerdefineret",
  "formatInstruction": "Formatinstruktion",
  "playback": "afspilningsposition gemt på kortet",
  "MMMMYYYY": "Juli 2015",
  "MMMYYYY": "Jul 2015",
  "MMMMDYYYY": "21. juli 2015",
  "dddMMMDDYYYY": "Tir 21. jul. 2015",
  "MDDYYYY": "21-07-2015",
  "YYYYMDD": "21/7/2015",
  "MDDYY": "21-07-2015",
  "YYYY": "2015",
  "MDDYYYYhmma": "21/7/2015 8:00",
  "dddMMMDDhmma": "Tir 21. jul. 8:00",
  "sliderSetting": "Indstillinger for skyderen",
  "autoRefresh": "Opdater skyderen hver",
  "timeSetting": "Tidsindstillinger",
  "useWebMapSetting": "Overhold tidsindstillingerne på webkortet",
  "useConfigureSetting": "Konfigurér tidsindstillinger",
  "timeSettingBtn": "indstilling",
  "calenderError": "Starttidspunktet skal være mindre end sluttidspunktet.",
  "timeSpan": "Tidsrum",
  "startTime": "Starttid",
  "endTime": "Sluttid",
  "unit": "Enhed",
  "timeDisplay": "Tidsvisning",
  "displayDataIn": "Vis data i",
  "interval": "Interval",
  "displayAllData": "Vis alle data progressivt",
  "layerTimeExtent": "Aktivér tidsanimation",
  "layerTableCol1": "Lag",
  "layerTableCol2": "Tidsudstrækning",
  "timeTo": "til",
  "calender": "Kalender",
  "time": "Tid",
  "now": "Nu",
  "today": "I dag",
  "maximum": "Største antal valgte",
  "minimum": "Mindste antal valgte"
});