define({
  "showLayerLabels": "Показать имена слоев",
  "autoPlay": "Автоматически запускать бегунок",
  "loopPlay": "Непрерывный цикл времени",
  "dateAndTimeFormat": "Формат даты и времени",
  "mapDefault": "Карта по умолчанию",
  "custom": "Пользовательский",
  "formatInstruction": "Инструкции по форматированию",
  "playback": "позиции воспроизведения, сохраненной с картой.",
  "MMMMYYYY": "Июль 2015",
  "MMMYYYY": "Июль 2015",
  "MMMMDYYYY": "21 июля 2015",
  "dddMMMDDYYYY": "Вт 21 июля 2015",
  "MDDYYYY": "7/21/2015",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/2015",
  "YYYY": "2015",
  "MDDYYYYhmma": "21.07.2015 08:00",
  "dddMMMDDhmma": "Вт 21 июля 08:00",
  "sliderSetting": "Настройки бегунка",
  "autoRefresh": "Обновлять бегунок каждые",
  "timeSetting": "Настройки времени",
  "useWebMapSetting": "Учитывать настройки времени в веб-карте",
  "useConfigureSetting": "Настройка параметров времени",
  "timeSettingBtn": "настройка",
  "calenderError": "Время начала должно быть меньше времени окончания.",
  "timeSpan": "Временной диапазон",
  "startTime": "Время начала",
  "endTime": "Время окончания",
  "unit": "Единицы измерения",
  "timeDisplay": "Отображение времени",
  "displayDataIn": "Отобразить данные в",
  "interval": "Интервал",
  "displayAllData": "Прогрессивное отображение всех данных",
  "layerTimeExtent": "Включение анимации во времени",
  "layerTableCol1": "Слой",
  "layerTableCol2": "Временной экстент",
  "timeTo": "по",
  "calender": "Календарь",
  "time": "Время",
  "now": "Сейчас",
  "today": "Сегодня",
  "maximum": "Максимальное из выбранного",
  "minimum": "Минимальное из выбранного"
});