//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/config dojo/Evented dijit/_WidgetBase dojo/when dojo/promise/all dojo/Deferred esri/request ./utils moment/moment dojo/date/locale dojo/i18n esri/lang esri/TimeExtent".split(" "),function(u,e,v,w,x,p,q,y,z,g,r,k,t,A,B){var m=u([x,w],{nls:null,config:null,map:null,layerInfosObj:null,_INIT_TIME_STEAMP:null,setLayerInfosObj:function(a){this.layerInfosObj=a},_getUpdatedFullTime:function(){var a=0,c,b,d=[],a=0;for(c=this.map.layerIds.length;a<c;a++)b=
this.map.layerIds[a],b=this.map.getLayer(b),d.push(this._getUpdatedTime(b));a=0;for(c=this.map.graphicsLayerIds.length;a<c;a++)b=this.map.graphicsLayerIds[a],b=this.map.getLayer(b),d.push(this._getUpdatedTime(b));return q(d).then(e.hitch(this,function(a){return this._getFullTimeExtent(a)}))},_getFullTimeExtent:function(a){return g.getFullTimeExtent(a)},_getUpdatedTime:function(a){if(a&&a.url&&g.hasLiveData(a)){var c=null;return z({url:a.url,callbackParamName:"callback",content:{f:"json",returnUpdates:!0}}).then(e.hitch(this,
function(b){b.timeExtent&&2===b.timeExtent.length&&(c=new B,c.startTime=new Date(b.timeExtent[0]),c.endTime=new Date(b.timeExtent[1]),a.timeInfo.timeExtent=c)})).always(e.hitch(this,function(){return p(c||e.getObject("timeInfo.timeExtent",!1,a)||null)}))}return p(e.getObject("timeInfo.timeExtent",!1,a)||null)},getUpdatedFullTime:function(){var a=0,c,b,d=[],a=0;for(c=this.map.layerIds.length;a<c;a++)b=this.map.layerIds[a],b=this.map.getLayer(b),d.push(this._getUpdatedTime(b));a=0;for(c=this.map.graphicsLayerIds.length;a<
c;a++)b=this.map.graphicsLayerIds[a],b=this.map.getLayer(b),d.push(this._getUpdatedTime(b));return q(d).then(e.hitch(this,function(a){return this._getFullTimeExtent(a)}))},setTimeSlider:function(a){this.timeSlider=a;this._INIT_TIME_STEAMP=(new Date).getTime()},_getTimeFormatLabel:function(a){var c=this.nls.timeExtent,b=null,d=null,f="",e="";if(!a&&this.timeSlider)2===this.timeSlider.thumbCount?(b=this.timeSlider.timeStops[this.timeSlider.thumbIndexes[0]],d=this.timeSlider.timeStops[this.timeSlider.thumbIndexes[1]]):
b=this.timeSlider.timeStops[this.timeSlider.thumbIndexes[0]];else if(a||this.timeSlider)b=a.startTime,0<a.endTime.getTime()-a.startTime.getTime()&&(d=a.endTime);else return"";if("auto"===this.config.timeFormat||"Custom"===this.config.timeFormat&&""===this.config.customDateFormat){var n=null,l=a=null,h=!1,f=m.localeDic[v.locale]||m.localeDic.en;d&&b.getFullYear()===d.getFullYear()?(b.getMonth()===d.getMonth()?b.getDate()===d.getDate()?a=b.getHours()===d.getHours()?b.getMinutes()===d.getMinutes()?b.getSeconds()===
d.getSeconds()?f.millisecondTimePattern:f.secondTimePattern:f.minuteTimePattern:f.minuteTimePattern:(2>d.getDate()-b.getDate()&&(a=f.minuteTimePattern),h=!0):h=!0,l="long"):d&&10<d.getFullYear()-b.getFullYear()?(n=f.yearPattern,h=!0):(h=!0,l="long");f=k.format(b,{datePattern:n,formatLength:l,selector:"date"});a&&(b=k.format(b,{timePattern:a,selector:"time"}),f=t.getLocalization("dojo.cldr","gregorian")["dateTimeFormat-medium"].replace(/\{1\}/g,f).replace(/\{0\}/g,b));g.isValidDataStrByDateLocale(f)||
(f="");d&&(h&&(e=k.format(d,{datePattern:n,formatLength:l,selector:"date"})),a&&(b=k.format(d,{timePattern:a,selector:"time"}),e=h&&a?t.getLocalization("dojo.cldr","gregorian")["dateTimeFormat-medium"].replace(/\{1\}/g,e).replace(/\{0\}/g,b):b));g.isValidDataStrByDateLocale(e)||(e="")}else a="Custom"===this.config.timeFormat?this.config.customDateFormat:this.config.timeFormat,f=r(b.getTime()).format(a),d&&(e=r(d.getTime()).format(a));return c=d?A.substitute({FROMTIME:f,ENDTIME:e},c):f+""},findDefaultInterval:function(a){var c;
a=(a.endTime.getTime()-a.startTime.getTime())/10;31104E8<a?(a=Math.round(a/31104E8),c="esriTimeUnitsCenturies"):31104E7<a?(a=Math.round(a/31104E7),c="esriTimeUnitsDecades"):31104E6<a?(a=Math.round(a/31104E6),c="esriTimeUnitsYears"):2592E6<a?(a=Math.round(a/2592E6),c="esriTimeUnitsMonths"):6048E5<a?(a=Math.round(a/6048E5),c="esriTimeUnitsWeeks"):864E5<a?(a=Math.round(a/864E5),c="esriTimeUnitsDays"):36E5<a?(a=Math.round(a/36E5),c="esriTimeUnitsHours"):6E4<a?(a=Math.round(a/6E4),c="esriTimeUnitsMinutes"):
1E3<a?(a=Math.round(a/1E3),c="esriTimeUnitsSeconds"):(a=Math.round(a),c="esriTimeUnitsMilliseconds");0===a&&(a=1);return{interval:a,units:c}},getPropsFromMultiLayerInfos:function(a,c){var b={};null===c?(b=a,b.thumbCount=2,b.thumbMovingRate=2E3):(b=c,a.timeExtent[0]<b.timeExtent[0]&&(b.timeExtent[0]=a.timeExtent[0]),a.timeExtent[1]>b.timeExtent[1]&&(b.timeExtent[1]=a.timeExtent[1]));return b},getTsPros:function(){var a=new y,c=e.getObject("itemData.widgets.timeSlider.properties",!1,this.map&&this.map.itemInfo),
b={};c?(b=e.clone(c),a.resolve(b)):a.resolve(null);return a},findClosestThumbIndex:function(a,c){a=a.timeStops;var b=a[0];if(c<b)return 0;for(var d=1;d<a.length;d++){if(a[d]>=c)return c-b<a[d]-c?d-1:d;if(d<a.length-1)b=a[d];else return d}},getCurrentTimeStops:function(a){var c=null,b=null;1===this.timeSlider.thumbCount?c=this.timeSlider.timeStops[this.timeSlider.thumbIndexes[0]]:2===this.timeSlider.thumbCount&&(c=this.timeSlider.timeStops[this.timeSlider.thumbIndexes[0]],b=this.timeSlider.timeStops[this.timeSlider.thumbIndexes[1]]);
return{timeStamp:a,thumbCount:this.timeSlider.thumbCount,startTime:(new Date(c)).getTime(),endTime:(new Date(b)).getTime()}},setAutoRefreshTimer:function(a){var c=this.config;if(c&&c.autoRefresh&&!0===c.autoRefresh.isAutoRefresh){if(this._autoRefreshFlag=!0,c=g.getAutoRefreshTime(c))this._autoRefreshTimer=setTimeout(e.hitch(this,function(){var b=this.getCurrentTimeStops(this._INIT_TIME_STEAMP);g.saveToLocalCache(this.widgetId,b);a._closeHanlder();a._openHanlder()}),c)}else this._autoRefreshFlag=!1,
this.clearAutoRefreshTimer()},clearAutoRefreshTimer:function(){this._autoRefreshTimer&&clearTimeout(this._autoRefreshTimer)},restoreAutoRefreshTimer:function(a){var c=g.getCacheByKeys(this.widgetId);if(c&&c.timeStamp&&this._INIT_TIME_STEAMP===c.timeStamp){var b;a.setThumbCount(c.thumbCount);b=this.findClosestThumbIndex(a,c.startTime);1===a.thumbCount?a.setThumbIndexes([b]):2===a.thumbCount&&(c=this.findClosestThumbIndex(a,c.endTime),a.setThumbIndexes([b,c]))}}});m.localeDic={ar:{datePattern:"dd MMMM, yyyy",
yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},cs:{datePattern:"MMMM d, yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"h:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},da:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},de:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",
hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},el:{datePattern:"d MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"h",minuteTimePattern:"hh:mm",secondTimePattern:"hh:mm:ss",millisecondTimePattern:"hh:mm:ss:SSS"},es:{datePattern:"d' de 'MMMM' de 'yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},et:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"H",
minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},fi:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"t",minuteTimePattern:"t:mm a",secondTimePattern:"t:mm:ss",millisecondTimePattern:"h:mm:ss:SSS"},fr:{datePattern:"d MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"HH",minuteTimePattern:"HH:mm",secondTimePattern:"HH:mm:ss",millisecondTimePattern:"HH:mm:ss:SSS"},he:{datePattern:"d, MMMM ,yyyy",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",
secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},it:{datePattern:"d MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H.mm",secondTimePattern:"H.mm.ss",millisecondTimePattern:"H.mm.ss.SSS"},ja:{datePattern:"yyyy'\u5e74'M'\u6708'd'\u65e5'",yearPattern:"yyyy'\u5e74'",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},ko:{datePattern:"yyyy\ub144 M\uc6d4 d\uc77c",yearPattern:"yyyy\ub144",hourTimePattern:"a h\uc2dc",
minuteTimePattern:"a h:mm",secondTimePattern:"a h:mm:ss",millisecondTimePattern:"a h:mm:ss:SSS"},lt:{datePattern:"yyyy MMMM dd",yearPattern:"yyyy",hourTimePattern:"H a",minuteTimePattern:"HH:mm",secondTimePattern:"HH:mm:ss",millisecondTimePattern:"HH:mm:ss:SSS"},lv:{datePattern:"dd.MM.yyyy",yearPattern:"yyyy",hourTimePattern:"H a",minuteTimePattern:"HH:mm",secondTimePattern:"HH:mm:ss",millisecondTimePattern:"HH:mm:ss:SSS"},nb:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H.mm",
secondTimePattern:"H.mm.ss",millisecondTimePattern:"H.mm.ss.SSS"},nl:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},pl:{datePattern:"dd-mm-yyyy",yearPattern:"yyyy",hourTimePattern:"hh",minuteTimePattern:"hh:mm",secondTimePattern:"hh:mm:ss",millisecondTimePattern:"hh:mm:ss:SSS"},"pt-br":{datePattern:"d' de 'MMMM' de 'yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"h:mm a",
secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},"pt-pt":{datePattern:"d' de 'MMMM' de 'yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},ro:{datePattern:"d. MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},ru:{datePattern:"MMMM d, yyyy",yearPattern:"yyyy",hourTimePattern:"H",minuteTimePattern:"h:mm",secondTimePattern:"h:mm:ss",
millisecondTimePattern:"h:mm:ss:SSS"},sv:{datePattern:"MMMM d, yyyy",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},th:{datePattern:"d MMMM,yyyy",yearPattern:"yyyy",hourTimePattern:"H a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},tr:{datePattern:"d MMMM yyyy",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",
millisecondTimePattern:"h:mm:ss:SSS a"},vi:{datePattern:"d MMMM, yyyy",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},"zh-cn":{datePattern:"yyyy'\u5e74'M'\u6708'd'\u65e5'",yearPattern:"yyyy'\u5e74'",hourTimePattern:"H",minuteTimePattern:"H:mm",secondTimePattern:"H:mm:ss",millisecondTimePattern:"H:mm:ss:SSS"},"zh-hk":{datePattern:"\u5e74\u6708\u65e5",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",
secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},"zh-tw":{datePattern:"\u5e74\u6708\u65e5",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"},en:{datePattern:"MMMM d, yyyy",yearPattern:"yyyy",hourTimePattern:"h a",minuteTimePattern:"h:mm a",secondTimePattern:"h:mm:ss a",millisecondTimePattern:"h:mm:ss:SSS a"}};return m});