//>>built
define(["dojo/date/locale","../../Color","../../core/lang","../../core/numberUtils","dojo/i18n!dojo/cldr/nls/gregorian"],function(n,q,f,k,t){function u(b){return b&&b.map(function(a){return new q(a)})}function r(b,a,e){var c="";return 0===a?c=m.lt+" ":a===e&&(c=m.gt+" "),c+b}var l={},m={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%",ld:"\u2013"},v={millisecond:0,second:1,minute:2,hour:3,day:4,month:5,year:6},w={millisecond:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},
second:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},minute:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},hour:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},day:{selector:"date",dateOptions:{formatLength:"long"}},month:{selector:"date",dateOptions:{formatLength:"long"}},year:{selector:"date",dateOptions:{selector:"year"}}},x={formatLength:"short",fullYear:!0},y={formatLength:"short"};return f.mixin(l,{meterIn:{inches:1/.0254,
feet:1/.3048,"us-feet":3.28084,yards:1/.9144,miles:1/1609.344,"nautical-miles":1/1852,millimeters:1E3,centimeters:100,decimeters:10,meters:1,kilometers:.001,"decimal-degrees":180/20015077},timelineDateFormatOptions:{selector:"date",dateOptions:{formatLength:"short",fullYear:!0}},formatDate:function(b,a){var e,c=[];null==b||b instanceof Date||(b=new Date(b));a=a||{};a=f.mixin({},a);var d=a.selector?a.selector.toLowerCase():null,p=!d||-1<d.indexOf("time"),d=!d||-1<d.indexOf("date");return p&&(a.timeOptions=
a.timeOptions||y,a.timeOptions&&(a.timeOptions=f.mixin({},a.timeOptions),a.timeOptions.selector=a.timeOptions.selector||"time",c.push(a.timeOptions))),d&&(a.dateOptions=a.dateOptions||x,a.dateOptions&&(a.dateOptions=f.mixin({},a.dateOptions),a.dateOptions.selector=a.dateOptions.selector||"date",c.push(a.dateOptions))),c&&c.length?(c=c.map(function(a){return n.format(b,a)}),e=1==c.length?c[0]:t["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(a,b){return c[b]})):e=n.format(b),
e},createColorStops:function(b){var a=b.values,e=b.colors,c=b.labelIndexes,d=b.isDate,p=b.dateFormatOptions;return a.map(function(b,g){var h=null;if(!c||-1<c.indexOf(g)){var f;(f=d?l.formatDate(b,p):k.format(b))&&(h=r(f,g,a.length-1))}return{value:b,color:e[g],label:h}})},updateColorStops:function(b){var a,e=b.stops,c=b.changes,d=b.isDate,p=b.dateFormatOptions,h=[],g=e.map(function(a){return a.value});c.forEach(function(a){h.push(a.index);g[a.index]=a.value});a=k.round(g,{indexes:h});e.forEach(function(b,
c){if(b.value=g[c],null!=b.label){var h,f=null;(h=d?l.formatDate(a[c],p):k.format(a[c]))&&(f=r(h,c,e.length-1));b.label=f}})},createClassBreakLabel:function(b){var a=b.minValue,e=b.maxValue,c=b.isFirstBreak?"":m.gt+" ";b="percent-of-total"===b.normalizationType?m.pct:"";return a=null==a?"":k.format(a),e=null==e?"":k.format(e),c+a+b+" "+m.ld+" "+e+b},setLabelsForClassBreaks:function(b){var a=b.classBreakInfos,e=b.classificationMethod,c=b.normalizationType,d=[];a&&a.length&&("standard-deviation"===
e?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):b.round?(d.push(a[0].minValue),a.forEach(function(a){d.push(a.maxValue)}),d=k.round(d),a.forEach(function(a,b){a.label=l.createClassBreakLabel({minValue:0===b?d[0]:d[b],maxValue:d[b+1],isFirstBreak:0===b,normalizationType:c})})):a.forEach(function(a,b){a.label=l.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===b,normalizationType:c})}))},updateClassBreak:function(b){var a,
e=b.classBreaks,c=b.normalizationType,d=b.change,f=d.index,d=d.value,h=-1,g=-1,k=e.length;if("standard-deviation"===b.classificationMethod)return void console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method.");0===f?h=f:f===k?g=f-1:(g=f-1,h=f);-1<h&&h<k&&(a=e[h],a.minValue=d,a.label=l.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===h,normalizationType:c}));-1<g&&g<k&&(a=e[g],a.maxValue=d,a.label=l.createClassBreakLabel({minValue:a.minValue,
maxValue:a.maxValue,isFirstBreak:0===g,normalizationType:c}))},calculateDateFormatInterval:function(b){var a,e,c,d,f,h,g,k,l,m=b.length,n=1/0;b=b.map(function(a){return new Date(a)});for(a=0;a<m-1;a++){c=b[a];f=[];g=1/0;k="";for(e=a+1;e<m;e++)d=b[e],d=c.getFullYear()!==d.getFullYear()&&"year"||c.getMonth()!==d.getMonth()&&"month"||c.getDate()!==d.getDate()&&"day"||c.getHours()!==d.getHours()&&"hour"||c.getMinutes()!==d.getMinutes()&&"minute"||c.getSeconds()!==d.getSeconds()&&"second"||"millisecond",
h=v[d],h<g&&(g=h,k=d),f.push(d);g<n&&(n=g,l=k)}return l},createUniqueValueLabel:function(b){var a=b.value,e=b.fieldInfo,c=b.domain;b=b.dateFormatInterval;var d=String(a),c=c&&c.codedValues?c.getName(a):null;return c?d=c:"number"==typeof a&&(d=e&&"date"===e.type?l.formatDate(a,b&&w[b]):k.format(a)),d},cloneColorVariable:function(b){var a;return b&&(a=f.mixin({},b),a.colors=u(a.colors),a.stops=a.stops&&a.stops.map(function(a){return a=f.mixin({},a),a.color&&(a.color=new q(a.color)),a}),a.legendOptions&&
(a.legendOptions=f.mixin({},a.legendOptions))),a},cloneOpacityVariable:function(b){var a;b&&(a=f.mixin({},b),(b=a.opacityValues)&&(a.opacityValues=b.slice(0)),(b=a.stops)&&(a.stops=b.map(function(a){return f.mixin({},a)})),(b=a.legendOptions)&&(a.legendOptions=f.mixin({},b)));return a},cloneSizeVariable:function(b){var a;b&&(a=f.mixin({},b),a.stops&&(a.stops=a.stops.map(function(a){return f.mixin({},a)})),(b=a.minSize)&&"object"==typeof b&&(a.minSize=l.cloneSizeVariable(b)),(b=a.maxSize)&&"object"==
typeof b&&(a.maxSize=l.cloneSizeVariable(b)),(b=a.legendOptions)&&(a.legendOptions=f.mixin({},b),(b=b.customValues)&&(a.legendOptions.customValues=b.slice(0))));return a}}),l});