define({
  "visible": "デフォルトで概観図を表示",
  "minWidth": "最小幅",
  "minHeight": "最小高さ",
  "maxWidth": "最大幅",
  "maxHeight": "最大高さ",
  "minText": "最小",
  "maxText": "最大",
  "attachText": "このウィジェットを配置する場所を指定します。",
  "expandText": "初期画面よりウィジェットを表示",
  "topLeft": "左上",
  "topRight": "右上",
  "bottomLeft": "左下",
  "bottomRight": "右下",
  "baseLayerType": "表示",
  "BaseMap": "マップのベースマップ",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "ArcGIS タイル マップ サービス",
  "dynamicMapService": "ArcGIS ダイナミック マップ サービス",
  "imageService": "ArcGIS イメージ サービス",
  "OSM": "オープン ストリート マップ",
  "bingRoad": "Bing Maps - 道路地図",
  "bingAerial": "Bing Maps - 航空写真",
  "bingHybrid": "Bing Maps - ハイブリッド",
  "WebTiled": "Web タイル レイヤー",
  "VETiled": "Virtual Earth タイル レイヤー",
  "tileLayerUrl": "タイル レイヤーの URL",
  "tile": "タイトル",
  "credits": "クレジット",
  "subdomain": "サブドメイン",
  "extent": "範囲",
  "initExtent": "初期範囲",
  "tileInfo": "TileInfo",
  "VEStyle": "Virtual Earth スタイル",
  "Aerial": "Bing Maps 航空写真レイヤー",
  "AerialWithLabels": "ラベル付き航空写真レイヤー",
  "Roads": "道路レイヤー",
  "errWkid": "WKID が一致しません",
  "errUrl": "Invalid URL",
  "errReqTimeout": "タイムアウトしました",
  "layerPlaceholder": "URL の入力"
});