//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/Logger ../core/accessorSupport/decorators ./Geometry ./SpatialReference ./support/spatialReferenceUtils ./support/webMercatorUtils".split(" "),function(l,y,t,h,u,d,v,w,x,n){function q(d){return d&&("esri.geometry.SpatialReference"===d.declaredClass||null!=d.wkid)}var k=[0,0],r=u.getLogger("esri.geometry.Point");l=function(l){function b(a,e,b,f,g){a=l.call(this)||this;return a.x=0,a.y=0,a.z=void 0,
a.m=void 0,a.type="point",a}return t(b,l),p=b,b.copy=function(a,e){e.x=a.x;e.y=a.y;e.z=a.z;e.m=a.m;e.spatialReference=Object.isFrozen(a.spatialReference)?a.spatialReference:a.spatialReference.clone()},b.distance=function(a,e){var b=a.x-e.x,f=a.y-e.y;a=a.hasZ&&e.hasZ?a.z-e.z:0;return Math.sqrt(b*b+f*f+a*a)},b.prototype.normalizeCtorArgs=function(a,e,b,f,g){var c;if(Array.isArray(a))c=a,g=e,a=c[0],e=c[1],b=c[2],f=c[3];else if(a&&"object"==typeof a){if(c=a,a=null!=c.x?c.x:c.longitude,e=null!=c.y?c.y:
c.latitude,b=null!=c.z?c.z:c.altitude,f=c.m,g=c.spatialReference,g&&"esri.geometry.SpatialReference"!==g.declaredClass&&(g=new w(g)),null!=c.longitude||null!=c.latitude)null==c.longitude?r.warn(".longitude\x3d","Latitude was defined without longitude"):null==c.latitude?r.warn(".latitude\x3d","Longitude was defined without latitude"):!c.declaredClass&&g&&g.isWebMercator&&(e=n.lngLatToXY(c.longitude,c.latitude,k),a=e[0],e=e[1])}else q(b)?(g=b,b=null):q(f)&&(g=f,f=null);a={x:a,y:e};return null!=g&&(a.spatialReference=
g),null!=b&&(a.z=b),null!=f&&(a.m=f),a},Object.defineProperty(b.prototype,"hasM",{get:function(){return void 0!==this.m},set:function(a){a!==this._get("hasM")&&(this._set("m",a?0:void 0),this._set("hasM",a))},enumerable:!0,configurable:!0}),Object.defineProperty(b.prototype,"hasZ",{get:function(){return void 0!==this.z},set:function(a){a!==this._get("hasZ")&&(this._set("z",a?0:void 0),this._set("hasZ",a))},enumerable:!0,configurable:!0}),Object.defineProperty(b.prototype,"latitude",{get:function(){var a=
this._get("spatialReference");if(a){if(a.isWebMercator)return n.xyToLngLat(this.x,this.y,k)[1];if(a.isWGS84)return this._get("y")}return null},set:function(a){var b=this._get("spatialReference");b&&(b.isWebMercator?this._set("y",n.lngLatToXY(this.x,a,k)[1]):b.isWGS84&&this._set("y",a),this._set("latitude",a))},enumerable:!0,configurable:!0}),Object.defineProperty(b.prototype,"longitude",{get:function(){var a=this._get("spatialReference");if(a){if(a.isWebMercator)return n.xyToLngLat(this._get("x"),
this._get("y"),k)[0];if(a.isWGS84)return this._get("x")}return null},set:function(a){var b=this._get("spatialReference");b&&(b.isWebMercator?this._set("x",n.lngLatToXY(a,this._get("y"),k)[0]):b.isWGS84&&this._set("x",a),this._set("longitude",a))},enumerable:!0,configurable:!0}),b.prototype.clone=function(){var a=new p;return a.x=this.x,a.y=this.y,a.z=this.z,a.m=this.m,a.spatialReference=this.spatialReference,a},b.prototype.copy=function(a){return p.copy(a,this),this},b.prototype.equals=function(a){if(!a)return!1;
var b=this.x,d=this.y,f=this.z,g=this.m,c=this.spatialReference,h=a.z,l=a.m,k=a.x,m=a.y;a=a.spatialReference;if(!c.equals(a)){if(c.isWebMercator&&a.isWGS84)m=n.lngLatToXY(k,m);else{if(!c.isWGS84||!a.isWebMercator)return!1;m=n.xyToLngLat(k,m)}k=m[0];m=m[1];a=c}return b===k&&d===m&&f===h&&g===l&&c.wkid===a.wkid},b.prototype.offset=function(a,b,d){return this.x+=a,this.y+=b,null!=d&&this.hasZ&&(this.z+=d),this},b.prototype.normalize=function(){if(!this.spatialReference)return this;var a=x.getInfo(this.spatialReference);
if(!a)return this;var b,d=this.x,f=a.valid,a=f[0],f=f[1],g=2*f;return d>f?(b=Math.ceil(Math.abs(d-f)/g),d-=b*g):d<a&&(b=Math.ceil(Math.abs(d-a)/g),d+=b*g),this._set("x",d),this},b.prototype.distance=function(a){return p.distance(this,a)},b.prototype.toArray=function(){var a=this.hasZ,b=this.hasM;return a&&b?[this.x,this.y,this.z,this.m]:a?[this.x,this.y,this.z]:b?[this.x,this.y,this.m]:[this.x,this.y]},b.prototype.toJSON=function(a){return this.write(null,a)},h([d.property({dependsOn:["x","y","z",
"m","spatialReference"]})],b.prototype,"cache",void 0),h([d.property({type:Boolean,dependsOn:["m"],json:{write:{enabled:!1,overridePolicy:null}}})],b.prototype,"hasM",null),h([d.property({type:Boolean,dependsOn:["z"],json:{write:{enabled:!1,overridePolicy:null}}})],b.prototype,"hasZ",null),h([d.property({type:Number,dependsOn:["y"]})],b.prototype,"latitude",null),h([d.property({type:Number,dependsOn:["x"]})],b.prototype,"longitude",null),h([d.property({type:Number,json:{write:{isRequired:!0}}})],
b.prototype,"x",void 0),h([d.property({type:Number,json:{write:!0}})],b.prototype,"y",void 0),h([d.property({type:Number,json:{write:{overridePolicy:function(){return{enabled:this.hasZ}}}}})],b.prototype,"z",void 0),h([d.property({type:Number,json:{write:{overridePolicy:function(){return{enabled:this.hasM}}}}})],b.prototype,"m",void 0),b=p=h([d.subclass("esri.geometry.Point")],b);var p}(d.declared(v));return l.prototype.toJSON.isDefaultToJSON=!0,l});