//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/lang ../core/accessorSupport/decorators ./Extent ./Geometry ./Point ./SpatialReference ./support/centroid ./support/contains ./support/coordsUtils ./support/intersects ./support/webMercatorUtils ./support/zmUtils".split(" "),function(r,U,M,f,A,g,J,N,h,O,P,Q,R,S,B,K){function L(g){return function(b,k){return null==b?k:null==k?b:g(b,k)}}var p=L(Math.min),n=L(Math.max);r=function(r){function b(){for(var a=
0;a<arguments.length;a++);a=r.call(this)||this;return a.rings=[],a.type="polygon",a}return M(b,r),k=b,b.createEllipse=function(a){var c=a.center.x,e=a.center.y,d=a.center.z,l=a.center.m,b=a.center.hasZ,g=a.center.hasM,T=a.longAxis,p=a.shortAxis,n=a.numberOfPoints;a=a.view;for(var t=[],f=2*Math.PI/n,h=b?3:2,v=0;v<n;v++){var q=a.toMap(T*Math.cos(v*f)+c,p*Math.sin(v*f)+e),q=[q.x,q.y];b&&(q[2]=d);g&&(q[h]=l);t.push(q)}t.push(t[0]);return new k({rings:[t],spatialReference:a.spatialReference})},b.createCircle=
function(a){return k.createEllipse({center:a.center,longAxis:a.r,shortAxis:a.r,numberOfPoints:a.numberOfPoints,view:a.view})},b.fromExtent=function(a){var c=a.clone().normalize();a=a.spatialReference;var e=!1,d=!1;c.map(function(a){a.hasZ&&(e=!0);a.hasM&&(d=!0)});c={rings:c.map(function(a){var c=[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]];if(e&&a.hasZ)for(var b=a.zmin+.5*(a.zmax-a.zmin),l=0;l<c.length;l++)c[l].push(b);if(d&&a.hasM)for(a=a.mmin+.5*(a.mmax-a.mmin),
l=0;l<c.length;l++)c[l].push(a);return c}),spatialReference:a};return e&&(c.hasZ=!0),d&&(c.hasM=!0),new k(c)},b.prototype.normalizeCtorArgs=function(a,c){var e,d,b=null,m=null;return a&&!Array.isArray(a)?(b=a.rings?a.rings:null,c||(a.spatialReference?c=a.spatialReference:a.rings||(c=a)),e=a.hasZ,d=a.hasM):b=a,b=b||[],c=c||O.WGS84,b.length&&b[0]&&null!=b[0][0]&&"number"==typeof b[0][0]&&(b=[b]),m=b[0]&&b[0][0],m&&(void 0===e&&void 0===d?(e=2<m.length,d=!1):void 0===e?e=!d&&3<m.length:void 0===d&&(d=
!e&&3<m.length)),{rings:b,spatialReference:c,hasZ:e,hasM:d}},Object.defineProperty(b.prototype,"centroid",{get:function(){var a=P.polygonCentroid(this);if(!a||isNaN(a[0])||isNaN(a[1])||this.hasZ&&isNaN(a[2]))return null;var c=new h;return c.x=a[0],c.y=a[1],c.spatialReference=this.spatialReference,this.hasZ&&(c.z=a[2]),c},enumerable:!0,configurable:!0}),Object.defineProperty(b.prototype,"extent",{get:function(){var a=this.hasZ,c=this.hasM,b=this.spatialReference,d=this.rings,l=a?3:2;if(!d.length||
!d[0].length)return null;for(var m=d[0][0],g=m[0],m=m[1],f=d[0][0],k=f[0],f=f[1],h=void 0,t=void 0,r=void 0,A=void 0,v=[],q=0;q<d.length;q++){for(var C=d[q],x=C[0],G=x[0],x=x[1],y=C[0],H=y[0],y=y[1],D=void 0,E=void 0,B=void 0,w=void 0,I=0;I<C.length;I++){var z=C[I],u=z[0],F=z[1];if(g=p(g,u),m=p(m,F),k=n(k,u),f=n(f,F),G=p(G,u),x=p(x,F),H=n(H,u),y=n(y,F),a&&2<z.length)u=z[2],h=p(h,u),t=n(t,u),D=p(D,u),E=n(E,u);c&&z.length>l&&(w=z[l],r=p(h,w),A=n(t,w),B=p(D,w),w=n(E,w))}v.push(new J({xmin:G,ymin:x,zmin:D,
mmin:B,xmax:H,ymax:y,zmax:E,mmax:w,spatialReference:b}))}d=new J;return d.xmin=g,d.ymin=m,d.xmax=k,d.ymax=f,d.spatialReference=b,a&&(d.zmin=h,d.zmax=t),c&&(d.mmin=r,d.mmax=A),d.cache._partwise=1<v.length?v:null,d},enumerable:!0,configurable:!0}),Object.defineProperty(b.prototype,"isSelfIntersecting",{get:function(){return S.isSelfIntersecting(this.rings)},enumerable:!0,configurable:!0}),b.prototype.writePaths=function(a,c,b,d){c.rings=A.clone(this.rings)},b.prototype.addRing=function(a){if(a){this.clearCache();
var c=this.rings,b=c.length;if(Array.isArray(a[0]))c[b]=a.concat();else{for(var d=[],f=0,g=a.length;f<g;f++)d[f]=a[f].toArray();c[b]=d}return this}},b.prototype.clone=function(){var a=new k;return a.spatialReference=this.spatialReference,a.rings=A.clone(this.rings),a.hasZ=this.hasZ,a.hasM=this.hasM,a},b.prototype.contains=function(a){return!!a&&(B.canProject(a,this.spatialReference)&&(a=B.project(a,this.spatialReference)),Q.polygonContainsPoint(this,a))},b.prototype.isClockwise=function(a){var c,
b=this;return c=Array.isArray(a[0])?a:a.map(function(a){return b.hasZ?b.hasM?[a.x,a.y,a.z,a.m]:[a.x,a.y,a.z]:[a.x,a.y]}),R.isClockwise(c,this.hasM,this.hasZ)},b.prototype.getPoint=function(a,c){if(!this._validateInputs(a,c))return null;a=this.rings[a][c];c=this.hasZ;var b=this.hasM;return c&&!b?new h(a[0],a[1],a[2],void 0,this.spatialReference):b&&!c?new h(a[0],a[1],void 0,a[2],this.spatialReference):c&&b?new h(a[0],a[1],a[2],a[3],this.spatialReference):new h(a[0],a[1],this.spatialReference)},b.prototype.insertPoint=
function(a,b,e){return this._validateInputs(a,b,!0)?(this.clearCache(),K.updateSupportFromPoint(this,e),Array.isArray(e)||(e=e.toArray()),this.rings[a].splice(b,0,e),this):this},b.prototype.removePoint=function(a,b){return this._validateInputs(a,b)?(this.clearCache(),new h(this.rings[a].splice(b,1)[0],this.spatialReference)):null},b.prototype.removeRing=function(a){if(!this._validateInputs(a,null))return null;this.clearCache();a=this.rings.splice(a,1)[0];var b=this.spatialReference;return a.map(function(a){return new h(a,
b)})},b.prototype.setPoint=function(a,b,e){return this._validateInputs(a,b)?(this.clearCache(),K.updateSupportFromPoint(this,e),Array.isArray(e)||(e=e.toArray()),this.rings[a][b]=e,this):this},b.prototype._validateInputs=function(a,b,e){return(void 0===e&&(e=!1),null==a||0>a||a>=this.rings.length)||null!=b&&(a=this.rings[a],e&&(0>b||b>a.length)||!e&&(0>b||b>=a.length))?!1:!0},b.prototype.toJSON=function(a){return this.write(null,a)},f([g.property({dependsOn:["hasM","hasZ","rings"]})],b.prototype,
"cache",void 0),f([g.property({readOnly:!0,dependsOn:["cache"]})],b.prototype,"centroid",null),f([g.property({dependsOn:["cache"],readOnly:!0})],b.prototype,"extent",null),f([g.property({dependsOn:["cache"],readOnly:!0})],b.prototype,"isSelfIntersecting",null),f([g.property({type:[[[Number]]],json:{write:{isRequired:!0}}})],b.prototype,"rings",void 0),f([g.writer("rings")],b.prototype,"writePaths",null),b=k=f([g.subclass("esri.geometry.Polygon")],b);var k}(g.declared(N));return r.prototype.toJSON.isDefaultToJSON=
!0,r});