define({
  "visible": "顯示預設的總覽圖",
  "minWidth": "最小寬度",
  "minHeight": "最小高度",
  "maxWidth": "最大寬度",
  "maxHeight": "最大高度",
  "minText": "最小值",
  "maxText": "最大值",
  "attachText": "指定要附加此 widget 的地圖角落。",
  "expandText": "最初展開的 widget",
  "topLeft": "左上",
  "topRight": "右上",
  "bottomLeft": "左下",
  "bottomRight": "右下",
  "baseLayerType": "顯示",
  "BaseMap": "地圖的底圖",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "ArcGIS 圖磚地圖服務",
  "dynamicMapService": "ArcGIS 動態地圖服務",
  "imageService": "ArcGIS 圖片服務",
  "OSM": "開啟街道地圖",
  "bingRoad": "Bing 道路地圖",
  "bingAerial": "Bing 航空地圖",
  "bingHybrid": "Bing 混合地圖",
  "WebTiled": "Web 圖磚圖層",
  "VETiled": "虛擬地球圖磚圖層",
  "tileLayerUrl": "圖磚圖層 Url",
  "tile": "標題",
  "credits": "點數",
  "subdomain": "子網域",
  "extent": "範圍",
  "initExtent": "初始範圍",
  "tileInfo": "TileInfo",
  "VEStyle": "虛擬地球樣式",
  "Aerial": "Bing 航空地圖圖層",
  "AerialWithLabels": "帶標籤的航空圖層",
  "Roads": "道路圖層",
  "errWkid": "Wkid 不符合",
  "errUrl": "無效的 URL",
  "errReqTimeout": "已過了逾時日期",
  "layerPlaceholder": "輸入 URL"
});