define({
  "instruction": "Úvodní obrazovka se zobrazí před otevřením aplikace.",
  "defaultContent": "Sem můžete přidat text, odkazy a malé obrázky.",
  "requireConfirm": "Vyžadovat potvrzení k pokračování",
  "noRequireConfirm": "Nevyžadovat potvrzení k pokračování",
  "optionText": "Možnost uživatele vypnout úvodní obrazovku při spuštění aplikace.",
  "confirmLabel": "Text potvrzení: ",
  "confirmLabelColor": "Barva textu potvrzení",
  "defaultConfirmText": "Souhlasím s výše uvedenými podmínkami a ujednáními",
  "confirmOption": "Zobrazovat tuto úvodní obrazovku při každém spuštění aplikace",
  "backgroundColor": "Barva pozadí",
  "content": "Obsah",
  "contentDescription": "Zadejte obsah, který bude zobrazen na úvodní obrazovce.",
  "appearance": "Vzhled",
  "appearanceDescription": "Nastavte vzhled úvodní obrazovky.",
  "size": "Velikost",
  "width": "Šířka",
  "height": "Výška",
  "custom": "Vlastní",
  "background": "Pozadí",
  "colorFill": "Výplň barvou",
  "imageFill": "Výplň obrazem",
  "chooseFile": "Vybrat soubor",
  "noFileChosen": "Není vybrán žádný soubor.",
  "sizeFill": "Výplň",
  "sizeFit": "Přizpůsobit",
  "sizeStretch": "Vyplnit roztažením",
  "sizeCenter": "Střed",
  "sizeTile": "Dlaždice",
  "buttonColor": "Barva tlačítka",
  "buttonText": "Text tlačítka",
  "buttonTextColor": "Barva textu tlačítka",
  "contentAlign": "Zarovnání obsahu",
  "alignTop": "Nahoře",
  "alignMiddle": "Na střed",
  "maskColor": "Barva masky",
  "options": "Možnosti",
  "optionsDescription": "Nastavte chování úvodní obrazovky."
});