// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/html dojo/query esri/lang dojo/keys dojo/on".split(" "),function(k,d,g,m,f,l){var e={firstFocusNodeClass:"firstFocusNode",lastFocusNodeClass:"lastFocusNode",lastFocusNodeClassInDOM:"lastFocusNodeInDOM",isInNavMode:function(){return d.hasClass(document.body,"jimu-nav-mode")?!0:!1},initTabIndexAndOrder:function(a){var b=e.getFirstFocusNode(a.domNode,a.inPanel),c=e.getLastFocusNode(a.domNode);b&&!c&&(c=b);a.isController&&(b=c=null);e.initFirstFocusNode(a.domNode,b);
e.initLastFocusNode(a.domNode,c);e.addLabelToWidgetDOM(a)},addLabelToWidgetDOM:function(a){if(0<=["ZoomSlider","AttributeTable","Search","ExtentNavigate","OverviewMap"].indexOf(a.name)){console.log(a.name);var b=m.substitute({widgetLabel:a.name},window.jimuNls.widgetToolTip);d.setAttr(a.domNode,"aria-label",b)}},isOnScreenNotCloseableOffPanel:function(a){return a.isOnScreen&&!a.inPanel&&!0!==a.closeable},preventMapNavigation:function(a){0<=[f.NUMPAD_PLUS,61,187,f.NUMPAD_MINUS,173,189,f.UP_ARROW,f.NUMPAD_8,
f.RIGHT_ARROW,f.NUMPAD_6,f.DOWN_ARROW,f.NUMPAD_2,f.LEFT_ARROW,f.NUMPAD_4,f.PAGE_UP,f.NUMPAD_9,f.PAGE_DOWN,f.NUMPAD_3,f.END,f.NUMPAD_1,f.HOME,f.NUMPAD_7].indexOf(a.keyCode)&&a.stopPropagation()},_addAttrsOnWidgetDom:function(a){var b=0<=["MyLocation","HomeButton","FullScreen"].indexOf(a.name)?"button":"";a.inPanel||d.setAttr(a.domNode,"role",b)},initWidgetCancelEvent:function(a){this._addAttrsOnWidgetDom(a);l(a.domNode,"keydown",k.hitch(this,function(b){e.preventMapNavigation(b);var c=b.target;a.inPanel||
0>[f.ENTER,f.ESCAPE].indexOf(b.keyCode)||(e.isOnScreenNotCloseableOffPanel(a)?b.keyCode===f.ENTER&&d.hasClass(c,a.baseClass)?(b.preventDefault(),e.focusFirstFocusNode(a.domNode)):b.keyCode===f.ESCAPE&&(d.hasClass(c,a.baseClass)?"Splash"!==a.name&&(c=a.domNode.parentNode,"map"===d.getAttr(c,"id")?(b.preventDefault(),c.focus()):(b="jimu-layout-manager"===d.getAttr(c,"id")?a.domNode:a.domNode.parentNode,e.trapToNextFocusContainer(b))):(b.stopPropagation(),a.domNode.focus())):b.keyCode!==f.ESCAPE||d.hasClass(c,
a.baseClass)||(a.domNode.focus(),a.onClose(),b.preventDefault(),b.stopPropagation()))}))},initFirstFocusNode:function(a,b){var c=e.getFirstFocusNode(a);c&&(d.removeClass(c,e.firstFocusNodeClass),c.firstNodeEvent&&c.firstNodeEvent.remove(),c===a&&(d.setAttr(c,"tabindex",null),d.setAttr(c,"role","")));b&&(b===a&&(d.setAttr(b,"tabindex",0),d.setAttr(b,"role","document")),d.addClass(b,e.firstFocusNodeClass),b.firstNodeEvent=l(b,"keydown",k.hitch(this,function(b){d.hasClass(b.target,e.firstFocusNodeClass)&&
b.keyCode===f.TAB&&(window.currentMsgPopup&&window.currentMsgPopup.firstFocusNode?(window.currentMsgPopup.focusedNodeBeforeOpen=b.target,b.preventDefault(),window.currentMsgPopup.firstFocusNode.focus()):!e.tryToFocusSplashWidget(b,a)&&b.shiftKey&&(b.preventDefault(),b=e.getLastFocusNode(a),e.isDomFocusable(b)?b.focus():(b=e.getFocusNodesInDom(b),1<=b.length&&b[b.length-1].focus())))})))},tryToFocusSplashWidget:function(a,b){var c=g(".jimu-widget-splash",g("#jimu-layout-manager")[0])[0];return c&&
"none"!==d.getStyle(c,"display")&&c!==b?(a.stopPropagation(),a.preventDefault(),g("."+e.firstFocusNodeClass,c)[0].focus(),!0):!1},initLastFocusNode:function(a,b){var c=e.getLastFocusNode(a);c&&(d.removeClass(c,e.lastFocusNodeClass),c.lastNodeEvent&&c.lastNodeEvent.remove(),c===a&&d.setAttr(c,"tabindex",null));b&&(b===a&&d.setAttr(b,"tabindex",0),d.addClass(b,e.lastFocusNodeClass),b.lastNodeEvent=l(b,"keydown",k.hitch(this,function(c){if(!c.shiftKey&&c.keyCode===f.TAB)if(a===b||d.hasClass(c.target,
e.lastFocusNodeClass)&&e.isDomFocusable(c.target))c.preventDefault(),this.focusFirstFocusNode(a);else{var h=this.getFocusNodesInDom(b);if(0===h.length||e._isLastFromInnerNodes(h,c.target))c.preventDefault(),this.focusFirstFocusNode(a)}})))},_isLastFromInnerNodes:function(a,b){var c=!1;if(b===a[a.length-1])c=!0;else for(var h=0;h<a.length;h++)if(b===a[h]&&d.hasClass(a[h],e.lastFocusNodeClassInDOM)){c=!0;break}return c},focusFirstFocusNode:function(a){var b=g("."+e.firstFocusNodeClass,a)[0];(b?b:a).focus()},
getFirstFocusNode:function(a,b){var c=d.hasClass(a,e.firstFocusNodeClass)?a:g("."+e.firstFocusNodeClass,a)[0];!c&&b&&(c=a,null===d.getAttr(c,"tabindex")&&d.setAttr(c,"tabindex","0"));return c},getLastFocusNode:function(a){return d.hasClass(a,e.lastFocusNodeClass)?a:g("."+e.lastFocusNodeClass,a)[0]},getFirstSkipLink:function(){return g("#skipContainer a")[0]},focusOnFirstSkipLink:function(){e.getFirstSkipLink().focus()},traversalDom:function(a,b){b=b?b:[];for(var c=a.childNodes,d=0;d<c.length;d++)a=
c[d],1===a.nodeType&&(b.push(a),e.traversalDom(a,b));return b},getFocusNodesInDom:function(a){a=e.traversalDom(a);for(var b=[],c=0;c<a.length;c++){var d=a[c];e.isDomFocusable(d)&&b.push(d)}return b},isDomFocusable:function(a){var b=["A","INPUT","BUTTON","SELECT","TEXTAREA"],c="hidden"!==d.getAttr(a,"type")&&"none"!==d.getStyle(a,"display"),e=!0!==d.getAttr(a,"disabled"),f=parseInt(d.getAttr(a,"tabindex"),10);return c&&e&&(0<=b.indexOf(a.tagName)&&-1!==f||0>b.indexOf(a.tagName)&&0<=f)?!0:!1},getFrameNodesByAsc:function(){for(var a=
g("#jimu-layout-manager")[0].children,b=[],c=0;c<a.length;c++){var e=a[c];0<parseInt(d.getAttr(e,"tabindex"),10)&&"none"!==d.getStyle(e,"display")&&b.push(e)}b.sort(function(a,b){a=parseInt(d.getAttr(a,"tabindex"),10);b=parseInt(d.getAttr(b,"tabindex"),10);return a<b?-1:a===b?0:1});return b},trapToNextFocusContainer:function(a){var b=e.getFrameNodesByAsc(),c=null;if("skipContainer"===d.getAttr(a,"id"))return(c=b[0])&&c.focus(),c;b.unshift(e.getFirstSkipLink());a=parseInt(d.getAttr(a,"tabindex"),10);
for(var f=0;f<b.length;f++)if(parseInt(d.getAttr(b[f],"tabindex"),10)===a){c=f===b.length-1?b[0]:b[f+1];break}c&&c.focus();return c},isAutoFocusFirstNodeWidget:function(a){var b=!0;e.isOnScreenNotCloseableOffPanel(a)?b=!1:a.openAtStart?a.openAtStartAysn?b=a.openAtStartAysn=!1:a._isFirstOpenAtStart||(a._isFirstOpenAtStart=!0,b=!1):a.isOnScreen&&"widgetOnScreen"!==a.gid?b=!1:a.inGroupPanel&&(b=!1);return b},_getTooltipLabel:function(a,b){var c=d.getAttr(a,"aria-label");a=d.getAttr(a,"title");return c||
a||b},addTooltipByDomNode:function(a,b,c){a.defaultPosition=["below-centered","above-centered","after-centered","before-centered"];var f;l(b,"focus",k.hitch(this,function(h){e.isInNavMode()&&(f&&d.setAttr(f,"role","presentation"),a.show(e._getTooltipLabel(b,c)+"\x26nbsp;\x26nbsp;",h.target),f||(f=g(".dijitTooltipContainer",document.body)[0],d.setAttr(f,"role","presentation")))}));l(b,"blur",k.hitch(this,function(b){a&&a.hide(b.target)}))}};return e});