// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/json dojo/Deferred esri/tasks/query esri/tasks/QueryTask esri/tasks/FeatureSet esri/graphic esri/SpatialReference esri/tasks/ProjectParameters esri/config esri/geometry/webMercatorUtils jimu/LayerInfos/LayerInfos ./utils ./CSVUtils ./GeojsonConverters libs/polyfills/FileSaver".split(" "),function(t,d,g,p,l,u,v,m,h,w,x,n,y,z,A,q,B){function r(a,b){10>dojo.isIE?saveTextAs(b,a,"utf-8"):(b=new Blob([b],{type:"text/plain;charset\x3dutf-8"}),
saveAs(b,a,!0))}var k={createDataSource:function(a){return new C(a)},TYPE_TABLE:"table",TYPE_FEATURESET:"FeatureSet",FORMAT_CSV:"CSV",FORMAT_FEATURESET:"FeatureSet",FORMAT_GEOJSON:"GeoJSON"},C=t(null,{filename:void 0,format:void 0,nls:void 0,data:null,url:null,constructor:function(a){this.nls=window.jimuNls.exportTo;this.data=a.data;this.url=a.url;this.filename=a.filename},setFormat:function(a){this.format=a},download:function(){if(this.format===k.FORMAT_CSV)return this.exportCSV();if(this.format===
k.FORMAT_FEATURESET)return this.exportFeatureCollection();if(this.format===k.FORMAT_GEOJSON)return this.exportGeoJSON()},getFeatureSet:function(){var a=new l;if(this.data)a.resolve(this.data);else if(this.url){var b=new u;b.returnGeometry=!0;b.outFields=["*"];this.queryTask=new v(this.url);this.queryTask.execute(b,d.hitch(this,function(b){a.resolve(b)}),d.hitch(this,function(){a.resolve(null)}))}else a.resolve(null);return a},findPopupInfo:function(a){if(!a||!a.features||0===a.features.length)return null;
a=a.features[0];if(a._layer&&(a=a._layer.id,a=z.getInstanceSync().getLayerInfoById(a))){var b=a.getPopupInfo();b||(b=a.layerObject.infoTemplate&&a.layerObject.infoTemplate.info);return b}return null},findLayerDefinition:function(a){if(!a||!a.features||0===a.features.length)return null;var b=a.features[0];if(b._layer)return{geometryType:a.geometryType,fields:b._layer.fields};var c=[],b=b.attributes,e;for(e in b)b.hasOwnProperty(e)&&c.push({name:e});return{geometryType:a.geometryType,fields:c}},formatAttributes:function(a){var b=
new l,c=this.findPopupInfo(a),e=this.findLayerDefinition(a);if(c&&e){var f=g.map(a.features,function(a){return a.attributes});q._formattedData(a.features[0]._layer,{data:f,outFields:e.fields},{formatNumber:!0,formatDate:!0,formatCodedValue:!0,popupInfo:c,richText:{}}).then(d.hitch(this,function(c){var e=c.datas;c=new m;var d=[];g.forEach(a.features,function(a,b){a=new h(a.toJson());a.attributes=e[b];d.push(a)});c.features=d;c.geometryType=a.geometryType;c.fieldAliases=a.fieldAliases;c.fields=a.fields;
b.resolve(c)}))}else b.resolve(a);return b},exportCSV:function(){return this.getFeatureSet().then(d.hitch(this,function(a){var b=this.findPopupInfo(a),c=this.findLayerDefinition(a),e=a.features;if(c&&c.fields){var f=d.clone(c.fields);this._addXYAttribute(f,"x");this._addXYAttribute(f,"y");c.fields=f;e=[];g.forEach(a.features,d.hitch(this,function(a){a=new h(a.toJson());a.attributes=this._getAttrsWithXY(a);e.push(a)}))}return q.exportCSVByGraphics(this.filename,c,e,{formatNumber:!0,formatDate:!0,formatCodedValue:!0,
popupInfo:b})}))},exportGeoJSON:function(){return this.getFeatureSet().then(d.hitch(this,function(a){return this.formatAttributes(a)})).then(d.hitch(this,function(a){return this._projectToWGS84(a)})).then(d.hitch(this,function(a){var b="";if(a&&a.features&&0<a.features.length){var c={type:"FeatureCollection",features:[]};g.forEach(a.features,function(a){c.features.push(B.arcgisToGeoJSON(a))});b=p.stringify(c)}return b})).then(d.hitch(this,function(a){r(this.filename+".geojson",a)}))},exportFeatureCollection:function(){return this.getFeatureSet().then(d.hitch(this,
function(a){return this.formatAttributes(a)})).then(d.hitch(this,function(a){var b="";a&&(a=a.toJson())&&(b=p.stringify(a));return b})).then(d.hitch(this,function(a){r(this.filename+".json",a)}))},exportToPortal:function(a,b){},_projectToWGS84:function(a){var b=new l,c=this._getSpatialReference(a);if(c)if(4326===parseInt(c.wkid,10))b.resolve(a);else if(c.isWebMercator()){var c=new m,d=[];g.forEach(a.features,function(a){var b=new h(a.toJson());b.geometry=y.webMercatorToGeographic(a.geometry);d.push(b)});
c.features=d;c.geometryType=a.geometryType;c.fieldAliases=a.fieldAliases;c.fields=a.fields;b.resolve(c)}else{c=new x;c.geometries=g.map(a.features,function(a){return a.geometry});c.outSR=new w(4326);var f=n&&n.defaults&&n.defaults.geometryService;f&&"esri.tasks.GeometryService"===f.declaredClass||(f=A.getArcGISDefaultGeometryService());f.project(c).then(function(c){var d=new m,e=[];g.forEach(a.features,function(a,b){a=new h(a.toJson());a.geometry=c[b];e.push(a)});d.features=e;d.geometryType=a.geometryType;
d.fieldAliases=a.fieldAliases;d.fields=a.fields;b.resolve(d)},function(a){console.error(a);b.resolve([])})}else b.resolve([]);return b},_getSpatialReference:function(a){if(a.spatialReference)return a.spatialReference;var b;g.some(a.features,function(a){if(a.geometry&&a.geometry.spatialReference)return b=a.geometry.spatialReference,!0});return b},_getAttrsWithXY:function(a){var b=a.geometry;return b&&"point"===b.type?(a=d.clone(a.attributes),"x"in a?a._x=b.x:a.x=b.x,"y"in a?a._y=b.y:a.y=b.y,a):a.attributes},
_addXYAttribute:function(a,b){var c;c=g.some(a,function(a){return a.name===b})?"_"+b:b;a.push({name:c,alias:c,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});return a}});return k});