// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/json","esri/lang"],function(d,e,f,c,b){return d(null,{id:null,baseRole:null,name:null,description:null,privileges:[],privilegeObj:null,constructor:function(a){a=a||{};this.id=a.id;this.baseRole=a.role;this.name=a.name;this.description=a.description},_initPrivilegesObject:function(){this.privilegeObj={portal:{admin:{inviteUsers:!1,disableUsers:!1,viewUsers:!1,updateUsers:!1,deleteUsers:!1,changeUserRoles:!1,viewGroups:!1,updateGroups:!1,
deleteGroups:!1,reassignGroups:!1,assignToGroups:!1,manageEnterpriseGroups:!1,viewItems:!1,updateItems:!1,deleteItems:!1,reassignItems:!1,manageLicenses:!1},publisher:{publishFeatures:!1,publishTiles:!1,publishScenes:!1},user:{createGroup:!1,joinGroup:!1,joinNonOrgGroup:!1,createItem:!1,shareToGroup:!1,shareToOrg:!1,shareToPublic:!1,shareGroupToOrg:!1,shareGroupToPublic:!1}},features:{user:{edit:!1,fullEdit:!1}},opendata:{user:{openDataAdmin:!1,designateGroup:!1}},premium:{user:{geocode:!1,networkanalysis:!1,
spatialanalysis:!1,geoenrichment:!1,demographics:!1,elevation:!1},publisher:{createNotebooks:!1}},marketplace:{admin:{manage:!1,purchase:!1,startTrial:!1}}}},_readPrivileges:function(a){b.isDefined(a)&&a instanceof Array&&f.forEach(a,e.hitch(this,function(a){this._readPrivilege(a)}))},_readPrivilege:function(a){this._applyEffectToAction(!0,a)},_applyEffectToAction:function(a,b){switch(b){case "portal:admin:inviteUsers":this.privilegeObj.portal.admin.inviteUsers=a;break;case "portal:admin:disableUsers":this.privilegeObj.portal.admin.disableUsers=
a;break;case "portal:admin:viewUsers":this.privilegeObj.portal.admin.viewUsers=a;break;case "portal:admin:updateUsers":this.privilegeObj.portal.admin.updateUsers=a;break;case "portal:admin:deleteUsers":this.privilegeObj.portal.admin.deleteUsers=a;break;case "portal:admin:changeUserRoles":this.privilegeObj.portal.admin.changeUserRoles=a;break;case "portal:admin:viewGroups":this.privilegeObj.portal.admin.viewGroups=a;break;case "portal:admin:updateGroups":this.privilegeObj.portal.admin.updateGroups=
a;break;case "portal:admin:deleteGroups":this.privilegeObj.portal.admin.deleteGroups=a;break;case "portal:admin:reassignGroups":this.privilegeObj.portal.admin.reassignGroups=a;break;case "portal:admin:assignToGroups":this.privilegeObj.portal.admin.assignToGroups=a;break;case "portal:admin:manageEnterpriseGroups":this.privilegeObj.portal.admin.manageEnterpriseGroups=a;break;case "portal:admin:viewItems":this.privilegeObj.portal.admin.viewItems=a;break;case "portal:admin:updateItems":this.privilegeObj.portal.admin.updateItems=
a;break;case "portal:admin:deleteItems":this.privilegeObj.portal.admin.deleteItems=a;break;case "portal:admin:reassignItems":this.privilegeObj.portal.admin.reassignItems=a;break;case "portal:admin:manageLicenses":this.privilegeObj.portal.admin.manageLicenses=a;break;case "portal:publisher:publishFeatures":this.privilegeObj.portal.publisher.publishFeatures=a;break;case "portal:publisher:publishTiles":this.privilegeObj.portal.publisher.publishTiles=a;break;case "portal:publisher:publishScenes":this.privilegeObj.portal.publisher.publishScenes=
a;break;case "portal:user:createGroup":this.privilegeObj.portal.user.createGroup=a;break;case "portal:user:joinGroup":this.privilegeObj.portal.user.joinGroup=a;break;case "portal:user:joinNonOrgGroup":this.privilegeObj.portal.user.joinNonOrgGroup=a;break;case "portal:user:createItem":this.privilegeObj.portal.user.createItem=a;break;case "portal:user:shareToGroup":this.privilegeObj.portal.user.shareToGroup=a;break;case "portal:user:shareToOrg":this.privilegeObj.portal.user.shareToOrg=a;break;case "portal:user:shareToPublic":this.privilegeObj.portal.user.shareToPublic=
a;break;case "portal:user:shareGroupToOrg":this.privilegeObj.portal.user.shareGroupToOrg=a;break;case "portal:user:shareGroupToPublic":this.privilegeObj.portal.user.shareGroupToPublic=a;break;case "features:user:edit":this.privilegeObj.features.user.edit=a;break;case "features:user:fullEdit":this.privilegeObj.features.user.fullEdit=a;break;case "opendata:user:openDataAdmin":this.privilegeObj.opendata.user.openDataAdmin=a;break;case "opendata:user:designateGroup":this.privilegeObj.opendata.user.designateGroup=
a;break;case "premium:user:geocode":this.privilegeObj.premium.user.geocode=a;break;case "premium:user:networkanalysis":this.privilegeObj.premium.user.networkanalysis=a;break;case "premium:user:spatialanalysis":this.privilegeObj.premium.user.spatialanalysis=a;break;case "premium:user:geoenrichment":this.privilegeObj.premium.user.geoenrichment=a;break;case "premium:user:demographics":this.privilegeObj.premium.user.demographics=a;break;case "premium:user:elevation":this.privilegeObj.premium.user.elevation=
a;break;case "premium:publisher:createNotebooks":this.privilegeObj.premium.publisher.createNotebooks=a;break;case "marketplace:admin:purchase":this.privilegeObj.marketplace.admin.purchase=a;break;case "marketplace:admin:manage":this.privilegeObj.marketplace.admin.manage=a;break;case "marketplace:admin:startTrial":this.privilegeObj.marketplace.admin.startTrial=a}},_applyToAll:function(a){this.privilegeObj.portal.admin.inviteUsers=a;this.privilegeObj.portal.admin.disableUsers=a;this.privilegeObj.portal.admin.viewUsers=
a;this.privilegeObj.portal.admin.updateUsers=a;this.privilegeObj.portal.admin.deleteUsers=a;this.privilegeObj.portal.admin.changeUserRoles=a;this.privilegeObj.portal.admin.viewGroups=a;this.privilegeObj.portal.admin.updateGroups=a;this.privilegeObj.portal.admin.deleteGroups=a;this.privilegeObj.portal.admin.reassignGroups=a;this.privilegeObj.portal.admin.assignToGroups=a;this.privilegeObj.portal.admin.manageEnterpriseGroups=a;this.privilegeObj.portal.admin.viewItems=a;this.privilegeObj.portal.admin.updateItems=
a;this.privilegeObj.portal.admin.deleteItems=a;this.privilegeObj.portal.admin.reassignItems=a;this.privilegeObj.portal.admin.manageLicenses=a;this.privilegeObj.portal.publisher.publishFeatures=a;this.privilegeObj.portal.publisher.publishTiles=a;this.privilegeObj.portal.publisher.publishScenes=a;this.privilegeObj.portal.user.createGroup=a;this.privilegeObj.portal.user.joinGroup=a;this.privilegeObj.portal.user.joinNonOrgGroup=a;this.privilegeObj.portal.user.createItem=a;this.privilegeObj.portal.user.shareToGroup=
a;this.privilegeObj.portal.user.shareToOrg=a;this.privilegeObj.portal.user.shareToPublic=a;this.privilegeObj.portal.user.shareGroupToOrg=a;this.privilegeObj.portal.user.shareGroupToPublic=a;this.privilegeObj.features.user.edit=a;this.privilegeObj.opendata.user.openDataAdmin=a;this.privilegeObj.opendata.user.designateGroup=a;this.privilegeObj.premium.user.geocode=a;this.privilegeObj.premium.user.networkanalysis=a;this.privilegeObj.premium.user.spatialanalysis=a;this.privilegeObj.premium.user.geoenrichment=
a;this.privilegeObj.premium.user.demographics=a;this.privilegeObj.premium.user.elevation=a;this.privilegeObj.premium.publisher.createNotebooks=a;this.privilegeObj.marketplace.admin.purchase=a;this.privilegeObj.marketplace.admin.manage=a;this.privilegeObj.marketplace.admin.startTrial=a},_buildPrivilegesArray:function(){var a=[];!0===this.privilegeObj.portal.admin.inviteUsers&&a.push("portal:admin:inviteUsers");!0===this.privilegeObj.portal.admin.disableUsers&&a.push("portal:admin:disableUsers");!0===
this.privilegeObj.portal.admin.viewUsers&&a.push("portal:admin:viewUsers");!0===this.privilegeObj.portal.admin.updateUsers&&a.push("portal:admin:updateUsers");!0===this.privilegeObj.portal.admin.deleteUsers&&a.push("portal:admin:deleteUsers");!0===this.privilegeObj.portal.admin.changeUserRoles&&a.push("portal:admin:changeUserRoles");!0===this.privilegeObj.portal.admin.viewGroups&&a.push("portal:admin:viewGroups");!0===this.privilegeObj.portal.admin.updateGroups&&a.push("portal:admin:updateGroups");
!0===this.privilegeObj.portal.admin.deleteGroups&&a.push("portal:admin:deleteGroups");!0===this.privilegeObj.portal.admin.reassignGroups&&a.push("portal:admin:reassignGroups");!0===this.privilegeObj.portal.admin.assignToGroups&&a.push("portal:admin:assignToGroups");!0===this.privilegeObj.portal.admin.manageEnterpriseGroups&&a.push("portal:admin:manageEnterpriseGroups");!0===this.privilegeObj.portal.admin.viewItems&&a.push("portal:admin:viewItems");!0===this.privilegeObj.portal.admin.updateItems&&
a.push("portal:admin:updateItems");!0===this.privilegeObj.portal.admin.deleteItems&&a.push("portal:admin:deleteItems");!0===this.privilegeObj.portal.admin.reassignItems&&a.push("portal:admin:reassignItems");!0===this.privilegeObj.portal.admin.manageLicenses&&a.push("portal:admin:manageLicenses");!0===this.privilegeObj.portal.publisher.publishFeatures&&a.push("portal:publisher:publishFeatures");!0===this.privilegeObj.portal.publisher.publishTiles&&a.push("portal:publisher:publishTiles");!0===this.privilegeObj.portal.publisher.publishScenes&&
a.push("portal:publisher:publishScenes");!0===this.privilegeObj.portal.user.createGroup&&a.push("portal:user:createGroup");!0===this.privilegeObj.portal.user.joinGroup&&a.push("portal:user:joinGroup");!0===this.privilegeObj.portal.user.joinNonOrgGroup&&a.push("portal:user:joinNonOrgGroup");!0===this.privilegeObj.portal.user.createItem&&a.push("portal:user:createItem");!0===this.privilegeObj.portal.user.shareToGroup&&a.push("portal:user:shareToGroup");!0===this.privilegeObj.portal.user.shareToOrg&&
a.push("portal:user:shareToOrg");!0===this.privilegeObj.portal.user.shareToPublic&&a.push("portal:user:shareToPublic");!0===this.privilegeObj.portal.user.shareGroupToOrg&&a.push("portal:user:shareGroupToOrg");!0===this.privilegeObj.portal.user.shareGroupToPublic&&a.push("portal:user:shareGroupToPublic");!0===this.privilegeObj.features.user.edit&&a.push("features:user:edit");!0===this.privilegeObj.features.user.fullEdit&&a.push("features:user:fullEdit");!0===this.privilegeObj.opendata.user.openDataAdmin&&
a.push("opendata:user:openDataAdmin");!0===this.privilegeObj.opendata.user.designateGroup&&a.push("opendata:user:designateGroup");!0===this.privilegeObj.premium.user.geocode&&a.push("premium:user:geocode");!0===this.privilegeObj.premium.user.networkanalysis&&a.push("premium:user:networkanalysis");!0===this.privilegeObj.premium.user.spatialanalysis&&a.push("premium:user:spatialanalysis");!0===this.privilegeObj.premium.user.geoenrichment&&a.push("premium:user:geoenrichment");!0===this.privilegeObj.premium.user.demographics&&
a.push("premium:user:demographics");!0===this.privilegeObj.premium.user.elevation&&a.push("premium:user:elevation");!0===this.privilegeObj.premium.publisher.createNotebooks&&a.push("premium:publisher:createNotebooks");!0===this.privilegeObj.marketplace.admin.purchase&&a.push("marketplace:admin:purchase");!0===this.privilegeObj.marketplace.admin.manage&&a.push("marketplace:admin:manage");!0===this.privilegeObj.marketplace.admin.startTrial&&a.push("marketplace:admin:startTrial");return a},isUser:function(){return b.isDefined(this.id)&&
("org_user"===this.id||"account_user"===this.id)},isPublisher:function(){return b.isDefined(this.id)&&("org_publisher"===this.id||"account_publisher"===this.id)},isAdmin:function(){return b.isDefined(this.id)&&("org_admin"===this.id||"account_admin"===this.id)},isBasedOnUser:function(){return this.isUser()||b.isDefined(this.baseRole)&&("org_user"===this.baseRole||"account_user"===this.baseRole)},isBasedOnPublisher:function(){return this.isPublisher()||b.isDefined(this.baseRole)&&("org_publisher"===
this.baseRole||"account_publisher"===this.baseRole)},isBasedOnAdmin:function(){return this.isAdmin()||b.isDefined(this.baseRole)&&("org_admin"===this.baseRole||"account_admin"===this.baseRole)},isCustom:function(){return!this.isUser()&&!this.isPublisher()&&!this.isAdmin()&&b.isDefined(this.id)&&0<this.id.length},canInviteUsers:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.inviteUsers},canDisableUsers:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.disableUsers},
canViewUsers:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.viewUsers},canUpdateUsers:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.updateUsers},canDeleteUsers:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.deleteUsers},canChangeUserRoles:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.changeUserRoles},canViewOrgGroups:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.viewGroups},canUpdateOrgGroups:function(){return this.privilegeObj&&
this.privilegeObj.portal.admin.updateGroups},canDeleteOrgGroups:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.deleteGroups},canReassignOrgGroups:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.reassignGroups},canAssignUsersToOrgGroups:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.assignToGroups},canManageEnterpriseGroups:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.manageEnterpriseGroups},canViewOrgItems:function(){return this.privilegeObj&&
this.privilegeObj.portal.admin.viewItems},canUpdateOrgItems:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.updateItems},canDeleteOrgItems:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.deleteItems},canReassignOrgItems:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.reassignItems},canManageLicenses:function(){return this.privilegeObj&&this.privilegeObj.portal.admin.manageLicenses},canCreateGroup:function(){return this.privilegeObj&&this.privilegeObj.portal.user.createGroup},
canJoinOrgGroup:function(){return this.privilegeObj&&this.privilegeObj.portal.user.joinGroup},canJoinNonOrgGroup:function(){return this.privilegeObj&&this.privilegeObj.portal.user.joinNonOrgGroup},canPublishFeatures:function(){return this.privilegeObj&&this.privilegeObj.portal.publisher.publishFeatures},canPublishTiles:function(){return this.privilegeObj&&this.privilegeObj.portal.publisher.publishTiles},canPublishScenes:function(){return this.privilegeObj&&this.privilegeObj.portal.publisher.publishScenes},
canCreateItem:function(){return this.privilegeObj&&this.privilegeObj.portal.user.createItem},canShareItemToGroup:function(){return this.privilegeObj&&this.privilegeObj.portal.user.shareToGroup},canShareItemToOrg:function(){return this.privilegeObj&&this.privilegeObj.portal.user.shareToOrg},canShareItemToPublic:function(){return this.privilegeObj&&this.privilegeObj.portal.user.shareToPublic},canShareGroupToOrg:function(){return this.privilegeObj&&this.privilegeObj.portal.user.shareGroupToOrg},canShareGroupToPublic:function(){return this.privilegeObj&&
this.privilegeObj.portal.user.shareGroupToPublic},canEditFeatures:function(){return this.privilegeObj&&this.privilegeObj.features.user.edit},canEditFeaturesFullControl:function(){return this.privilegeObj&&this.privilegeObj.features.user.fullEdit},canManageOpenData:function(){return this.privilegeObj&&this.privilegeObj.opendata.user.openDataAdmin},canDesignateOpenDataGroups:function(){return this.privilegeObj&&this.privilegeObj.opendata.user.designateGroup},canUseGeocode:function(){return this.privilegeObj&&
this.privilegeObj.premium.user.geocode},canUseNetworkAnalysis:function(){return this.privilegeObj&&this.privilegeObj.premium.user.networkanalysis},canUseSpatialAnalysis:function(){return this.privilegeObj&&this.privilegeObj.premium.user.spatialanalysis},canUseGeoenrichment:function(){return this.privilegeObj&&this.privilegeObj.premium.user.geoenrichment},canUseDemographics:function(){return this.privilegeObj&&this.privilegeObj.premium.user.demographics},canCreateNotebooks:function(){return this.privilegeObj&&
this.privilegeObj.premium.publisher.createNotebooks},canPurchaseMarketplace:function(){return this.privilegeObj&&this.privilegeObj.marketplace.admin.purchase},canManageMarketplace:function(){return this.privilegeObj&&this.privilegeObj.marketplace.admin.manage},canTrialMarketplace:function(){return this.privilegeObj&&this.privilegeObj.marketplace.admin.startTrial},setPrivileges:function(a){this.privileges=a;this._initPrivilegesObject();b.isDefined(a)&&this._readPrivileges(a)},stringify:function(){return c.stringify({id:this.id,
name:this.name,description:this.description,privileges:this._buildPrivilegesArray()})},stringifyRole:function(){return c.stringify({id:this.id,name:this.name,description:this.description})},stringifyPrivileges:function(){return c.stringify({privileges:this._buildPrivilegesArray()})},stringifyPretty:function(){return c.stringify({id:this.id,name:this.name,description:this.description,privileges:this._buildPrivilegesArray()},null,"  ")}})});