// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/Deferred dojo/topic dojo/Evented dojo/on dijit/Tooltip dojo/aspect dojo/json dojo/query dojo/request/xhr dojo/promise/all dijit/registry ./utils jimu/tokenUtils ./dijit/Message ./DataSourceManager".split(" "),function(B,d,l,m,k,h,C,D,E,n,v,F,w,q,r,e,z,x,A){var t=null,y=B(C,{constructor:function(){this.loaded=[];this.missedActions=[];this.activeWidget=null;window.isBuilder?(h.subscribe("app/mapLoaded",d.hitch(this,this._onMapLoaded)),
h.subscribe("app/mapChanged",d.hitch(this,this._onMapChanged))):(h.subscribe("mapLoaded",d.hitch(this,this._onMapLoaded)),h.subscribe("mapChanged",d.hitch(this,this._onMapChanged)));window.isBuilder?(h.subscribe("app/sceneViewLoaded",d.hitch(this,this._onSceneViewLoaded)),h.subscribe("app/sceneViewChanged",d.hitch(this,this._onSceneViewChanged))):(h.subscribe("sceneViewLoaded",d.hitch(this,this._onSceneViewLoaded)),h.subscribe("sceneViewChanged",d.hitch(this,this._onSceneViewChanged)));window.isBuilder?
(h.subscribe("app/appConfigLoaded",d.hitch(this,this._onAppConfigLoaded)),h.subscribe("app/appConfigChanged",d.hitch(this,this._onAppConfigChanged))):(h.subscribe("appConfigLoaded",d.hitch(this,this._onAppConfigLoaded)),h.subscribe("appConfigChanged",d.hitch(this,this._onAppConfigChanged)));h.subscribe("userSignIn",d.hitch(this,this._onUserSignIn));h.subscribe("userSignOut",d.hitch(this,this._onUserSignOut));h.subscribe("builder/actionTriggered",d.hitch(this,this._onActionTriggered));h.subscribe("/dnd/move/start",
d.hitch(this,this._onMoveStart))},loadWidget:function(a){var b=new k,c;a=d.clone(a);(c=this.getWidgetById(a.id))?b.resolve(c):q([this.loadWidgetClass(a),this.loadWidgetManifest(a)]).then(d.hitch(this,function(a){var c=a[0],f=a[1];this.loadWidgetResources(f).then(d.hitch(this,function(a){try{var g=this.createWidget(f,c,a);m.setAttr(g.domNode,"data-widget-name",f.name);console.log("widget ["+f.uri+"] created.")}catch(u){console.log("create ["+f.uri+"] error:"+u.stack),new x({message:window.jimuNls.widgetManager.createWidgetError+
": "+f.uri}),r.byId(f.id)&&r.byId(f.id).destroy(),b.reject(u)}setTimeout(d.hitch(this,function(){b.resolve(g);this.emit("widget-created",g);h.publish("widgetCreated",g)}),50)}),function(a){b.reject(a)})}),function(a){b.reject(a)});return b},loadWidgetClass:function(a){var b=new k,c;if(a.isRemote)return c=a.uri+".js",setTimeout(function(){b.reject("Not allow.")},10),b;c=a.uri;require(e.getRequireConfig(),[c],d.hitch(this,function(a){b.resolve(a)}));e.checkError(a.uri,b);return b},loadWidgetResources:function(a){var b=
new k,c,f,g,p=[];g=d.clone(a);a=this.tryLoadWidgetConfig(g);c=this._tryLoadResource(g,"i18n");f=this._tryLoadResource(g,"style");g=this._tryLoadResource(g,"template");p.push(a);p.push(c);p.push(g);p.push(f);q(p).then(d.hitch(this,function(a){var c={};c.config=a[0];c.i18n=a[1];c.template=a[2];c.style=a[3];b.resolve(c)}),function(a){b.reject(a)});return b},loadWidgetManifest:function(a){var b=new k,c=e.getUriInfo(a.uri);if(c.isRemote)return c=c.folderUrl+"manifest.json?f\x3djson",setTimeout(function(){b.reject("Not allow.")},
10),b;c=c.folderUrl+"manifest.json";if(a.manifest)return b.resolve(a),b;w(c,{handleAs:"json",headers:{"X-Requested-With":null}}).then(d.hitch(this,function(c){if(c.error&&c.error.code)return b.reject(c.error);c.category="widget";d.mixin(c,e.getUriInfo(a.uri));e.manifest.addI18NLabel(c).then(d.hitch(this,function(){this._processManifest(c);e.widgetJson.addManifest2WidgetJson(a,c);b.resolve(a)}))}),function(a){b.reject(a)});return b},getWidgetMarginBox:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),
!a))return{};if(a._marginBox)return a._marginBox;var b={left:-9999,top:-9999,relativeTo:a.position.relativeTo};a._isTestSizeFlag=!0;a.setPosition(b);this.openWidget(a);a._marginBox=a.getMarginBox();this.closeWidget(a);"undefined"!==typeof a._isTestSizeFlag&&delete a._isTestSizeFlag;return a._marginBox},_processManifest:function(a){e.manifest.addManifestProperies(a);e.manifest.processManifestLabel(a,window.dojoConfig.locale)},createWidget:function(a,b,c){if(this.getWidgetById(a.id))return this.getWidgetById(a.id);
c.config&&c.i18n&&(c.config=e.replacePlaceHolder(c.config,c.i18n));a.rawConfig=a.config;a.config=c.config||{};this.appConfig._appData&&this._mergeAgolConfig(a);a.nls=c.i18n||{};c.template&&(a.templateString=c.template);a["class"]="jimu-widget";a.label||(a.label=a.name);this.map&&(a.map=this.map);a.appConfig=this.appConfig;c={};for(var f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);c.widgetManager=this;a=new b(c);a.clazz=b;n.after(a,"startup",d.hitch(this,this._postWidgetStartup,a));n.before(a,"destroy",
d.hitch(this,this._onDestroyWidget,a));a.domNode.addEventListener(this._getActiveEventName(),d.hitch(this,this._onClickWidget,a),{capture:!0});this.loaded.push(a);return a},getAllWidgets:function(){return this.loaded},destroyAllWidgets:function(){var a=l.map(this.loaded,function(a){return a.id});l.forEach(a,function(a){this.destroyWidget(a)},this);this.loaded=[]},loadWidgetSettingPage:function(a){var b=new k;a=d.clone(a);a.id+="_setting";q([this.loadWidgetSettingClass(a)]).then(d.hitch(this,function(c){var f=
c[0];this.loadWidgetSettingPageResources(a).then(d.hitch(this,function(c){var g,e={nls:c.i18n,appConfig:this.appConfig,"class":"jimu-widget-setting"};null!==c.template&&(e.templateString=c.template);"HTML3D"===window.appInfo.appType?e.sceneView=this.sceneView:e.map=this.map;for(var h in a)a.hasOwnProperty(h)&&(e[h]=a[h]);try{g=new f(e),m.setAttr(g.domNode,"data-widget-name-setting",e.name),n.before(g,"destroy",d.hitch(this,this._onDestroyWidgetSetting,g)),b.resolve(g)}catch(u){new x({message:window.jimuNls.widgetManager.createWidgetSettingPageError+
":"+a.uri}),r.byId(e.id)&&r.byId(e.id).destroy(),b.reject(u)}}),function(a){console.log(a)})}),function(a){b.reject(a)});return b},loadWidgetSettingClass:function(a){var b=new k,c;c=a.isRemote?a.folderUrl+"setting/Setting.js":a.amdFolder+"setting/Setting";require(e.getRequireConfig(),[c],d.hitch(this,function(a){b.resolve(a)}));e.checkError(a.folderUrl+"setting/Setting.js",b);return b},loadWidgetSettingPageResources:function(a){var b=new k,c,f,g=[];a=d.clone(a);c=this._tryLoadResource(a,"settingI18n");
f=this._tryLoadResource(a,"settingTemplate");a=this._tryLoadResource(a,"settingStyle");g.push(c);g.push(f);g.push(a);q(g).then(d.hitch(this,function(a){var c={};c.i18n=a[0]||{};c.template=a[1];c.style=a[2];b.resolve(c)}),function(a){console.log(a)});return b},getWidgetById:function(a){var b;l.some(this.loaded,function(c){if(c.id===a)return b=c,!0},this);return b},getWidgetByLabel:function(a){var b;l.some(this.loaded,function(c){if(c.label===a)return b=c,!0},this);return b},getWidgetsByName:function(a){var b=
[];l.some(this.loaded,function(c){c.name===a&&b.push(c)},this);return b},changeWindowStateTo:function(a,b){"normal"===b?this.normalizeWidget(a):"minimized"===b?this.minimizeWidget(a):"maximized"===b?this.maximizeWidget(a):console.log("error state: "+b)},closeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;if("closed"!==a.state){this.activeWidget&&this.activeWidget.id===a.id&&(this.activeWidget.onDeActive(),this.activeWidget=null);m.setStyle(a.domNode,"display","none");
a.setState("closed");try{a.onClose()}catch(b){console.log(console.error("fail to close widget "+a.name+". "+b.stack))}}this.appConfig.mode||this._removeDataSourceUsage(a)},openWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;if(!a.started)try{a.started=!0,a.startup()}catch(b){console.error("fail to startup widget "+a.name+". "+b.stack)}if("closed"===a.state){m.setStyle(a.domNode,"display","");a.setState("opened");try{a.onOpen()}catch(b){console.error("fail to open widget "+
a.name+". "+b.stack)}e.isAutoFocusFirstNodeWidget(a)&&e.focusFirstFocusNode(a.domNode);this.appConfig.mode||this._addDataSourceUsage(a)}},activateWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"opened"===a.state&&this._activeWidget(a)},maximizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("maximized");try{a.onMaximize()}catch(b){console.log(console.error("fail to maximize widget "+
a.name+". "+b.stack))}},minimizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("minimized");try{a.onMinimize()}catch(b){console.log(console.error("fail to minimize widget "+a.name+". "+b.stack))}},normalizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("normal");try{a.onNormalize()}catch(b){console.log(console.error("fail to normalize widget "+
a.name+". "+b.stack))}},destroyWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;this._removeWidget(a);try{a.destroy()}catch(b){console.log(console.error("fail to destroy widget "+a.name+". "+b.stack))}},tryLoadWidgetConfig:function(a){return this._tryLoadWidgetConfig(a).then(d.hitch(this,function(b){return this._upgradeWidgetConfig(a,b).then(function(b){return a.config=b})}))},triggerWidgetOpen:function(a){function b(a){var b=n.after(a,"onOpen",function(){b.remove();
c.resolve(a)})}var c=new k,f=this.getWidgetById(a);if(f){if("closed"!==f.state)return c.resolve(f),c;b(f)}else var g=h.subscribe("widgetCreated",d.hitch(this,function(b){b.id===a&&(g.remove(),c.resolve(b))}));h.publish("openWidget",a);return c},_tryLoadWidgetConfig:function(a){var b=new k;if(a.config&&d.isObject(a.config))return b.resolve(a.config),b;if(a.config){if(require.cache["url:"+a.config])return b.resolve(v.parse(require.cache["url:"+a.config])),b;b=e.processUrlInAppConfig(a.config);b=b.split("/");
b[b.length-1]=encodeURIComponent(b[b.length-1]);b=b.join("/");return w(b,{handleAs:"json",headers:{"X-Requested-With":null}})}return this._tryLoadResource(a,"config").then(function(b){a.isDefaultConfig=!0;return b})},_upgradeWidgetConfig:function(a,b){var c=new k,f=a.manifest.version,g=a.version,h;if(f===g)return c.resolve(b),c;if(!1===a.hasVersionManager)return a.version=f,c.resolve(b),c;require(e.getRequireConfig(),[a.amdFolder+(a.isRemote?"VersionManager.js":"VersionManager")],d.hitch(this,function(d){d=
new d;var e=d.getVersionIndex(g),k=d.getVersionIndex(f);if(e>k)c.reject("Bad widget version number, "+a.name+","+g);else try{h=d.upgrade(b,g,f),a.version=f,c.resolve(h)}catch(G){console.log("Read widget ["+a.name+"] old config error,"+G.stack),c.resolve(b)}}));return c},loadWidgetStyle:function(a){var b=this._getStyleIdFromWidgetJson(a,!1),c=new k;return m.byId(b)?(c.resolve("load"),c):e.loadStyleLink(b,a.styleFile,"theme_"+this.appConfig.theme.name+"_style_common")},loadWidgetSettingStyle:function(a){var b=
this._getStyleIdFromWidgetJson(a,!0),c=new k;return m.byId(b)?(c.resolve("load"),c):e.loadStyleLink(b,a.settingStyleFile)},loadWidgetConfig:function(a){a=require(e.getRequireConfig()).toUrl(a.configFile);if(require.cache["url:"+a]){var b=new k;b.resolve(v.parse(require.cache["url:"+a]));return b}return w(a,{handleAs:"json",headers:{"X-Requested-With":null}})},loadWidgetI18n:function(a){var b=new k;require(e.getRequireConfig(),["dojo/i18n!"+a.i18nFile],function(a){b.resolve(a)});return b},loadWidgetSettingI18n:function(a){var b=
new k;require(e.getRequireConfig(),["dojo/i18n!"+a.settingI18nFile],function(a){b.resolve(a)});return b},loadWidgetTemplate:function(a){var b=new k;require(e.getRequireConfig(),["dojo/text!"+a.templateFile],function(a){b.resolve(a)});e.checkError(a.templateFile,b);return b},loadWidgetSettingTemplate:function(a){var b=new k;require(e.getRequireConfig(),["dojo/text!"+a.settingTemplateFile],function(a){b.resolve(a)});e.checkError(a.settingTemplateFile,b);return b},removeWidgetStyle:function(a){this._removeStyle(this._getStyleIdFromWidgetJson(a,
!1))},removeWidgetSettingStyle:function(a){this._removeStyle(this._getStyleIdFromWidgetJson(a,!0))},_removeStyle:function(a){if(m.byId(a)){var b=m.attr(a,"data-import-styles");if(b)for(var c=0;c<parseInt(b,10);c++)m.destroy(a+"_import_"+c);m.destroy(a)}},_getStyleIdFromWidgetJson:function(a,b){return this._replaceId("widget/style/"+(a.itemId?a.itemId:a.uri)+(b?"/setting":""))},getControllerWidgets:function(){return l.filter(this.loaded,function(a){return a.isController})},getOffPanelWidgets:function(){return l.filter(this.loaded,
function(a){return!a.inPanel})},getOnScreenOffPanelWidgets:function(){return l.filter(this.loaded,function(a){return a.isOnScreen&&!a.inPanel})},closeOtherWidgetsInTheSameGroup:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;for(var b=0;b<this.loaded.length;b++)this.loaded[b].gid===a.gid&&this.loaded[b].id!==a.id&&this.closeWidget(this.loaded[b])},closeAllWidgetsInGroup:function(a){for(var b=0;b<this.loaded.length;b++)this.loaded[b].gid===a&&this.closeWidget(this.loaded[b])},
_addDataSourceUsage:function(a){l.forEach(this._getUsedDataSourceIdFromWidget(a),function(b){A.getInstance().addDataSourceUsage(b,a.id)})},_removeDataSourceUsage:function(a){l.forEach(this._getUsedDataSourceIdFromWidget(a),function(b){A.getInstance().removeDataSourceUsage(b,a.id)})},_getUsedDataSourceIdFromWidget:function(a){if((a=this.appConfig.getConfigElementById(a.id))&&a.config){var b=v.stringify(a.config);return l.filter(Object.keys(this.appConfig.dataSource.dataSources),function(a){return-1<
b.indexOf(a)},this)}},_mergeAgolConfig:function(a){var b=this.appConfig._appData.values,c="widgets["+a.id+"]",f;for(f in b){var d=f.replace(/\//g,"_").indexOf(c+"_config");0<=d&&e.template.setConfigValue(a,f.replace(/\//g,"_").substr(d,f.length).replace(c,"widget"),b[f])}},_onUserSignIn:function(a){l.forEach(this.loaded,function(b){b.onSignIn(a)},this)},_onUserSignOut:function(){l.forEach(this.loaded,function(a){a.onSignOut()},this)},_activeWidget:function(a){if(this.activeWidget){if(this.activeWidget.id===
a.id){!1===this.activeWidget.inPanel&&this.activeWidget.moveTopOnActive&&m.setStyle(this.activeWidget.domNode,"zIndex",101);return}"active"===this.activeWidget.state&&(this.activeWidget.setState("opened"),!1===this.activeWidget.inPanel&&m.setStyle(a.domNode,"zIndex","zIndex"in a.position?a.position.zIndex:"auto"),this.activeWidget.onDeActive())}this.activeWidget=a;"opened"===this.activeWidget.state&&(this.activeWidget.setState("active"),!1===this.activeWidget.inPanel&&this.activeWidget.moveTopOnActive&&
m.setStyle(this.activeWidget.domNode,"zIndex",101),this.activeWidget.onActive(),h.publish("widgetActived",a))},_onClickWidget:function(a,b){var c=F(".jimu-widget",a.domNode);if(0<c.length)for(var d=0;d<c.length;d++)if(b.target===c[d]||m.isDescendant(b.target,c[d]))return;this._activeWidget(a)},_onMoveStart:function(a){l.forEach(this.loaded,function(b){b.domNode===a.node&&this._activeWidget(b)},this)},_onAppConfigLoaded:function(a){this.appConfig=a=d.clone(a);z.setPortalUrl(a.portalUrl)},_onMapLoaded:function(a){this.map=
a},_onMapChanged:function(a){this.map=a},_onSceneViewLoaded:function(a){this.sceneView=a},_onSceneViewChanged:function(a){this.sceneView=a},_onAppConfigChanged:function(a,b,c,f){var e=d.clone(a);this.appConfig=e;l.forEach(this.loaded,function(a){a&&(a.onAppConfigChanged(e,b,c,f),"widgetChange"===b&&this._onConfigChanged(c.id,c.config,f))},this)},_onConfigChanged:function(a,b){if(a=this.getWidgetById(a))a.onConfigChanged(b),d.mixin(a.config,b)},_onActionTriggered:function(a){if("map"!==a.elementId&&
"app"!==a.elementId){var b=this.getWidgetById(a.elementId);if(b)b.onAction(a.action,a.data);else this.missedActions.push({id:a.elementId,action:{name:a.action,data:a.data}});l.forEach(this.getControllerWidgets(),function(b){if(b.widgetIsControlled(a.elementId))b.onAction(a.action,{widgetId:a.elementId,data:a.data})},this)}},_resetFirstFocusNode:function(a){if(window.isMoveFocusWhenInit){var b=this.getWidgetsByName("Splash")[0];if(b&&"none"!==m.getStyle(b.domNode,"display"))window.isMoveFocusWhenInit=
!1,a&&"Splash"===a.name||b.domNode.focus();else if(window.currentMsgPopup&&window.currentMsgPopup.firstFocusNode)window.isMoveFocusWhenInit=!1,window.currentMsgPopup.focusedNodeBeforeOpen=e.getFirstSkipLink(),window.currentMsgPopup.firstFocusNode.focus();else if(window.isMoveFocusWhenInit)window.isMoveFocusWhenInit=!1,e.isInNavMode()&&e.focusOnFirstSkipLink();else return!1;return!0}},_postWidgetStartup:function(a){a.started=!0;e.setVerticalCenter(a.domNode);n.after(a,"resize",d.hitch(this,e.setVerticalCenter,
a.domNode));e.initTabIndexAndOrder(a);e.initWidgetCancelEvent(a);var b=a.position||a.panel&&a.panel.position;b&&"browser"===b.relativeTo&&D(a.domNode,"focus",d.hitch(this,function(){this._resetFirstFocusNode()}));this.openWidget(a);if(b=z.getPortalCredential(this.appConfig.portalUrl))a.onSignIn(b);else a.onSignOut();this._triggerMissedAction(a);a.inPanel||e.addTooltipByDomNode(E,a.domNode,a.label)},_triggerMissedAction:function(a){this.missedActions.forEach(function(b){if(b.id===a.id)a.onAction(b.action.name,
b.action.data)})},_remove:function(a){return l.some(this.loaded,function(b,c){if(b.id===a)return this.loaded.splice(c,1),!0},this)},_tryLoadResource:function(a,b){var c,d=new k;if("config"===b)c=a.amdFolder+"config.json",a.configFile=c,c="hasConfig";else if("style"===b)c=a.amdFolder+"css/style.css",a.styleFile=c,c="hasStyle";else if("i18n"===b)c=a.amdFolder+"nls/strings.js",a.i18nFile=a.isRemote?c:a.amdFolder+"nls/strings",c="hasLocale";else if("template"===b)c=a.amdFolder+"Widget.html",a.templateFile=
c,c="hasUIFile";else if("settingTemplate"===b)c=a.amdFolder+"setting/Setting.html",a.settingTemplateFile=c,c="hasSettingUIFile";else if("settingI18n"===b)c=a.amdFolder+"setting/nls/strings.js",a.settingI18nFile=a.isRemote?c:a.amdFolder+"setting/nls/strings",c="hasSettingLocale";else if("settingStyle"===b)c=a.amdFolder+"setting/css/style.css",a.settingStyleFile=c,c="hasSettingStyle";else return d;a[c]?function(){var c;if("config"===b)c=this.loadWidgetConfig(a);else if("style"===b)c=this.loadWidgetStyle(a);
else if("i18n"===b)c=this.loadWidgetI18n(a);else if("template"===b)c=this.loadWidgetTemplate(a);else if("settingTemplate"===b)c=this.loadWidgetSettingTemplate(a);else if("settingStyle"===b)c=this.loadWidgetSettingStyle(a);else if("settingI18n"===b)c=this.loadWidgetSettingI18n(a);else return d;c.then(function(a){d.resolve(a)},function(c){console.error("Load widget resource error. resource:",b);console.error(c);new x({message:window.jimuNls.widgetManager.loadWidgetResourceError+": "+a.uri});d.reject(c)})}.apply(this):
d.resolve(null);return d},_replaceId:function(a){return a.replace(/\//g,"_").replace(/\./g,"_")},_onDestroyWidget:function(a){"closed"!==a.state&&this.closeWidget(a);this._removeWidget(a);this.emit("widget-destroyed",a.id);h.publish("widgetDestroyed",a.id);console.log("destroy widget ["+a.uri+"].")},_onDestroyWidgetSetting:function(a){this.removeWidgetSettingStyle(a)},_removeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;this.activeWidget&&this.activeWidget.id===a.id&&
(this.activeWidget=null);this._remove(a.id);0===this.getWidgetsByName(a.name).length&&this.removeWidgetStyle(a)},_getActiveEventName:function(){var a="PointerEvent"in window?"pointer":"MSPointerEvent"in window?"MSPointer":!1,b=a&&"MS"===a.slice(0,2);return a?a+(b?"Down":"down"):"mousedown"}});y.getInstance=function(a){null===t&&(t=new y(a),window._widgetManager=t);return t};return y});