//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Logger ../../../../../../core/screenUtils ../../../../../../core/libs/gl-matrix/mat2d ../../../../../../core/libs/gl-matrix/vec2 ../../color ../../definitions ../../enums ../../number ../../WGLDisplayRecord ./WGLMeshTemplate".split(" "),function(u,z,C,D,r,y,v,A,E,w,t,F,G){Object.defineProperty(z,"__esModule",{value:!0});var B=D.getLogger("esri.views.2d.engine.webgl.WGLMeshTemplate");u=function(u){function d(c,
a,b,n,f,h,l,m,g,d,p){var k=u.call(this)||this;k.geometryType=w.WGLGeometryType.MARKER;var e=v.create(),q=y.create(),x=p.sdf?.5:1;(y.translate(q,q,new Float32Array([x*b,x*-n])),f)&&y.rotate(q,q,3.14159265359/180*f);k._materialStore=c;k.vvFlags=a;k._materialId=c.createSpriteMaterial(p,k.geometryType,a);k._fillColor=h;k._outlineColor=g;k._sizeOutlineWidth=t.i8888to32(l,m,d,0);c=Math.round(p.rect.x/4);a=Math.round(p.rect.y/4);f=c+Math.round(p.rect.width/4);p=a+Math.round(p.rect.height/4);return e.set([-.5*
l,-.5*m]),v.transformMat2d(e,e,q),k._offsetAndTexUpperLeft=t.i8888to32(e[0],e[1],c,a),e.set([.5*l,-.5*m]),v.transformMat2d(e,e,q),k._offsetAndTexUpperRight=t.i8888to32(e[0],e[1],f,a),e.set([-.5*l,.5*m]),v.transformMat2d(e,e,q),k._offsetAndTexBottomLeft=t.i8888to32(e[0],e[1],c,p),e.set([.5*l,.5*m]),v.transformMat2d(e,e,q),k._offsetAndTexBottomRight=t.i8888to32(e[0],e[1],f,p),k.height=m,k.width=l,k.xOffset=b,k.yOffset=n,k}return C(d,u),d.fromPictureMarker=function(c,a,b,n,f){f=Math.round(r.pt2px(b.width));
var h=Math.round(r.pt2px(b.height)),l=E.PICTURE_FILL_COLOR;return new d(c,a,Math.round(r.pt2px(b.xoffset||0)),Math.round(r.pt2px(b.yoffset||0)),b.angle,l,f,h,0,0,n)},d.fromSimpleMarker=function(c,a,b,n,f){f=A.premultiplyAlphaRGBA(b.color);var h=Math.round(r.pt2px(b.size)),l=Math.round(r.pt2px(b.xoffset||0)),m=Math.round(r.pt2px(b.yoffset||0)),g=b.outline,x=0|(g&&g.color&&A.premultiplyAlphaRGBA(g.color)),g=0|(g&&g.width&&Math.round(r.pt2px(g.width)));return new d(c,a,l,m,b.angle,f,h,h,x,g,n)},d.prototype.writeMesh=
function(c,a,b,n,f,h,l){h=this._materialStore.get(this._materialId);var m=a.indexVector;a=a.get("geometry");var g=new F(n,this.geometryType,this._materialId),d=this._getOffset(a,h);switch(c.push(g),g.vertexFrom=d,g.indexFrom=m.length,b){case "esriGeometryPoint":return b=f.geometry,c=b.x,b=b.y,this._writeVertices(g,a,n,this._getPos(c,b),h,l),void this._writeIndices(g,m,d);case "esriGeometryPolyline":return void this._writeMany(g,m,a,d,n,f.geometry.paths[0],h,l);case "esriGeometryPolygon":(b=f.centroid)?
(c=b.x,b=b.y,this._writeVertices(g,a,n,this._getPos(c,b),h,l),this._writeIndices(g,m,d)):B.error("Tried to render polygon geometries as markers, but found no centroid!");break;case "esriGeometryMultipoint":return void this._writeMany(g,m,a,d,n,f.geometry.points,h,l);default:B.error("Unable to handle geometryType: "+b)}},d.prototype._getPos=function(c,a){return t.i1616to32(c,a)},d.prototype._writeMany=function(c,a,b,d,f,h,l,m){for(var g=0,n=0,p=0,k=0;k<h.length;k++){var e=h[k],q=e[0],e=e[1];this._writeVertices(c,
b,f,this._getPos(q+g,e+n),l,m);this._writeIndices(c,a,d+p);g+=q;n+=e;p+=4}},d.prototype._getOffset=function(c,a){a=a.materialKeyInfo.hasVV()?10:6;return c.length/a},d.prototype._writeVertices=function(c,a,b,d,f,h){a.push(d);a.push(this._offsetAndTexUpperLeft);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,h,f);a.push(d);a.push(this._offsetAndTexUpperRight);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);
this._writeVV(a,h,f);a.push(d);a.push(this._offsetAndTexBottomLeft);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,h,f);a.push(d);a.push(this._offsetAndTexBottomRight);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,h,f);c.vertexCount+=4},d.prototype._writeVV=function(c,a,b){b.materialKeyInfo.hasVV()&&(c.push(a[w.VVType.SIZE]),c.push(a[w.VVType.COLOR]),c.push(a[w.VVType.OPACITY]),
c.push(a[w.VVType.ROTATION]))},d.prototype._writeIndices=function(c,a,b){a.push(b+0);a.push(b+1);a.push(b+2);a.push(b+1);a.push(b+3);a.push(b+2);c.indexCount+=6},d}(G.default);z.default=u});