//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Logger ../../../../../../core/screenUtils ../../color ../../definitions ../../enums ../../Geometry ../../number ../../TextShaping ../../WGLDisplayRecord ../../collisions/BoundingBox ./WGLMeshTemplate ../../util/BidiText".split(" "),function(w,v,D,E,l,x,F,u,p,q,y,z,G,H,I){Object.defineProperty(v,"__esModule",{value:!0});var J=E.getLogger("esri.views.2d.engine.webgl.WGLTextTemplate"),A=1.2*24,C=function(){function l(b,
h,a,c,e,d,g,f,k){this.materialId=b;this.vertexOffsetUpperLeft=h;this.vertexOffsetUpperRight=a;this.vertexOffsetLowerLeft=c;this.vertexOffsetLowerRight=e;this.texFontSizeUpperLeft=d;this.texFontSizeUpperRight=g;this.texFontSizeLowerLeft=f;this.texFontSizeLowerRight=k}return l.from=function(b,h,a,c,e){var d,g=b.glyphMosaicItem;d=g.rect;var f=g.metrics,g=Math.round(d.x/4),k=Math.round(d.y/4),r=g+Math.round(d.width/4),B=k+Math.round(d.height/4);if(b.codePoint){var t=b.x+0+f.left;b=b.y+-17-f.top;b=new p.Point(t-
4,b-4);d=new p.Point(b.x+d.width,b.y+d.height)}else t=b.x,b=b.y,b=new p.Point(t,b),d=new p.Point(b.x+f.width,b.y+f.height);f=new p.Point(b.x,d.y);t=new p.Point(d.x,b.y);if(a){var n=Math.cos(a);a=Math.sin(a);b.rotate(n,a);d.rotate(n,a);f.rotate(n,a);t.rotate(n,a)}return new l(h,q.i1616to32(8*b.x,8*b.y),q.i1616to32(8*t.x,8*t.y),q.i1616to32(8*f.x,8*f.y),q.i1616to32(8*d.x,8*d.y),q.i8888to32(g,k,c,e),q.i8888to32(r,k,c,e),q.i8888to32(g,B,c,e),q.i8888to32(r,B,c,e))},l}();v.ComputedGlyph=C;w=function(p){function b(h,
a,c){var e=p.call(this)||this;e.geometryType=u.WGLGeometryType.TEXT;var d=c.haloColor;e.color=0|(c.color&&x.premultiplyAlphaRGBA(c.color));e.textSize=l.pt2px(c.font.size);var b=c.yoffset/c.font.size;return e.shapingXOffset=c.xoffset/c.font.size*24,e.shapingYOffset=24*b,e.haloColor=0|(d&&x.premultiplyAlphaRGBA(d)),e.haloSize=10*l.pt2px(l.toPt(c.haloSize||0)),e.textPropColor=e.color||F.PICTURE_FILL_COLOR,e.textPropSize=l.pt2px(c.font.size),e.textPropAngle=c.angle*Math.PI/180,e.xOffset=l.pt2px(c.xoffset),
e.yOffset=l.pt2px(c.yoffset),e.textPropHAnchor="left"===c.horizontalAlignment?0:"right"===c.horizontalAlignment?1:.5,e.textPropVAnchor="top"===c.verticalAlignment?0:"bottom"===c.verticalAlignment?1:.5,e.textPropHaloColor=e.haloColor||4294967295,e.textPropHaloSize=l.pt2px(l.toPt(c.haloSize||0)),e._materialStore=h,e.vvFlags=a,e}return D(b,p),b.fromText=function(h,a,c,e,d){h=new b(h,a,c);return h.computeGlyphs(d,c.text,!1),h},b.prototype.writeMesh=function(b,a,c,e,d,g,f){g=a.indexVector;var h=a.get("geometry");
a=a.get("visibility");var r=this._getOffset(h);switch(c){case "esriGeometryPoint":return d=d.geometry,c=d.x,d=d.y,void this._writeVertices(b,g,h,a,r,e,c,d,f);case "esriGeometryPolygon":if(d.centroid)return d=d.centroid,c=d.x,d=d.y,void this._writeVertices(b,g,h,a,r,e,c,d,f);default:J.error("Unable to handle geometryType: "+c)}},b.prototype.computeGlyphs=function(b,a,c){if(!a||!a.length)return this._computedGlyphs=[],null;b=this._computeShaping(b,240,A,0,this.shapingXOffset,this.shapingYOffset,this.textPropHAnchor,
this.textPropVAnchor,.5);a=I.bidiText(a);a=b.getShaping(a[0],a[1]);b=Array(a.length);for(var e=0;e<a.length;e++){var d=this.textPropAngle,h=this.textSize,f=this.haloSize,k=this._materialStore.createGlyphMaterial(a[e].glyphMosaicItem,u.WGLGeometryType.TEXT,this.vvFlags);b[e]=C.from(a[e],k,d,h,f)}if(this._computedGlyphs=b,!c)return null;c=y.getBox(a);return c.width*=this.textSize/24,c.height*=this.textSize/24,new G.default(c.x,c.y,c.width,c.height)},b.prototype._computeShaping=function(b,a,c,e,d,g,
f,k,r){return this._shaping=new y([b],240,A,0,[d,g],f,k,.5),this._shaping},b.prototype._getOffset=function(b){return b.length/(this.vvFlags?9:5)},b.prototype._writeVertices=function(b,a,c,e,d,g,f,k,r){var h=this._computedGlyphs,l=q.i1616to32(2*f,2*k);f=q.i1616to32(2*f+1,2*k);k=0;if(this.haloSize)for(var n=0;n<h.length;n++,k+=4){var m=h[n].materialId,p=this._materialStore.get(m),m=new z(g,this.geometryType,m);m.vertexFrom=d;m.indexFrom=a.length;this._writeVertex(m,c,e,g,f,this.haloColor,h[n],p,r);
this._writeIndices(m,a,d+k);b.push(m)}for(n=0;n<h.length;n++,k+=4)m=h[n].materialId,p=this._materialStore.get(m),m=new z(g,this.geometryType,m),m.vertexFrom=d,m.indexFrom=a.length,this._writeVertex(m,c,e,g,l,this.color,h[n],p,r),this._writeIndices(m,a,d+k),b.push(m)},b.prototype._writeVertex=function(b,a,c,e,d,g,f,k,l){a.push(d);a.push(e);a.push(g);a.push(f.vertexOffsetUpperLeft);a.push(f.texFontSizeUpperLeft);this._writeVV(a,l,k);a.push(d);a.push(e);a.push(g);a.push(f.vertexOffsetUpperRight);a.push(f.texFontSizeUpperRight);
this._writeVV(a,l,k);a.push(d);a.push(e);a.push(g);a.push(f.vertexOffsetLowerLeft);a.push(f.texFontSizeLowerLeft);this._writeVV(a,l,k);a.push(d);a.push(e);a.push(g);a.push(f.vertexOffsetLowerRight);a.push(f.texFontSizeLowerRight);this._writeVV(a,l,k);c.push(4294967295);b.vertexCount+=4},b.prototype._writeVV=function(b,a,c){c.materialKeyInfo.hasVV()&&(b.push(a[u.VVType.SIZE]),b.push(a[u.VVType.COLOR]),b.push(a[u.VVType.OPACITY]),b.push(a[u.VVType.ROTATION]))},b.prototype._writeIndices=function(b,a,
c){a.push(c+0);a.push(c+1);a.push(c+2);a.push(c+1);a.push(c+3);a.push(c+2);b.indexCount+=6},b}(H.default);v.default=w});