define({
  "visible": "Показывать обзорную карту по умолчанию",
  "minWidth": "Мин. ширина",
  "minHeight": "Мин. высота",
  "maxWidth": "Макс. ширина",
  "maxHeight": "Макс. высота",
  "minText": "Минимум",
  "maxText": "максимум",
  "attachText": "Выберите угол карты, куда закрепить виджет.",
  "expandText": "Открыть при запуске",
  "topLeft": "Сверху слева",
  "topRight": "Сверху справа",
  "bottomLeft": "Снизу слева",
  "bottomRight": "Снизу справа",
  "baseLayerType": "Отобразить",
  "BaseMap": "Базовая карта этой карты",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "Полистный картографический сервис ArcGIS",
  "dynamicMapService": "Динамический картографический сервис ArcGIS",
  "imageService": "Сервис изображений ArcGIS",
  "OSM": "Открыть карту улиц",
  "bingRoad": "Bing Maps Road",
  "bingAerial": "Bing Maps Aerial",
  "bingHybrid": "Bing Maps Hybrid",
  "WebTiled": "Веб-слой листов",
  "VETiled": "Слой листов Virtual Earth",
  "tileLayerUrl": "Url слоя листов",
  "tile": "Название",
  "credits": "Авторы",
  "subdomain": "Субдомен",
  "extent": "Экстент",
  "initExtent": "Исходный экстент",
  "tileInfo": "TileInfo",
  "VEStyle": "Стиль Virtual Earth",
  "Aerial": "Слой Bing Maps Aerial",
  "AerialWithLabels": "Слой снимков с надписями",
  "Roads": "Слой дорог",
  "errWkid": "Wkid не совпадает",
  "errUrl": "Неправильный URL-адрес",
  "errReqTimeout": "Время истекло",
  "layerPlaceholder": "Введите URL"
});