define({
  "styleText": "Typ av svepverktyg",
  "vertical": "Lodrät stapel",
  "horizontal": "Vågrät stapel",
  "scope": "Kikare",
  "placement": "Vägbeskrivning",
  "showLeftSide": "Visa sveplager på vänster sida",
  "showRigthSide": "Visa sveplager på höger sida",
  "showUpSide": "Visa sveplager överst",
  "showDownSide": "Visa sveplager nederst",
  "barColor": "Stapelfärg",
  "swipeMode": "Svepläge",
  "singleLayer": "Enstaka lager",
  "MultipleLayers": "Flera lager",
  "allowToSwipe": "Tillåt svep",
  "layer": "Lager",
  "swipeByDefault": "Svep som standard",
  "defaultLayerMustBeVisible": "standardlagret måste vara synligt",
  "noDefaultLayer": "Ange de lager som ska svepas som standard",
  "defaultLayerHolder": "Klicka för att välja",
  "selectLayers": "Välj lager",
  "layerText": "Standardsveplager",
  "spyglassText": "Välj det lager som ska visas som standard i kikaren.",
  "layerHint": "Obs! Om lagret är dolt av högre lager har det ingen effekt när du sveper.",
  "isZoom": "Zooma till sveplagret",
  "isZooms": "Zooma för att svepa lager",
  "layersAvailable": "Svepbara lager",
  "hidePanel": "Dölj panelen för val av lager när widgeten öppnas"
});