define({
  "styleText": "Tipo da ferramenta de oscilação",
  "vertical": "Barra vertical",
  "horizontal": "Barra horizontal",
  "scope": "Luneta",
  "placement": "Direção",
  "showLeftSide": "Exibir camadas osciladas no lado esquerdo",
  "showRigthSide": "Exibir camadas osciladas no lado direito",
  "showUpSide": "Exibir camadas osciladas no lado superior",
  "showDownSide": "Exibir camadas osciladas no lado inferior",
  "barColor": "Cor da barra",
  "swipeMode": "Modo Oscilar",
  "singleLayer": "Única camada",
  "MultipleLayers": "Múltiplas camadas",
  "allowToSwipe": "Permitir oscilar",
  "layer": "Camada",
  "swipeByDefault": "Utilizar por padrão",
  "defaultLayerMustBeVisible": "A camada padrão deve ser visível",
  "noDefaultLayer": "Defina as camadas para oscilar por padrão",
  "defaultLayerHolder": "Clique para selecionar",
  "selectLayers": "Selecionar camadas",
  "layerText": "Camada de oscilação padrão",
  "spyglassText": "Selecione a camada para aparecer dentro da luneta por padrão.",
  "layerHint": "Nota: Se a camada estiver oculta por camadas superiores, a oscilação não terá qualquer efeito.",
  "isZoom": "Zoom na camada de oscilação",
  "isZooms": "Zoom nas camadas de oscilação",
  "layersAvailable": "Camadas osciláveis",
  "hidePanel": "Ocultar o painel de seleção da camada ao abrir o widget"
});