define({
  "visible": "Εμφάνιση χάρτη αναφοράς εξ' ορισμού",
  "minWidth": "Ελάχ. πλάτος",
  "minHeight": "Ελάχ. ύψος",
  "maxWidth": "Μέγ. πλάτος",
  "maxHeight": "Μέγ. ύψος",
  "minText": "Ελάχιστο",
  "maxText": "μέγιστο",
  "attachText": "Καθορίστε σε ποια γωνία του χάρτη θα επισυναφθεί αυτό το widget.",
  "expandText": "Το widget να είναι αρχικά ανοιχτό",
  "topLeft": "Επάνω αριστερά",
  "topRight": "Επάνω δεξιά",
  "bottomLeft": "Κάτω αριστερά",
  "bottomRight": "Κάτω δεξιά",
  "baseLayerType": "Παρουσίαση στην οθόνη",
  "BaseMap": "Το υπόβαθρο του χάρτη",
  "ArcGIS": "ArcGIS",
  "tiledMapService": "ArcGIS Tiled Map Service",
  "dynamicMapService": "ArcGIS Dynamic Map Service",
  "imageService": "ArcGIS Image Service",
  "OSM": "Open Street Map",
  "bingRoad": "Bing Maps Road",
  "bingAerial": "Bing Maps Aerial",
  "bingHybrid": "Bing Maps Hybrid",
  "WebTiled": "Web Tiled Layer",
  "VETiled": "Virtual Earth Tiled Layer",
  "tileLayerUrl": "Διεύθυνση URL tile layer",
  "tile": "Τίτλος",
  "credits": "Μονάδες κατανάλωσης",
  "subdomain": "Υποτομείς",
  "extent": "Έκταση",
  "initExtent": "Αρχική έκταση",
  "tileInfo": "Πληροφορίες tile",
  "VEStyle": "Στιλ Virtual Earth",
  "Aerial": "Θεματικό επίπεδο Bing Maps Aerial",
  "AerialWithLabels": "Θεματικό επίπεδο αεροφωτογραφία με ετικέτες",
  "Roads": "Θεματικό επίπεδο οδών",
  "errWkid": "Το wkid δεν συμφωνεί.",
  "errUrl": "Μη έγκυρη διεύθυνση URL",
  "errReqTimeout": "Υπέρβαση χρονικού ορίου",
  "layerPlaceholder": "Καταχώριση διεύθυνσης URL"
});