// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoom Slider",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Home",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,
sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"widgets/MyLocation/nls/strings":{_widgetLabel:"My Location",title:"Find my location",browserError:"Geolocation is not supported by this browser.",failureFinding:"Can not find your location. Please check your browser to ensure that your location is shared.",httpNotSupportError:"This widget is available only when the app is accessed through HTTPS in this browser.",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,
hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Coordinate",hintMessage:"Click the map to get coordinates",defaultLabel:"Default",realtimeLabel:"Move mouse to get coordinates",computing:"Computing...",latitudeLabel:"Latitude",longitudeLabel:"Longitude",loading:"loading...",enableClick:"Click to enable clicking map to get coordinates",disableClick:"Click to disable clicking map to get coordinates",
Default:"Default",Inches:"Inches",Foot:"Feet",Foot_US:"Feet_US",Yards:"Yards",Miles:"Miles",Nautical_Miles:"Nautical miles",Millimeters:"Millimeters",Centimeters:"Centimeters",Meter:"Meters",Kilometers:"Kilometers",Decimeters:"Decimeters",Decimal_Degrees:"Degrees",Degree_Minutes_Seconds:"Degrees minutes seconds",MGRS:"MGRS",USNG:"USNG",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,
sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Scalebar",scale:"Scale",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Overview Map",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,
de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"widgets/Search/nls/strings":{_widgetLabel:"Search",searchResult:"Search result",showAllResults:"Show search results for ",showAll:"Show search results",more:"more",untitled:"Untitled",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,
"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}},"widgets/Splash/nls/strings":{_widgetLabel:"Splash",welcomeMessage:"Welcome to ArcGIS Web Application!",licenceAgree:"I agree to",licenceTerm:"ArcGIS Web Application Terms",labelContinue:"Continue",errorString:"* You need to agree to the license to continue.",notShowAgain:"Do not show this splash screen again.",ok:"OK",cancel:"Cancel",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,
hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}}});