define({
  "visible": "Afficher la vue générale par défaut",
  "minWidth": "Largeur min.",
  "minHeight": "Hauteur min.",
  "maxWidth": "Largeur max.",
  "maxHeight": "Hauteur max.",
  "minText": "Minimum",
  "maxText": "Maximum",
  "attachText": "Spécifiez la position",
  "expandText": "Ouvert au démarrage",
  "topLeft": "En haut à gauche",
  "topRight": "En haut à droite",
  "bottomLeft": "En bas à gauche",
  "bottomRight": "En bas à droite",
  "baseLayerType": "Affichage",
  "BaseMap": "Fond de carte de la carte",
  "ArcGIS": "sur le portail",
  "tiledMapService": "Service de cartes tuilées ArcGIS",
  "dynamicMapService": "Service de carte dynamique ArcGIS",
  "imageService": "Service d’imagerie ArcGIS",
  "OSM": "Ouvrir Street Map",
  "bingRoad": "Cartes routières Bing Maps",
  "bingAerial": "Cartes aériennes Bing Maps",
  "bingHybrid": "Bing Maps Hybrid",
  "WebTiled": "Couche tuilée web",
  "VETiled": "Couche tuilée Virtual Earth",
  "tileLayerUrl": "URL de couche de tuiles",
  "tile": "Titre",
  "credits": "Crédits",
  "subdomain": "Sous-domaine",
  "extent": "Etendue",
  "initExtent": "Initialiser l’étendue",
  "tileInfo": "Informations de tuile",
  "VEStyle": "Style Virtual Earth",
  "Aerial": "Couche Cartes aériennes Bing Maps",
  "AerialWithLabels": "Couche Aérien avec étiquettes",
  "Roads": "Couche Routes",
  "errWkid": "ID connu non apparié",
  "errUrl": "URL non valide",
  "errReqTimeout": "Délai dépassé",
  "layerPlaceholder": "Saisir une URL"
});