define({
  "showLayerLabels": "Parādīt slāņu nosaukumus",
  "autoPlay": "Automātiski atskaņot slīdni",
  "loopPlay": "Cikla laiks — nepārtraukts",
  "dateAndTimeFormat": "Datuma un laika formāts",
  "mapDefault": "Noklusējuma karte",
  "custom": "Pielāgots",
  "formatInstruction": "Norādījums par formātu",
  "playback": "saglabātā atskaņošanas vieta ar karti",
  "MMMMYYYY": "2015. gada jūlijs",
  "MMMYYYY": "2015. gada jūlijs",
  "MMMMDYYYY": "2015. gada 21. jūlijs",
  "dddMMMDDYYYY": "Otrdiena, 2015. gada 21. jūlijs",
  "MDDYYYY": "21.07.2015.",
  "YYYYMDD": "21.07.2015.",
  "MDDYY": "21.07.2015.",
  "YYYY": "2015",
  "MDDYYYYhmma": "21.07.2015. 8:00",
  "dddMMMDDhmma": "Otrdiena, 21. jūlijs, plkst. 8:00",
  "sliderSetting": "Slīdņa iestatījumi",
  "autoRefresh": "Atjaunojiet slīdni katru",
  "timeSetting": "Laika iestatījumi",
  "useWebMapSetting": "Tīmekļa kartes laika iestatījumi",
  "useConfigureSetting": "Konfigurēt laika iestatījumus",
  "timeSettingBtn": "iestatījums",
  "calenderError": "Sākuma laikam ir jābūt mazākam par Beigu laiku.",
  "timeSpan": "Laika sprīdis",
  "startTime": "Sākuma laiks",
  "endTime": "Beigu laiks",
  "unit": "Mērvienība",
  "timeDisplay": "Laika displejs",
  "displayDataIn": "Rādīt datus",
  "interval": "Intervāls",
  "displayAllData": "Pakāpeniski parādīt visus datus",
  "layerTimeExtent": "Aktivizēt laika animāciju",
  "layerTableCol1": "Slānis",
  "layerTableCol2": "Laika pārklājums",
  "timeTo": "līdz",
  "calender": "Kalandrs",
  "time": "Laiks",
  "now": "Tagad",
  "today": "Šodien",
  "maximum": "Maksimālais no visiem izvēlētiem",
  "minimum": "Minimālais no visiem izvēlētiem"
});