//>>built
define(["require","exports","../2d/engine/webgl/Geometry","./GeometryUtils"],function(n,p,t,r){Object.defineProperty(p,"__esModule",{value:!0});n=function(){function e(a,b,g,c){this.left=a;this.top=b;this.right=g;this.bottom=c}return e.prototype.clone=function(){return new e(this.left,this.top,this.right,this.bottom)},e.prototype.move=function(a,b){this.left+=a;this.top+=b;this.right+=a;this.bottom+=b},e.prototype.rotate=function(a,b){var g=this.left,c=this.right,d=this.top,f=this.bottom,e=g*a-d*
b,k=g*b+d*a,h=c*a-d*b,d=c*b+d*a,l=g*a-f*b,g=g*b+f*a,m=c*a-f*b;a=c*b+f*a;this.left=Math.min(e,h,l,m);this.top=Math.min(k,d,g,a);this.right=Math.max(e,h,l,m);this.bottom=Math.max(k,d,g,a)},e.overlaps=function(a,b){return a.right>b.left&&a.left<b.right&&a.bottom>b.top&&a.top<b.bottom},e}();p.Box=n;var u=function(){function e(a,b,g,c){this.anchor=a;this.corners=b;this.minzoom=g;this.maxzoom=c}return e.prototype.left=function(){return this.corners[0].x},e.prototype.right=function(){return this.corners[2].x},
e.prototype.top=function(){return this.corners[1].y},e.prototype.bottom=function(){return this.corners[3].y},e}();p.Obstacle=u;n=function(){function e(a,b,g){this.obstacles=[];this.mapAngle=a;this.padding=b;this.isScreenAligned=g;this.minzoom=v}return e.prototype.addBox=function(a,b,g,c,d,f,e){var k=b.left*g-this.padding,h=b.top*g-this.padding,l=b.right*g+this.padding;b=b.bottom*g+this.padding;k=[new t.Point(k,h),new t.Point(l,h),new t.Point(l,b),new t.Point(k,b)];0!==this.mapAngle&&(h=Math.cos(this.mapAngle),
l=Math.sin(this.mapAngle),a=a.clone(),a.rotate(h,l));if(this.isScreenAligned||(c+=this.mapAngle),0!==c){h=Math.cos(c);l=Math.sin(c);k[0].rotate(h,l);k[1].rotate(h,l);k[2].rotate(h,l);k[3].rotate(h,l);c=0;for(h=1;4>h;h++)k[h].x<k[c].x?c=h:k[h].x===k[c].x&&k[h].y<k[c].y&&(c=h);if(c){l=[];for(h=0;4>h;h++)l.push(k[(h+c)%4]);k=l}}if(d)for(c=0,h=k;c<h.length;c++)h[c].move(d[0],d[1]);this.obstacles.push(new u(a,k,f,e))},e}();p.Footprint=n;var v=.5;n=function(){function e(){this._grid=[]}return e.prototype.setAngle=
function(a){},e.prototype.reset=function(){this._grid=[]},e.prototype.add=function(a){var b=this._grid,g=0;for(a=a.obstacles;g<a.length;g++)for(var c=a[g],d=c.anchor,f=e._gridClamp(Math.min(c.left()+d.x,d.x)),q=e._gridClamp(Math.max(c.right()+d.x,d.x)),k=e._gridClamp(Math.min(c.top()+d.y,d.y)),d=e._gridClamp(Math.max(c.bottom()+d.y,d.y));k<=d;k++)for(var h=f;h<=q;h++){var l=b[16*k+h];l||(l=b[16*k+h]=[]);l.push(c)}},e.prototype.getMinZoom=function(a,b,g,c){if(0===a.obstacles.length)return r.C_INFINITY;
g=this._grid;c=0;for(a=a.obstacles;c<a.length;c++)for(var d=a[c],f=d.anchor,q=e._gridClamp(Math.min(d.left()+f.x,f.x)),k=e._gridClamp(Math.max(d.right()+f.x,f.x)),h=e._gridClamp(Math.min(d.top()+f.y,f.y)),f=e._gridClamp(Math.max(d.bottom()+f.y,f.y));h<=f;h++)for(var l=q;l<=k;l++){var m=g[16*h+l];if(m)for(var n=0;n<m.length;n++){var p=m[n];if(!(d.minzoom>=p.maxzoom||p.minzoom>=d.maxzoom)&&2<=(b=e._calcPlacementZoom(d,p,b)))return r.C_INFINITY}}return 2>b?b:r.C_INFINITY},e._gridClamp=function(a){return r.clamp(a>>
9,-7,8)},e._calcPlacementZoom=function(a,b,g){var c=b.anchor.x-a.anchor.x;if(0===c&&(a.right()<b.left()||b.right()<a.left()))return g;var d=b.anchor.y-a.anchor.y;if(0===d&&(a.bottom()<b.top()||b.bottom()<a.top()))return g;var f=r.C_INFINITY;if(0!==c){var q=(0<c?a.right()-b.left():a.left()-b.right())/c;q<f&&(f=q);c=0<c?e._calcExtZoomX(a,b,q):e._calcExtZoomX(b,a,q);c<f&&(f=c)}0!==d&&(c=(0<d?a.bottom()-b.top():a.top()-b.bottom())/d,c<f&&(f=c),d=0<d?e._calcExtZoomY(a,b,c):e._calcExtZoomY(b,a,c),d<f&&
(f=d));return f<a.minzoom||f<b.minzoom?g:(f=Math.min(f,a.maxzoom,b.maxzoom),f<g&&(f=g),f)},e._calcExtZoomX=function(a,b,g){var c,d,f,e;if(a.anchor.y+a.corners[2].y/g<b.anchor.y+b.corners[0].y/g){var k=a.corners[2].x-a.corners[3].x,h=a.corners[2].y-a.corners[3].y,l=b.corners[1].x-b.corners[0].x,m=b.corners[1].y-b.corners[0].y;0<=k*m-h*l?a.anchor.y+a.corners[3].y/g<b.anchor.y+b.corners[0].y/g?(c=a.corners[3],d=b.corners[0],f=b.corners[1],e=1):(c=b.corners[0],d=a.corners[3],f=a.corners[2],e=-1):a.anchor.y+
a.corners[2].y/g>b.anchor.y+b.corners[1].y/g?(c=a.corners[2],d=b.corners[0],f=b.corners[1],e=1):(c=b.corners[1],d=a.corners[3],f=a.corners[2],e=-1)}else k=a.corners[2].x-a.corners[1].x,h=a.corners[2].y-a.corners[1].y,l=b.corners[3].x-b.corners[0].x,m=b.corners[3].y-b.corners[0].y,0>k*m-h*l?a.anchor.y+a.corners[1].y/g>b.anchor.y+b.corners[0].y/g?(c=a.corners[1],d=b.corners[0],f=b.corners[3],e=1):(c=b.corners[0],d=a.corners[1],f=a.corners[2],e=-1):a.anchor.y+a.corners[2].y/g<b.anchor.y+b.corners[3].y/
g?(c=a.corners[2],d=b.corners[0],f=b.corners[3],e=1):(c=b.corners[3],d=a.corners[1],f=a.corners[2],e=-1);g=f.x-d.x;f=f.y-d.y;return e*((c.y-d.y)*g-(c.x-d.x)*f)/((a.anchor.x-b.anchor.x)*f-(a.anchor.y-b.anchor.y)*g)},e._calcExtZoomY=function(a,b,g){var c,d,f,e;if(a.anchor.x+a.corners[3].x/g<b.anchor.x+b.corners[1].x/g){var k=a.corners[3].x-a.corners[2].x,h=a.corners[3].y-a.corners[2].y,l=b.corners[0].x-b.corners[1].x,m=b.corners[0].y-b.corners[1].y;0>k*m-h*l?a.anchor.x+a.corners[2].x/g<b.anchor.x+b.corners[1].x/
g?(c=a.corners[2],d=b.corners[1],f=b.corners[0],e=1):(c=b.corners[1],d=a.corners[2],f=a.corners[3],e=-1):a.anchor.x+a.corners[3].x/g>b.anchor.x+b.corners[0].x/g?(c=a.corners[3],d=b.corners[1],f=b.corners[0],e=1):(c=b.corners[0],d=a.corners[2],f=a.corners[3],e=-1)}else k=a.corners[3].x-a.corners[0].x,h=a.corners[3].y-a.corners[0].y,l=b.corners[2].x-b.corners[1].x,m=b.corners[2].y-b.corners[1].y,0<k*m-h*l?a.anchor.x+a.corners[0].x/g>b.anchor.x+b.corners[1].x/g?(c=a.corners[0],d=b.corners[1],f=b.corners[2],
e=1):(c=b.corners[1],d=a.corners[0],f=a.corners[3],e=-1):a.anchor.x+a.corners[3].x/g<b.anchor.x+b.corners[2].x/g?(c=a.corners[3],d=b.corners[1],f=b.corners[2],e=1):(c=b.corners[2],d=a.corners[0],f=a.corners[3],e=-1);g=f.x-d.x;f=f.y-d.y;return e*((c.y-d.y)*g-(c.x-d.x)*f)/((a.anchor.x-b.anchor.x)*f-(a.anchor.y-b.anchor.y)*g)},e}();p.ConflictEngine=n});