//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper dojox/string/BidiEngine ../2d/engine/webgl/Geometry ../2d/engine/webgl/TextShaping ./Bucket ./GeometryUtils ./Placement ./style/StyleLayer".split(" "),function(Q,R,L,S,M,B,N,O,u,F,I){function P(u,h){return u.iconMosaicItem&&h.iconMosaicItem?u.iconMosaicItem.page===h.iconMosaicItem.page?0:u.iconMosaicItem.page<h.iconMosaicItem.page?-1:1:u.iconMosaicItem&&!h.iconMosaicItem?1:!u.iconMosaicItem&&h.iconMosaicItem?
-1:0}!0;return function(K){function h(a,c,g,d,f,b,e,p){c=K.call(this,a,c)||this;if(c._markerMap=new Map,c._glyphMap=new Map,c._glyphBufferDataStorage=new Map,c._sdfMarkers=!1,a.hasDataDrivenIcon!==g.isDataDriven())throw Error("incompatible icon buffer");if(a.hasDataDrivenText!==f.isDataDriven())throw Error("incompatible text buffer");return c._iconVertexBuffer=g,c._iconIndexBuffer=d,c._textVertexBuffer=f,c._textIndexBuffer=b,c._placementEngine=e,c._workerTileHandler=p,c}return L(h,K),Object.defineProperty(h.prototype,
"markerPageMap",{get:function(){return this._markerMap},enumerable:!0,configurable:!0}),Object.defineProperty(h.prototype,"glyphsPageMap",{get:function(){return this._glyphMap},enumerable:!0,configurable:!0}),Object.defineProperty(h.prototype,"sdfMarker",{get:function(){return this._sdfMarkers},enumerable:!0,configurable:!0}),h.prototype.copy=function(a,c,g,d,f){a=new h(this.layer,this.zoom,a,c,g,d,f,this._workerTileHandler);return a.layerIndex=this.layerIndex,a.layerExtent=this.layerExtent,a._iconIndexStart=
c.index,a._textIndexStart=d.index,a._iconIndexCount=0,a._textIndexCount=0,a._symbolInstances=this._symbolInstances,a._workerTileHandler=this._workerTileHandler,a._fontArray=this._fontArray,a._textLayout=this._textLayout,a._iconLayout=this._iconLayout,a._isLinePlacement=this._isLinePlacement,a._avoidEdges=this._avoidEdges,a},h.prototype.getResources=function(a,c,g){var d=this.layer,f=this.zoom,b=d.hasDataDrivenIcon,e=d.hasDataDrivenText;a&&a.setExtent(this.layerExtent);for(var p=d.getLayoutProperty("icon-image"),
k=d.getLayoutProperty("text-field"),D=d.getLayoutValue("text-font",f),m=d.getLayoutValue("text-transform",f),v=[],l=[1,1,1,1],w=1,r=1,n=[1,1,1,1],y=1,t=1,q=0,z=this._features;q<z.length;q++){var x=z[q],C=x.getGeometry(a);if(C&&0!==C.length){var u=void 0;p&&(u=d.getLayoutValue("icon-image",f,x),p.isDataDriven||(u=this._replaceKeys(u,x.values)),u&&c.add(u));var A=void 0,E=!1;if(k&&(A=d.getLayoutValue("text-field",f,x),k.isDataDriven||(A=this._replaceKeys(A,x.values)),A=A.replace(/\\n/g,"\n"))){switch(m){case 2:A=
A.toLowerCase();break;case 1:A=A.toUpperCase()}h._bidiEngine.hasBidiChar(A)&&(E=void 0,E="rtl"===h._bidiEngine.checkContextual(A)?"IDNNN":"ICNNN",A=h._bidiEngine.bidiTransform(A,E,"VLYSN"),E=!0);var B=A.length;if(0<B)for(var G=0,F=D;G<F.length;G++){var H=F[G],J=g[H];J||(J=g[H]=new Set);for(H=0;H<B;H++){var I=A.charCodeAt(H);J.add(I)}}}if(u||A)B=d.getLayoutValue("icon-size",f,x),G=d.getLayoutValue("text-size",f,x),d.hasDataDrivenIconColor&&(l=d.getPaintValue("icon-color",f,x)),d.hasDataDrivenIconOpacity&&
(w=d.getPaintValue("icon-opacity",f,x)),d.hasDataDrivenIconSize&&(r=B),d.hasDataDrivenTextColor&&(n=d.getPaintValue("text-color",f,x)),d.hasDataDrivenTextOpacity&&(y=d.getPaintValue("text-opacity",f,x)),d.hasDataDrivenTextSize&&(t=G),x={sprite:u,label:A,rtl:E,type:x.type,geometry:C,iconSize:B,iconRotate:d.getLayoutValue("icon-rotate",f,x),ddIconValues:b?{color:l,opacity:w,size:r}:null,textSize:G,textRotate:d.getLayoutValue("text-rotate",f,x),ddTextValues:e?{color:n,opacity:y,size:t}:null},v.push(x)}}this._symbolFeatures=
v},h.prototype.processFeatures=function(a,c){a&&a.setExtent(this.layerExtent);var g,d,f=this.layer,b=this.zoom;c=this._isLinePlacement=1===f.getLayoutValue("symbol-placement",b);a=this._avoidEdges=f.getLayoutValue("symbol-avoid-edges",b)&&!c;var e=8*f.getLayoutValue("symbol-spacing",b),p=f.getLayoutProperty("icon-image"),k=f.getLayoutProperty("text-field"),D=this._workerTileHandler;p&&(this._iconLayout=new I.IconLayout(f,b,c),g=D.getSpriteItems(),d=this._getTranslate(!0));var m,v,l;if(k){m=this._textLayout=
new I.TextLayout(f,b,c);this._fontArray=m.fontArray;l=.5;switch(m.anchor){case 5:case 1:case 7:l=0;break;case 6:case 2:case 8:l=1}v=.5;switch(m.anchor){case 5:case 3:case 6:v=0;break;case 7:case 4:case 8:v=1}f=.5;switch(m.justify){case 0:f=0;break;case 2:f=1}var b=24*m.letterSpacing,p=c?0:24*m.maxWidth,k=24*m.lineHeight,w=[24*m.offset[0],24*m.offset[1]];m=this._fontArray.map(function(a){return D.getGlyphItems(a)});v=new N(m,p,k,b,w,l,v,f);l=this._getTranslate(!1)}this._iconIndexStart=this._iconIndexBuffer.index;
this._textIndexStart=this._textIndexBuffer.index;this._textIndexCount=this._iconIndexCount=0;this._markerMap.clear();this._glyphMap.clear();this._symbolInstances=f=[];b=this._textLayout;p=1;b&&b.size&&(p=b.size/24);k=b?b.maxAngle*u.C_DEG_TO_RAD:0;m=b?8*b.size:0;for(var w=0,r=this._symbolFeatures;w<r.length;w++){var n=r[w],y=void 0;n.sprite&&(y=g[n.sprite])&&y.sdf&&(this._sdfMarkers=!0);var t=void 0,q=n.label,z=0;if(q&&(t=v.getShaping(q,n.rtl))&&0<t.length){for(var z=1E30,q=-1E30,x=0,C=t;x<C.length;x++)var B=
C[x],z=Math.min(z,B.x),q=Math.max(q,B.x);z=(q-z+48)*p*8}q=0;for(x=n.geometry;q<x.length;q++){var C=x[q],A=void 0;c?(t&&0<t.length&&b&&b.size&&h._smoothVertices(C,8*b.size*(2+Math.min(2,4*Math.abs(b.offset[1])))),A=h._findAnchors(C,e,z)):A=3===n.type?h._findCentroid(C):[new F.Anchor(C[0].x,C[0].y)];for(B=0;B<A.length;B++){var E=A[B];0>E.x||4096<E.x||0>E.y||4096<E.y||c&&0<z&&0===b.rotationAlignment&&!h._honorsTextMaxAngle(C,E,z,k,m)||f.push({shaping:t,line:C,iconMosaicItem:y,anchor:E,iconSize:n.iconSize,
iconRotate:n.iconRotate,ddIconValues:n.ddIconValues,textSize:n.textSize,textRotate:n.textRotate,ddTextValues:n.ddTextValues})}}}f.sort(P);for(g=0;g<f.length;g++)this._processFeature(f[g],d,l,a);this._addPlacedGlyphs()},h.prototype.updateSymbols=function(){this._iconIndexStart=this._iconIndexBuffer.index;this._textIndexStart=this._textIndexBuffer.index;this._textIndexCount=this._iconIndexCount=0;this._markerMap.clear();this._glyphMap.clear();var a,c=this._avoidEdges,g=this.layer;g.getLayoutProperty("icon-image")&&
(a=this._getTranslate(!0));var d;g.getLayoutProperty("text-field")&&(d=this._getTranslate(!1));for(var g=0,f=this._symbolInstances;g<f.length;g++)this._processFeature(f[g],a,d,c);this._addPlacedGlyphs()},h.prototype._getTranslate=function(a){var c=this.layer.getPaintValue(a?"icon-translate":"text-translate",this.zoom);if(0!==c[0]||0!==c[1]){var g=this._placementEngine.mapAngle;return 0!==g&&0===this.layer.getPaintValue(a?"icon-translate-anchor":"text-translate-anchor",this.zoom)?(a=Math.sin(g),g=
Math.cos(g),[8*(c[0]*g-c[1]*a),8*(c[0]*a+c[1]*g)]):[8*c[0],8*c[1]]}},h.prototype._replaceKeys=function(a,c){return a.replace(/{([^{}]+)}/g,function(a,d){return d in c?c[d]:""})},h.prototype._processFeature=function(a,c,g,d){var f=a.line,b=a.iconMosaicItem,e=a.shaping,p=a.anchor,k=this._iconLayout,D=k&&!!b,m=!0,v=1;D&&(k.size=a.iconSize,k.rotate=a.iconRotate,v=8*k.size,m=k.optional||!b);var l=this._textLayout,h=l&&e&&0<e.length,r=1,n=r,y=!0;h&&(l.size=a.textSize,l.rotate=a.textRotate,r=l.size/24,n=
8*r,y=l.optional||!e||0===e.length);var t,r=new B.Point(0,-17);if(D&&(t=this._placementEngine.getIconPlacement(p,c,b,v,f,k,d),p.minzoom>t.footprint.minzoom&&(t.footprint.minzoom=p.minzoom),t.footprint.minzoom===u.C_INFINITY&&(t=null)),t||m){var q;if(h&&(q=this._placementEngine.getTextPlacement(p,g,r,e,n,f,l,d))&&(p.minzoom>q.footprint.minzoom&&(q.footprint.minzoom=p.minzoom),q.footprint.minzoom===u.C_INFINITY&&(q=null)),q||y){if(t&&q||(y||m?y||q?m||t||(q=null):t=null:(t=null,q=null)),t&&q&&!y&&!m)c=
Math.max(t.footprint.minzoom,q.footprint.minzoom),t.footprint.minzoom=c,q.footprint.minzoom=c;q&&(l.ignorePlacement||this._placementEngine.add(q),this._storePlacedGlyphs(q.shapes,q.footprint.minzoom,this.zoom,a.ddTextValues));t&&(k.ignorePlacement||this._placementEngine.add(t),this._addPlacedIcons(t.shapes,t.footprint.minzoom,this.zoom,b.page,a.ddIconValues))}}},h.prototype._addPlacedIcons=function(a,c,g,d,f){c=Math.max(g+u.log2(c),0);for(var b=this._iconVertexBuffer,e=this._iconIndexBuffer,p=0;p<
a.length;p++){var k=a[p],D=Math.max(g+u.log2(k.minzoom),c),m=Math.min(g+u.log2(k.maxzoom),25);if(!(m<=D)){var h=k.tl,l=k.tr,w=k.bl,r=k.br,n=k.mosaicRect,y=k.labelAngle,k=k.anchor,t=b.index,q=n.x,z=n.y,x=q+n.width,n=z+n.height;b.add(k.x,k.y,h.x,h.y,q,z,y,D,m,c,f);b.add(k.x,k.y,l.x,l.y,x,z,y,D,m,c,f);b.add(k.x,k.y,w.x,w.y,q,n,y,D,m,c,f);b.add(k.x,k.y,r.x,r.y,x,n,y,D,m,c,f);e.add(t+0,t+1,t+2);e.add(t+1,t+2,t+3);this._markerMap.has(d)?this._markerMap.get(d)[1]+=6:this._markerMap.set(d,[this._iconIndexStart+
this._iconIndexCount,6]);this._iconIndexCount+=2}}},h.prototype._addPlacedGlyphs=function(){var a=this,c=this._textVertexBuffer,g=this._textIndexBuffer;this._glyphBufferDataStorage.forEach(function(d,f){for(var b=0;b<d.length;b++){var e=d[b],p=c.index;c.add(e.glyphAnchor[0],e.glyphAnchor[1],e.tl[0],e.tl[1],e.xmin,e.ymin,e.labelAngle,e.minLod,e.maxLod,e.placementLod,e.ddValues);c.add(e.glyphAnchor[0],e.glyphAnchor[1],e.tr[0],e.tr[1],e.xmax,e.ymin,e.labelAngle,e.minLod,e.maxLod,e.placementLod,e.ddValues);
c.add(e.glyphAnchor[0],e.glyphAnchor[1],e.bl[0],e.bl[1],e.xmin,e.ymax,e.labelAngle,e.minLod,e.maxLod,e.placementLod,e.ddValues);c.add(e.glyphAnchor[0],e.glyphAnchor[1],e.br[0],e.br[1],e.xmax,e.ymax,e.labelAngle,e.minLod,e.maxLod,e.placementLod,e.ddValues);g.add(p+0,p+1,p+2);g.add(p+1,p+2,p+3);a._glyphMap.has(f)?a._glyphMap.get(f)[1]+=6:a._glyphMap.set(f,[a._textIndexStart+a._textIndexCount,6]);a._textIndexCount+=2}});this._glyphBufferDataStorage.clear()},h.prototype._storePlacedGlyphs=function(a,
c,g,d){c=Math.max(g+u.log2(c),0);for(var f=0;f<a.length;f++){var b=a[f],e=Math.max(g+u.log2(b.minzoom),c),p=Math.min(g+u.log2(b.maxzoom),25);if(!(p<=e)){var k=b.tl,h=b.tr,m=b.bl,v=b.br,l=b.labelAngle,w=b.anchor,r=b.mosaicRect;this._glyphBufferDataStorage.has(b.page)||this._glyphBufferDataStorage.set(b.page,[]);this._glyphBufferDataStorage.get(b.page).push({glyphAnchor:[w.x,w.y],tl:[k.x,k.y],tr:[h.x,h.y],bl:[m.x,m.y],br:[v.x,v.y],xmin:r.x,ymin:r.y,xmax:r.x+r.width,ymax:r.y+r.height,labelAngle:l,minLod:e,
maxLod:p,placementLod:c,ddValues:d})}}},h._findAnchors=function(a,c,g){c+=g;for(var d=0,f=a.length-1,b=0;b<f;b++)d+=B.Point.distance(a[b],a[b+1]);b=g||c;if(b*=.5,d<=b)return[];g=b/d;c=d/Math.max(Math.round(d/c),1);for(var d=0,f=-c/2,e=[],p=a.length-1,b=0;b<p;b++){for(var k=a[b],h=a[b+1],m=h.x-k.x,v=h.y-k.y,l=Math.sqrt(m*m+v*v),w=void 0;f+c<d+l;){var f=f+c,r=(f-d)/l,n=u.interpolate(k.x,h.x,r),r=u.interpolate(k.y,h.y,r);void 0===w&&(w=Math.atan2(v,m));e.push(new F.Anchor(n,r,w,b,g))}d+=l}return e},
h._deviation=function(a,c,g){return Math.atan2((c.x-a.x)*(g.y-c.y)-(c.y-a.y)*(g.x-c.x),(c.x-a.x)*(g.x-c.x)+(c.y-a.y)*(g.y-c.y))},h._honorsTextMaxAngle=function(a,c,g,d,f){var b=0;g/=2;for(var e=new B.Point(c.x,c.y),p=c.segment+1;b>-g;){if(0>--p)return!1;b-=B.Point.distance(a[p],e);e=a[p]}b+=B.Point.distance(a[p],a[p+1]);c=[];for(var e=0,k=a.length;b<g;){var h=a[p],m=void 0;do{if(++p===k)return!1;m=a[p]}while(m.isEqual(h));var v=p,l=void 0;do{if(++v===k)return!1;l=a[v]}while(l.isEqual(m));h=this._deviation(h,
m,l);c.push({deviation:h,distToAnchor:b});for(e+=h;b-c[0].distToAnchor>f;)e-=c.shift().deviation;if(Math.abs(e)>d)return!1;b+=B.Point.distance(m,l)}return!0},h._smoothVertices=function(a,c){if(!(0>=c)){var g=a.length;if(!(3>g)){var d=[],f=0;d.push(0);for(var b=1;b<g;b++)f+=B.Point.distance(a[b],a[b-1]),d.push(f);c=Math.min(c,.2*f);f=[];f.push(a[0].x);f.push(a[0].y);var e=a[g-1].x,h=a[g-1].y,b=B.Point.sub(a[0],a[1]);b.normalize();a[0].x+=c*b.x;a[0].y+=c*b.y;b.assignSub(a[g-1],a[g-2]);b.normalize();
a[g-1].x+=c*b.x;a[g-1].y+=c*b.y;for(b=1;b<g;b++)d[b]+=c;d[g-1]+=c;for(var k=.5*c,b=1;b<g-1;b++){for(var u=0,m=0,v=0,l=b-1;0<=l&&!(d[l+1]<d[b]-k);l--){var w=k+d[l+1]-d[b],r=d[l+1]-d[l],n=d[b]-d[l]<k?1:w/r;if(1E-6>Math.abs(n))break;var y=n*n,t=n*w-.5*y*r,q=n*r/c,z=a[l+1],x=a[l].x-z.x,C=a[l].y-z.y,u=u+q/t*(z.x*n*w+.5*y*(w*x-r*z.x)-y*n*r*x/3),m=m+q/t*(z.y*n*w+.5*y*(w*C-r*z.y)-y*n*r*C/3),v=v+q}for(l=b+1;l<g&&!(d[l-1]>d[b]+k);l++){w=k-d[l-1]+d[b];r=d[l]-d[l-1];n=d[l]-d[b]<k?1:w/r;if(1E-6>Math.abs(n))break;
y=n*n;t=n*w-.5*y*r;q=n*r/c;z=a[l-1];x=a[l].x-z.x;C=a[l].y-z.y;u+=q/t*(z.x*n*w+.5*y*(w*x-r*z.x)-y*n*r*x/3);m+=q/t*(z.y*n*w+.5*y*(w*C-r*z.y)-y*n*r*C/3);v+=q}f.push(u/v);f.push(m/v)}f.push(e);f.push(h);for(l=b=0;b<g;b++)a[b].x=f[l++],a[b].y=f[l++]}}},h._findCentroid=function(a){var c=a.length-1,g=0,d=0,f=0,b=a[0].x,e=a[0].y;4096<b&&(b=4096);0>b&&(b=0);4096<e&&(e=4096);0>e&&(e=0);for(var h=1;h<c;h++){var k=a[h].x,u=a[h].y,m=a[h+1].x,v=a[h+1].y;4096<k&&(k=4096);0>k&&(k=0);4096<u&&(u=4096);0>u&&(u=0);4096<
m&&(m=4096);0>m&&(m=0);4096<v&&(v=4096);0>v&&(v=0);var l=(k-b)*(v-e)-(m-b)*(u-e),g=g+l*(b+k+m),d=d+l*(e+u+v),f=f+l}return g/=3*f,d/=3*f,isNaN(g)||isNaN(d)?[]:[new F.Anchor(g,d)]},h._bidiEngine=new M,h}(O)});