// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/templates/_TreeNode.html":'\x3cdiv class\x3d"dijitTreeNode" role\x3d"presentation"\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"rowNode" class\x3d"dijitTreeRow" role\x3d"presentation"\x3e\r\n\t\t\x3cspan data-dojo-attach-point\x3d"expandoNode" class\x3d"dijitInline dijitTreeExpando" role\x3d"presentation"\x3e\x3c/span\x3e\r\n\t\t\x3cspan data-dojo-attach-point\x3d"expandoNodeText" class\x3d"dijitExpandoText" role\x3d"presentation"\x3e\x3c/span\x3e\r\n\t\t\x3cspan data-dojo-attach-point\x3d"contentNode" class\x3d"dijitTreeContent" role\x3d"presentation"\x3e\r\n\t\t\t\x3cspan role\x3d"presentation" class\x3d"dijitInline dijitIcon dijitTreeIcon" data-dojo-attach-point\x3d"iconNode"\x3e\x3c/span\x3e\r\n\t\t\t\x3cspan data-dojo-attach-point\x3d"labelNode,focusNode" class\x3d"dijitTreeLabel" role\x3d"treeitem" tabindex\x3d"-1" aria-selected\x3d"false"\x3e\x3c/span\x3e\r\n\t\t\x3c/span\x3e\r\n\t\x3c/div\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"containerNode" class\x3d"dijitTreeNodeContainer" role\x3d"presentation" style\x3d"display: none;"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/_TreeNode.html dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/event dojo/query dojo/aspect dojo/on dojo/keys dojo/Evented dijit/registry dijit/Tree jimu/utils".split(" "),function(f,v,w,n,d,c,e,p,q,r,g,h,k,l,m,t){var u=f([m._TreeNode,k],{templateString:n,declaredClass:"jimu._TreeNode",isLeaf:!1,groupId:"",postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-tree-node");this.isLeaf=
!!this.isLeaf;this.groupId?(this.checkNode=c.toDom('\x3cinput type\x3d"radio" /\x3e'),this.checkNode.name=this.groupId):this.checkNode=c.toDom('\x3cinput type\x3d"checkbox" /\x3e');c.addClass(this.checkNode,"jimu-tree-check-node");c.place(this.checkNode,this.contentNode,"first");this.own(g(this.checkNode,"click",d.hitch(this,this._onClick)));this.own(g(this.rowNode,"keydown",d.hitch(this,function(a,b){b.target=a;b.keyCode!==h.ENTER&&b.keyCode!==h.SPACE||this._onClick(b)},this.checkNode)));this.isLeaf?
this.groupId?c.setStyle(this.checkNode,"display","none"):c.setStyle(this.checkNode,"display","inline"):c.setStyle(this.checkNode,"display","none");this.isLeaf?c.addClass(this.domNode,"jimu-tree-leaf-node"):c.addClass(this.domNode,"jimu-tree-not-leaf-node")},select:function(){this.isLeaf&&(this.checkNode.checked=!0,c.addClass(this.domNode,"jimu-tree-selected-leaf-node"))},unselect:function(){this.isLeaf&&(this.checkNode.checked=!1,c.removeClass(this.domNode,"jimu-tree-selected-leaf-node"))},toggleSelect:function(){this.isLeaf&&
(this.checkNode.checked?this.unselect():this.select())},_onClick:function(a){(a.target||a.srcElement)===this.checkNode?this.tree._onCheckNodeClick(this,this.checkNode.checked,a):this.tree._onClick(this,a)},_onChange:function(){this.isLeaf&&setTimeout(d.hitch(this,function(){this.checkNode.checked?this.emit("tn-select",this):this.emit("tn-unselect",this)}),100)},destroy:function(){delete this.tree;this.inherited(arguments)}});return f([m,k],{declaredClass:"jimu._Tree",openOnClick:!0,multiple:!0,uniqueId:"",
showRoot:!1,postMixInProperties:function(){this.inherited(arguments);this.uniqueId="tree_"+t.getRandomString()},postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-tree");this.own(r.before(this,"onClick",d.hitch(this,this._jimuBeforeClick)));this.rootLoadingIndicator&&c.setStyle(this.rootLoadingIndicator,"display","none");this.dndController.singular=!0;c.setAttr(this.domNode,"tabindex",0)},removeItem:function(a){this.model.store.remove(a)},getAllItems:function(){var a=this.getAllTreeNodeWidgets();
return e.map(a,d.hitch(this,function(a){var b=a.item;b.selected=a.checkNode.checked;return b}))},getSelectedItems:function(){var a=this.getAllTreeNodeWidgets(),a=e.filter(a,d.hitch(this,function(a){return a.checkNode.checked}));return e.map(a,d.hitch(this,function(a){return a.item}))},getFilteredItems:function(a){var b=this.getAllTreeNodeWidgets(),b=e.map(b,d.hitch(this,function(a){var b=a.item;b.selected=a.checkNode.checked;return b}));return e.filter(b,d.hitch(this,function(b){return a(b)}))},getTreeNodeByItemId:function(a){for(var b=
this._getAllTreeNodeDoms(),c=0;c<b.length;c++){var d=l.byNode(b[c]);if(d.item.id.toString()===a.toString())return d}return null},selectItem:function(a){(a=this.getTreeNodeByItemId(a))&&a.isLeaf&&this.selectNodeWidget(a)},unselectItem:function(a){(a=this.getTreeNodeByItemId(a))&&a.isLeaf&&a.unselect()},getAllLeafTreeNodeWidgets:function(){var a=this.getAllTreeNodeWidgets();return e.filter(a,d.hitch(this,function(a){return a.isLeaf}))},getAllTreeNodeWidgets:function(){var a=this._getAllTreeNodeDoms();
return e.map(a,d.hitch(this,function(a){return l.byNode(a)}))},isLeafItem:function(a){return a&&a.isLeaf},_getAllTreeNodeDoms:function(){return q(".dijitTreeNode",this.domNode)},_createTreeNode:function(a){a.isLeaf=this.isLeafItem(a.item);this.multiple||(a.groupId=this.uniqueId);return new u(a)},_onTreeNodeSelect:function(a){this.emit("item-select",{item:a.item,treeNode:a})},_onTreeNodeUnselect:function(a){this.emit("item-unselect",{item:a.item,treeNode:a})},selectNodeWidget:function(a){this.multiple||
this.unselectAllLeafNodeWidgets();a.select()},_jimuBeforeClick:function(a,b,d){b.isLeaf&&(c.hasClass(d.target||d.srcElement,"jimu-tree-check-node")||(this.multiple?b.toggleSelect():this.selectNodeWidget(b)));return arguments},_onCheckNodeClick:function(a,b,c){!this.multiple&&b&&this.unselectAllLeafNodeWidgets();p.stop(c);this.focusNode(a);setTimeout(d.hitch(this,function(){b?this.selectNodeWidget(a):a.unselect();this.onClick(a.item,a,c)}),0)},unselectAllLeafNodeWidgets:function(){var a=this.getAllLeafTreeNodeWidgets();
e.forEach(a,d.hitch(this,function(a){a.unselect()}))}})});