// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/query dojo/NodeList-manipulate dojo/when jimu/dijit/formSelect esri/lang jimu/dijit/Popup jimu/dijit/LoadingIndicator jimu/utils jimu/statisticsUtils".split(" "),function(k,r,e,c,m,t,u,y,z,v,A,w,x,B,g){return k([r],{statInfo:null,postMixInProperties:function(){this.nls=window.jimuNls.fieldStatistics;e.mixin(this.nls,window.jimuNls.common)},showContent:function(b){this.statInfo=b;0!==this.statInfo.fieldNames.length&&
(b=c.create("div",{className:"stat-container"},this.domNode),this._createFieldDom(b),1===this.statInfo.fieldNames.length&&(this.statInfo.fieldName=this.statInfo.fieldNames[0],this._showOneFieldStatContent(this.statInfo,b)))},showContentAsPopup:function(b){this.statInfo=b;this._statisticsPopup&&this._statisticsPopup.domNode&&this._statisticsPopup.close();this._statisticsPopup=null;this._statisticsPopup=new w({titleLabel:this.nls.statistics,content:this.domNode,width:270,height:265,buttons:[{label:this.nls.ok}]});
this.showContent(b)},_showOneFieldStatContent:function(b,a){var d;g.isStatFromServer(this.statInfo)&&(d=new x,d.placeAt(a),d.show());g.getStatisticsResult(this.statInfo).then(e.hitch(this,function(b){d&&d.destroy();u(".esriAGOTableStatistics",a).remove();b=this._createStatContent(b);c.place(b,a)}))},_getFieldAliaseFromStatInfo:function(b){var a=this.statInfo.featureSet;(a=a&&a.fieldAliases)&&"undefined"!==typeof a[b]?a=a[b]:this.statInfo.layer?(a=m.filter(this.statInfo.layer.fields,function(a){return a.name===
b}),a=a[0]?a[0].alias:""):a=b;return a},_createFieldDom:function(b){var a;if(1<this.statInfo.fieldNames.length){a=c.create("div",{className:"header"},b);c.create("span",{innerHTML:this.nls.field+": "},a);var d=new v({options:this.statInfo.fieldNames.map(e.hitch(this,function(a){return{value:a,label:this._getFieldAliaseFromStatInfo(a)}})),style:{width:"150px"},"aria-label":this.nls.field});this.own(t(d,"change",e.hitch(this,function(a){this.statInfo.fieldName=a;this._showOneFieldStatContent(this.statInfo,
b)})));d.placeAt(a);this.statInfo.fieldName=this.statInfo.fieldNames[0];this._showOneFieldStatContent(this.statInfo,b)}else a=c.create("div",{className:"header",innerHTML:"\x3cspan\x3e"+this.nls.field+"\x3c/span\x3e: "+this._getFieldAliaseFromStatInfo(this.statInfo.fieldNames[0])},b);return a},_createStatContent:function(b){var a={},d="count sum min max ave stddev".split(" "),h,e,g,l,f,n,p,q;h=c.create("div",{className:"esriAGOTableStatistics",innerHTML:""});c.create("div",{className:"hzLine",innerHTML:""},
h);e=c.create("table",{className:"attrTable",tabindex:"0",innerHTML:"",style:{cellpadding:0,cellspacing:0}},h);for(f in b)b.hasOwnProperty(f)&&(a[f.toLowerCase()]=b[f]);f=a.countfield;q=a.sumfield||"";p=a.minfield||"";n=a.maxfield||"";b=a.avgfield||"";a=a.stddevfield||"";g=c.create("tbody",{},e);var k=this;m.forEach([f,q,p,n,b,a],function(a,b){""!==a&&(l=c.create("tr",{valign:"top"},g),c.create("td",{"class":"attrName",innerHTML:k.nls[d[b]]},l),c.create("td",{"class":"attrValue",innerHTML:a},l))});
c.create("div",{className:"break",innerHTML:""},h);return h}})});