// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/Deferred dojo/promise/all dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/_base/html dojo/_base/array dojo/query dijit/registry jimu/filterUtils jimu/utils ./_SingleFilterParameter ./_filter/ValueProviderFactory".split(" "),function(m,q,r,t,u,v,w,x,e,n,h,p,y,z,A,B,C){return u([v,w,x,q],{baseClass:"jimu-filter-parameters",templateString:'\x3cdiv\x3e\x3ctable style\x3d"width:100%;border-collapse:collapse;"\x3e\x3ctbody data-dojo-attach-point\x3d"tbody"\x3e\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e',
_filterUtils:null,_spObj:null,nls:null,partsObj:null,layerInfo:null,OPERATORS:null,url:null,featureLayerId:null,widgetId:"",postMixInProperties:function(){this.nls=window.jimuNls.filterBuilder;this._filterUtils=new z;this.OPERATORS=e.clone(this._filterUtils.OPERATORS);this._spObj={}},destroy:function(){this.clear();this._filterUtils=null;this.inherited(arguments)},getFilterExpr:function(a){var b=this._getNewValidPartsObj(this.partsObj,!0),c=b?this._getFilterExprByPartsObj(b):null;return a&&a.ifDisplaySQL?
void 0===b.displaySQL?c:b.displaySQL:c},getValueProviders:function(){for(var a=[],b=this._getAllInteractiveSinglePartArray(this.partsObj),c=0;c<b.length;c++){var d=b[c].spId;d&&(d=this._getSingleFilterParameterBySpId(d),a.push(d))}return a},_getNewValidPartsObj:function(a,b){a=e.clone(a);for(var c={logicalOperator:a.logicalOperator,parts:[]},d=e.hitch(this,function(a){if(a.spId){var b=this._getSingleFilterParameterBySpId(a.spId),c=b.getValueObject();a.valueObj=c;if(!c||"uniquePredefined"!==c.type&&
"multiplePredefined"!==c.type)return c&&"multipleDynamic"===c.type?0<c.value.length?1:-1:c&&"unique"===c.type?null===c.value||void 0===c.value||""===c.value?-1:1:b.getStatus();var b=[],d;for(d in c.value)c.value[d].isChecked&&b.push(c.value[d]);if(0<b.length)return a.valueObj.value=b,1;a.valueObj.value="";return-1}return a.valueObj?1:-1}),f=e.hitch(this,function(a){var b=d(a);0<b&&c.parts.push(a);return b}),g=e.hitch(this,function(a){var b=[];a.parts=h.filter(a.parts,e.hitch(this,function(a){a=d(a);
b.push(a);return 0<a}));1===a.parts.length?c.parts.push(a.parts[0]):2<=a.parts.length&&c.parts.push(a);return Math.min.apply(b,b)}),l=0;l<a.parts.length;l++){var k=a.parts[l];if(k.parts){if(0>g(k)&&b)return null}else if(0>f(k)&&b&&k.valueObj&&"uniquePredefined"!==k.valueObj.type&&"multiplePredefined"!==k.valueObj.type&&"unique"!==k.valueObj.type)return null}return c},_getFilterExprByPartsObj:function(a){this._filterUtils.isHosted=A.isHostedService(this.url);return this._filterUtils.getExprByFilterObj(a)},
_getSingleFilterParameterBySpId:function(a){return this._spObj[a]},_getCascadeFilterPartsObj:function(a){var b={logicalOperator:this.partsObj.logicalOperator,parts:[]},c=e.clone(this.partsObj),d,f,g;d="none";a.interactiveObj&&a.interactiveObj.cascade&&(d=a.interactiveObj.cascade);if("previous"===d)for(d=0;d<c.parts.length;d++)f=c.parts[d],f.majorCascadeIndex<a.majorCascadeIndex?b.parts.push(f):f.parts&&f.majorCascadeIndex===a.majorCascadeIndex&&(g=e.clone(f),g.parts=h.filter(g.parts,e.hitch(this,
function(b){return b.minorCascadeIndex<a.minorCascadeIndex})),b.parts.push(g));else if("all"===d)for(d=0;d<c.parts.length;d++)f=c.parts[d],f.majorCascadeIndex!==a.majorCascadeIndex?b.parts.push(f):f.majorCascadeIndex===a.majorCascadeIndex&&f.parts&&(g=e.clone(f),h.some(f.parts,e.hitch(this,function(b){return b.spId===a.spId}))&&(g.parts=h.filter(g.parts,e.hitch(this,function(b){return b.minorCascadeIndex!==a.minorCascadeIndex})),b.parts.push(g)));return b=this._getNewValidPartsObj(b,!1)},_getCascadeFilterExpr:function(a){var b=
"1\x3d1";(a=this._getCascadeFilterPartsObj(a))&&(b=this._getFilterExprByPartsObj(a));b||(b="1\x3d1");return b},clear:function(){this.featureLayerId=this.url=null;this.widgetId="";var a=p(".jimu-single-filter-parameter",this.tbody);h.forEach(a,e.hitch(this,function(a){y.byNode(a).destroy()}));n.empty(this.tbody);this.layerInfo=this.partsObj=null},build:function(a,b,c,d,f){var g=new r;this.clear();this.url=a;this.layerInfo=b;this.partsObj=e.clone(c);this.partsObj=this._updatePartsObj(this.partsObj);
this.featureLayerId=d;this.widgetId=f;this._setCascadeIndexForPartsObj(this.partsObj);a=this._getAllInteractiveSinglePartArray(this.partsObj);var l=this.partsObj.wId;if(0<a.length){var k=new C({url:this.url,layerDefinition:b,featureLayerId:this.featureLayerId});a=h.map(a,e.hitch(this,function(a,c){l&&(a.vpId=l+"_"+c);a.widgetId=this.widgetId;c=n.create("tr",{innerHTML:"\x3ctd\x3e\x3c/td\x3e"},this.tbody);c=p("td",c)[0];var d=this._getFieldInfo(a.fieldObj.name,this.layerInfo),d=new B({nls:this.nls,
url:this.url,layerDefinition:b,fieldInfo:d,part:a,valueProviderFactory:k});this.own(m(d,"change",e.hitch(this,this._onSingleFilterParameterChanged)));this.own(m(d,"enter",e.hitch(this,this._catchSingleFilterParameterEnter)));d.placeAt(c);d.startup();a.spId=d.id;return this._spObj[d.id]=d}));h.forEach(a,e.hitch(this,function(a){a.valueProvider.getCascadeFilterExpr=e.hitch(this,this._getCascadeFilterExpr,a.part);a.valueProvider.getCascadeFilterPartsObj=e.hitch(this,this._getCascadeFilterPartsObj,a.part)}));
a=h.map(a,e.hitch(this,function(a){return a.init()}));t(a).then(e.hitch(this,function(a){g.resolve(a)}),e.hitch(this,function(){g.reject()}))}else g.resolve();return g},_updatePartsObj:function(a){h.forEach(a,e.hitch(this,function(a){a.parts?h.forEach(a.parts,e.hitch(this,function(a){a.interactiveObj&&!0===a.interactiveObj.cascade?a.interactiveObj.cascade="previous":!1===a.interactiveObj.cascade&&(a.interactiveObj.cascade="none")})):a.interactiveObj&&!0===a.interactiveObj.cascade?a.interactiveObj.cascade=
"previous":!1===a.interactiveObj.cascade&&(a.interactiveObj.cascade="none")}));return a},_setCascadeIndexForPartsObj:function(a){for(var b=0;b<a.parts.length;b++){var c=a.parts[b];c.majorCascadeIndex="AND"===a.logicalOperator?b:0;c.minorCascadeIndex=0;c.cascadeIndex=c.majorCascadeIndex;if(c.parts)for(var d=0;d<c.parts.length;d++){var f=c.parts[d];f.majorCascadeIndex=c.majorCascadeIndex;f.minorCascadeIndex="AND"===c.logicalOperator?d:0;f.cascadeIndex=parseFloat(f.majorCascadeIndex+"."+f.minorCascadeIndex)}}},
_getFieldInfo:function(a,b){b=b.fields;for(var c=0;c<b.length;c++){var d=b[c];if(a===d.name)return d}return null},_getAllInteractiveSinglePartArray:function(a){for(var b=[],c=0;c<a.parts.length;c++){var d=a.parts[c];if(d.parts)for(var f=0;f<d.parts.length;f++){var e=d.parts[f];e.interactiveObj&&b.push(e)}else d.interactiveObj&&b.push(d)}return b},_catchSingleFilterParameterEnter:function(){this.emit("enter")},_onSingleFilterParameterChanged:function(){this.emit("change",this.getFilterExpr(!1))}})});