// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/store/Memory dojo/Deferred dojo/store/Observable dijit/tree/ObjectStoreModel dojo/promise/all dojo/_base/lang dojo/_base/html dojo/_base/array jimu/utils jimu/dijit/_Tree jimu/LayerInfos/LayerInfos jimu/dijit/LoadingIndicator".split(" "),function(r,t,u,v,w,x,y,n,z,A,l,b,p,h,m,B,C,D){var f=u([v,w,x,t],{templateString:'\x3cdiv style\x3d"width:100%;"\x3e\x3cdiv data-dojo-attach-point\x3d"errorTipSection" class\x3d"error-tip-section"\x3e\x3cspan class\x3d"jimu-icon jimu-icon-error"\x3e\x3c/span\x3e\x3cspan class\x3d"jimu-state-error-text" data-dojo-attach-point\x3d"errTip"\x3e${nls.noLayersTip}\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e',
_store:null,_id:0,_treeClass:"layer-chooser-tree",createMapResponse:null,multiple:!1,onlyShowVisible:!1,updateWhenLayerInfosIsShowInMapChanged:!1,onlyShowWebMapLayers:!1,displayTooltipForTreeNode:!1,postMixInProperties:function(){this.nls=window.jimuNls.basicLayerChooserFromMap},postCreate:function(){this.inherited(arguments);p.addClass(this.domNode,"jimu-basic-layer-chooser-from-map");this.multiple=!!this.multiple;this.shelter=new D({hidden:!0});this.shelter.placeAt(this.domNode);this.shelter.startup();
this._createTree();this.basicFilter=b.hitch(this,this.basicFilter);this.filter=f.andCombineFilters([this.basicFilter,this.filter]);this.createMapResponse&&this.setCreateMapResponse(this.createMapResponse)},basicFilter:function(a){var c=new n;this.onlyShowVisible?c.resolve(a.isShowInMap()):c.resolve(!0);return c},filter:function(a){a=new n;a.resolve(!0);return a},getSelectedItems:function(){var a=this.tree.getSelectedItems();return h.map(a,b.hitch(this,function(a){return this.getHandledItem(a)}))},
getAllItems:function(){var a=this.tree.getAllItems(),c=[];h.forEach(a,b.hitch(this,function(a){"root"!==a.id&&(a=this.getHandledItem(a),c.push(a))}));return c},getHandledItem:function(a){return{name:a.name,layerInfo:a.layerInfo}},_isLeafItem:function(a){return a.isLeaf},setCreateMapResponse:function(a){this.createMapResponse=a;C.getInstance(this.createMapResponse.map,this.createMapResponse.itemInfo).then(b.hitch(this,function(a){this.layerInfosObj=a;this.own(r(this.layerInfosObj,"layerInfosChanged",
b.hitch(this,this._onLayerInfosChanged)));this.updateWhenLayerInfosIsShowInMapChanged&&this.own(r(this.layerInfosObj,"layerInfosIsShowInMapChanged",b.hitch(this,this._onLayerInfosIsShowInMapChanged)));this._buildTree(this.layerInfosObj)}))},_onLayerInfosChanged:function(a,c){this._buildTree(this.layerInfosObj);this.emit("update")},_onLayerInfosIsShowInMapChanged:function(a){this._buildTree(this.layerInfosObj);this.emit("update")},_buildTree:function(a){this._clear();p.setStyle(this.errorTipSection,
"display","block");var c=[];this.onlyShowWebMapLayers?(c=a.getLayerInfoArrayOfWebmap(),c=c.concat(a.getTableInfoArrayOfWebmap())):(c=a.getLayerInfoArray(),c=c.concat(a.getTableInfoArray()));0!==c.length&&(p.setStyle(this.errorTipSection,"display","none"),h.forEach(c,b.hitch(this,function(a){this._addDirectLayerInfo(a)})))},_addDirectLayerInfo:function(a){a&&a.getLayerObject().then(b.hitch(this,function(){this._addItem("root",a)}),b.hitch(this,function(a){console.error(a)}))},_clear:function(){var a=
this._store.query({parent:"root"});h.forEach(a,b.hitch(this,function(a){a&&"root"!==a.id&&this._store.remove(a.id)}))},_addItem:function(a,c){var d=null,e=c.getLayerType(),k=this.filter(c);l({layerType:e,valid:k}).then(b.hitch(this,function(e){if(e.valid){var g=b.hitch(this,function(b,k){this._id++;d={name:c.title||"",parent:a,layerInfo:c,type:e.layerType,layerClass:c.layerObject.declaredClass,id:this._id.toString(),isLeaf:b,hasChildren:k};this._store.add(d)}),q=c.getSubLayers(),k=0===q.length;k?
g(k,!1):(q=h.map(q,b.hitch(this,function(a){return this.filter(a)})),l(q).then(b.hitch(this,function(a){(a=h.some(a,function(a){return a}))&&g(k,a)})))}}))},_getRootItem:function(){return{id:"root",name:"Map Root",type:"root",isLeaf:!1,hasChildren:!0}},_createTree:function(){var a=this._getRootItem(),a=new y({data:[a],getChildren:function(a){return this.query({parent:a.id})}});this._store=new z(a);a=new A({store:this._store,query:{id:"root"},mayHaveChildren:b.hitch(this,this._mayHaveChildren)});this.tree=
new B({multiple:this.multiple,model:a,showRoot:!1,isLeafItem:b.hitch(this,this._isLeafItem),style:{width:"100%"},onOpen:b.hitch(this,function(a,d){"root"!==a.id&&this._onTreeOpen(a,d)}),onClick:b.hitch(this,function(a,d,e){this._onTreeClick(a,d,e);this.emit("tree-click",a,d,e)}),getIconStyle:b.hitch(this,function(a,d){var c=null;if(!a||"root"===a.id)return null;var b={width:"20px",height:"20px",backgroundRepeat:"no-repeat",backgroundPosition:"center center",backgroundImage:""},g=window.location.protocol+
"//"+window.location.host+require.toUrl("jimu");if(a=this._getIconInfo(a,d).imageName)b.backgroundImage="url("+g+"/css/images/"+a+")",c=b;return c}),getIconClass:b.hitch(this,function(a,d){return this._getIconInfo(a,d).className}),getTooltip:b.hitch(this,function(a){return this.displayTooltipForTreeNode?a.layerInfo.title:""})});p.addClass(this.tree.domNode,this._treeClass);this.tree.placeAt(this.shelter.domNode,"before")},_mayHaveChildren:function(a){return a.hasChildren},_getIconInfo:function(a,
c){var d="",e="";"ArcGISDynamicMapServiceLayer"===a.type||"ArcGISTiledMapServiceLayer"===a.type?c?(d="mapserver_open.png",e="mapservice-layer-icon open"):(d="mapserver_close.png",e="mapservice-layer-icon close"):"GroupLayer"===a.type?c?(d="group_layer2.png",e="group-layer-icon open"):(d="group_layer1.png",e="group-layer-icon close"):"FeatureLayer"===a.type?(a=m.getTypeByGeometryType(a.layerInfo.layerObject.geometryType),"point"===a?(d="point_layer1.png",e="point-layer-icon"):"polyline"===a?(d="line_layer1.png",
e="line-layer-icon"):"polygon"===a&&(d="polygon_layer1.png",e="polygon-layer-icon")):"Table"===a.type?(d="table.png",e="table-icon"):"ArcGISImageServiceLayer"===a.type||"ArcGISImageServiceVectorLayer"===a.type?(d="image_layer.png",e="iamge-layer-icon"):c?(d="mapserver_open.png",e="mapservice-layer-icon open"):(d="mapserver_close.png",e="mapservice-layer-icon close");return{imageName:d,className:e}},_onTreeOpen:function(a,c){if("root"!==a.id){var d=[];c=[];d=a.layerInfo.getSubLayers();a.checked||(this.shelter.show(),
c=h.map(d,b.hitch(this,function(a){return a.getLayerObject()})),l(c).then(b.hitch(this,function(){this.domNode&&(h.forEach(d,b.hitch(this,function(c){this._addItem(a.id,c)})),a.checked=!0,this.shelter.hide())}),b.hitch(this,function(a){console.error(a);this.shelter.hide()})))}},_onTreeClick:function(a,c,d){},destroy:function(){this.shelter&&(this.shelter.destroy(),this.shelter=null);this.tree&&this.tree.destroy();this.inherited(arguments)}});f.createFilterByLayerType=function(a){b.isArrayLike(a)||
(a=[]);return function(c){var d=new n;if(0===a.length)d.resolve(!0);else{var e=[];c.traversal(function(a){e.push(a.getLayerType())});l(e).then(function(c){for(var e=0;e<c.length;e++)for(var b=0;b<a.length;b++)if(c[e]===a[b]){d.resolve(!0);return}d.resolve(!1)},function(a){console.error(a);d.reject(a)})}return d}};f.createFeaturelayerFilter=function(a,c,d,e){var b=["point","polyline","polygon"];a&&0<a.length?(a=h.filter(a,function(a){return 0<=b.indexOf(a)}),0===a.length&&(a=b)):a=b;return function(b){var g=
b.getLayerType();b=b.getLayerObject();return l({layerType:g,layerObject:b}).then(function(b){var g=b.layerType;b=b.layerObject;if("ArcGISDynamicMapServiceLayer"===g||"ArcGISTiledMapServiceLayer"===g||"GroupLayer"===g||"FeatureCollection"===g)return!0;if("FeatureLayer"===g){var g=m.getTypeByGeometryType(b.geometryType),g=0<=h.indexOf(a,g),k=f._shouldPassStatisticsCheck(e,b);return b.url?(b=m.isFeaturelayerUrlSupportQuery(b.url,b.capabilities),g&&b&&k):c&&g}return"Table"===g?(g=m.isFeaturelayerUrlSupportQuery(b.url,
b.capabilities),b=f._shouldPassStatisticsCheck(e,b),d&&g&&b):!1})}};f.createImageServiceLayerFilter=function(a,b){return function(c){var d=c.getLayerType();c=c.getLayerObject();return l({layerType:d,layerObject:c}).then(function(c){var d=c.layerType,e=c.layerObject;return"ArcGISImageServiceLayer"===d||"ArcGISImageServiceVectorLayer"===d?a?m.isImageServiceSupportQuery(c.layerObject.capabilities)?b?f._shouldPassStatisticsCheck(b,e):!0:!1:!0:!1})}};f._shouldPassStatisticsCheck=function(a,b){return a?
(a=!1,a=b.advancedQueryCapabilities?!!b.advancedQueryCapabilities.supportsStatistics:!!b.supportsStatistics):!0};f.createQueryableLayerFilter=function(a){var b=f.createFeaturelayerFilter(["point","polyline","polygon"],!1,!0,a);a=f.createImageServiceLayerFilter(!0,a);return f.orCombineFilters([b,a])};f.andCombineFilters=function(a){return f._combineFilters(a,!0)};f.orCombineFilters=function(a){return f._combineFilters(a,!1)};f._combineFilters=function(a,b){return function(c){var d=new n,f=h.map(a,
function(a){return a(c)});l(f).then(function(a){var c=!1,c=b?h.every(a,function(a){return a}):h.some(a,function(a){return a});d.resolve(c)},function(a){console.error(a);d.reject(a)});return d}};return f});