// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/templates/TabContainer3.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"control-node" data-dojo-attach-point\x3d"controlNode"\x3e\r\n    \x3ctable data-dojo-attach-point\x3d"controlTable" class\x3d"control-table" cellpading\x3d"0"\x3e\r\n      \x3ctbody\x3e\r\n        \x3ctr data-dojo-attach-point\x3d"tabTr"\x3e\r\n        \x3c/tr\x3e\r\n      \x3c/tbody\x3e\r\n    \x3c/table\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"container-node" data-dojo-attach-point\x3d"containerNode"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"tab-shelter" data-dojo-attach-point\x3d"shelter"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/keys dojo/Evented dojo/query dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/TabContainer3.html jimu/dijit/ViewStack jimu/utils".split(" "),function(l,f,g,d,h,e,m,k,n,p,q,r,t){return l([n,p,m],{templateString:q,baseClass:"jimu-tab3",declaredClass:"jimu.dijit.TabContainer3",_currentIndex:-1,selected:"",tabs:null,average:!0,postCreate:function(){this.inherited(arguments);this._initSelf();this.selected?
this.selectTab(this.selected):0<this.tabs.length&&this.selectTab(this.tabs[0].title)},selectTab:function(b){g.forEach(this.tabItems,f.hitch(this,function(a,c){d.removeClass(a,"jimu-state-active");d.setAttr(a,"tabindex","-1");a.label===b&&(d.addClass(a,"jimu-state-active"),d.setAttr(a,"tabindex","0"),this._currentIndex=c)}));this.viewStack.switchView(b);this.emit("tabChanged",b)},addTab:function(b){if(!this.average){var a=k("td:last-child",this.tabTr);0<a.length&&d.destroy(a[0])}0<g.filter(this.tabs,
function(a){return a.title===b.title}).length?console.error("tab title conflict: "+b.title):(this.tabs.push(b),this._createTab(b),this.average||this._addEmptyTab())},_addEmptyTab:function(){var b=d.toDom('\x3ctd nowrap class\x3d"tab-item-td tab-item-td-empty" style\x3d"border-bottom:1px solid #ccc;"\x3e\x3cdiv class\x3d"tab-item-div"\x3e\x3c/div\x3e\x3c/td\x3e');d.place(b,this.tabTr)},removeTab:function(b){var a=-1;if(g.some(this.tabs,function(d,c){if(d.title===b)return a=c,!0})){var c=this.tabs.splice(a,
1)[0];g.some(this.tabItems,function(a,c){if(a.label===b)return this.tabItems.splice(c,1),d.destroy(a),!0},this);this.viewStack.removeView(c.content)}},showShelter:function(){d.setStyle(this.shelter,"display","block")},hideShelter:function(){d.setStyle(this.shelter,"display","none")},getSelectedIndex:function(){return this._currentIndex},getSelectedTitle:function(){return this.viewStack.getSelectedLabel()},_initSelf:function(){this.viewStack=new r(null,this.containerNode);this.own(h(this.containerNode,
"keydown",f.hitch(this,function(b){b.keyCode===e.ESCAPE&&(b.stopPropagation(),this.tabItems[this._currentIndex].focus())})));this.tabItems=[];g.forEach(this.tabs,function(b){this._createTab(b)},this);this.own(h(this.tabTr,"keydown",f.hitch(this,function(b){var a=b.target,c;b.keyCode===e.RIGHT_ARROW?c=a.nextElementSibling?!this.average&&d.hasClass(a.nextElementSibling,"tab-item-td-empty")?this.tabItems[0]:a.nextElementSibling:this.tabItems[0]:b.keyCode===e.LEFT_ARROW?c=a.previousElementSibling?a.previousElementSibling:
this.tabItems[this.tabItems.length-1]:b.keyCode===e.HOME?c=this.tabItems[0]:b.keyCode===e.END&&(c=this.tabItems[this.tabItems.length-1]);c&&(a=c,c.focus())})));this.average?(this.controlTable.style.tableLayout="fixed",d.addClass(this.domNode,"average")):this._addEmptyTab()},startup:function(){this.inherited(arguments);this._started=!0},_createTab:function(b){var a=d.toDom('\x3ctd nowrap class\x3d"tab-item-td"\x3e\x3cdiv class\x3d"tab-item-div"\x3e\x3c/div\x3e\x3c/td\x3e');a.label=b.title||"";a.title=
b.title;d.place(a,this.tabTr);var c=k(".tab-item-div",a)[0];c.innerHTML=t.sanitizeHTML(a.label);c.label=a.label;b.content.label=a.label;this.viewStack.addView(b.content);this.own(h(a,"click",f.hitch(this,function(a){this._onSelect(b.title,a)})));this.own(h(a,"keydown",f.hitch(this,function(a){a.keyCode!==e.ENTER&&a.keyCode!==e.SPACE||this._onSelect(b.title,a)})));this.tabItems.push(a)},_onSelect:function(b,a){d.hasClass(a.target,"jimu-state-active")||this.selectTab(b)}})});