//>>built
define("dojo/_base/declare jimu/BaseWidgetSetting dijit/_WidgetsInTemplateMixin dojo/on dojo/_base/lang dojo/_base/html dojo/keys dojo/Deferred jimu/utils ./ConfigureTimeSettings jimu/dijit/Popup jimu/dijit/CheckBox dijit/form/Select dijit/form/ValidationTextBox".split(" "),function(g,h,k,c,b,d,f,l,m,n,p,e,q){return g([h,k],{baseClass:"jimu-widget-timeslider-setting",configureTimeSettings:null,postCreate:function(){this._timeFormatOptions=[{label:this.nls.mapDefault,value:"auto"},{label:"July 2015",
value:"MMMM YYYY"},{label:"Jul 2015",value:"MMM YYYY"},{label:"July 21,2015",value:"MMMM D,YYYY"},{label:"Tue Jul 21,2015",value:"ddd MMM DD,YYYY"},{label:"7/21/2015",value:"M/DD/YYYY"},{label:"2015/7/21",value:"YYYY/M/DD"},{label:"7/21/15",value:"M/DD/YY"},{label:"2015",value:"YYYY"},{label:"7/21/2015 8:00 am",value:"M/DD/YYYY  h:mm a"},{label:"Tue Jul 21 8:00 am",value:"ddd MMM DD  h:mm a"},{label:this.nls.custom,value:"Custom"}];this.showLabelsBox=new e({label:this.nls.showLayerLabels,checked:!1},
this.showLabelsBox);this.showLabelsBox.startup();this.autoPlay=new e({label:this.nls.autoPlay,checked:!1},this.autoPlay);this.autoPlay.startup();this.loopPlay=new e({label:this.nls.loopPlay,checked:!1},this.loopPlay);this.loopPlay.startup();this.timeFormat=new q({options:this._timeFormatOptions},this.timeFormat);this.inherited(arguments)},startup:function(){this.config||(this.config={});this.customDateFormat.setAttribute("placeHolder","YYYY-MM-dd h:m:s Z");this.own(c(this.timeFormat,"click",b.hitch(this,
function(){"undefined"===typeof this._firstChange&&(this._firstChange=!1)})));this.own(c(this.timeFormat,"change",b.hitch(this,function(a){"undefined"===typeof this._firstChange?this._firstChange=!1:this._initOptionsUI(a)})));this.own(c(this.webMapSettingRaido,"change",b.hitch(this,function(){this._updateTimeSettingBtnUI()})));this.own(c(this.configureSettingRaido,"change",b.hitch(this,function(){this._updateTimeSettingBtnUI()})));this.setConfig(this.config);this.inherited(arguments)},_initOptionsUI:function(a,
r){"Custom"!==a?(d.addClass(this.customDateContainer,"hide"),this.customDateFormat.set("value","")):(d.removeClass(this.customDateContainer,"hide"),this.customDateFormat.set("value",r||""));this.own(c(this.timeSettingBtn,"click",b.hitch(this,function(){this.configureSettingRaido.checked&&this._createTimeConfigSetting().then(b.hitch(this,function(a){this.popup=new p({titleLabel:this.nls.timeSetting,autoHeight:!0,content:this.configureTimeSettings,container:"main-page",width:680,buttons:[{label:window.jimuNls.common.ok,
key:f.ENTER,disable:a,onClick:b.hitch(this,"_onPopupOk")},{label:window.jimuNls.common.cancel,classNames:["jimu-btn-vacation"],key:f.ESCAPE}],onClose:b.hitch(this,"_onPopupClose")});d.addClass(this.popup.domNode,"timeslider-widget-setting-popup")}))})))},_onPopupOk:function(){if(!1===this.configureTimeSettings.isValid())return!1;this.config=this.configureTimeSettings.getConfig(this.config);this.popup.close();this.popup=this.configureTimeSettings=null},_onPopupClose:function(){this.popup=this.configureTimeSettings=
null},setConfig:function(a){this.config=a;a.showLabels?this.showLabelsBox.setValue(!0):this.showLabelsBox.setValue(!1);!1===a.autoPlay?this.autoPlay.setValue(!1):this.autoPlay.setValue(!0);!1===a.loopPlay?this.loopPlay.setValue(!1):this.loopPlay.setValue(!0);if(a.timeFormat){this.timeFormat.setValue(a.timeFormat);var b;a.customDateFormat&&(b=a.customDateFormat);this._initOptionsUI(a.timeFormat,b)}else this.timeFormat.setValue("auto");"undefined"===typeof a.isHonorWebMap||!0===a.isHonorWebMap?(a.isHonorWebMap=
!0,this.webMapSettingRaido.setChecked(!0)):(a.isHonorWebMap=!1,this.configureSettingRaido.setChecked(!0));this._updateTimeSettingBtnUI()},getConfig:function(){if("Custom"===this.timeFormat.getValue()&&""===this.customDateFormat.get("value"))return this.customDateFormat.focus(),this.customDateFormat.set("state","Error"),!1;this.config.showLabels=this.showLabelsBox.getValue();this.config.autoPlay=this.autoPlay.getValue();this.config.loopPlay=this.loopPlay.getValue();this.config.timeFormat=this.timeFormat.getValue();
this.customDateFormat.get("value")?this.config.customDateFormat=this.customDateFormat.get("value"):this.config.customDateFormat="";this.config.isHonorWebMap=this.webMapSettingRaido.checked?!0:!1;this.configureTimeSettings||this._createTimeConfigSetting();this.configureTimeSettings&&this.configureTimeSettings.getConfig&&(this.config=this.configureTimeSettings.getConfig(this.config));return this.config},_onCustomDateFormatBlur:function(){this.customDateFormat.value=m.stripHTML(this.customDateFormat.value||
"")},_updateTimeSettingBtnUI:function(){this.webMapSettingRaido.checked&&d.addClass(this.timeSettingBtn,"disabled");this.configureSettingRaido.checked&&d.removeClass(this.timeSettingBtn,"disabled")},_createTimeConfigSetting:function(){var a=new l;this.configureTimeSettings=new n({nls:this.nls,map:this.map,config:this.config},this.configureTimeSettingsContainer);this.own(c(this.configureTimeSettings,"initedLayers",b.hitch(this,function(b){var c=!1;b&&b.isNoLayer&&(c=!0);a.resolve(c)})));this.configureTimeSettings.startup();
return a}})});