define({
  "_widgetLabel": "Координата",
  "hintMessage": "Клацніть на карті для отримання координат",
  "defaultLabel": "За замовчуванням",
  "realtimeLabel": "Перемістіть мишу для отримання координат",
  "computing": "Виконується обчислення...",
  "latitudeLabel": "Широта",
  "longitudeLabel": "Довгота",
  "loading": "завантажується...",
  "enableClick": "Клацніть для активації клацання на карті для отримання координат",
  "disableClick": "Клацніть для деактивації клацання на карті для отримання координат",
  "Default": "За замовчуванням",
  "Inches": "Дюйми",
  "Foot": "Фути",
  "Foot_US": "Фути_США",
  "Yards": "Ярди",
  "Miles": "Милі",
  "Nautical_Miles": "Морські милі",
  "Millimeters": "Міліметри",
  "Centimeters": "Сантиметри",
  "Meter": "Метри",
  "Kilometers": "Кілометри",
  "Decimeters": "Дециметри",
  "Decimal_Degrees": "Градуси",
  "Degree_Minutes_Seconds": "Градуси/хвилини/секунди",
  "MGRS": "MGRS",
  "USNG": "USNG"
});